table medidas_html
	lineageTag: f371007f-daa0-4acf-919c-58dc35ff6b74

	/// Cabeçalho executivo do dashboard Journey, com dados de CONTRATOS_OPORTUNIDADES e PROJECT_QBERT_JOBS.
	measure Titulo_Diagnostico_HTML_2026_Novo_Estilo_DOCUMENTACAO = ```
					VAR vCalendarStart = MIN ( 'dCalendar'[Date] )
					VAR vCalendarEnd = MAX ( 'dCalendar'[Date] )
					VAR vHasCalendarFilter =
						ISFILTERED ( 'dCalendar'[Date] )
							|| ISFILTERED ( 'dCalendar'[YearMonthName] )
							|| ISFILTERED ( 'dCalendar'[YearMonth] )
							|| ISFILTERED ( 'dCalendar'[MonthNumber] )
							|| ISFILTERED ( 'dCalendar'[Year] )
					VAR vDateFormat = "dd/mm/yyyy"
					VAR vMinData = MINX ( CONTRATOS_OPORTUNIDADES, CONTRATOS_OPORTUNIDADES[data_contrato] )
					VAR vMaxData = MAXX ( CONTRATOS_OPORTUNIDADES, CONTRATOS_OPORTUNIDADES[data_contrato] )
					VAR vPeriodo =
						IF (
							ISBLANK ( vMinData ) || ISBLANK ( vMaxData ),
							"Período não definido",
							FORMAT ( vMinData, vDateFormat ) & " a " & FORMAT ( vMaxData, vDateFormat )
						)
					VAR vTotalProdutos = DISTINCTCOUNT ( CONTRATOS_OPORTUNIDADES[oportunidade] )
					VAR vJobsCO = DISTINCTCOUNT ( CONTRATOS_OPORTUNIDADES[job] )
					VAR vEstimativaTotal = SUM ( CONTRATOS_OPORTUNIDADES[estimativa] )
					VAR vDataAtual = FORMAT ( NOW (), "dd/mm/yyyy HH:mm" )
					VAR vCSS =
					"
					<style>
					*{margin:0;padding:0;box-sizing:border-box}
					.diag-title-shell{width:1910px;min-width:1910px;max-width:1910px;height:165px;min-height:165px;max-height:165px;overflow:hidden;font-family:'Segoe UI',Arial,sans-serif;color:#E8EEF5;border-radius:18px;border:1px solid rgba(213,174,119,.36);background:radial-gradient(circle at 0% 0%,rgba(213,174,119,.22),transparent 33%),radial-gradient(circle at 92% 18%,rgba(139,224,209,.13),transparent 28%),linear-gradient(135deg,#060B10 0%,#0B141B 46%,#10201F 100%);box-shadow:0 16px 38px rgba(0,0,0,.50),inset 0 1px 0 rgba(255,255,255,.05);position:relative}
					.diag-title-shell:before{content:'';position:absolute;left:0;top:0;bottom:0;width:8px;background:linear-gradient(180deg,#F4D9A9,#D5AE77,#8BE0D1);opacity:.92}
					.diag-title-grid{position:relative;z-index:2;width:100%;height:100%;display:grid;grid-template-columns:150px minmax(0,1fr) 430px;align-items:center;gap:24px;padding:18px 26px 18px 34px}
					.brand-panel{height:100%;min-width:0;display:flex;align-items:center;justify-content:center}
					.logo-card{width:118px;height:82px;border-radius:16px;display:flex;align-items:center;justify-content:center;padding:10px;background:radial-gradient(circle at 28% 12%,rgba(213,174,119,.18),transparent 36%),#030506;border:1px solid rgba(213,174,119,.40);box-shadow:0 12px 24px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.06);overflow:hidden}
					.logo-text{width:100%;height:100%;display:flex;align-items:center;justify-content:center;color:#fff;font-family:Georgia,'Times New Roman',serif;font-size:13px;font-weight:700;line-height:1;letter-spacing:-.05em;text-align:center;white-space:nowrap;overflow:hidden}
					.logo-text .studio{color:#D5AE77;margin-left:1px}
					.center-panel{min-width:0;height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;text-align:center;position:relative}
					.center-panel:before,.center-panel:after{content:'';width:88px;height:1px;background:linear-gradient(90deg,transparent,rgba(213,174,119,.65),transparent)}
					.title-kicker{color:#8BE0D1;font-size:10px;font-weight:950;letter-spacing:.22em;text-transform:uppercase;line-height:1;white-space:nowrap}
					.main-title{color:#fff;font-size:38px;font-weight:950;letter-spacing:.09em;text-transform:uppercase;line-height:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-shadow:0 4px 16px rgba(0,0,0,.72)}
					.main-title .gold{color:#F4D9A9}
					.subline{max-width:100%;color:#D5AE77;font-size:11px;font-weight:950;letter-spacing:.10em;text-transform:uppercase;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
					.right-panel{height:100%;display:grid;grid-template-columns:168px minmax(0,1fr) 68px;align-items:center;gap:14px;min-width:0}
					.doc-title-button{position:relative;min-height:44px;display:inline-flex;align-items:center;justify-content:center;padding:12px 17px;border-radius:14px;color:#081018;border:1px solid rgba(244,217,169,.72);background:linear-gradient(135deg,#F4D9A9 0%,#D5AE77 48%,#8BE0D1 100%);box-shadow:0 14px 28px rgba(213,174,119,.24),0 0 0 1px rgba(255,255,255,.08) inset,0 0 22px rgba(139,224,209,.18);font-size:11px;font-weight:950;letter-spacing:.10em;text-transform:uppercase;white-space:nowrap;overflow:hidden}
					.doc-title-button:before{content:'i';display:inline-flex;align-items:center;justify-content:center;width:21px;height:21px;margin-right:8px;border-radius:50%;background:rgba(8,16,24,.18);border:1px solid rgba(8,16,24,.24);color:#081018;font-size:12px;font-weight:950;font-style:italic;line-height:1}
					.update-box{display:flex;flex-direction:column;align-items:flex-end;justify-content:center;gap:10px;min-width:0}
					.update-line{display:flex;flex-direction:column;align-items:flex-end;gap:3px;min-width:0}
					.update-label{color:#F4D9A9;font-size:9px;font-weight:950;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap}
					.update-value{color:#E8EEF5;font-size:12px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:160px;text-align:right}
					.avatar{position:relative;width:62px;height:62px;border-radius:50%;display:flex;align-items:center;justify-content:center;color:#F4D9A9;font-size:18px;font-weight:950;letter-spacing:.05em;background:linear-gradient(145deg,rgba(213,174,119,.14),rgba(255,255,255,.035));border:1px solid rgba(213,174,119,.58);box-shadow:0 0 0 5px rgba(213,174,119,.06),inset 0 1px 0 rgba(255,255,255,.10)}
					.avatar:after{content:'';position:absolute;right:2px;bottom:5px;width:9px;height:9px;border-radius:50%;background:#21E66D;box-shadow:0 0 12px rgba(33,230,109,.75);border:2px solid #10201F}
					</style>
					"
					VAR vHTML =
						"<div class='diag-title-shell'><div class='diag-title-grid'>"
							& "<div class='brand-panel'><div class='logo-card'><div class='logo-text'><span>GRUPO</span><span class='studio'>STUDIO</span></div></div></div>"
							& "<div class='center-panel'><div class='title-kicker'>Grupo Studio · Diagnóstico TAX</div><div class='main-title'>Oportunidades <span class='gold'>- Journey</span></div><div class='subline'>" & FORMAT ( vTotalProdutos, "#,##0" ) & " produtos · " & FORMAT ( vJobsCO, "#,##0" ) & " empresas | " & vPeriodo & "</div></div>"
							& "<div class='right-panel'><div class='doc-title-button'>Documentação</div><div class='update-box'><div class='update-line'><span class='update-label'>Atualizado em</span><span class='update-value'>" & vDataAtual & "</span></div><div class='update-line'><span class='update-label'>Créd. Estimado</span><span class='update-value'>" & FORMAT ( vEstimativaTotal, "R$ #,##0" ) & "</span></div></div><div class='avatar'>GS</div></div>"
						& "</div></div>"
					RETURN
						vCSS & vHTML
			```
		displayFolder: HTML
		lineageTag: c4874ca8-7357-4c3e-b3e5-6180c4491f86

	/// Documentação executiva da refatoração com CONTRATOS_OPORTUNIDADES como base de produtos.
	measure DOCUMENTACAO_DIAGNOSTICO_JOURNEY_HTML_V4_FORMAL_TODO_PERIODO = ```
					VAR vTotalProdutos = DISTINCTCOUNT ( CONTRATOS_OPORTUNIDADES[oportunidade] )
					VAR vTotalJobsCO = DISTINCTCOUNT ( CONTRATOS_OPORTUNIDADES[job] )
					VAR vTotalRegCO = COUNTROWS ( CONTRATOS_OPORTUNIDADES )
					VAR vTotalEstimativa = SUM ( CONTRATOS_OPORTUNIDADES[estimativa] )
					VAR vPeriodoInicial = MINX ( CONTRATOS_OPORTUNIDADES, CONTRATOS_OPORTUNIDADES[data_contrato] )
					VAR vPeriodoFinal = MAXX ( CONTRATOS_OPORTUNIDADES, CONTRATOS_OPORTUNIDADES[data_contrato] )
					VAR vPeriodo =
						IF (
							ISBLANK ( vPeriodoInicial ) || ISBLANK ( vPeriodoFinal ),
							"Sem dados no recorte",
							FORMAT ( vPeriodoInicial, "dd/MM/yyyy" ) & " a " & FORMAT ( vPeriodoFinal, "dd/MM/yyyy" )
						)
					VAR vAtualizado = FORMAT ( NOW (), "dd/mm/yyyy HH:mm" )
					VAR vCSS =
					"
					<style>
					.doc-page{width:1910px;height:1070px;box-sizing:border-box;padding:20px;font-family:'Segoe UI',Arial,sans-serif;background:radial-gradient(circle at 0% 0%,rgba(213,174,119,.18),transparent 32%),radial-gradient(circle at 94% 7%,rgba(139,224,209,.12),transparent 30%),linear-gradient(180deg,#101923 0%,#0B1219 100%);color:#E8EEF5;overflow:hidden}
					.doc-shell{width:100%;height:100%;display:grid;grid-template-columns:390px 1fr;gap:16px}
					.doc-sidebar{height:100%;box-sizing:border-box;border-radius:20px;border:1px solid rgba(213,174,119,.28);background:linear-gradient(180deg,rgba(213,174,119,.15),rgba(255,255,255,.025));box-shadow:0 18px 42px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.05);padding:24px 20px 20px;overflow:hidden;position:relative}
					.doc-sidebar:before{content:'';position:absolute;left:0;top:0;bottom:0;width:7px;background:linear-gradient(180deg,#F4D9A9,#D5AE77,#8BE0D1)}
					.brand-kicker{font-size:12.5px;text-transform:uppercase;letter-spacing:1.7px;color:#8BE0D1;font-weight:950;margin-bottom:10px}
					.brand-title{color:#F4D9A9;font-size:37.5px;line-height:1.02;font-weight:950;letter-spacing:.02em;margin-bottom:10px;text-transform:uppercase;text-shadow:0 8px 18px rgba(0,0,0,.35)}
					.brand-sub{font-size:15.6px;line-height:1.48;color:#B7C2CD;margin-bottom:14px}
					.side-card{border:1px solid rgba(255,255,255,.09);background:rgba(255,255,255,.04);border-radius:15px;padding:12px;margin-bottom:10px}
					.side-card.highlight{background:linear-gradient(135deg,rgba(213,174,119,.17),rgba(255,255,255,.035));border-color:rgba(213,174,119,.30)}
					.side-label{display:block;font-size:11.9px;color:#8796A5;text-transform:uppercase;letter-spacing:.85px;font-weight:950;margin-bottom:5px}
					.side-value{display:block;font-size:17.5px;color:#F0F5FA;font-weight:900;line-height:1.25}
					.side-value.big{color:#F4D9A9;font-size:27.5px}
					.side-small{color:#AEB8C2;font-size:13.4px;line-height:1.4;margin-top:5px}
					.nav-title{margin-top:14px;margin-bottom:9px;font-size:12.5px;text-transform:uppercase;letter-spacing:.95px;color:#D5AE77;font-weight:950}
					.nav-list{display:flex;flex-direction:column;gap:6px}.nav-pill{font-size:13.5px;color:#DCE5EE;border:1px solid rgba(213,174,119,.16);background:rgba(255,255,255,.04);border-radius:999px;padding:7px 10px;font-weight:850;line-height:1}.nav-pill.active{color:#8BE0D1;border-color:rgba(139,224,209,.30);background:rgba(139,224,209,.08)}
					.doc-main{height:100%;background:linear-gradient(180deg,#121C25 0%,#0D151D 100%);border:1px solid rgba(213,174,119,.20);border-radius:20px;box-shadow:0 18px 42px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.05);overflow:hidden;display:flex;flex-direction:column}
					.doc-header{padding:17px 20px 15px;border-bottom:1px solid rgba(213,174,119,.16);display:flex;align-items:flex-start;justify-content:space-between;gap:18px;background:linear-gradient(90deg,rgba(255,255,255,.03),rgba(213,174,119,.035))}
					.doc-header h1{margin:0;color:#F4D9A9;font-size:33.8px;line-height:1.08;font-weight:950;letter-spacing:.3px;text-transform:uppercase}.doc-header p{margin:7px 0 0;color:#B7C2CD;font-size:16px;line-height:1.4;max-width:1120px}
					.badge-wrap{display:flex;justify-content:flex-end;align-items:center;flex-wrap:wrap;gap:6px}.badge{display:inline-flex;border-radius:999px;border:1px solid rgba(213,174,119,.30);background:rgba(213,174,119,.08);color:#F4D9A9;font-size:12.5px;font-weight:950;text-transform:uppercase;letter-spacing:.6px;padding:5px 10px;white-space:nowrap}.badge.teal{color:#8BE0D1;border-color:rgba(139,224,209,.34);background:rgba(139,224,209,.08)}
					.doc-scroll{flex:1 1 auto;min-height:0;overflow-y:auto;overflow-x:hidden;padding:18px 20px 20px;box-sizing:border-box;scrollbar-width:thin;scrollbar-color:rgba(213,174,119,.60) rgba(8,14,20,.95)}
					.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:11px;margin-bottom:14px}.metric{position:relative;min-height:124px;padding:15px 13px 13px;border-radius:18px;background:linear-gradient(160deg,rgba(18,28,37,.96),rgba(11,18,25,.94));border:1px solid rgba(255,255,255,.10);box-shadow:0 16px 28px rgba(0,0,0,.22),inset 0 1px 0 rgba(255,255,255,.06);overflow:hidden}.metric:before{content:'';position:absolute;left:14px;top:0;width:42px;height:4px;border-radius:0 0 10px 10px;background:linear-gradient(90deg,#F4D9A9,#8BE0D1)}.metric.primary{background:linear-gradient(155deg,rgba(213,174,119,.20),rgba(18,28,37,.96) 36%,rgba(11,18,25,.96));border-color:rgba(213,174,119,.40)}.m-label{display:block;color:#AEB9C4;font-size:12.5px;letter-spacing:.08em;text-transform:uppercase;font-weight:950;margin-bottom:8px}.m-value{display:block;color:#F4D9A9;font-size:32.5px;font-weight:950;line-height:1.05;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.m-note{display:block;color:#8B98A6;font-size:13.8px;line-height:1.28;margin-top:7px;font-weight:850}
					.doc-section{border:1px solid rgba(213,174,119,.19);background:rgba(255,255,255,.027);border-radius:17px;margin-bottom:12px;overflow:hidden}.doc-section summary{cursor:pointer;list-style:none;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 15px;background:linear-gradient(90deg,rgba(213,174,119,.17),rgba(213,174,119,.035));border-bottom:1px solid rgba(213,174,119,.13)}.summary-left{display:flex;align-items:center;gap:10px;min-width:0}.summary-index{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:50%;background:rgba(213,174,119,.19);border:1px solid rgba(213,174,119,.30);color:#F4D9A9;font-size:12.5px;font-weight:950}.summary-title{color:#F4D9A9;font-size:17.5px;font-weight:950;text-transform:uppercase;letter-spacing:.45px}.summary-action{color:#B7C2CD;font-size:12.2px;font-weight:950;text-transform:uppercase;letter-spacing:.5px;border:1px solid rgba(255,255,255,.10);background:rgba(255,255,255,.04);border-radius:999px;padding:5px 9px;white-space:nowrap}.section-body{padding:15px}
					.doc-table{width:100%;border-collapse:separate;border-spacing:0;table-layout:fixed;overflow:hidden;border-radius:13px;border:1px solid rgba(255,255,255,.08);margin-bottom:10px}.doc-table th{background:#111A22;color:#D5AE77;font-size:12.5px;font-weight:950;text-transform:uppercase;letter-spacing:.55px;text-align:left;padding:10px;border-bottom:1px solid rgba(213,174,119,.30)}.doc-table td{color:#DCE5EE;font-size:14px;line-height:1.45;padding:9px 10px;border-bottom:1px solid rgba(255,255,255,.055);vertical-align:top}.doc-table tr:last-child td{border-bottom:none}.doc-table td strong{color:#F4D9A9}.callout{border-left:4px solid rgba(213,174,119,.82);background:rgba(213,174,119,.06);border-radius:13px;padding:12px 13px;color:#DCE5EE;font-size:14.2px;line-height:1.5;margin:10px 0}.callout.tech{border-left-color:#8BE0D1;background:rgba(139,224,209,.055)}.footer-doc{font-size:13.4px;color:#8796A5;line-height:1.38;padding:10px 2px 2px}
					</style>
					"
					VAR vHTML =
					"<div class='doc-page'><div class='doc-shell'><aside class='doc-sidebar'>"
						& "<div class='brand-kicker'>Power BI · Documentação</div><div class='brand-title'>Diagnóstico<br><span style='color:#8BE0D1'>Journey</span></div>"
						& "<div class='brand-sub'>Refatoração com CONTRATOS_OPORTUNIDADES como dimensão principal de produtos. As etapas do funil continuam baseadas em PROJECT_QBERT_JOBS para classificação de stages.</div>"
						& "<div class='side-card highlight'><span class='side-label'>Estrutura atual</span><span class='side-value big'>4 medidas</span><div class='side-small'>Todas na pasta simples HTML. A lógica foi refatorada para usar CO como fonte de produtos.</div></div>"
						& "<div class='side-card'><span class='side-label'>Bases usadas</span><span class='side-value'>CO + PQBJ</span><div class='side-small'>CONTRATOS_OPORTUNIDADES para dimensão de produtos e valores. PROJECT_QBERT_JOBS para tracking de etapas do funil.</div></div>"
						& "<div class='side-card'><span class='side-label'>Período exibido</span><span class='side-value'>" & vPeriodo & "</span><div class='side-small'>Calculado por data_contrato da tabela CONTRATOS_OPORTUNIDADES.</div></div>"
						& "<div class='side-card'><span class='side-label'>Atualização</span><span class='side-value'>" & vAtualizado & "</span><div class='side-small'>Atualizado no cálculo da medida HTML.</div></div>"
						& "<div class='nav-title'>Conteúdo</div><div class='nav-list'><div class='nav-pill active'>01. Resumo</div><div class='nav-pill'>02. Medidas mantidas</div><div class='nav-pill'>03. Regra das etapas</div><div class='nav-pill'>04. Limitações</div></div>"
					& "</aside><main class='doc-main'><div class='doc-header'><div><h1>Documentação · Diagnóstico - Journey</h1><p>Versão refatorada com CONTRATOS_OPORTUNIDADES como base de produtos TAX e PROJECT_QBERT_JOBS para classificação de etapas do funil operacional.</p></div><div class='badge-wrap'><span class='badge'>Diretoria</span><span class='badge'>Técnico</span><span class='badge teal'>CO + PQBJ</span></div></div><div class='doc-scroll'>"
						& "<div class='metric-grid'><div class='metric primary'><span class='m-label'>Produtos</span><span class='m-value'>" & FORMAT ( vTotalProdutos, "#,##0" ) & "</span><span class='m-note'>Oportunidades distintas</span></div><div class='metric'><span class='m-label'>Empresas</span><span class='m-value'>" & FORMAT ( vTotalJobsCO, "#,##0" ) & "</span><span class='m-note'>JOBS com oportunidade</span></div><div class='metric'><span class='m-label'>Reg. CO</span><span class='m-value'>" & FORMAT ( vTotalRegCO, "#,##0" ) & "</span><span class='m-note'>Linhas na CONTRATOS_OPORTUNIDADES</span></div><div class='metric'><span class='m-label'>Créd. Estimado</span><span class='m-value'>" & FORMAT ( vTotalEstimativa, "R$ #,##0" ) & "</span><span class='m-note'>Soma estimativa CO</span></div></div>"
						& "<details class='doc-section' open><summary><div class='summary-left'><span class='summary-index'>01</span><span class='summary-title'>Resumo da refatoração</span></div><span class='summary-action'>CO + PQBJ</span></summary><div class='section-body'><table class='doc-table'><thead><tr><th>Item</th><th>Antes</th><th>Agora</th><th>Impacto</th></tr></thead><tbody><tr><td><strong>Dimensão principal</strong></td><td>Journey 360 (CODIGO_PRODUTO=360, FIM=1).</td><td>Produtos TAX via CONTRATOS_OPORTUNIDADES[oportunidade].</td><td>Visão por linha de negócio TAX.</td></tr><tr><td><strong>Bases</strong></td><td>Somente PROJECT_QBERT_JOBS.</td><td>CONTRATOS_OPORTUNIDADES (produtos/valores) + PROJECT_QBERT_JOBS (etapas).</td><td>Enriquecimento com dados de oportunidade.</td></tr><tr><td><strong>Colunas</strong></td><td>7 etapas: CADASTRO a CRÉDITOS.</td><td>8 colunas: PRODUTOS + 7 etapas.</td><td>Nova coluna PRODUTOS como identificador da linha.</td></tr><tr><td><strong>Créditos</strong></td><td>ESTIMATIVA_CREDITO/SIMULACAO_CREDITO da PQBJ.</td><td>CONTRATOS_OPORTUNIDADES[estimativa].</td><td>Valor de oportunidade como métrica de crédito.</td></tr></tbody></table></div></details>"
						& "<details class='doc-section' open><summary><div class='summary-left'><span class='summary-index'>02</span><span class='summary-title'>Medidas mantidas</span></div><span class='summary-action'>HTML</span></summary><div class='section-body'><table class='doc-table'><thead><tr><th>Medida</th><th>Função</th></tr></thead><tbody><tr><td><strong>Titulo_Diagnostico_HTML_2026_Novo_Estilo_DOCUMENTACAO</strong></td><td>Cabeçalho premium com dados de CONTRATOS_OPORTUNIDADES.</td></tr><tr><td><strong>HTML Diagnóstico Journey | Visual Principal</strong></td><td>Visual principal com 8 colunas: PRODUTOS, CADASTRO, PROCURAÇÃO, CHECKLIST, OPERAÇÃO, REUNIÃO TEC, DIAGNÓSTICO, CRÉDITOS.</td></tr><tr><td><strong>HTML_DETALHAMENTO_DIAGNOSTICO_JOURNEY_SEM_ESPACO_OCIOSO</strong></td><td>Detalhamento operacional em tabela HTML, com busca e cópia.</td></tr><tr><td><strong>DOCUMENTACAO_DIAGNOSTICO_JOURNEY_HTML_V4_FORMAL_TODO_PERIODO</strong></td><td>Esta página de documentação.</td></tr></tbody></table></div></details>"
						& "<details class='doc-section' open><summary><div class='summary-left'><span class='summary-index'>03</span><span class='summary-title'>Regra das etapas</span></div><span class='summary-action'>DAX</span></summary><div class='section-body'><table class='doc-table'><thead><tr><th>Coluna visual</th><th>Critério na PROJECT_QBERT_JOBS</th></tr></thead><tbody><tr><td><strong>PRODUTOS</strong></td><td>CONTRATOS_OPORTUNIDADES[oportunidade] — dimensão principal da linha.</td></tr><tr><td><strong>CADASTRO</strong></td><td>JOB sem marcos posteriores (stage 1).</td></tr><tr><td><strong>PROCURAÇÃO</strong></td><td>DATA_PROC_ELETRONICA identificada.</td></tr><tr><td><strong>CHECKLIST</strong></td><td>CONTRATOCHECKLISTOK / CONTRATOCHECKLISTOK_DATA.</td></tr><tr><td><strong>OPERAÇÃO</strong></td><td>CODIGO_OP / PARECER_OP.</td></tr><tr><td><strong>REUNIÃO TEC</strong></td><td>PRAZO_ATA / ATA_ASSINADA.</td></tr><tr><td><strong>DIAGNÓSTICO</strong></td><td>DATA_ENTREGA / FIM.</td></tr><tr><td><strong>CRÉDITOS</strong></td><td>CREDITOS_QUALIFICADOS, ESTIMATIVA_CREDITO ou SIMULACAO_CREDITO.</td></tr></tbody></table><div class='callout tech'>O mapeamento entre CONTRATOS_OPORTUNIDADES e PROJECT_QBERT_JOBS é feito via campo [job] ↔ [JOB]. Os jobs CO são os Journey (CODIGO_PRODUTO=360, FIM=1) na PQBJ; as etapas são contadas nos filhos (PAI = CODIGO do Journey).</div></div></details>"
						& "<details class='doc-section' open><summary><div class='summary-left'><span class='summary-index'>04</span><span class='summary-title'>Limitações assumidas</span></div><span class='summary-action'>Dados</span></summary><div class='section-body'><div class='callout'>CONTRATOS_OPORTUNIDADES não possui campos de progressão de etapas (DATA_PROC_ELETRONICA, CONTRATOCHECKLISTOK, etc). Por isso as etapas continuam sendo classificadas via PROJECT_QBERT_JOBS. Se um job não existir na PQBJ, ele será excluído da contagem de etapas (5 jobs de 970 não têm match).</div><div class='callout tech'>A métrica de crédito mudou de ESTIMATIVA_CREDITO/SIMULACAO_CREDITO (PQBJ) para CONTRATOS_OPORTUNIDADES[estimativa]. Valores podem divergir entre as tabelas.</div><div class='footer-doc'>Recorte atual: " & vPeriodo & ". Produtos: " & FORMAT ( vTotalProdutos, "#,##0" ) & ". Empresas: " & FORMAT ( vTotalJobsCO, "#,##0" ) & ". Atualizado em " & vAtualizado & ".</div></div></details>"
					& "</div></main></div></div>"
					RETURN
						vCSS & vHTML
			```
		displayFolder: HTML
		lineageTag: f12039a5-a0eb-4967-9a5c-c2c27638806e

	/// Detalhamento operacional com CONTRATOS_OPORTUNIDADES como fonte de jobs e etapas via PQBJ.
	measure HTML_DETALHAMENTO_DIAGNOSTICO_JOURNEY_SEM_ESPACO_OCIOSO = ```
					VAR vLimiteLinhas = 750
					VAR vIntFormat = "#,##0"
					VAR vCO_Jobs = VALUES ( CONTRATOS_OPORTUNIDADES[job] )
					VAR vPQBJ_Parents = FILTER ( 'PROJECT_QBERT_JOBS', 'PROJECT_QBERT_JOBS'[JOB] IN vCO_Jobs )
					VAR vParentCodes = SELECTCOLUMNS ( vPQBJ_Parents, "@Codigo", 'PROJECT_QBERT_JOBS'[CODIGO] )
					VAR vBase = FILTER ( 'PROJECT_QBERT_JOBS', 'PROJECT_QBERT_JOBS'[PAI] IN vParentCodes && NOT ISBLANK ( 'PROJECT_QBERT_JOBS'[JOB] ) )
					VAR vRows =
						ADDCOLUMNS (
							vBase,
							"__HasProc", NOT ISBLANK ( 'PROJECT_QBERT_JOBS'[DATA_PROC_ELETRONICA] ),
							"__HasChecklist", COALESCE ( 'PROJECT_QBERT_JOBS'[CONTRATOCHECKLISTOK], 0 ) = 1 || NOT ISBLANK ( 'PROJECT_QBERT_JOBS'[CONTRATOCHECKLISTOK_DATA] ),
							"__HasOperacao", NOT ISBLANK ( 'PROJECT_QBERT_JOBS'[CODIGO_OP] ) || COALESCE ( 'PROJECT_QBERT_JOBS'[PARECER_OP], 0 ) = 1,
							"__HasReuniao", COALESCE ( 'PROJECT_QBERT_JOBS'[ATA_ASSINADA], 0 ) = 1 || NOT ISBLANK ( 'PROJECT_QBERT_JOBS'[PRAZO_ATA] ),
							"__HasDiagnostico", COALESCE ( 'PROJECT_QBERT_JOBS'[FIM], 0 ) = 1 || NOT ISBLANK ( 'PROJECT_QBERT_JOBS'[DATA_ENTREGA] ),
							"__HasCredito", COALESCE ( 'PROJECT_QBERT_JOBS'[CREDITOS_QUALIFICADOS], 0 ) = 1 || COALESCE ( 'PROJECT_QBERT_JOBS'[ESTIMATIVA_CREDITO], 0 ) > 0 || COALESCE ( 'PROJECT_QBERT_JOBS'[SIMULACAO_CREDITO], 0 ) > 0,
							"__Movimento", COALESCE ( 'PROJECT_QBERT_JOBS'[DATA_RECEBIMENTO], 'PROJECT_QBERT_JOBS'[DATA_ENTREGA], 'PROJECT_QBERT_JOBS'[DATA_CADASTRO] ),
							"__CreditoValor", MAX ( COALESCE ( 'PROJECT_QBERT_JOBS'[ESTIMATIVA_CREDITO], 0 ), COALESCE ( 'PROJECT_QBERT_JOBS'[SIMULACAO_CREDITO], 0 ) )
						)
					VAR vClassificados =
						ADDCOLUMNS (
							vRows,
							"__Stage",
								SWITCH (
									TRUE (),
									[__HasCredito], 7,
									[__HasDiagnostico], 6,
									[__HasReuniao], 5,
									[__HasOperacao], 4,
									[__HasChecklist], 3,
									[__HasProc], 2,
									1
								),
							"__Etapa",
								SWITCH (
									TRUE (),
									[__HasCredito], "Créditos",
									[__HasDiagnostico], "Diagnóstico",
									[__HasReuniao], "Reunião Tec",
									[__HasOperacao], "Operação",
									[__HasChecklist], "Checklist",
									[__HasProc], "Procuração",
									"Cadastro"
								),
							"__Acao",
								SWITCH (
									TRUE (),
									[__HasCredito], "Monitorar créditos",
									[__HasDiagnostico], "Qualificar créditos",
									[__HasReuniao], "Concluir diagnóstico",
									[__HasOperacao], "Agendar reunião técnica",
									[__HasChecklist], "Iniciar operação",
									[__HasProc], "Concluir checklist",
									"Emitir procuração"
								)
						)
					VAR vDetalhe =
						TOPN (
							vLimiteLinhas,
							vClassificados,
							[__Stage], ASC,
							[__Movimento], DESC,
							'PROJECT_QBERT_JOBS'[JOB], ASC
						)
					VAR vTotalRows = COUNTROWS ( vClassificados )
					VAR vTotalJobs = DISTINCTCOUNT ( 'PROJECT_QBERT_JOBS'[JOB] )
					VAR vAtivos = COUNTROWS ( FILTER ( vClassificados, [__Stage] < 7 ) )
					VAR vCreditos = COUNTROWS ( FILTER ( vClassificados, [__Stage] = 7 ) )
					VAR vEstimativaCO = SUM ( CONTRATOS_OPORTUNIDADES[estimativa] )
					VAR vCSS =
					"
					<style>
					:root{--bg:#080b10;--panel:rgba(14,18,24,.965);--border:rgba(213,174,119,.16);--border-soft:rgba(255,255,255,.055);--gold:#F4D9A9;--gold-2:#D5AE77;--teal:#8BE0D1;--text:#fff;--text-2:#AEB9C4;--text-3:#6E7A86;--green:#4ade80;--red:#FFB0A8;--hover:rgba(213,174,119,.08);--font:'Segoe UI',system-ui,sans-serif}
					html,body{margin:0;padding:0;width:100vw;height:100vh;background:var(--bg);font-family:var(--font);color:var(--text);overflow:hidden}*{box-sizing:border-box}
					.painel{height:calc(100vh - 20px);margin:10px;padding:24px;display:flex;flex-direction:column;border-radius:18px;border:1px solid var(--border);background:radial-gradient(circle at 0% 0%,rgba(213,174,119,.16),transparent 28%),radial-gradient(circle at 92% 4%,rgba(139,224,209,.10),transparent 28%),linear-gradient(180deg,#101923 0%,#0B1219 100%);box-shadow:0 18px 48px rgba(0,0,0,.48),inset 0 1px 0 rgba(255,255,255,.05)}
					.cabecalho{display:flex;justify-content:space-between;align-items:center;gap:18px;flex-shrink:0;padding-bottom:15px;margin-bottom:14px;border-bottom:1px solid var(--border)}.cabecalho-esquerda{display:flex;align-items:center;gap:16px;min-width:0}.btn-voltar,.btn-copiar{display:flex;align-items:center;justify-content:center;gap:7px;min-height:38px;border-radius:10px;padding:9px 15px;border:1px solid var(--border);background:rgba(213,174,119,.08);color:var(--gold);cursor:pointer;font-family:var(--font);font-size:13.8px;font-weight:950;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap}.titulo{display:flex;align-items:center;gap:11px;color:var(--gold);font-size:30px;font-weight:950;letter-spacing:.10em;text-transform:uppercase;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.titulo:before{content:'';display:inline-block;width:7px;height:28px;border-radius:6px;background:linear-gradient(180deg,var(--gold),var(--gold-2),var(--teal));box-shadow:0 0 18px rgba(213,174,119,.22)}
					.controles{display:flex;align-items:center;justify-content:flex-end;gap:12px;flex-shrink:0}.busca-global{width:390px;border-radius:10px;border:1px solid var(--border);outline:none;background:rgba(213,174,119,.055);color:#fff;font-family:var(--font);font-size:15.6px;padding:13px 18px}.busca-global:focus{width:450px;border-color:var(--gold-2);background:rgba(213,174,119,.09);box-shadow:0 0 0 3px rgba(213,174,119,.06)}
					.resumo{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;flex-shrink:0;margin-bottom:13px}.kpi{min-height:92px;position:relative;overflow:hidden;border-radius:15px;border:1px solid rgba(255,255,255,.09);background:linear-gradient(155deg,rgba(18,28,37,.96),rgba(11,18,25,.94));padding:14px 13px 12px;box-shadow:0 14px 26px rgba(0,0,0,.20),inset 0 1px 0 rgba(255,255,255,.05)}.kpi.primary{border-color:rgba(213,174,119,.38);background:linear-gradient(155deg,rgba(213,174,119,.18),rgba(18,28,37,.96) 34%,rgba(11,18,25,.96))}.kpi:before{content:'';position:absolute;left:13px;top:0;width:42px;height:4px;border-radius:0 0 9px 9px;background:linear-gradient(90deg,var(--gold),var(--teal))}.kpi-label{display:block;color:var(--text-2);font-size:10.8px;font-weight:950;letter-spacing:.08em;text-transform:uppercase;margin-bottom:7px}.kpi-value{display:block;color:var(--gold);font-size:28.8px;font-weight:950;line-height:1.05;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.kpi-note{display:block;color:var(--text-3);font-size:13px;font-weight:850;margin-top:6px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
					.table-wrapper{flex:1 1 auto;min-height:0;overflow-y:auto;overflow-x:hidden;padding-right:8px;position:relative}.table-wrapper::-webkit-scrollbar{width:8px;height:0}.table-wrapper::-webkit-scrollbar-track{background:rgba(255,255,255,.025);border-radius:999px}.table-wrapper::-webkit-scrollbar-thumb{background:rgba(213,174,119,.38);border-radius:999px}.tabela{width:100%;min-width:0;max-width:100%;table-layout:fixed;border-collapse:collapse}.tabela th{position:sticky;top:0;z-index:5;padding:12px 8px;background:#0e1218;color:var(--gold-2);border-bottom:1px solid rgba(213,174,119,.28);box-shadow:0 1px 0 var(--border);text-align:left;font-size:11.7px;font-weight:950;text-transform:uppercase;letter-spacing:.09em}.tabela td{padding:12px 8px;color:#fff;border-bottom:1px solid var(--border-soft);font-size:14px;line-height:1.32;vertical-align:middle;transition:background .18s ease}.tabela tr:hover td{background:var(--hover)}
					.col-filter{width:100%;margin-top:7px;padding:7px 8px;border-radius:6px;border:1px solid var(--border);background:rgba(0,0,0,.28);color:#fff;outline:none;font-family:var(--font);font-size:11.8px;font-weight:700}.td-job{font-weight:950;color:#F8EFE1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.td-code,.td-date,.td-num{text-align:center;color:#DCE5EE;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chip{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:5px 8px;font-size:11.9px;font-weight:950;letter-spacing:.04em;text-transform:uppercase;white-space:nowrap;border:1px solid rgba(255,255,255,.10);background:rgba(255,255,255,.045);color:var(--text-2)}.chip-cadastro,.chip-checklist{color:var(--red);border-color:rgba(255,176,168,.32);background:rgba(217,93,93,.10)}.chip-procuracao,.chip-operacao{color:var(--gold);border-color:rgba(213,174,119,.34);background:rgba(213,174,119,.10)}.chip-reuniao,.chip-diagnostico{color:var(--teal);border-color:rgba(139,224,209,.34);background:rgba(139,224,209,.09)}.chip-creditos{color:var(--green);border-color:rgba(74,222,128,.34);background:rgba(74,222,128,.08)}.empty{text-align:center;padding:46px!important;color:var(--text-3)!important;font-size:17.5px!important}.tabela tfoot td{position:sticky;bottom:-1px;z-index:5;background:#0e1218;border-top:2px solid var(--gold-2);border-bottom:none;color:var(--gold);font-size:15px;font-weight:950;letter-spacing:.06em;text-transform:uppercase}.count-destaque{display:inline-flex;align-items:center;justify-content:center;min-width:44px;margin-left:8px;padding:5px 10px;border-radius:8px;border:1px solid var(--gold-2);background:rgba(213,174,119,.18);color:#fff;font-size:20px;font-weight:950}
					@media(max-width:1500px){.tabela th{font-size:10.5px;padding:10px 6px}.tabela td{font-size:12.8px;padding:10px 6px}.chip{font-size:9.6px;padding:4px 6px}.col-filter{font-size:10.5px;padding:6px 6px}.resumo{grid-template-columns:repeat(5,minmax(180px,1fr));overflow-x:auto}}
					</style>
					"
					VAR vJS =
					"
					<script>
					function safeText(selector,row){var el=row.querySelector(selector);return el?el.textContent.toLowerCase():'';}
					function filtrarTabela(){var q=document.getElementById('buscaGlobal').value.toLowerCase();var qJ=document.getElementById('buscaColJob').value.toLowerCase();var qE=document.getElementById('buscaColEtapa').value.toLowerCase();var rows=document.querySelectorAll('.linha-detalhe');var count=0;for(var i=0;i<rows.length;i++){var t=rows[i].textContent.toLowerCase();var tJ=safeText('.td-job',rows[i]);var tE=safeText('.td-etapa',rows[i]);var ok=(q===''||t.indexOf(q)>-1)&&tJ.indexOf(qJ)>-1&&tE.indexOf(qE)>-1;if(ok){rows[i].style.display='';count++;}else{rows[i].style.display='none';}}var countEl=document.getElementById('totalJobsCount');if(countEl){countEl.textContent=count;}}
					setTimeout(filtrarTabela,100);
					function copiarTabela(){var btn=document.getElementById('btnCopiar');var originalText=btn.innerHTML;btn.innerHTML='&#8982; Copiando...';var textToCopy='';var ths=document.querySelectorAll('.tabela thead th');for(var i=0;i<ths.length;i++){var span=ths[i].querySelector('span');var thText=span?span.textContent.trim():ths[i].textContent.trim();textToCopy+=thText+(i===ths.length-1?'\n':'\t');}var rows=document.querySelectorAll('.linha-detalhe');var copiedCount=0;for(var r=0;r<rows.length;r++){if(rows[r].style.display!=='none'){var tds=rows[r].querySelectorAll('td');for(var j=0;j<tds.length;j++){var cellText=tds[j].textContent.trim().replace(/\s+/g,' ');textToCopy+=cellText+(j===tds.length-1?'\n':'\t');}copiedCount++;}}try{var textArea=document.createElement('textarea');textArea.value=textToCopy;textArea.style.position='fixed';textArea.style.opacity='0';document.body.appendChild(textArea);textArea.focus();textArea.select();var successful=document.execCommand('copy');document.body.removeChild(textArea);if(successful){btn.innerHTML='&#10004; Copiado ('+copiedCount+' linhas)';btn.style.borderColor='var(--green)';btn.style.color='var(--green)';setTimeout(function(){btn.innerHTML=originalText;btn.style.borderColor='var(--border)';btn.style.color='var(--gold)';},3000);}else{throw new Error('copy failed');}}catch(err){btn.innerHTML='&#10060; Erro ao copiar';setTimeout(function(){btn.innerHTML=originalText;},3000);}}
					</script>
					"
					VAR vLinhas =
						CONCATENATEX (
							vDetalhe,
							VAR vEtapa = [__Etapa]
							VAR vClass =
								"chip-" &
								SWITCH (
									[__Stage],
									1, "cadastro",
									2, "procuracao",
									3, "checklist",
									4, "operacao",
									5, "reuniao",
									6, "diagnostico",
									"creditos"
								)
							RETURN
								"<tr class='linha-detalhe'>"
									& "<td class='td-job'>" & 'PROJECT_QBERT_JOBS'[JOB] & "</td>"
									& "<td class='td-etapa'><span class='chip " & vClass & "'>" & vEtapa & "</span></td>"
									& "<td>" & [__Acao] & "</td>"
									& "<td class='td-code'>" & FORMAT ( 'PROJECT_QBERT_JOBS'[CODIGO], "0" ) & "</td>"
									& "<td class='td-code'>" & FORMAT ( 'PROJECT_QBERT_JOBS'[PAI], "0" ) & "</td>"
									& "<td class='td-code'>" & FORMAT ( 'PROJECT_QBERT_JOBS'[CODIGO_PRODUTO], "0" ) & "</td>"
									& "<td class='td-date'>" & IF ( ISBLANK ( 'PROJECT_QBERT_JOBS'[DATA_CADASTRO] ), "-", FORMAT ( 'PROJECT_QBERT_JOBS'[DATA_CADASTRO], "dd/MM/yyyy" ) ) & "</td>"
									& "<td class='td-date'>" & IF ( ISBLANK ( [__Movimento] ), "-", FORMAT ( [__Movimento], "dd/MM/yyyy" ) ) & "</td>"
									& "<td class='td-num'>" & FORMAT ( [__CreditoValor], "R$ #,##0" ) & "</td>"
								& "</tr>",
							"",
							[__Stage], ASC,
							[__Movimento], DESC
						)
					VAR vAvisoLimite =
						IF (
							vTotalRows > vLimiteLinhas,
							" · exibindo " & FORMAT ( vLimiteLinhas, vIntFormat ) & " de " & FORMAT ( vTotalRows, vIntFormat ) & " registros; use slicers para reduzir o recorte",
							""
						)
					VAR vHTML =
						"<html><head><meta charset='UTF-8'>" & vCSS & "</head><body>"
							& "<div class='painel'><div class='cabecalho'><div class='cabecalho-esquerda'><button class='btn-voltar'>&#8592; Voltar</button><div class='titulo'>Detalhamento Diagnóstico - Journey</div></div><div class='controles'><input class='busca-global' id='buscaGlobal' type='text' placeholder='Busca nos registros carregados...' oninput='filtrarTabela()'><button id='btnCopiar' class='btn-copiar' onclick='copiarTabela()' title='Copia a tabela filtrada para colar no Excel'>&#128203; Copiar tabela</button></div></div>"
							& "<div class='resumo'><div class='kpi primary'><span class='kpi-label'>Registros</span><span class='kpi-value'>" & FORMAT ( vTotalRows, vIntFormat ) & "</span><span class='kpi-note'>Base PQBJ" & vAvisoLimite & "</span></div><div class='kpi'><span class='kpi-label'>Jobs</span><span class='kpi-value'>" & FORMAT ( vTotalJobs, vIntFormat ) & "</span><span class='kpi-note'>JOB distinto</span></div><div class='kpi'><span class='kpi-label'>Em andamento</span><span class='kpi-value'>" & FORMAT ( vAtivos, vIntFormat ) & "</span><span class='kpi-note'>Antes de créditos</span></div><div class='kpi'><span class='kpi-label'>Créditos</span><span class='kpi-value'>" & FORMAT ( vCreditos, vIntFormat ) & "</span><span class='kpi-note'>Etapa final</span></div><div class='kpi'><span class='kpi-label'>Estimativa CO</span><span class='kpi-value'>" & FORMAT ( vEstimativaCO, "R$ #,##0" ) & "</span><span class='kpi-note'>CONTRATOS_OPORTUNIDADES</span></div></div>"
							& "<div class='table-wrapper'><table class='tabela'><thead><tr><th style='width:14%'><div style='display:flex;flex-direction:column'><span>Job</span><input id='buscaColJob' class='col-filter' type='text' placeholder='Filtrar...' oninput='filtrarTabela()'></div></th><th style='width:12%'><div style='display:flex;flex-direction:column'><span>Etapa</span><input id='buscaColEtapa' class='col-filter' type='text' placeholder='Filtrar...' oninput='filtrarTabela()'></div></th><th style='width:18%'><span>Ação sugerida</span></th><th style='width:8%;text-align:center'><span>Código</span></th><th style='width:8%;text-align:center'><span>Pai</span></th><th style='width:9%;text-align:center'><span>Produto</span></th><th style='width:10%;text-align:center'><span>Cadastro</span></th><th style='width:10%;text-align:center'><span>Últ. mov.</span></th><th style='width:11%;text-align:center'><span>Crédito</span></th></tr></thead><tbody id='tbodyDetalhe'>"
							& IF ( ISBLANK ( vLinhas ), "<tr><td colspan='9' class='empty'>Nenhum registro encontrado com os filtros atuais.</td></tr>", vLinhas )
							& "</tbody><tfoot><tr><td colspan='9' style='text-align:right'>Total visível após filtros: <span class='count-destaque' id='totalJobsCount'>0</span> de " & FORMAT ( vTotalRows, vIntFormat ) & " no período</td></tr></tfoot></table></div></div>"
							& vJS
						& "</body></html>"
					RETURN
						vHTML
			```
		displayFolder: HTML
		lineageTag: 7cc4cf4f-59eb-4360-8f7e-9a14c4534d03

	/// Visual principal com 8 colunas: PRODUTOS + 7 etapas. Journey 360 como base para stages e cards.
	measure 'HTML Diagnóstico Journey | Visual Principal' = ```
					VAR vIntFormat = "#,##0"
					VAR vPctFormat = "0.0%"
					VAR vTopProdutos = 30
					VAR vTopFilhos = 10
					VAR vCalendarStart = MIN ( 'dCalendar'[Date] )
					VAR vCalendarEnd = MAX ( 'dCalendar'[Date] )
					VAR vHasCalendarFilter =
						ISFILTERED ( 'dCalendar'[Date] )
							|| ISFILTERED ( 'dCalendar'[YearMonthName] )
							|| ISFILTERED ( 'dCalendar'[YearMonth] )
							|| ISFILTERED ( 'dCalendar'[MonthNumber] )
							|| ISFILTERED ( 'dCalendar'[Year] )
					VAR vPeriodo =
						IF (
							vHasCalendarFilter,
							FORMAT ( vCalendarStart, "dd/MM/yyyy" ) & " a " & FORMAT ( vCalendarEnd, "dd/MM/yyyy" ),
							"Todo o período"
						)
					VAR vCO_Jobs = VALUES ( CONTRATOS_OPORTUNIDADES[job] )
					VAR vJourneyParents =
						FILTER (
							'PROJECT_QBERT_JOBS',
							'PROJECT_QBERT_JOBS'[JOB] IN vCO_Jobs
								&& 'PROJECT_QBERT_JOBS'[CODIGO_PRODUTO] = 360
								&& COALESCE ( 'PROJECT_QBERT_JOBS'[FIM], 0 ) = 1
								&& (
									NOT vHasCalendarFilter
										|| (
											'PROJECT_QBERT_JOBS'[DATA_CADASTRO] >= vCalendarStart
												&& 'PROJECT_QBERT_JOBS'[DATA_CADASTRO] < vCalendarEnd + 1
										)
								)
						)
					VAR vParentCodes = SELECTCOLUMNS ( vJourneyParents, "@Codigo", 'PROJECT_QBERT_JOBS'[CODIGO] )
					VAR vAllChildren = FILTER ( 'PROJECT_QBERT_JOBS', 'PROJECT_QBERT_JOBS'[PAI] IN vParentCodes )
					VAR vChildrenFlags =
						ADDCOLUMNS (
							vAllChildren,
							"__HasProc", NOT ISBLANK ( 'PROJECT_QBERT_JOBS'[DATA_PROC_ELETRONICA] ),
							"__HasChecklist", COALESCE ( 'PROJECT_QBERT_JOBS'[CONTRATOCHECKLISTOK], 0 ) = 1 || NOT ISBLANK ( 'PROJECT_QBERT_JOBS'[CONTRATOCHECKLISTOK_DATA] ),
							"__HasOperacao", NOT ISBLANK ( 'PROJECT_QBERT_JOBS'[CODIGO_OP] ) || COALESCE ( 'PROJECT_QBERT_JOBS'[PARECER_OP], 0 ) = 1,
							"__HasReuniao", COALESCE ( 'PROJECT_QBERT_JOBS'[ATA_ASSINADA], 0 ) = 1 || NOT ISBLANK ( 'PROJECT_QBERT_JOBS'[PRAZO_ATA] ),
							"__HasDiagnostico", COALESCE ( 'PROJECT_QBERT_JOBS'[FIM], 0 ) = 1 || NOT ISBLANK ( 'PROJECT_QBERT_JOBS'[DATA_ENTREGA] ),
							"__HasCredito", COALESCE ( 'PROJECT_QBERT_JOBS'[CREDITOS_QUALIFICADOS], 0 ) = 1 || COALESCE ( 'PROJECT_QBERT_JOBS'[ESTIMATIVA_CREDITO], 0 ) > 0 || COALESCE ( 'PROJECT_QBERT_JOBS'[SIMULACAO_CREDITO], 0 ) > 0,
							"__Move", COALESCE ( 'PROJECT_QBERT_JOBS'[DATA_RECEBIMENTO], 'PROJECT_QBERT_JOBS'[DATA_ENTREGA], 'PROJECT_QBERT_JOBS'[DATA_CADASTRO] ),
							"__PAI_Code", 'PROJECT_QBERT_JOBS'[PAI]
						)
					VAR vChildrenStages =
						ADDCOLUMNS (
							vChildrenFlags,
							"__Stage",
								SWITCH (
									TRUE (),
									[__HasCredito], 7,
									[__HasDiagnostico], 6,
									[__HasReuniao], 5,
									[__HasOperacao], 4,
									[__HasChecklist], 3,
									[__HasProc], 2,
									1
								),
							"__StageName",
								SWITCH (
									[__HasCredito], "CRÉDITOS",
									[__HasDiagnostico], "DIAGNÓSTICO",
									[__HasReuniao], "REUNIÃO TEC",
									[__HasOperacao], "OPERAÇÃO",
									[__HasChecklist], "CHECKLIST",
									[__HasProc], "PROCURAÇÃO",
									"CADASTRO"
								)
						)
					VAR vEmpresas = DISTINCTCOUNT ( CONTRATOS_OPORTUNIDADES[job] )
					VAR vTotalJobs = COUNTROWS ( vAllChildren )
					VAR vJobsAtivos = COUNTROWS ( FILTER ( vAllChildren, COALESCE ( 'PROJECT_QBERT_JOBS'[FIM], 0 ) <> 1 ) )
					VAR vTotalOportunidades = DISTINCTCOUNT ( CONTRATOS_OPORTUNIDADES[oportunidade] )
					VAR vEstimativaCO = SUM ( CONTRATOS_OPORTUNIDADES[estimativa] )
					VAR vCadastro = COUNTROWS ( FILTER ( vChildrenStages, [__Stage] = 1 ) )
					VAR vProcuracao = COUNTROWS ( FILTER ( vChildrenStages, [__Stage] = 2 ) )
					VAR vChecklist = COUNTROWS ( FILTER ( vChildrenStages, [__Stage] = 3 ) )
					VAR vOperacao = COUNTROWS ( FILTER ( vChildrenStages, [__Stage] = 4 ) )
					VAR vReuniao = COUNTROWS ( FILTER ( vChildrenStages, [__Stage] = 5 ) )
					VAR vDiagnostico = COUNTROWS ( FILTER ( vChildrenStages, [__Stage] = 6 ) )
					VAR vCreditos = COUNTROWS ( FILTER ( vChildrenStages, [__Stage] = 7 ) )
					VAR vJobToParent = SELECTCOLUMNS ( vJourneyParents, "@Job", 'PROJECT_QBERT_JOBS'[JOB], "@Codigo", 'PROJECT_QBERT_JOBS'[CODIGO] )
					VAR vProductList = SUMMARIZE ( CONTRATOS_OPORTUNIDADES, CONTRATOS_OPORTUNIDADES[oportunidade] )
					VAR vTotalProdutos = COUNTROWS ( vProductList )
					VAR vProductSummary =
						ADDCOLUMNS (
							vProductList,
							"@Estimativa", CALCULATE ( SUM ( CONTRATOS_OPORTUNIDADES[estimativa] ) ),
							"@JobsCO", CALCULATE ( DISTINCTCOUNT ( CONTRATOS_OPORTUNIDADES[job] ) ),
							"@PQBJ_Match",
								VAR vProd = CONTRATOS_OPORTUNIDADES[oportunidade]
								VAR vCOJobsForProd = CALCULATETABLE ( VALUES ( CONTRATOS_OPORTUNIDADES[job] ), CONTRATOS_OPORTUNIDADES[oportunidade] = vProd )
								VAR vCodes = SELECTCOLUMNS ( FILTER ( vJobToParent, [@Job] IN vCOJobsForProd ), "@c", [@Codigo] )
								RETURN COUNTROWS ( FILTER ( vChildrenStages, [__PAI_Code] IN vCodes ) ),
							"@Cadastro",
								VAR vProd = CONTRATOS_OPORTUNIDADES[oportunidade]
								VAR vCOJobsForProd = CALCULATETABLE ( VALUES ( CONTRATOS_OPORTUNIDADES[job] ), CONTRATOS_OPORTUNIDADES[oportunidade] = vProd )
								VAR vCodes = SELECTCOLUMNS ( FILTER ( vJobToParent, [@Job] IN vCOJobsForProd ), "@c", [@Codigo] )
								RETURN COUNTROWS ( FILTER ( vChildrenStages, [__PAI_Code] IN vCodes && [__Stage] = 1 ) ),
							"@Procuracao",
								VAR vProd = CONTRATOS_OPORTUNIDADES[oportunidade]
								VAR vCOJobsForProd = CALCULATETABLE ( VALUES ( CONTRATOS_OPORTUNIDADES[job] ), CONTRATOS_OPORTUNIDADES[oportunidade] = vProd )
								VAR vCodes = SELECTCOLUMNS ( FILTER ( vJobToParent, [@Job] IN vCOJobsForProd ), "@c", [@Codigo] )
								RETURN COUNTROWS ( FILTER ( vChildrenStages, [__PAI_Code] IN vCodes && [__Stage] = 2 ) ),
							"@Checklist",
								VAR vProd = CONTRATOS_OPORTUNIDADES[oportunidade]
								VAR vCOJobsForProd = CALCULATETABLE ( VALUES ( CONTRATOS_OPORTUNIDADES[job] ), CONTRATOS_OPORTUNIDADES[oportunidade] = vProd )
								VAR vCodes = SELECTCOLUMNS ( FILTER ( vJobToParent, [@Job] IN vCOJobsForProd ), "@c", [@Codigo] )
								RETURN COUNTROWS ( FILTER ( vChildrenStages, [__PAI_Code] IN vCodes && [__Stage] = 3 ) ),
							"@Operacao",
								VAR vProd = CONTRATOS_OPORTUNIDADES[oportunidade]
								VAR vCOJobsForProd = CALCULATETABLE ( VALUES ( CONTRATOS_OPORTUNIDADES[job] ), CONTRATOS_OPORTUNIDADES[oportunidade] = vProd )
								VAR vCodes = SELECTCOLUMNS ( FILTER ( vJobToParent, [@Job] IN vCOJobsForProd ), "@c", [@Codigo] )
								RETURN COUNTROWS ( FILTER ( vChildrenStages, [__PAI_Code] IN vCodes && [__Stage] = 4 ) ),
							"@Reuniao",
								VAR vProd = CONTRATOS_OPORTUNIDADES[oportunidade]
								VAR vCOJobsForProd = CALCULATETABLE ( VALUES ( CONTRATOS_OPORTUNIDADES[job] ), CONTRATOS_OPORTUNIDADES[oportunidade] = vProd )
								VAR vCodes = SELECTCOLUMNS ( FILTER ( vJobToParent, [@Job] IN vCOJobsForProd ), "@c", [@Codigo] )
								RETURN COUNTROWS ( FILTER ( vChildrenStages, [__PAI_Code] IN vCodes && [__Stage] = 5 ) ),
							"@Diagnostico",
								VAR vProd = CONTRATOS_OPORTUNIDADES[oportunidade]
								VAR vCOJobsForProd = CALCULATETABLE ( VALUES ( CONTRATOS_OPORTUNIDADES[job] ), CONTRATOS_OPORTUNIDADES[oportunidade] = vProd )
								VAR vCodes = SELECTCOLUMNS ( FILTER ( vJobToParent, [@Job] IN vCOJobsForProd ), "@c", [@Codigo] )
								RETURN COUNTROWS ( FILTER ( vChildrenStages, [__PAI_Code] IN vCodes && [__Stage] = 6 ) ),
							"@Creditos",
								VAR vProd = CONTRATOS_OPORTUNIDADES[oportunidade]
								VAR vCOJobsForProd = CALCULATETABLE ( VALUES ( CONTRATOS_OPORTUNIDADES[job] ), CONTRATOS_OPORTUNIDADES[oportunidade] = vProd )
								VAR vCodes = SELECTCOLUMNS ( FILTER ( vJobToParent, [@Job] IN vCOJobsForProd ), "@c", [@Codigo] )
								RETURN COUNTROWS ( FILTER ( vChildrenStages, [__PAI_Code] IN vCodes && [__Stage] = 7 ) )
						)
					VAR vProductTop =
						TOPN ( vTopProdutos, FILTER ( vProductSummary, [@PQBJ_Match] > 0 ), [@PQBJ_Match], DESC, [@Estimativa], DESC, CONTRATOS_OPORTUNIDADES[oportunidade], ASC )
					VAR vCSS =
					"
					<style>
					.diag-wrap{font-family:'Segoe UI',Arial,sans-serif;width:100%;height:calc(100vh - 2px);box-sizing:border-box;color:#E8EEF5;background:radial-gradient(circle at top left,rgba(213,174,119,.18),transparent 32%),linear-gradient(135deg,#101923 0%,#0B1219 100%);border:1px solid rgba(213,174,119,.28);border-radius:18px;overflow:auto;box-shadow:0 18px 48px rgba(0,0,0,.34);scrollbar-width:thin;scrollbar-color:rgba(213,174,119,.48) rgba(6,11,16,.96)}
					.diag-wrap::-webkit-scrollbar{width:13px;height:10px}.diag-wrap::-webkit-scrollbar-track{background:linear-gradient(180deg,#060B10 0%,#0B1219 100%);border-left:1px solid rgba(213,174,119,.10);border-radius:999px}.diag-wrap::-webkit-scrollbar-thumb{background:linear-gradient(180deg,rgba(213,174,119,.58),rgba(17,28,35,.96));border:3px solid #060B10;border-radius:999px;box-shadow:inset 0 1px 0 rgba(255,255,255,.08)}
					.sticky{position:sticky;top:0;z-index:60;background:rgba(11,18,25,.98);border-bottom:1px solid rgba(213,174,119,.18);box-shadow:0 16px 30px rgba(0,0,0,.36);overflow:visible}.diag-head{padding:20px 24px 28px;overflow:visible}.slicer-space{height:64px;width:100%;margin-bottom:8px;display:flex;align-items:flex-start;justify-content:flex-end;padding-top:2px}.doc-button{position:relative;display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:12px 20px 12px 18px;border-radius:14px;color:#081018;border:1px solid rgba(244,217,169,.72);background:linear-gradient(135deg,#F4D9A9 0%,#D5AE77 48%,#8BE0D1 100%);box-shadow:0 14px 28px rgba(213,174,119,.24),0 0 0 1px rgba(255,255,255,.08) inset,0 0 22px rgba(139,224,209,.18);font-size:13px;font-weight:950;letter-spacing:.10em;text-transform:uppercase;white-space:nowrap;overflow:hidden}.doc-button:before{content:'\25A6';display:inline-flex;align-items:center;justify-content:center;width:22px;height:22px;margin-right:9px;border-radius:8px;background:rgba(8,16,24,.18);border:1px solid rgba(8,16,24,.22);font-size:12px;line-height:1;color:#081018;font-weight:950}.doc-button:after{content:'';position:absolute;inset:-1px;border-radius:14px;background:linear-gradient(90deg,transparent,rgba(255,255,255,.45),transparent);transform:translateX(-120%);animation:shineDetalhe 3.6s ease-in-out infinite}@keyframes shineDetalhe{0%{transform:translateX(-120%)}48%{transform:translateX(-120%)}72%{transform:translateX(120%)}100%{transform:translateX(120%)}}
					.diag-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;margin-top:0;position:relative;z-index:90;overflow:visible}.kpi-card{position:relative;min-width:0;padding:21px 18px 18px;border-radius:20px;background:linear-gradient(160deg,rgba(18,28,37,.96),rgba(11,18,25,.94));border:1px solid rgba(255,255,255,.10);overflow:visible;box-shadow:0 18px 32px rgba(0,0,0,.24),inset 0 1px 0 rgba(255,255,255,.06);transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.kpi-card.primary{background:linear-gradient(155deg,rgba(213,174,119,.18),rgba(18,28,37,.96) 36%,rgba(11,18,25,.96));border-color:rgba(213,174,119,.42)}.kpi-card.attention{background:linear-gradient(155deg,rgba(139,224,209,.08),rgba(18,28,37,.96) 34%,rgba(11,18,25,.96));border-color:rgba(139,224,209,.30)}.kpi-card:before{content:'';position:absolute;left:16px;top:0;width:46px;height:4px;border-radius:0 0 10px 10px;background:linear-gradient(90deg,#F4D9A9,#8BE0D1);opacity:.92}.kpi-card:hover{transform:translateY(-2px);border-color:rgba(213,174,119,.34);box-shadow:0 22px 40px rgba(0,0,0,.28),0 0 0 1px rgba(213,174,119,.08),inset 0 1px 0 rgba(255,255,255,.08)}.kpi-card[data-tip]:hover:after{content:attr(data-tip);position:absolute;left:14px;right:14px;top:calc(100% + 12px);padding:11px 12px;border-radius:12px;background:linear-gradient(160deg,rgba(7,13,18,.98),rgba(12,22,29,.98));border:1px solid rgba(213,174,119,.34);color:#E8EEF5;font-size:11.5px;font-weight:820;line-height:1.35;box-shadow:0 16px 32px rgba(0,0,0,.34);z-index:999;white-space:normal;pointer-events:none}.kpi-label{color:#AEB9C4;font-size:12px;font-weight:950;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.kpi-value{margin-top:10px;color:#F4D9A9;font-size:32px;font-weight:950;line-height:1.05;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.kpi-caption{margin-top:9px;color:#8B98A6;font-size:13px;font-weight:850;line-height:1.25}
					.table-head{display:grid;grid-template-columns:210px repeat(7,minmax(115px,1fr));min-width:1600px;background:#121C25;border-bottom:1px solid rgba(213,174,119,.20)}.table-head div{padding:16px 10px;color:#D5AE77;font-size:13px;font-weight:950;text-transform:uppercase;letter-spacing:.07em;text-align:center}.rows{min-width:1600px}.diag-row{border-bottom:1px solid rgba(255,255,255,.055)}.diag-row summary{list-style:none;cursor:pointer}.diag-row summary::-webkit-details-marker{display:none}.journey-title{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:15px 18px 10px;background:rgba(255,255,255,.018)}.title-line{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.row-title{color:#F8EFE1;font-size:17px;font-weight:950;line-height:1.2}.row-sub{margin-top:5px;color:#9FAAB5;font-size:13px;font-weight:820}.badge{display:inline-flex;align-items:center;padding:6px 10px;border-radius:999px;font-size:11px;font-weight:950;text-transform:uppercase;letter-spacing:.04em;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.055)}.badge.good{color:#8BE0D1;border-color:rgba(139,224,209,.30);background:rgba(139,224,209,.08)}.badge.attention{color:#F4D9A9;border-color:rgba(213,174,119,.34);background:rgba(213,174,119,.10)}.prod-title{display:flex;flex-direction:column;justify-content:center;align-items:center;gap:5px;min-height:96px;padding:13px 10px;text-align:center;border-left:1px solid rgba(255,255,255,.05)}.prod-title:first-child{border-left:none}.prod-title b{color:#F4D9A9;font-size:14px;font-weight:950}.prod-title small{color:#8796A5;font-size:10px;font-weight:850;text-transform:uppercase;letter-spacing:.04em}.stage-grid{display:grid;grid-template-columns:210px repeat(7,minmax(115px,1fr));align-items:stretch;transition:all .18s ease}.stage-grid:hover{background:rgba(213,174,119,.08)}.stage-cell{display:flex;flex-direction:column;justify-content:center;align-items:center;gap:6px;min-height:96px;padding:13px 10px;text-align:center;border-left:1px solid rgba(255,255,255,.05)}.stage-cell:first-child{border-left:none}.stage-cell b{color:#E8EEF5;font-size:22px;font-weight:950}.stage-cell small{color:#8B98A6;font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.05em}.stage-cell.creditos b{color:#8BE0D1}.mini-progress{width:78%;height:8px;border-radius:999px;background:rgba(255,255,255,.07);overflow:hidden}.mini-progress span{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,#D5AE77,#8BE0D1)}
					.detail-box{display:grid;grid-template-columns:1.3fr .9fr;gap:16px;padding:16px 18px 20px;background:rgba(2,7,12,.38);border-top:1px solid rgba(213,174,119,.12)}.detail-card{border:1px solid rgba(213,174,119,.16);background:rgba(255,255,255,.035);border-radius:15px;padding:14px;min-width:0}.detail-title{color:#F4D9A9;font-size:13px;font-weight:950;letter-spacing:.06em;text-transform:uppercase;margin-bottom:12px}.cmp-head,.cmp-row{display:grid;grid-template-columns:1.2fr .7fr .7fr .7fr 1.2fr;gap:8px;align-items:center}.cmp-head{color:#D5AE77;font-size:11px;font-weight:950;text-transform:uppercase;letter-spacing:.06em;padding-bottom:8px;border-bottom:1px solid rgba(213,174,119,.16)}.cmp-row{min-height:34px;border-bottom:1px solid rgba(255,255,255,.045);color:#DCE5EE;font-size:12.5px;font-weight:850}.cmp-row:last-child{border-bottom:none}.cmp-val,.cmp-pct{text-align:right}.cmp-bar{height:8px;border-radius:999px;background:rgba(255,255,255,.07);overflow:hidden}.cmp-bar span{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,#D5AE77,#8BE0D1)}.pill-wrap{display:flex;flex-wrap:wrap;gap:8px}.pill{display:inline-flex;align-items:center;gap:6px;border:1px solid rgba(213,174,119,.18);background:rgba(213,174,119,.07);color:#E8EEF5;border-radius:999px;padding:7px 10px;font-size:12px;font-weight:850}.pill.pass{border-color:rgba(139,224,209,.26);background:rgba(139,224,209,.08);color:#8BE0D1}.empty-state{margin:24px;padding:34px;border:1px dashed rgba(213,174,119,.28);border-radius:16px;color:#AEB9C4;text-align:center;font-weight:900}.foot-note{padding:12px 24px 24px;color:#6E7A86;font-size:12px;font-weight:820}
					@media(max-width:900px){.diag-kpis{grid-template-columns:repeat(4,minmax(210px,1fr));overflow-x:auto}.detail-box{grid-template-columns:1fr}}
					</style>
					"
					VAR vCards =
						"<div class='diag-kpis qbert-kpis'>"
							& "<div class='kpi-card primary' data-tip='Empresas distintas com oportunidade na tabela CONTRATOS_OPORTUNIDADES.'><div class='kpi-label'>Empresas</div><div class='kpi-value'>" & FORMAT ( vEmpresas, vIntFormat ) & "</div><div class='kpi-caption'>JOBS na CO · " & vPeriodo & "</div></div>"
							& "<div class='kpi-card primary' data-tip='Total de jobs filhos dos Journey 360 (CODIGO_PRODUTO=360, FIM=1) no período.'><div class='kpi-label'>Jobs Totais</div><div class='kpi-value'>" & FORMAT ( vTotalJobs, vIntFormat ) & "</div><div class='kpi-caption'>Filhos Journey 360</div></div>"
							& "<div class='kpi-card attention' data-tip='Jobs ativos: filhos com FIM diferente de 1.'><div class='kpi-label'>Jobs Ativos</div><div class='kpi-value'>" & FORMAT ( vJobsAtivos, vIntFormat ) & "</div><div class='kpi-caption'>FIM diferente de 1</div></div>"
							& "<div class='kpi-card' data-tip='Número de oportunidades distintas na tabela CONTRATOS_OPORTUNIDADES.'><div class='kpi-label'>Oportunidades</div><div class='kpi-value'>" & FORMAT ( vTotalOportunidades, vIntFormat ) & "</div><div class='kpi-caption'>Produtos TAX distintos</div></div>"
						& "</div>"
					VAR vTabelaHead =
						"<div class='table-head'><div>PRODUTOS</div><div>CADASTRO</div><div>PROCURAÇÃO</div><div>CHECKLIST</div><div>OPERAÇÃO</div><div>REUNIÃO TEC</div><div>DIAGNÓSTICO</div><div>CRÉDITOS</div></div>"
					VAR vRows =
						CONCATENATEX (
							vProductTop,
							VAR vProduto = CONTRATOS_OPORTUNIDADES[oportunidade]
							VAR vEstimativa = [@Estimativa]
							VAR vTotalLinha = [@PQBJ_Match]
							VAR vJobsCO = [@JobsCO]
							VAR vStageLine =
								UNION (
									ROW ( "Ordem", 1, "Etapa", "CADASTRO", "Qtd", [@Cadastro], "Total", vCadastro, "Class", "cadastro" ),
									ROW ( "Ordem", 2, "Etapa", "PROCURAÇÃO", "Qtd", [@Procuracao], "Total", vProcuracao, "Class", "procuracao" ),
									ROW ( "Ordem", 3, "Etapa", "CHECKLIST", "Qtd", [@Checklist], "Total", vChecklist, "Class", "checklist" ),
									ROW ( "Ordem", 4, "Etapa", "OPERAÇÃO", "Qtd", [@Operacao], "Total", vOperacao, "Class", "operacao" ),
									ROW ( "Ordem", 5, "Etapa", "REUNIÃO TEC", "Qtd", [@Reuniao], "Total", vReuniao, "Class", "reuniao" ),
									ROW ( "Ordem", 6, "Etapa", "DIAGNÓSTICO", "Qtd", [@Diagnostico], "Total", vDiagnostico, "Class", "diagnostico" ),
									ROW ( "Ordem", 7, "Etapa", "CRÉDITOS", "Qtd", [@Creditos], "Total", vCreditos, "Class", "creditos" )
								)
							VAR vProdCell =
								"<div class='prod-title'><b>" & vProduto & "</b><small>" & FORMAT ( vJobsCO, vIntFormat ) & " empresas · " & FORMAT ( vTotalLinha, vIntFormat ) & " jobs</small></div>"
							VAR vStageCells =
								CONCATENATEX (
									vStageLine,
									VAR vPctLinha = DIVIDE ( [Qtd], vTotalLinha, 0 )
									VAR vBar = MAX ( 2, ROUND ( vPctLinha * 100, 0 ) )
									RETURN
										"<div class='stage-cell " & [Class] & "'><b>" & FORMAT ( [Qtd], vIntFormat ) & "</b><small>" & FORMAT ( vPctLinha, vPctFormat ) & " dos jobs</small><div class='mini-progress'><span style='width:" & FORMAT ( vBar, "0" ) & "%'></span></div></div>",
									"",
									[Ordem], ASC
								)
							VAR vComparativo =
								CONCATENATEX (
									vStageLine,
									VAR vPctTotal = DIVIDE ( [Qtd], [Total], 0 )
									VAR vBarTotal = MAX ( 2, ROUND ( vPctTotal * 100, 0 ) )
									RETURN
										"<div class='cmp-row'><div>" & [Etapa] & "</div><div class='cmp-val'>" & FORMAT ( [Qtd], vIntFormat ) & "</div><div class='cmp-val'>" & FORMAT ( [Total], vIntFormat ) & "</div><div class='cmp-pct'>" & FORMAT ( vPctTotal, vPctFormat ) & "</div><div class='cmp-bar'><span style='width:" & FORMAT ( vBarTotal, "0" ) & "%'></span></div></div>",
									"",
									[Ordem], ASC
								)
							VAR vCOJobsForProduct = CALCULATETABLE ( VALUES ( CONTRATOS_OPORTUNIDADES[job] ), CONTRATOS_OPORTUNIDADES[oportunidade] = vProduto )
							VAR vPCodes = SELECTCOLUMNS ( FILTER ( vJobToParent, [@Job] IN vCOJobsForProduct ), "@c", [@Codigo] )
							VAR vFilhosTop =
								TOPN ( vTopFilhos, FILTER ( vChildrenStages, [__PAI_Code] IN vPCodes ), [__Move], DESC, 'PROJECT_QBERT_JOBS'[CODIGO], ASC )
							VAR vFilhosHTML =
								CONCATENATEX (
									vFilhosTop,
									"<span class='pill'><b>" & 'PROJECT_QBERT_JOBS'[JOB] & "</b> " & [__StageName] & "</span>",
									"",
									[__Move], DESC
								)
							RETURN
								"<details class='diag-row'><summary><div class='journey-title'><div><div class='title-line'><span class='row-title'>" & vProduto & "</span><span class='badge good'>" & FORMAT ( vJobsCO, vIntFormat ) & " empresas</span><span class='badge attention'>" & FORMAT ( vTotalLinha, vIntFormat ) & " jobs</span></div><div class='row-sub'>Créd. estimado " & FORMAT ( vEstimativa, "R$ #,##0" ) & " · " & FORMAT ( DIVIDE ( [@Creditos], vTotalLinha, 0 ), vPctFormat ) & " em créditos</div></div><span class='badge'>Expandir</span></div><div class='stage-grid'>" & vProdCell & vStageCells & "</div></summary><div class='detail-box'><div class='detail-card'><div class='detail-title'>Comparativo: " & vProduto & " vs total geral</div><div class='cmp-head'><div>Etapa</div><div>Produto</div><div>Total</div><div>% Total</div><div></div></div>" & vComparativo & "</div><div class='detail-card'><div class='detail-title'>Jobs recentes do produto</div><div class='pill-wrap'>" & IF ( ISBLANK ( vFilhosHTML ), "<span class='pill'>Sem jobs filhos no recorte.</span>", vFilhosHTML ) & "</div><div class='pill-wrap' style='margin-top:12px'><span class='pill pass'>Use a aba Detalhamento para busca, filtros por coluna e cópia para Excel.</span></div></div></div></details>",
							"",
							[@PQBJ_Match], DESC,
							[@Estimativa], DESC
						)
					VAR vLimiteNota =
						IF ( COUNTROWS ( FILTER ( vProductSummary, [@PQBJ_Match] > 0 ) ) > vTopProdutos, "Exibindo os " & FORMAT ( vTopProdutos, vIntFormat ) & " produtos com mais jobs. Use o slicer de período para reduzir o recorte.", "" )
					RETURN
						vCSS
							& "<div class='diag-wrap'><div class='sticky'><div class='diag-head'><div class='slicer-space'><div class='doc-button'>Detalhamento</div></div>" & vCards & "</div></div>" & vTabelaHead & "<div class='rows'>" & IF ( ISBLANK ( vRows ), "<div class='empty-state'>Nenhum produto com oportunidades encontrado no período selecionado.</div>", vRows ) & "</div><div class='foot-note'>" & vLimiteNota & "</div></div>"
			```
		displayFolder: HTML
		lineageTag: b0000702-d1ag-ba5e-b010-ba5e00000702

	column Column
		formatString: 0
		lineageTag: 2ec931fb-c2e0-4926-ad68-5e513c5ba130
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition medidas_html = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 1fcf0b6930bb4e10a61b1c725afbbaf7

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

