table medidas_html
	lineageTag: f371007f-daa0-4acf-919c-58dc35ff6b74

	/// Cabeçalho executivo do dashboard Journey, baseado nas novas views de Journey e Jobs.
	measure Titulo_Diagnostico_HTML_2026_Novo_Estilo_DOCUMENTACAO =
			VAR vIntFormat = "#,##0"
				VAR vCalendarStart = MIN ( 'dCalendar'[Date] )
				VAR vCalendarEnd = MAX ( 'dCalendar'[Date] )
				VAR vHasCalendarFilter = COUNTROWS ( 'dCalendar' ) < COUNTROWS ( ALL ( 'dCalendar' ) )
				VAR vHasJobFilter =
				    ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[JOB] )
				        || ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[CODIGO] )
				        || ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[CODIGO_PRODUTO] )
				        || ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[GppNome] )
				VAR vJourneysPeriod =
				    SELECTCOLUMNS (
				        FILTER (
				            ALLSELECTED ( 'vw_powerbi_journeys' ),
				            NOT vHasCalendarFilter
				                || (
				                    'vw_powerbi_journeys'[DATA_CADASTRO] >= vCalendarStart
				                        && 'vw_powerbi_journeys'[DATA_CADASTRO] < vCalendarEnd + 1
				                )
				        ),
				        "__JourneyJob", 'vw_powerbi_journeys'[JOB],
				        "__Fim", 'vw_powerbi_journeys'[FIM],
				        "__Data", 'vw_powerbi_journeys'[DATA_CADASTRO]
				    )
				VAR vJobsPeriod =
				    ADDCOLUMNS (
				        SELECTCOLUMNS (
				            FILTER (
				                ALLSELECTED ( 'vw_powerbi_journeys_filhos_novos' ),
				                NOT vHasCalendarFilter
				                    || (
				                        'vw_powerbi_journeys_filhos_novos'[DATA_CADASTRO] >= vCalendarStart
				                            && 'vw_powerbi_journeys_filhos_novos'[DATA_CADASTRO] < vCalendarEnd + 1
				                    )
				            ),
				            "__Codigo", 'vw_powerbi_journeys_filhos_novos'[CODIGO],
				            "__Job", 'vw_powerbi_journeys_filhos_novos'[JOB],
				            "__ProdutoCodigo", 'vw_powerbi_journeys_filhos_novos'[CODIGO_PRODUTO],
				            "__Produto", 'vw_powerbi_journeys_filhos_novos'[GppNome],
				            "__Fim", 'vw_powerbi_journeys_filhos_novos'[FIM],
				            "__Data", 'vw_powerbi_journeys_filhos_novos'[DATA_CADASTRO]
				        ),
				        "__ParentJob", VAR j = [__Job] RETURN LEFT ( j, SEARCH ( "-", j & "-", 1, LEN ( j ) + 1 ) - 1 )
				    )
				VAR vJobParents = DISTINCT ( SELECTCOLUMNS ( vJobsPeriod, "__JourneyJob", [__ParentJob] ) )
			VAR vJourneysBase = FILTER ( vJourneysPeriod, NOT ( vHasJobFilter ) || [__JourneyJob] IN vJobParents )
				VAR vJourneyKeys = DISTINCT ( SELECTCOLUMNS ( vJourneysBase, "__ParentJob", [__JourneyJob] ) )
				VAR vJobsBase = FILTER ( vJobsPeriod, [__ParentJob] IN vJourneyKeys )
				VAR vMinData = MINX ( vJourneysBase, [__Data] )
				VAR vMaxData = MAXX ( vJourneysBase, [__Data] )
				VAR vPeriodo =
				    IF (
				        ISBLANK ( vMinData ) || ISBLANK ( vMaxData ),
				        "Sem dados no recorte",
				        FORMAT ( vMinData, "dd/MM/yyyy" ) & " a " & FORMAT ( vMaxData, "dd/MM/yyyy" )
				    )
				VAR vJourneys = COUNTROWS ( vJourneysBase )
				VAR vJourneysAtivos = COUNTROWS ( FILTER ( vJourneysBase, [__Fim] = 1 ) )
				VAR vJobs = COUNTROWS ( vJobsBase )
				VAR vProdutos = COUNTROWS ( SUMMARIZE ( vJobsBase, [__ProdutoCodigo], [__Produto] ) )
				VAR vDataAtual = FORMAT ( NOW (), "dd/MM/yyyy HH:mm" )
				VAR vCSS =
				"
				<style>
				*{margin:0;padding:0;box-sizing:border-box}
				.diag-title-shell{width:1910px;min-width:1910px;max-width:1910px;height:165px;min-height:165px;max-height:165px;overflow:hidden;font-family:'Segoe UI',Arial,sans-serif;color:#E8EEF5;border-radius:18px;border:1px solid rgba(213,174,119,.36);background:radial-gradient(circle at 0% 0%,rgba(213,174,119,.22),transparent 33%),radial-gradient(circle at 92% 18%,rgba(139,224,209,.13),transparent 28%),linear-gradient(135deg,#060B10 0%,#0B141B 46%,#10201F 100%);box-shadow:0 16px 38px rgba(0,0,0,.50),inset 0 1px 0 rgba(255,255,255,.05);position:relative}
				.diag-title-shell:before{content:'';position:absolute;left:0;top:0;bottom:0;width:8px;background:linear-gradient(180deg,#F4D9A9,#D5AE77,#8BE0D1);opacity:.92}
				.diag-title-grid{position:relative;z-index:2;width:100%;height:100%;display:grid;grid-template-columns:150px minmax(0,1fr) 430px;align-items:center;gap:24px;padding:18px 26px 18px 34px}
				.brand-panel{height:100%;min-width:0;display:flex;align-items:center;justify-content:center}.logo-card{width:118px;height:82px;border-radius:16px;display:flex;align-items:center;justify-content:center;padding:10px;background:radial-gradient(circle at 28% 12%,rgba(213,174,119,.18),transparent 36%),#030506;border:1px solid rgba(213,174,119,.40);box-shadow:0 12px 24px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.06);overflow:hidden}.logo-text{width:100%;height:100%;display:flex;align-items:center;justify-content:center;color:#fff;font-family:Georgia,'Times New Roman',serif;font-size:13px;font-weight:700;line-height:1;letter-spacing:-.05em;text-align:center;white-space:nowrap;overflow:hidden}.logo-text .studio{color:#D5AE77;margin-left:1px}
				.center-panel{min-width:0;height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;text-align:center;position:relative}.center-panel:before,.center-panel:after{content:'';width:88px;height:1px;background:linear-gradient(90deg,transparent,rgba(213,174,119,.65),transparent)}.title-kicker{color:#8BE0D1;font-size:10px;font-weight:950;letter-spacing:.22em;text-transform:uppercase;line-height:1;white-space:nowrap}.main-title{color:#fff;font-size:38px;font-weight:950;letter-spacing:.09em;text-transform:uppercase;line-height:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-shadow:0 4px 16px rgba(0,0,0,.72)}.main-title .gold{color:#F4D9A9}.subline{max-width:100%;color:#D5AE77;font-size:11px;font-weight:950;letter-spacing:.10em;text-transform:uppercase;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
				.right-panel{height:100%;display:grid;grid-template-columns:168px minmax(0,1fr) 68px;align-items:center;gap:14px;min-width:0}.doc-title-button{position:relative;min-height:44px;display:inline-flex;align-items:center;justify-content:center;padding:12px 17px;border-radius:14px;color:#081018;border:1px solid rgba(244,217,169,.72);background:linear-gradient(135deg,#F4D9A9 0%,#D5AE77 48%,#8BE0D1 100%);box-shadow:0 14px 28px rgba(213,174,119,.24),0 0 0 1px rgba(255,255,255,.08) inset,0 0 22px rgba(139,224,209,.18);font-size:11px;font-weight:950;letter-spacing:.10em;text-transform:uppercase;white-space:nowrap;overflow:hidden}.doc-title-button:before{content:'i';display:inline-flex;align-items:center;justify-content:center;width:21px;height:21px;margin-right:8px;border-radius:50%;background:rgba(8,16,24,.18);border:1px solid rgba(8,16,24,.24);color:#081018;font-size:12px;font-weight:950;font-style:italic;line-height:1}
				.update-box{display:flex;flex-direction:column;align-items:flex-end;justify-content:center;gap:10px;min-width:0}.update-line{display:flex;flex-direction:column;align-items:flex-end;gap:3px;min-width:0}.update-label{color:#F4D9A9;font-size:9px;font-weight:950;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap}.update-value{color:#E8EEF5;font-size:12px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:160px;text-align:right}.avatar{position:relative;width:62px;height:62px;border-radius:50%;display:flex;align-items:center;justify-content:center;color:#F4D9A9;font-size:18px;font-weight:950;letter-spacing:.05em;background:linear-gradient(145deg,rgba(213,174,119,.14),rgba(255,255,255,.035));border:1px solid rgba(213,174,119,.58);box-shadow:0 0 0 5px rgba(213,174,119,.06),inset 0 1px 0 rgba(255,255,255,.10)}.avatar:after{content:'';position:absolute;right:2px;bottom:5px;width:9px;height:9px;border-radius:50%;background:#21E66D;box-shadow:0 0 12px rgba(33,230,109,.75);border:2px solid #10201F}
				</style>
				"
				RETURN
				    vCSS
				        & "<div class='diag-title-shell'><div class='diag-title-grid'>"
				        & "<div class='brand-panel'><div class='logo-card'><div class='logo-text'><span>GRUPO</span><span class='studio'>STUDIO</span></div></div></div>"
				        & "<div class='center-panel'><div class='title-kicker'>Grupo Studio · Diagnóstico TAX</div><div class='main-title'>Oportunidades <span class='gold'>- Journey</span></div><div class='subline'>" & FORMAT ( vProdutos, vIntFormat ) & " produtos · " & FORMAT ( vJourneys, vIntFormat ) & " journeys · " & FORMAT ( vJobs, vIntFormat ) & " jobs | " & vPeriodo & "</div></div>"
				        & "<div class='right-panel'><div class='doc-title-button'>Documentação</div><div class='update-box'><div class='update-line'><span class='update-label'>Atualizado em</span><span class='update-value'>" & vDataAtual & "</span></div><div class='update-line'><span class='update-label'>Journeys ativos</span><span class='update-value'>" & FORMAT ( vJourneysAtivos, vIntFormat ) & "</span></div></div><div class='avatar'>GS</div></div>"
				        & "</div></div>"
		displayFolder: HTML
		lineageTag: c4874ca8-7357-4c3e-b3e5-6180c4491f86

	/// Documentação executiva da refatoração com as views vw_powerbi_journeys.
	measure DOCUMENTACAO_DIAGNOSTICO_JOURNEY_HTML_V4_FORMAL_TODO_PERIODO = ```
				VAR vIntFormat = "#,##0"
				VAR vCalendarStart = MIN ( 'dCalendar'[Date] )
				VAR vCalendarEnd = MAX ( 'dCalendar'[Date] )
				VAR vHasCalendarFilter = COUNTROWS ( 'dCalendar' ) < COUNTROWS ( ALL ( 'dCalendar' ) )
				VAR vHasJobFilter =
				    ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[JOB] )
				        || ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[CODIGO] )
				        || ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[CODIGO_PRODUTO] )
				        || ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[GppNome] )
				VAR vJourneysPeriod =
				    SELECTCOLUMNS (
				        FILTER (
				            ALLSELECTED ( 'vw_powerbi_journeys' ),
				            NOT vHasCalendarFilter
				                || (
				                    'vw_powerbi_journeys'[DATA_CADASTRO] >= vCalendarStart
				                        && 'vw_powerbi_journeys'[DATA_CADASTRO] < vCalendarEnd + 1
				                )
				        ),
				        "__JourneyJob", 'vw_powerbi_journeys'[JOB],
				        "__Fim", 'vw_powerbi_journeys'[FIM]
				    )
				VAR vJobsPeriod =
				    ADDCOLUMNS (
				        SELECTCOLUMNS (
				            FILTER (
				                ALLSELECTED ( 'vw_powerbi_journeys_filhos_novos' ),
				                NOT vHasCalendarFilter
				                    || (
				                        'vw_powerbi_journeys_filhos_novos'[DATA_CADASTRO] >= vCalendarStart
				                            && 'vw_powerbi_journeys_filhos_novos'[DATA_CADASTRO] < vCalendarEnd + 1
				                    )
				            ),
				            "__Codigo", 'vw_powerbi_journeys_filhos_novos'[CODIGO],
				            "__Job", 'vw_powerbi_journeys_filhos_novos'[JOB],
				            "__ProdutoCodigo", 'vw_powerbi_journeys_filhos_novos'[CODIGO_PRODUTO],
				            "__Produto", 'vw_powerbi_journeys_filhos_novos'[GppNome],
				            "__Fim", 'vw_powerbi_journeys_filhos_novos'[FIM]
				        ),
				        "__ParentJob", VAR j = [__Job] RETURN LEFT ( j, SEARCH ( "-", j & "-", 1, LEN ( j ) + 1 ) - 1 )
				    )
				VAR vAreas =
				    SELECTCOLUMNS (
				        ALLSELECTED ( 'vw_powerbi_journeys_menor_area_novos' ),
				        "__PmvJob", 'vw_powerbi_journeys_menor_area_novos'[PmvJob],
				        "__Etapa", COALESCE ( 'vw_powerbi_journeys_menor_area_novos'[ParNome], "SEM ETAPA" )
				    )
				VAR vHasEtapaFilter =
				    ISFILTERED ( 'vw_powerbi_journeys_menor_area_novos'[ParNome] )
				        || ISFILTERED ( 'vw_powerbi_journeys_menor_area_novos'[PmvArea] )
				        || ISFILTERED ( 'vw_powerbi_journeys_menor_area_novos'[PmvJob] )
				VAR vAreaJobCodes = DISTINCT ( SELECTCOLUMNS ( vAreas, "__Codigo", [__PmvJob] ) )
				VAR vJobsPeriodEtapa = FILTER ( vJobsPeriod, NOT vHasEtapaFilter || [__Codigo] IN vAreaJobCodes )
				VAR vJobParents = DISTINCT ( SELECTCOLUMNS ( vJobsPeriodEtapa, "__JourneyJob", [__ParentJob] ) )
				VAR vJourneysBase = FILTER ( vJourneysPeriod, NOT ( vHasJobFilter || vHasEtapaFilter ) || [__JourneyJob] IN vJobParents )
				VAR vJourneyKeys = DISTINCT ( SELECTCOLUMNS ( vJourneysBase, "__ParentJob", [__JourneyJob] ) )
				VAR vJobsBase = FILTER ( vJobsPeriodEtapa, [__ParentJob] IN vJourneyKeys )
				
				VAR vJourneys = COUNTROWS ( vJourneysBase )
				VAR vJourneysAtivos = COUNTROWS ( FILTER ( vJourneysBase, [__Fim] = 1 ) )
				VAR vJobs = COUNTROWS ( vJobsBase )
				VAR vJobsAtivos = COUNTROWS ( FILTER ( vJobsBase, [__Fim] = 1 ) )
				VAR vPctAtivosJourneys = DIVIDE ( vJourneysAtivos, vJourneys, 0 )
				VAR vInativosJourneys = vJourneys - vJourneysAtivos
				VAR vCrossSell = DIVIDE ( vJobs, vJourneys, 0 )
				VAR vPctAtivosJobs = DIVIDE ( vJobsAtivos, vJobs, 0 )
				VAR vProdutos = COUNTROWS ( SUMMARIZE ( vJobsBase, [__ProdutoCodigo], [__Produto] ) )
				VAR vPeriodo =
				    IF (
				        vHasCalendarFilter,
				        FORMAT ( vCalendarStart, "dd/MM/yyyy" ) & " a " & FORMAT ( vCalendarEnd, "dd/MM/yyyy" ),
				        "Todo o período"
				    )
				VAR vAtualizado = FORMAT ( NOW (), "dd/MM/yyyy HH:mm" )
				VAR vCSS =
				"
				<style>
				.doc-page{width:1910px;height:1070px;box-sizing:border-box;padding:20px;font-family:'Segoe UI',Arial,sans-serif;background:radial-gradient(circle at 0% 0%,rgba(213,174,119,.15),transparent 35%),radial-gradient(circle at 100% 100%,rgba(139,224,209,.10),transparent 30%),linear-gradient(135deg,#050A0F 0%,#0E1720 100%);color:#F4F7FA;overflow:hidden}
				.doc-shell{width:100%;height:100%;display:grid;grid-template-columns:420px 1fr;gap:20px}
				.doc-sidebar{height:100%;box-sizing:border-box;border-radius:20px;border:1px solid rgba(213,174,119,.28);background:linear-gradient(180deg,rgba(14,23,32,.95),rgba(9,15,21,.98));box-shadow:0 20px 50px rgba(0,0,0,.50),inset 0 1px 0 rgba(255,255,255,.05);padding:28px 24px;overflow-y:auto;position:relative}
				.doc-sidebar::-webkit-scrollbar{width:6px}
				.doc-sidebar::-webkit-scrollbar-track{background:transparent}
				.doc-sidebar::-webkit-scrollbar-thumb{background:rgba(213,174,119,.3);border-radius:10px}
				.doc-sidebar:before{content:'';position:absolute;left:0;top:0;bottom:0;width:6px;background:linear-gradient(180deg,#F4D9A9,#D5AE77,#8BE0D1)}
				.brand-kicker{font-size:11px;text-transform:uppercase;letter-spacing:2px;color:#8BE0D1;font-weight:1000;margin-bottom:8px}
				.brand-title{color:#F4D9A9;font-size:32px;line-height:1.1;font-weight:1000;letter-spacing:.025em;margin-bottom:16px;text-transform:uppercase}
				.brand-sub{font-size:14px;line-height:1.5;color:#A8B4C0;margin-bottom:24px;font-weight:500}
				.side-card{border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.02);border-radius:16px;padding:16px;margin-bottom:14px;transition:transform .15s ease,border-color .15s ease}
				.side-card:hover{transform:translateY(-2px);border-color:rgba(213,174,119,.3)}
				.side-card.highlight{background:linear-gradient(135deg,rgba(213,174,119,.12),rgba(18,31,42,.4));border-color:rgba(213,174,119,.25)}
				.side-label{display:block;font-size:11px;color:#8B98A6;text-transform:uppercase;letter-spacing:1px;font-weight:900;margin-bottom:6px}
				.side-value{display:block;font-size:18px;color:#F4F7FA;font-weight:850;line-height:1.3}
				.side-value.big{color:#F4D9A9;font-size:24px}
				.side-small{color:#8B98A6;font-size:12px;line-height:1.4;margin-top:8px}
				
				.nav-menu{margin-top:20px;border-top:1px solid rgba(255,255,255,.08);padding-top:16px;display:flex;flex-direction:column;gap:8px}
				.nav-item{display:flex;align-items:center;padding:10px 14px;border-radius:10px;color:#A8B4C0;text-decoration:none;font-size:12.5px;font-weight:800;background:rgba(255,255,255,.015);border:1px solid rgba(255,255,255,.04);transition:all .15s ease}
				.nav-item:hover{color:#F4D9A9;background:rgba(213,174,119,.08);border-color:rgba(213,174,119,.25);transform:translateX(2px)}
				.nav-item:before{content:'✦';color:#8BE0D1;margin-right:8px;font-size:10px}
				
				.doc-main{height:100%;background:linear-gradient(180deg,rgba(14, 23, 32, 0.95) 0%,rgba(9, 15, 21, 0.98) 100%);border:1px solid rgba(213,174,119,.20);border-radius:20px;box-shadow:0 20px 50px rgba(0,0,0,.50),inset 0 1px 0 rgba(255,255,255,.05);overflow:hidden;display:flex;flex-direction:column}
				.doc-header{padding:22px 28px;border-bottom:1px solid rgba(213,174,119,.16);display:flex;align-items:center;justify-content:space-between;background:linear-gradient(90deg,rgba(255,255,255,.02),rgba(213,174,119,.02))}
				.doc-header h1{margin:0;color:#F4D9A9;font-size:28px;font-weight:1000;letter-spacing:.05em;text-transform:uppercase}
				.doc-header p{margin:4px 0 0;color:#A8B4C0;font-size:14px;font-weight:500}
				.doc-scroll{flex:1;overflow-y:auto;padding:28px;box-sizing:border-box;scroll-behavior:smooth}
				.doc-scroll::-webkit-scrollbar{width:12px}
				.doc-scroll::-webkit-scrollbar-track{background:rgba(0,0,0,.15)}
				.doc-scroll::-webkit-scrollbar-thumb{background:linear-gradient(180deg,rgba(244,217,169,.4),rgba(139,224,209,.2));border:3px solid #0E1720;border-radius:999px}
				.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:24px}
				.metric{position:relative;padding:16px 20px 15px;border-radius:16px;background:linear-gradient(155deg,rgba(18, 31, 42, 0.98),rgba(9, 15, 21, 0.96));border:1px solid rgba(255,255,255,.08);box-shadow:0 10px 24px rgba(0,0,0,0.2);overflow:hidden;transition:transform .15s ease,border-color .15s ease,box-shadow .15s ease;display:flex;align-items:center;justify-content:space-between;gap:12px}
				.metric:hover{transform:translateY(-2px);border-color:rgba(244,217,169,.25);box-shadow:0 14px 30px rgba(0,0,0,0.3)}
				.metric:before{content:'';position:absolute;left:18px;top:0;width:56px;height:5px;border-radius:0 0 10px 10px;background:linear-gradient(90deg,#F4D9A9,#8BE0D1)}
				.metric.primary{background:linear-gradient(155deg,rgba(213,174,119,.1),rgba(18,31,42,.98) 50%,rgba(9,15,21,.96));border-color:rgba(213,174,119,.35)}
				.metric-content{min-width:0;flex:1;display:flex;flex-direction:column;align-items:flex-start}
				.m-label{display:block;color:#A8B4C0;font-size:11.5px;letter-spacing:.08em;text-transform:uppercase;font-weight:1000}
				.m-value{display:block;color:#F4D9A9;font-size:32px;font-weight:1000;margin-top:8px;line-height:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
				.m-note{display:block;color:#6D7A86;font-size:11px;margin-top:6px;font-weight:850;line-height:1.25}
				.metric-side-badge{display:flex;flex-direction:column;align-items:center;justify-content:center;padding:8px 10px;border-radius:10px;background:linear-gradient(135deg,rgba(213,174,119,.08),rgba(139,224,209,.04));border:1px solid rgba(213,174,119,.18);min-width:88px;text-align:center;transition:all .15s ease}
				.metric-side-badge .badge-val{color:#F4D9A9;font-size:16px;font-weight:1000;line-height:1.15}
				.metric-side-badge .badge-lbl{color:#A8B4C0;font-size:9.0px;font-weight:1000;text-transform:uppercase;letter-spacing:.05em;margin-top:3px}
				.metric:hover .metric-side-badge{background:linear-gradient(135deg,rgba(213,174,119,.16),rgba(139,224,209,.07));border-color:#D5AE77;transform:scale(1.03)}
				.doc-section{border:1px solid rgba(213,174,119,.16);background:rgba(255,255,255,.015);border-radius:16px;margin-bottom:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.15);transition:border-color .15s ease}
				.doc-section:hover{border-color:rgba(213,174,119,.3)}
				.doc-section summary{cursor:pointer;list-style:none;display:flex;align-items:center;justify-content:space-between;padding:16px 20px;background:linear-gradient(90deg,rgba(213,174,119,.08),rgba(213,174,119,.01));border-bottom:1px solid rgba(213,174,119,.1);outline:none}
				.doc-section summary::-webkit-details-marker{display:none}
				.summary-title{color:#F4D9A9;font-size:15px;font-weight:1000;text-transform:uppercase;letter-spacing:1px;display:flex;align-items:center;gap:10px}
				.summary-title:before{content:'✦';color:#8BE0D1;font-size:12px}
				.summary-chevron{color:#D5AE77;font-size:12px;transition:transform .2s ease;font-weight:1000}
				.doc-section[open] .summary-chevron{transform:rotate(90deg)}
				.section-body{padding:24px;font-size:14.5px;line-height:1.65;color:#DCE5EE}
				.section-body h2{font-size:16px;color:#F4D9A9;margin:24px 0 12px;text-transform:uppercase;letter-spacing:.5px;font-weight:900}
				.section-body h2:first-child{margin-top:0}
				.section-body p{margin-bottom:14px}
				.section-body ul{margin-bottom:16px;padding-left:20px}
				.section-body li{margin-bottom:8px}
				.section-body strong{color:#F4D9A9;font-weight:700}
				.doc-table{width:100%;border-collapse:separate;border-spacing:0;table-layout:fixed;overflow:hidden;border-radius:12px;border:1px solid rgba(255,255,255,.08);margin:16px 0}
				.doc-table th{background:#0E1720;color:#D5AE77;font-size:12px;font-weight:1000;text-transform:uppercase;letter-spacing:.5px;text-align:left;padding:12px 16px;border-bottom:1px solid rgba(213,174,119,.25)}
				.doc-table td{color:#DCE5EE;font-size:13.5px;line-height:1.55;padding:12px 16px;border-bottom:1px solid rgba(255,255,255,.05);vertical-align:top}
				.doc-table tr:last-child td{border-bottom:none}
				.doc-table tr:hover td{background:rgba(255,255,255,.015)}
				.callout{border-left:4px solid #D5AE77;background:rgba(213,174,119,.05);border-radius:8px;padding:16px;color:#DCE5EE;font-size:14px;line-height:1.5;margin:18px 0}
				.callout.info{border-left-color:#8BE0D1;background:rgba(139,224,209,.04)}
				.callout.alert{border-left-color:#FF9C93;background:rgba(255,156,147,.04)}
				
				.timeline{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin:24px 0;position:relative;padding-top:10px}
				.timeline:before{content:'';position:absolute;top:30px;left:8%;right:8%;height:2px;background:rgba(255,255,255,.08);z-index:1}
				.timeline-item{text-align:center;position:relative;z-index:2}
				.timeline-badge{width:42px;height:42px;border-radius:50%;background:#0E1720;border:2px solid rgba(255,255,255,0.15);display:flex;align-items:center;justify-content:center;margin:0 auto 12px;font-weight:1000;font-size:14px;color:#A8B4C0;transition:all .2s ease;box-shadow:0 4px 10px rgba(0,0,0,0.3)}
				.timeline-item:hover .timeline-badge{transform:scale(1.1)}
				.timeline-badge.cad{border-color:#A8B4C0;color:#A8B4C0;background:rgba(168,180,192,.1)}
				.timeline-badge.proc{border-color:#9CCBFF;color:#9CCBFF;background:rgba(156,203,255,.1)}
				.timeline-badge.check{border-color:#F4D9A9;color:#F4D9A9;background:rgba(244,217,169,.1)}
				.timeline-badge.oper{border-color:#FFCF87;color:#FFCF87;background:rgba(255,207,135,.1)}
				.timeline-badge.reu{border-color:#8BE0D1;color:#8BE0D1;background:rgba(139,224,209,.1)}
				.timeline-badge.fim{border-color:#7BEEA6;color:#7BEEA6;background:rgba(123,238,166,.1)}
				.timeline-title{font-size:13px;font-weight:900;color:#F4D9A9;margin-bottom:4px;text-transform:uppercase;letter-spacing:.3px}
				.timeline-desc{font-size:11px;color:#A8B4C0;line-height:1.3;padding:0 4px}
				
				.guide-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:16px 0}
				.guide-card{background:rgba(255, 255, 255, 0.02);border:1px solid rgba(255, 255, 255, 0.06);border-radius:12px;padding:16px}
				.guide-card h3{font-size:14px;color:#8BE0D1;margin-bottom:8px;text-transform:uppercase;font-weight:900}
				
				.faq-item{border-bottom:1px solid rgba(255, 255, 255, 0.05);padding:14px 0}
				.faq-item:last-child{border-bottom:none;padding-bottom:0}
				.faq-item:first-child{padding-top:0}
				.faq-q{font-weight:900;color:#F4D9A9;margin-bottom:6px;font-size:14px}
				.faq-a{color:#B7C2CD;font-size:13.5px;line-height:1.5}
				
				.footer-doc{margin-top:24px;padding-top:16px;border-top:1px solid rgba(255,255,255,.06);display:flex;justify-content:space-between;color:#6D7A86;font-size:12px;font-weight:700}
				
				[data-tip]{position:relative;cursor:help}.metric[data-tip]:hover{outline:1px solid rgba(244,217,169,.22);outline-offset:-1px}
				.float-tip{position:fixed;z-index:2147483647;display:none;max-width:500px;min-width:280px;padding:16px 18px;border-radius:15px;background:linear-gradient(160deg,rgba(7,12,18,.99),rgba(15,27,36,.99));border:1px solid rgba(244,217,169,.45);color:#F4F7FA;font-family:'Segoe UI',Arial,sans-serif;font-size:15px;font-weight:800;line-height:1.5;text-align:left;box-shadow:0 18px 40px rgba(0,0,0,.48),0 0 0 1px rgba(139,224,209,.08),inset 0 1px 0 rgba(255,255,255,.07);pointer-events:none;white-space:normal}
				.float-tip.on{display:block}
				.float-tip b{color:#F4D9A9}
				.float-tip code{color:#8BE0D1;font-family:Consolas,'Courier New',monospace;font-size:.95em}
				
				.dept-badge{display:inline-flex;align-items:center;justify-content:center;padding:4px 8px;border-radius:6px;font-size:11px;font-weight:900;text-transform:uppercase}
				.dept-comercial{background:rgba(255,207,135,.12);color:#FFCF87;border:1px solid rgba(255,207,135,.25)}
				.dept-backoffice{background:rgba(156,203,255,.12);color:#9CCBFF;border:1px solid rgba(156,203,255,.25)}
				.dept-cs{background:rgba(244,217,169,.12);color:#F4D9A9;border:1px solid rgba(244,217,169,.25)}
				.dept-operacao{background:rgba(139,224,209,.12);color:#8BE0D1;border:1px solid rgba(139,224,209,.25)}
				.dept-financeiro{background:rgba(123,238,166,.12);color:#7BEEA6;border:1px solid rgba(123,238,166,.25)}
				.dept-legal{background:rgba(203,156,255,.12);color:#D19CFF;border:1px solid rgba(203,156,255,.25)}
				
				.prod-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:16px 0}
				.prod-card{background:rgba(255,255,255,.015);border:1px solid rgba(255,255,255,.06);border-radius:12px;padding:14px;transition:transform .15s ease,border-color .15s ease}
				.prod-card:hover{transform:translateY(-2px);border-color:rgba(139,224,209,.3)}
				.prod-card h4{font-size:13px;color:#F4D9A9;margin-bottom:6px;text-transform:uppercase;font-weight:900}
				.prod-card p{font-size:11.5px;color:#B7C2CD;line-height:1.4;margin:0}
				</style>
				"
				VAR vTipJourneys = "<b>JOURNEYS (JORNADAS PAI)</b><br/>Quantidade total de jornadas pai no período e filtros ativos.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys</code><br/><b>Colunas Usadas:</b> <code>CODIGO</code>, <code>JOB</code>, <code>DATA_CADASTRO</code>, <code>FIM</code><br/><b>Regra de Cálculo:</b> Conta as linhas da tabela de jornadas filtradas pela coluna <code>DATA_CADASTRO</code> no slicer de período. Se filtros de produto, job ou etapa estiverem ativos (tabela de jobs filhos), a listagem restringe-se apenas aos journeys vinculados a esses jobs correspondentes."
				VAR vTipJourneysAtivos = "<b>JOURNEYS ATIVOS (FIM = 1)</b><br/>Quantidade de jornadas pai consideradas ativas no recorte selecionado.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys</code><br/><b>Colunas Usadas:</b> <code>CODIGO</code>, <code>JOB</code>, <code>DATA_CADASTRO</code>, <code>FIM</code><br/><b>Regra de Cálculo:</b> Filtra as jornadas do período pelo critério <code>vw_powerbi_journeys[FIM] = 1</code>. Respeita os filtros cruzados de produtos, jobs e etapas aplicados no painel."
				VAR vTipJobs = "<b>JOBS (TRABALHOS FILHOS)</b><br/>Quantidade total de jobs filhos associados a jornadas no recorte selecionado.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code><br/><b>Colunas Usadas:</b> <code>CODIGO</code>, <code>JOB</code>, <code>DATA_CADASTRO</code>, <code>CODIGO_PRODUTO</code>, <code>GppNome</code>, <code>FIM</code><br/><b>Regra de Cálculo:</b> Conta os jobs cujos pais (jornadas) estão no período de cadastro selecionado. Os jobs são cruzados com os filtros de produto e etapa aplicados."
				VAR vTipJobsAtivos = "<b>JOBS ATIVOS (FIM = 1)</b><br/>Quantidade de jobs filhos com status ativo no recorte selecionado.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code><br/><b>Colunas Usadas:</b> <code>CODIGO</code>, <code>JOB</code>, <code>DATA_CADASTRO</code>, <code>FIM</code><br/><b>Regra de Cálculo:</b> Filtra a lista de jobs do recorte pelo critério <code>vw_powerbi_journeys_filhos_novos[FIM] = 1</code>. A etapa atual mostrada na distribuição do produto é baseada apenas nestes jobs ativos."
				RETURN
				    vCSS
				        & "<div class='doc-page'><div class='doc-shell'><aside class='doc-sidebar'>"
				        & "<div class='brand-kicker'>Grupo Studio · Guia Executivo</div><div class='brand-title'>Manual do<br><span style='color:#8BE0D1'>Diretor</span></div>"
				        & "<div class='brand-sub'>Portal conceitual e regulamentar do Painel de Oportunidades x Jobs.</div>"
				        & "<div class='side-card highlight'><span class='side-label'>Público Alvo</span><span class='side-value'>Diretoria e Gestores</span><div class='side-small'>Linguagem focada em tomada de decisão operacional e comercial.</div></div>"
				        & "<div class='side-card'><span class='side-label'>Propósito Operacional</span><span class='side-value'>Diagnóstico Fiscal (Tax)</span><div class='side-small'>Acompanhamento dos serviços em andamento e identificação de gargalos.</div></div>"
				        & "<div class='nav-menu'><span class='side-label'>Navegação Rápida</span>"
				        & "<a href='#sec01' class='nav-item'>01. Jornadas vs. Serviços</a>"
				        & "<a href='#sec02' class='nav-item'>02. Regra da Versão Ativa</a>"
				        & "<a href='#sec03' class='nav-item'>03. Ciclo de Vida & Funil</a>"
				        & "<a href='#sec04' class='nav-item'>04. Matriz de SLA e Prazos</a>"
				        & "<a href='#sec05' class='nav-item'>05. Dicionário de Soluções</a>"
				        & "<a href='#sec06' class='nav-item'>06. Canais de Escalação</a>"
				        & "<a href='#sec07' class='nav-item'>07. Guia de Ação Prática</a>"
				        & "<a href='#sec08' class='nav-item'>08. Segurança & Monetização</a>"
				        & "<a href='#sec09' class='nav-item'>09. Perguntas Frequentes</a>"
				        & "</div>"
				        & "</aside><main class='doc-main'><div class='doc-header'><div><h1>Documentação de Negócio · Diagnóstico Fiscal</h1><p>Entenda a lógica de funcionamento, os conceitos e como extrair o máximo valor do relatório. Recorte: <strong>" & vPeriodo & "</strong></p></div></div><div class='doc-scroll'>"
				        & "<div class='metric-grid'>"
				        & "<div class='metric primary' data-tip='" & vTipJourneys & "'><div class='metric-content'><span class='m-label'>Clientes (Journeys)</span><span class='m-value'>" & FORMAT ( vJourneys, vIntFormat ) & "</span><span class='m-note'>Volume total de contratos</span></div><div class='metric-side-badge'><div class='badge-val'>" & FORMAT ( vPctAtivosJourneys, "0.0%" ) & "</div><div class='badge-lbl'>Ativos</div></div></div>"
				        & "<div class='metric' data-tip='" & vTipJourneysAtivos & "'><div class='metric-content'><span class='m-label'>Clientes Ativos</span><span class='m-value'>" & FORMAT ( vJourneysAtivos, vIntFormat ) & "</span><span class='m-note'>Operação vigente em andamento</span></div><div class='metric-side-badge'><div class='badge-val'>" & FORMAT ( vInativosJourneys, vIntFormat ) & "</div><div class='badge-lbl'>Históricos</div></div></div>"
				        & "<div class='metric primary' data-tip='" & vTipJobs & "'><div class='metric-content'><span class='m-label'>Serviços (Jobs)</span><span class='m-value'>" & FORMAT ( vJobs, vIntFormat ) & "</span><span class='m-note'>Subprodutos solicitados</span></div><div class='metric-side-badge'><div class='badge-val'>" & FORMAT ( vCrossSell, "0.0" ) & "</div><div class='badge-lbl'>Jobs/Cliente</div></div></div>"
				        & "<div class='metric' data-tip='" & vTipJobsAtivos & "'><div class='metric-content'><span class='m-label'>Serviços Ativos</span><span class='m-value'>" & FORMAT ( vJobsAtivos, vIntFormat ) & "</span><span class='m-note'>Carga de trabalho em execução</span></div><div class='metric-side-badge'><div class='badge-val'>" & FORMAT ( vPctAtivosJobs, "0.0%" ) & "</div><div class='badge-lbl'>Operando</div></div></div>"
				        & "</div>"
				        & "<details class='doc-section' id='sec01' open><summary><span class='summary-title'>01. Conceito Central: Jornadas (Journeys) vs. Serviços (Jobs)</span><span class='summary-chevron'>›</span></summary><div class='section-body'>"
				        & "<p>Para facilitar a interpretação dos volumes exibidos no relatório, é fundamental compreender a diferença entre os termos <strong>Jornada (Journey)</strong> e <strong>Serviço/Trabalho (Job)</strong>:</p>"
				        & "<table class='doc-table'><thead><tr><th>Termo de Negócio</th><th>O que representa?</th><th>Exemplo Prático</th><th>Vínculo Técnico (Modelo de Dados)</th></tr></thead><tbody>"
				        & "<tr><td><strong>Jornada (Journey)</strong></td><td>É o <strong>veículo contratual ou a conta principal</strong> do cliente. Representa a empresa parceira que iniciou um ciclo de diagnóstico com o Grupo Studio. Cada cliente possui apenas uma Jornada ativa na base principal.</td><td>Empresa ABC Ltda entra como um cliente de diagnóstico fiscal.</td><td>Chave identificadora única na tabela <code>vw_powerbi_journeys[JOB]</code>.</td></tr>"
				        & "<tr><td><strong>Serviço / Trabalho (Job)</strong></td><td>São os <strong>subprodutos ou serviços individuais contratados</strong> sob a mesma Jornada. Uma única empresa (Jornada) pode contratar e ter em andamento diversos serviços tributários específicos de forma simultânea.</td><td>A mesma Empresa ABC Ltda executa em paralelo: <em>Diagnóstico de ICMS</em>, <em>Diagnóstico Previdenciário</em> e <em>Exclusão do ICMS da Base do PIS/COFINS</em>.</td><td>Registros filhos vinculados na tabela <code>vw_powerbi_journeys_filhos_novos[JOB]</code> através do código prefixo do pai.</td></tr>"
				        & "</tbody></table>"
				        & "<div class='callout info'><strong>Visão da Diretoria:</strong> Se você deseja saber quantos clientes únicos estamos atendendo, olhe para os indicadores de <strong>Jornadas (Journeys)</strong>. Se você quer entender o volume de entrega operacional e a carga de trabalho dos analistas fiscais, olhe para os indicadores de <strong>Serviços (Jobs)</strong>.</div>"
				        & "</div></details>"
				        & "<details class='doc-section' id='sec02' open><summary><span class='summary-title'>02. A Regra da Versão Ativa (Por que filtramos por FIM = 1?)</span><span class='summary-chevron'>›</span></summary><div class='section-body'>"
				        & "<p>No sistema operacional do Grupo Studio, sempre que um serviço passa por uma atualização cadastral, alteração de escopo, mudança de responsável ou readequação técnica, o sistema grava uma nova linha na base de dados para registrar o histórico (versionamento). Este mecanismo gera dois cenários:</p>"
				        & "<ul>"
				        & "<li><strong>Versão Ativa (FIM = 1):</strong> Representa o registro atualizado, oficial e válido do serviço. É o que está correndo na operação neste exato momento.</li>"
				        & "<li><strong>Versões Anteriores / Histórico (FIM = 0):</strong> Rascunhos antigos, registros substituídos ou históricos superados.</li>"
				        & "</ul>"
				        & "<h2>O que mudaria se NÃO limitássemos a contagem ao critério FIM = 1?</h2>"
				        & "<p>Se o painel mostrasse os registros com <strong>FIM = 0</strong> ativados e misturados:</p>"
				        & "<ul>"
				        & "<li><strong>Duplicidade Crítica de Dados:</strong> O mesmo serviço (ex: Diagnóstico de PIS/COFINS da Empresa ABC) seria contato 3, 4 ou mais vezes na base. Isso distorceria completamente os cartões de KPIs.</li>"
				        & "<li><strong>Inflação Artificial da Operação:</strong> A diretoria teria a falsa impressão de que a equipe operacional tem o triplo de trabalho pendente do que o real.</li>"
				        & "<li><strong>Perda de Rastreabilidade de SLA:</strong> O cálculo de tempo em cada etapa seria corrompido, pois o sistema tentaria calcular prazos de versões antigas e inativas.</li>"
				        & "</ul>"
				        & "<div class='callout alert'><strong>Regra de Negócio Absoluta:</strong> Apenas as linhas com <strong>FIM = 1</strong> representam a realidade ativa da nossa operação. As linhas com <strong>FIM = 0</strong> devem ser tratadas exclusivamente como uma trilha de auditoria histórica, e por isso são desconsideradas nos cartões de resumos operacionais.</div>"
				        & "</div></details>"
				        & "<details class='doc-section' id='sec03' open><summary><span class='summary-title'>03. O Ciclo de Vida do Serviço (Funil de Etapas)</span><span class='summary-chevron'>›</span></summary><div class='section-body'>"
				        & "<p>Cada serviço (Job) ativo percorre obrigatoriamente um ciclo de vida composto por 6 etapas sequenciais dentro do Grupo Studio. A distribuição dessas etapas nos permite diagnosticar a saúde da nossa esteira produtiva:</p>"
				        & "<div class='timeline'>"
				        & "  <div class='timeline-item'><div class='timeline-badge cad'>1</div><div class='timeline-title'>Cadastro</div><div class='timeline-desc'>Registro inicial e parametrização do contrato.</div></div>"
				        & "  <div class='timeline-item'><div class='timeline-badge proc'>2</div><div class='timeline-title'>Procuração</div><div class='timeline-desc'>Aguardando cliente conceder acessos no e-CAC.</div></div>"
				        & "  <div class='timeline-item'><div class='timeline-badge check'>3</div><div class='timeline-title'>Checklist</div><div class='timeline-desc'>Coleta de SPEDs e balancetes complementares.</div></div>"
				        & "  <div class='timeline-item'><div class='timeline-badge oper'>4</div><div class='timeline-title'>Operação</div><div class='timeline-desc'>Cruzamento técnico e apuração de créditos.</div></div>"
				        & "  <div class='timeline-item'><div class='timeline-badge reu'>5</div><div class='timeline-title'>Reunião</div><div class='timeline-desc'>Apresentação dos laudos e validação jurídica.</div></div>"
				        & "  <div class='timeline-item'><div class='timeline-badge fim'>6</div><div class='timeline-title'>Fim</div><div class='timeline-desc'>Diagnóstico concluído e pronto para faturamento.</div></div>"
				        & "</div>"
				        & "<h2>Gatilhos e Transições do Funil:</h2>"
				        & "<ul>"
				        & "<li><strong>De Cadastro para Procuração:</strong> Automatizado. Oportunidade é criada e inserida no fluxo de Backoffice para emissão do termo de procuração.</li>"
				        & "<li><strong>De Procuração para Checklist:</strong> Ocorre quando o cliente assina digitalmente ou outorga a procuração do e-CAC ao CNPJ do Grupo Studio, liberando os acessos governamentais.</li>"
				        & "<li><strong>De Checklist para Operação:</strong> O CS valida que todos os arquivos contábeis obrigatórios (SPEDs, XMLs, relatórios auxiliares) foram anexados e estão íntegros.</li>"
				        & "<li><strong>De Operação para Reunião:</strong> Os auditores concluem os cálculos fiscais, revisam as divergências matemáticas e o coordenador homologa o relatório de oportunidades.</li>"
				        & "<li><strong>De Reunião para Fim:</strong> O consultor comercial realiza a reunião técnica com o cliente, que dá o aceite/assinatura formal no laudo de diagnóstico.</li>"
				        & "</ul>"
				        & "</div></details>"
				        & "<details class='doc-section' id='sec04'><summary><span class='summary-title'>04. Matriz de SLA e Prazos por Etapa</span><span class='summary-chevron'>›</span></summary><div class='section-body'>"
				        & "<p>O Acordo de Nível de Serviço (SLA) define o tempo máximo aceitável que um Job ativo pode permanecer em cada etapa. Ultrapassar esses limites indica gargalos que necessitam de intervenção direta da liderança:</p>"
				        & "<table class='doc-table'><thead><tr><th>Etapa</th><th>Área Responsável</th><th>SLA Máximo</th><th>Critério de Saída Operacional</th><th>Impacto Financeiro do Atraso</th></tr></thead><tbody>"
				        & "<tr><td><strong>1. Cadastro</strong></td><td><span class='dept-badge dept-comercial'>Comercial</span></td><td><strong>1 dia útil</strong></td><td>Parâmetros contratuais básicos inseridos na plataforma.</td><td>Atrasa o início da busca de acessos fiscais.</td></tr>"
				        & "<tr><td><strong>2. Procuração</strong></td><td><span class='dept-badge dept-backoffice'>Backoffice</span></td><td><strong>5 dias úteis</strong></td><td>Liberação completa de acessos no e-CAC por parte do cliente.</td><td>Impede a extração direta de dados governamentais.</td></tr>"
				        & "<tr><td><strong>3. Checklist</strong></td><td><span class='dept-badge dept-cs'>Customer Success</span></td><td><strong>10 dias úteis</strong></td><td>Recebimento e validação de 100% das obrigações contábeis solicitadas.</td><td>Retém a esteira técnica por falta de insumos de cálculo.</td></tr>"
				        & "<tr><td><strong>4. Operação</strong></td><td><span class='dept-badge dept-operacao'>Time Técnico</span></td><td><strong>15 dias úteis</strong></td><td>Geração do laudo fiscal final devidamente auditado e revisado.</td><td>Adia o agendamento de reuniões comerciais de entrega.</td></tr>"
				        & "<tr><td><strong>5. Reunião Técnica</strong></td><td><span class='dept-badge dept-comercial'>Comercial / Closer</span></td><td><strong>5 dias úteis</strong></td><td>Apresentação das oportunidades e assinatura do termo de aceite pelo cliente.</td><td>Gargalo crítico que atrasa a entrada em faturamento.</td></tr>"
				        & "<tr><td><strong>6. Fim</strong></td><td><span class='dept-badge dept-financeiro'>Financeiro</span></td><td><strong>2 dias úteis</strong></td><td>Faturamento do honorário (êxito ou fixo) gerado e enviado ao cliente.</td><td>Impacta diretamente o fluxo de caixa (Cash Inflow).</td></tr>"
				        & "</tbody></table>"
				        & "<div class='callout alert'><strong>Alerta para Gestores:</strong> Quando o tempo médio na aba operacional ultrapassa a soma destes SLAs (38 dias úteis totais), a esteira é considerada ineficiente. É vital analisar a aba de <em>Detalhamento</em> para filtrar os contratos específicos que estão estourando o SLA individual e cobrar as equipes correspondentes.</div>"
				        & "</div></details>"
				        & "<details class='doc-section' id='sec05'><summary><span class='summary-title'>05. Dicionário de Soluções Tributárias (Nossos Produtos)</span><span class='summary-chevron'>›</span></summary><div class='section-body'>"
				        & "<p>Para apoiar a tomada de decisões sem a necessidade de profundidade técnica tributária, veja abaixo o significado prático e o impacto financeiro médio de cada linha de produto ofertada pelo Grupo Studio:</p>"
				        & "<div class='prod-grid'>"
				        & "  <div class='prod-card'><h4>Federal (Lucro Real / Presumido)</h4><p>Revisão abrangente de IRPJ e CSLL. Apura deduções não aproveitadas, incentivos fiscais e base de cálculo de estimativas mensais. Costuma ter o maior ticket médio de recuperação e é voltada para médias e grandes empresas.</p></div>"
				        & "  <div class='prod-card'><h4>Contribuições (PIS / COFINS)</h4><p>Mapeamento de créditos sobre insumos de produção, despesas operacionais (energia, aluguel) permitidas pela legislação e regimes de substituição tributária de bens de consumo.</p></div>"
				        & "  <div class='prod-card'><h4>Previdenciário (INSS Folha)</h4><p>Análise de recolhimentos previdenciários indevidos sobre verbas de caráter estritamente indenizatório na folha de pagamentos (como aviso prévio indenizado, terço constitucional de férias, etc.).</p></div>"
				        & "  <div class='prod-card'><h4>Tese do Século (Tema 69 STF)</h4><p>Exclusão do ICMS da base de cálculo do PIS e da COFINS. Trata-se de uma tese jurídica pacificada pelo Supremo Tribunal Federal, com alto e rápido retorno para empresas comerciais e industriais.</p></div>"
				        & "  <div class='prod-card'><h4>Crédito Acumulado de ICMS</h4><p>Recuperação, apropriação e homologação de saldos credores acumulados de ICMS junto às Secretarias Estaduais de Fazenda (SEFAZ), comum em indústrias, exportadoras e operações com alíquotas diferenciadas.</p></div>"
				        & "  <div class='prod-card'><h4>Simples Nacional (Monofásicos)</h4><p>Revisão de impostos para farmácias, petshops, autopeças, perfumarias e distribuidores optantes pelo Simples Nacional, segregando produtos com PIS/COFINS já pagos pelo fabricante na origem (tributação monofásica).</p></div>"
				        & "  <div class='prod-card'><h4>ISS (Imposto sobre Serviços)</h4><p>Análise de alíquotas aplicadas por municípios, bitributações em serviços tomados de outros municípios e deduções da base de cálculo de serviços de engenharia e construção civil.</p></div>"
				        & "  <div class='prod-card'><h4>Trabalhista (FGTS / Múltiplos Vínculos)</h4><p>Auditoria de depósitos de FGTS e recolhimentos acima do teto constitucional de colaboradores que possuem múltiplos vínculos empregatícios simultâneos.</p></div>"
				        & "</div>"
				        & "</div></details>"
				        & "<details class='doc-section' id='sec06'><summary><span class='summary-title'>06. Canais de Escalação e Governança Operacional</span><span class='summary-chevron'>›</span></summary><div class='section-body'>"
				        & "<p>Se ao analisar o painel você identificar gargalos severos em etapas específicas, utilize a matriz de escalação abaixo para acionar os responsáveis operacionais corretos:</p>"
				        & "<table class='doc-table'><thead><tr><th>Fase do Gargalo</th><th>Responsável Direto</th><th>Canal / Equipe</th><th>Escalação Nível 2 (Liderança / Diretoria)</th></tr></thead><tbody>"
				        & "<tr><td><strong>Etapa 1. Cadastro</strong></td><td>Assistente Comercial</td><td>Time de Implantação e Contratos</td><td>Coordenador de Operações Comerciais</td></tr>"
				        & "<tr><td><strong>Etapa 2. Procuração</strong></td><td>Analista de Backoffice</td><td>Equipe de Acessos Fiscais (Backoffice)</td><td>Coordenador Jurídico / Gerente Legal</td></tr>"
				        & "<tr><td><strong>Etapa 3. Checklist</strong></td><td>Analista de CS (Customer Success)</td><td>Atendimento e Relacionamento</td><td>Coordenador de CS / Diretor de Operações</td></tr>"
				        & "<tr><td><strong>Etapa 4. Operação</strong></td><td>Auditor Tributário Líder</td><td>Equipe de Auditoria e Engenharia Fiscal</td><td>Supervisor Técnico / Coordenador Tributário</td></tr>"
				        & "<tr><td><strong>Etapa 5. Reunião Técnica</strong></td><td>Executivo de Contas / Closer</td><td>Comercial Técnico</td><td>Diretor Comercial regional</td></tr>"
				        & "<tr><td><strong>Etapa 6. Fim</strong></td><td>Analista Financeiro</td><td>Faturamento e Cobrança</td><td>Controlador Financeiro / CFO</td></tr>"
				        & "</tbody></table>"
				        & "<div class='callout info'><strong>Diretriz de Governança:</strong> Recomenda-se que a Diretoria realize reuniões semanais de 'Pipeline Review' com os Coordenadores de CS, Backoffice e Auditoria Técnica para cobrar o avanço dos contratos que constam na aba de <em>Detalhamento</em> como estourados ou atrasados.</div>"
				        & "</div></details>"
				        & "<details class='doc-section' id='sec07' open><summary><span class='summary-title'>07. Guia de Ação e Tomada de Decisão (Como o Diretor deve agir?)</span><span class='summary-chevron'>›</span></summary><div class='section-body'>"
				        & "<p>Este relatório foi desenhado para atuar como um painel de alerta rápido para ações gerenciais. Veja como ler os dados e agir de forma estratégica:</p>"
				        & "<div class='guide-grid'>"
				        & "  <div class='guide-card'><h3>Gargalo na Fase de Procuração / Checklist</h3><p>Se você identificar um acúmulo de serviços nestas duas colunas para um determinado produto ou carteira, <strong>o problema não é a equipe operacional</strong>. O gargalo é o cliente que não nos concedeu acesso ou não enviou os documentos. <strong>Ação:</strong> A Diretoria deve acionar os gerentes comerciais ou o time de Atendimento ao Cliente (CS) para fazer uma força-tarefa de cobrança junto a esses clientes.</p></div>"
				        & "  <div class='guide-card'><h3>Acúmulo na Fase de Operação</h3><p>Significa que a equipe de auditores está com um grande volume de serviço em andamento técnico. Se os prazos médios de entrega estiverem subindo, indica necessidade de suporte interno. <strong>Ação:</strong> Avaliar dimensionamento de analistas, priorização de produtos de maior retorno financeiro e otimização de automações de cálculo.</p></div>"
				        & "  <div class='guide-card'><h3>Volume Elevado em Reunião Técnica</h3><p>Representa o nosso <strong>pipeline de faturamento de curto prazo</strong>. São diagnósticos já calculados e finalizados internamente que aguardam apenas a agenda comercial de homologação técnica. <strong>Ação:</strong> Cobrar os responsáveis pelas contas (Commercial Account Managers) para acelerar o agendamento dessas reuniões, destravando a receita.</p></div>"
				        & "  <div class='guide-card'><h3>Uso Estratégico dos Filtros</h3><p>Utilize os filtros do topo para isolar produtos específicos ou períodos cadastrais. Na aba <strong>Detalhamento</strong>, você pode extrair a lista nominal exata de todos os clientes e jobs correspondentes à sua seleção, permitindo cobrar diretamente os responsáveis por cada contrato.</p></div>"
				        & "</div>"
				        & "</div></details>"
				        & "<details class='doc-section' id='sec08'><summary><span class='summary-title'>08. Segurança Jurídica, Compliance e Formas de Monetização</span><span class='summary-chevron'>›</span></summary><div class='section-body'>"
				        & "<p>Para responder a dúvidas frequentes dos clientes e parceiros sobre os laudos gerados pelo Grupo Studio, o Diretor deve dominar as seguintes premissas de compliance e monetização:</p>"
				        & "<h2>Como o cliente usufrui dos créditos encontrados (Monetização)?</h2>"
				        & "<ul>"
				        & "<li><strong>1. Compensação Tributária (PER/DCOMP):</strong> É a forma mais ágil de monetização. O crédito homologado é utilizado para compensar (abater) débitos tributários federais correntes gerados mensalmente pela empresa (como o PIS, COFINS, IRPJ, CSLL e contribuições previdenciárias patronais). A compensação é informada eletronicamente à Receita Federal e gera impacto imediato de caixa positivo para o cliente, que deixa de desembolsar o dinheiro dos impostos do mês.</li>"
				        & "<li><strong>2. Restituição Financeira (Dinheiro na Conta):</strong> O cliente solicita à Receita Federal o depósito em dinheiro do valor do crédito tributário em sua conta bancária. Esse processo é comum para empresas que não geram impostos suficientes a pagar para compensar o saldo credor. É um processo que passa por auditoria manual e depósito governamental, podendo levar de 6 meses a alguns anos dependendo do regime do produto.</li>"
				        & "<li><strong>3. Retificação Contábil-Fiscal:</strong> Para dar segurança à compensação ou restituição, o Grupo Studio retifica as declarações fiscais do cliente (SPEDs, DCTFs, etc.) do período correspondente. Isso insere oficialmente o crédito na conta corrente fiscal do cliente junto à Receita Federal.</li>"
				        & "</ul>"
				        & "<h2>Segurança Jurídica das Auditorias</h2>"
				        & "<p>O Grupo Studio atua com o mais alto nível de compliance, reduzindo a zero os riscos de fiscalização do cliente:</p>"
				        & "<ul>"
				        & "<li><strong>Teses de Jurisprudência Pacífica:</strong> Trabalhamos apenas com teses já transitadas em julgado e sumuladas pelos tribunais superiores (STF e STJ) ou que possuem autorização expressa em Soluções de Consulta COSIT da Receita Federal. Não aplicamos teses de risco ou de interpretação duvidosa.</li>"
				        & "<li><strong>Cruzamento Estritamente Matemático:</strong> A auditoria baseia-se no cruzamento eletrônico dos arquivos digitais (SPEDs e XMLs) que a própria empresa enviou originalmente ao fisco. O que fazemos é identificar erros de preenchimento ou pagamentos a maior gerados por erros de parametrização interna do cliente.</li>"
				        & "</ul>"
				        & "</div></details>"
				        & "<details class='doc-section' id='sec09' open><summary><span class='summary-title'>09. Perguntas Frequentes (FAQ & Dúvidas Comuns)</span><span class='summary-chevron'>›</span></summary><div class='section-body'>"
				        & "  <div class='faq-item'><div class='faq-q'>Por que os números de cartões mudam quando aplico filtros de produtos?</div><div class='faq-a'>Diferente da estrutura antiga, a lógica atual calcula os números de forma dinâmica. Se você filtrar pelo produto <em>'Crédito Acumulado de ICMS'</em>, os cartões de Journeys e Jobs mostrarão apenas os contratos e serviços que pertencem a essa vertical. Isso garante visibilidade setorial real.</div></div>"
				        & "  <div class='faq-item'><div class='faq-q'>O que muda de fato se eu desativar a limitação ao critério FIM = 1?</div><div class='faq-a'>A coluna <code>FIM</code> indica se aquela linha é a versão final ativa (<code>1</code>) ou um histórico inativo (<code>0</code>). Se você desativar esse filtro e contar todas as linhas indistintamente, o painel contará as versões históricas antigas do mesmo serviço. O resultado será um número inflado artificialmente, que não condiz com a quantidade de serviços que de fato correm na operação hoje. Mantê-la restrita ao <strong>FIM = 1</strong> é vital para a precisão estatística.</div></div>"
				        & "  <div class='faq-item'><div class='faq-q'>E se eu deixar o status FIM = 0 ativado e disponível também, o que muda?</div><div class='faq-a'>Deixar ambos disponíveis permite ver toda a trilha de auditoria e versionamentos históricos na base. Isso é útil para auditoria pontual da TI (para saber quantas alterações um contrato sofreu), mas prejudica a leitura gerencial da diretoria, pois a soma geral de jobs ativos e inativos duplicará a contagem de clientes e serviços em andamento. No relatório gerencial, ocultamos o 0 por padrão para simplificar a visão executiva.</div></div>"
				        & "  <div class='faq-item'><div class='faq-q'>Como posso exportar a lista de serviços de uma etapa específica para o Excel?</div><div class='faq-a'>Vá para a aba de <strong>Detalhamento</strong>, selecione o produto ou etapa desejada nos filtros do painel central e clique no botão <strong>Copiar</strong> (canto superior direito da área de filtros). Abra uma planilha em branco no Excel e aperte <strong>Ctrl+V</strong>. Toda a listagem ativa formatada será transferida instantaneamente.</div></div>"
				        & "  <div class='faq-item'><div class='faq-q'>O que significa quando o status do serviço está como 'Inativo' na lista?</div><div class='faq-a'>Significa que o registro representa uma versão anterior de um job (versionado histórico - FIM = 0). O painel o traz na aba de documentação geral apenas para fins de auditoria detalhada, mas ele não entra nos cálculos de metas operacionais e KPIs executivos.</div></div>"
				        & "  <div class='faq-item'><div class='faq-q'>O que são os serviços que constam como 'Sem Etapa'?</div><div class='faq-a'>São jobs ativos (em andamento, FIM = 1) que ainda não possuem um registro de menor área operacional associado no banco de dados. Isso geralmente ocorre nas primeiras horas após a assinatura do contrato e indica que o serviço está aguardando parametrização inicial pela TI ou pelo suporte operacional para ingressar na primeira etapa do funil.</div></div>"
				        & "</div></details>"
				        & "<div class='footer-doc'><span>Produtos distintos mapeados no recorte: " & FORMAT ( vProdutos, vIntFormat ) & "</span><span>Atualizado em " & vAtualizado & "</span></div>"
				        & "<script>"
				        & "(function(){"
				        & "    var tip;"
				        & "    function ensure(){"
				        & "        if(tip) return tip;"
				        & "        tip = document.createElement('div');"
				        & "        tip.className = 'float-tip';"
				        & "        document.body.appendChild(tip);"
				        & "        return tip;"
				        & "    }"
				        & "    function place(e){"
				        & "        if(!tip) return;"
				        & "        var pad=18, w=tip.offsetWidth||360, h=tip.offsetHeight||120, x=e.clientX+pad, y=e.clientY+pad;"
				        & "        if(x+w > window.innerWidth-8) x = e.clientX-w-pad;"
				        & "        if(y+h > window.innerHeight-8) y = e.clientY-h-pad;"
				        & "        tip.style.left = Math.max(8, x)+'px';"
				        & "        tip.style.top = Math.max(8, y)+'px';"
				        & "    }"
				        & "    function bind(){"
				        & "        document.querySelectorAll('[data-tip]').forEach(function(el){"
				        & "            if(el.getAttribute('data-tip-bound')) return;"
				        & "            el.setAttribute('data-tip-bound','1');"
				        & "            el.addEventListener('mouseenter',function(e){"
				        & "                var t=ensure();"
				        & "                t.innerHTML=el.getAttribute('data-tip')||'';"
				        & "                t.classList.add('on');"
				        & "                place(e);"
				        & "            });"
				        & "            el.addEventListener('mousemove',place);"
				        & "            el.addEventListener('mouseleave',function(){"
				        & "                if(tip) tip.classList.remove('on');"
				        & "            });"
				        & "        });"
				        & "    }"
				        & "    if(document.readyState==='loading'){"
				        & "        document.addEventListener('DOMContentLoaded',bind);"
				        & "    }else{"
				        & "        setTimeout(bind,50);"
				        & "    }"
				        & "})();"
				        & "</script>"
				        & "</div></main></div></div>"
			```       & "        });"
				        & "    }"
				        & "    if(document.readyState==='loading'){"
				        & "        document.addEventListener('DOMContentLoaded',bind);"
				        & "    }else{"
				        & "        setTimeout(bind,50);"
				        & "    }"
				        & "})();"
				        & "</script>"
				        & "</div></main></div></div>"
			```
		displayFolder: HTML
		lineageTag: f12039a5-a0eb-4967-9a5c-c2c27638806e

	/// Detalhamento operacional no mesmo layout anterior, com as novas views de Journey.
	measure 'HTML Macro Oportunidades x Jobs | Aba Documentação' = ```
				VAR vIntFormat = "#,##0"
				VAR vLimiteLinhas = 3000
				VAR vCalendarStart = MIN ( 'dCalendar'[Date] )
				VAR vCalendarEnd = MAX ( 'dCalendar'[Date] )
				VAR vHasCalendarFilter = COUNTROWS ( 'dCalendar' ) < COUNTROWS ( ALL ( 'dCalendar' ) )
				VAR vPeriodo =
				    IF (
				        vHasCalendarFilter,
				        FORMAT ( vCalendarStart, "dd/MM/yyyy" ) & " a " & FORMAT ( vCalendarEnd, "dd/MM/yyyy" ),
				        "Todo o período"
				    )
				VAR vHasJobFilter =
				    ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[JOB] )
				        || ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[CODIGO] )
				        || ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[CODIGO_PRODUTO] )
				        || ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[GppNome] )
				VAR vJourneysPeriod =
				    SELECTCOLUMNS (
				        FILTER (
				            ALLSELECTED ( 'vw_powerbi_journeys' ),
				            NOT vHasCalendarFilter
				                || (
				                    'vw_powerbi_journeys'[DATA_CADASTRO] >= vCalendarStart
				                        && 'vw_powerbi_journeys'[DATA_CADASTRO] < vCalendarEnd + 1
				                )
				        ),
				        "__JourneyJob", 'vw_powerbi_journeys'[JOB],
				        "__Fim", 'vw_powerbi_journeys'[FIM]
				    )
				VAR vJobsPeriod =
				    ADDCOLUMNS (
				        SELECTCOLUMNS (
				            FILTER (
				                ALLSELECTED ( 'vw_powerbi_journeys_filhos_novos' ),
				                NOT vHasCalendarFilter
				                    || (
				                        'vw_powerbi_journeys_filhos_novos'[DATA_CADASTRO] >= vCalendarStart
				                            && 'vw_powerbi_journeys_filhos_novos'[DATA_CADASTRO] < vCalendarEnd + 1
				                    )
				            ),
				            "__Codigo", 'vw_powerbi_journeys_filhos_novos'[CODIGO],
				            "__Job", 'vw_powerbi_journeys_filhos_novos'[JOB],
				            "__Data", 'vw_powerbi_journeys_filhos_novos'[DATA_CADASTRO],
				            "__Produto", COALESCE ( 'vw_powerbi_journeys_filhos_novos'[GppNome], "Sem produto" ),
				            "__Fim", 'vw_powerbi_journeys_filhos_novos'[FIM]
				        ),
				        "__Journey", VAR j = COALESCE ( [__Job], "" ) RETURN LEFT ( j, SEARCH ( "-", j & "-", 1, LEN ( j ) + 1 ) - 1 )
				    )
				VAR vAreas =
				    SELECTCOLUMNS (
				        ALLSELECTED ( 'vw_powerbi_journeys_menor_area_novos' ),
				        "__PmvJob", 'vw_powerbi_journeys_menor_area_novos'[PmvJob],
				        "__Etapa", COALESCE ( 'vw_powerbi_journeys_menor_area_novos'[ParNome], "SEM ETAPA" )
				    )
				VAR vHasEtapaFilter =
				    ISFILTERED ( 'vw_powerbi_journeys_menor_area_novos'[ParNome] )
				        || ISFILTERED ( 'vw_powerbi_journeys_menor_area_novos'[PmvArea] )
				        || ISFILTERED ( 'vw_powerbi_journeys_menor_area_novos'[PmvJob] )
				VAR vAreaJobCodes = DISTINCT ( SELECTCOLUMNS ( vAreas, "__Codigo", [__PmvJob] ) )
				VAR vJobsPeriodEtapa = FILTER ( vJobsPeriod, NOT vHasEtapaFilter || [__Codigo] IN vAreaJobCodes )
				VAR vJobParents = DISTINCT ( SELECTCOLUMNS ( vJobsPeriodEtapa, "__JourneyJob", [__Journey] ) )
				VAR vJourneysBase = FILTER ( vJourneysPeriod, NOT ( vHasJobFilter || vHasEtapaFilter ) || [__JourneyJob] IN vJobParents )
				VAR vJourneyKeys = DISTINCT ( SELECTCOLUMNS ( vJourneysBase, "__JourneyJob", [__JourneyJob] ) )
				VAR vJobsBase = FILTER ( vJobsPeriodEtapa, [__Journey] IN vJourneyKeys )
				VAR vDetalheAll =
				    ADDCOLUMNS (
				        vJobsBase,
				        "__Etapa", VAR c = [__Codigo] RETURN COALESCE ( MAXX ( FILTER ( vAreas, [__PmvJob] = c ), [__Etapa] ), IF ( [__Fim] = 1, "SEM ETAPA", "INATIVO" ) ),
				        "__Status", IF ( [__Fim] = 1, "Ativo", "Inativo" )
				    )
				VAR vDetalheTop = TOPN ( vLimiteLinhas, vDetalheAll, [__Data], DESC, [__Job], ASC )
				VAR vTotalRows = COUNTROWS ( vDetalheAll )
				VAR vRowsVisiveis = COUNTROWS ( vDetalheTop )
				VAR vJourneys = COUNTROWS ( vJourneysBase )
				VAR vJourneysAtivos = COUNTROWS ( FILTER ( vJourneysBase, [__Fim] = 1 ) )
				VAR vJobs = COUNTROWS ( vJobsBase )
				VAR vJobsAtivos = COUNTROWS ( FILTER ( vJobsBase, [__Fim] = 1 ) )
				VAR vPctAtivosJourneys = DIVIDE ( vJourneysAtivos, vJourneys, 0 )
				VAR vInativosJourneys = vJourneys - vJourneysAtivos
				VAR vCrossSell = DIVIDE ( vJobs, vJourneys, 0 )
				VAR vPctAtivosJobs = DIVIDE ( vJobsAtivos, vJobs, 0 )
				VAR vCSS =
				"
				<style>
				:root{--bg:#050A0F;--panel:#0E1720;--panel2:#111D27;--line:rgba(255,255,255,.075);--gold:#F4D9A9;--gold2:#D5AE77;--teal:#8BE0D1;--text:#F4F7FA;--muted:#A8B4C0;--dim:#6D7A86;--red:#FF9C93;--green:#7BEEA6;--blue:#9CCBFF}
				html,body{margin:0;padding:0;background:var(--bg);color:var(--text);font-family:'Segoe UI',Arial,sans-serif;overflow:hidden}.wrap{height:calc(100vh - 2px);box-sizing:border-box;padding:18px;border-radius:20px;border:1px solid rgba(213,174,119,.28);background:radial-gradient(circle at 0 0,rgba(213,174,119,.15),transparent 30%),radial-gradient(circle at 100% 0,rgba(139,224,209,.09),transparent 28%),linear-gradient(135deg,#101A24,#050A0F);box-shadow:0 22px 60px rgba(0,0,0,.45);display:flex;flex-direction:column}.head{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:12px}.title{color:var(--gold);font-size:30px;font-weight:1000;letter-spacing:.07em;text-transform:uppercase}.subtitle{color:var(--muted);font-size:16px;font-weight:850;margin-top:5px;line-height:1.25}.period{color:var(--teal);font-size:15px;font-weight:1000;border:1px solid rgba(139,224,209,.32);background:rgba(139,224,209,.08);border-radius:999px;padding:10px 14px;white-space:nowrap}.kpis{display:grid;grid-template-columns:repeat(5,minmax(145px,1fr));gap:12px;margin-bottom:14px}.kpi{position:relative;padding:15px 18px 14px;border-radius:17px;background:linear-gradient(155deg,rgba(18,31,42,.98),rgba(9,15,21,.96));border:1px solid rgba(255,255,255,.10);box-shadow:0 12px 24px rgba(0,0,0,.24);overflow:hidden;transition:transform .15s ease,border-color .15s ease,box-shadow .15s ease;display:flex;align-items:center;justify-content:space-between;gap:10px}.kpi:before{content:'';position:absolute;left:14px;top:0;width:42px;height:4px;border-radius:0 0 10px 10px;background:linear-gradient(90deg,var(--gold),var(--teal))}.kpi:hover{transform:translateY(-3px);border-color:rgba(244,217,169,.42);box-shadow:0 18px 34px rgba(0,0,0,.32)}.kpi-content{min-width:0;flex:1;display:flex;flex-direction:column;align-items:flex-start}.kpi-label{display:block;color:var(--muted);font-size:11.5px;font-weight:1000;text-transform:uppercase;letter-spacing:.08em}.kpi-value{display:block;color:var(--gold);font-size:32px;font-weight:1000;margin-top:8px;line-height:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.kpi-note{display:block;color:var(--dim);font-size:11px;font-weight:850;line-height:1.25;margin-top:6px}.kpi-side-badge{display:flex;flex-direction:column;align-items:center;justify-content:center;padding:8px 10px;border-radius:10px;background:linear-gradient(135deg,rgba(213,174,119,.08),rgba(139,224,209,.04));border:1px solid rgba(213,174,119,.18);min-width:88px;text-align:center;transition:all .15s ease}.kpi-side-badge .badge-val{color:var(--gold);font-size:16px;font-weight:1000;line-height:1.15}.kpi-side-badge .badge-lbl{color:var(--muted);font-size:9.0px;font-weight:1000;text-transform:uppercase;letter-spacing:.05em;margin-top:3px}.kpi:hover .kpi-side-badge{background:linear-gradient(135deg,rgba(213,174,119,.16),rgba(139,224,209,.07));border-color:var(--gold2);transform:scale(1.03)}.controls.doc-filters{display:grid!important;grid-template-columns:1.25fr repeat(6,minmax(0,1fr)) auto!important;gap:9px!important;margin-bottom:12px!important;align-items:end!important}.doc-filter{display:flex;flex-direction:column;gap:5px;min-width:0}.doc-filter label{color:var(--gold2);font-size:11px;font-weight:1000;letter-spacing:.075em;text-transform:uppercase}.doc-filter input,.doc-filter select{height:42px;width:100%;box-sizing:border-box;border:1px solid rgba(213,174,119,.28);background:#071018;color:#F4F7FA;border-radius:11px;padding:0 11px;font-size:13px;font-weight:850;outline:none;box-shadow:inset 0 1px 0 rgba(255,255,255,.04)}.doc-filter input:focus,.doc-filter select:focus{border-color:rgba(139,224,209,.62);box-shadow:0 0 0 3px rgba(139,224,209,.08),inset 0 1px 0 rgba(255,255,255,.06)}.doc-actions{display:flex;gap:8px;align-items:end;justify-content:flex-end}.btn{border:1px solid rgba(213,174,119,.34);background:rgba(213,174,119,.10);color:var(--gold);border-radius:12px;height:42px;padding:0 13px;font-size:12px;font-weight:1000;letter-spacing:.06em;text-transform:uppercase;cursor:pointer;white-space:nowrap;transition:transform .15s ease,background .15s ease}.btn:hover{transform:translateY(-2px);background:rgba(213,174,119,.18)}.table-wrap{flex:1;min-height:0;overflow-y:auto;overflow-x:hidden;border:1px solid rgba(213,174,119,.16);border-radius:18px;background:rgba(255,255,255,.022);box-shadow:inset 0 1px 0 rgba(255,255,255,.035)}.table-wrap::-webkit-scrollbar{width:12px;height:0}.table-wrap::-webkit-scrollbar-track{background:#071018}.table-wrap::-webkit-scrollbar-thumb{background:linear-gradient(180deg,rgba(244,217,169,.78),rgba(139,224,209,.44));border:3px solid #071018;border-radius:999px}table{border-collapse:collapse;width:100%;min-width:0;table-layout:fixed}th{position:sticky;top:0;z-index:4;background:linear-gradient(180deg,#111D27,#0B141D);color:var(--gold2);font-size:14px;font-weight:1000;text-transform:uppercase;letter-spacing:.07em;padding:15px 13px;text-align:left;border-bottom:1px solid rgba(213,174,119,.25);white-space:nowrap}
th:nth-child(1),td:nth-child(1){width:32%;text-align:left;padding-left:12px}
th:nth-child(2),td:nth-child(2){width:8%;text-align:center}
th:nth-child(3),td:nth-child(3){width:12%;text-align:center}
th:nth-child(4),td:nth-child(4){width:8%;text-align:center}
th:nth-child(5),td:nth-child(5){width:16%;text-align:center}
th:nth-child(6),td:nth-child(6){width:10%;text-align:center}
th:nth-child(7),td:nth-child(7){width:14%;text-align:right;padding-right:12px}
td{font-size:16px;font-weight:820;color:#EEF3F8;padding:15px 13px;border-bottom:1px solid rgba(255,255,255,.055);vertical-align:middle;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;line-height:1.25}tr{transition:background .14s ease,transform .14s ease}tr:hover td{background:rgba(213,174,119,.075)}tr:hover{transform:translateX(2px)}td.prod{font-weight:1000;color:#FFF2DE}td.journey,td.job,td.codigo{font-family:Consolas,'Courier New',monospace;color:var(--gold);font-size:15px}td.date{font-family:Consolas,'Courier New',monospace;color:#B9C7D5;font-size:15px;text-align:center}.chip{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:8px 12px;font-size:13px;font-weight:1000;text-transform:uppercase;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.055);min-width:100px}.ativo{color:#8BE0D1;border-color:rgba(139,224,209,.25)}.inativo{color:var(--red);border-color:rgba(255,156,147,.25)}.etapa{color:#F4D9A9;border-color:rgba(244,217,169,.25)}.foot{margin-top:11px;color:var(--dim);font-size:14px;font-weight:850}.empty{margin:24px;padding:34px;border:1px dashed rgba(213,174,119,.30);border-radius:18px;color:var(--muted);text-align:center;font-size:18px;font-weight:900}@media(max-width:1200px){.controls.doc-filters{grid-template-columns:repeat(4,minmax(0,1fr))!important}.doc-actions{justify-content:flex-start}.kpis{grid-template-columns:repeat(5,minmax(145px,1fr));overflow-x:auto}}
				[data-tip]{position:relative;cursor:help}.kpi[data-tip]:hover,th[data-tip]:hover{outline:1px solid rgba(244,217,169,.22);outline-offset:-1px}.float-tip{position:fixed;z-index:2147483647;display:none;max-width:500px;min-width:280px;padding:16px 18px;border-radius:15px;background:linear-gradient(160deg,rgba(7,12,18,.99),rgba(15,27,36,.99));border:1px solid rgba(244,217,169,.45);color:#F4F7FA;font-family:'Segoe UI',Arial,sans-serif;font-size:15px;font-weight:800;line-height:1.5;text-align:left;box-shadow:0 18px 40px rgba(0,0,0,.48),0 0 0 1px rgba(139,224,209,.08),inset 0 1px 0 rgba(255,255,255,.07);pointer-events:none;white-space:normal}.float-tip.on{display:block}.float-tip b{color:#F4D9A9}.float-tip code{color:#8BE0D1;font-family:Consolas,'Courier New',monospace;font-size:.95em}
				</style>
				<script>
				function normDoc(s){try{return (s||'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}catch(e){return (s||'').toString().toLowerCase();}}
				function valDoc(id){var el=document.getElementById(id);return el?normDoc(el.value):'';}
				function filtrarDoc(){var q=valDoc('q');var fProd=valDoc('fDocProduto');var fJourney=valDoc('fDocJourney');var fJob=valDoc('fDocJob');var fCodigo=valDoc('fDocCodigo');var fEtapa=valDoc('fDocEtapa');var fStatus=valDoc('fDocStatus');var rows=document.querySelectorAll('.linha');var n=0;rows.forEach(function(r){var ok=true;var txt=normDoc(r.textContent);if(q&&txt.indexOf(q)===-1)ok=false;if(fProd&&normDoc(r.getAttribute('data-prod')).indexOf(fProd)===-1)ok=false;if(fJourney&&normDoc(r.getAttribute('data-journey')).indexOf(fJourney)===-1)ok=false;if(fJob&&normDoc(r.getAttribute('data-job')).indexOf(fJob)===-1)ok=false;if(fCodigo&&normDoc(r.getAttribute('data-codigo')).indexOf(fCodigo)===-1)ok=false;if(fEtapa&&normDoc(r.getAttribute('data-etapa')).indexOf(fEtapa)===-1)ok=false;if(fStatus&&normDoc(r.getAttribute('data-status')).indexOf(fStatus)===-1)ok=false;r.style.display=ok?'':'none';if(ok)n++;});var hasFilter=(q||fProd||fJourney||fJob||fCodigo||fEtapa||fStatus);var el=document.getElementById('vis');if(el)el.textContent=hasFilter?n:el.getAttribute('data-total');var empty=document.getElementById('docNoMatch');if(empty)empty.style.display=n===0?'block':'none';}
				function limparFiltrosDoc(){['q','fDocProduto','fDocJourney','fDocJob','fDocCodigo','fDocEtapa','fDocStatus'].forEach(function(id){var el=document.getElementById(id);if(el)el.value='';});filtrarDoc();}
				function copiarTabela(){var rows=document.querySelectorAll('tr');var out=[];rows.forEach(function(r){if(r.className==='linha'&&r.style.display==='none')return;var cells=r.querySelectorAll('th,td');var vals=[];cells.forEach(function(c){vals.push(c.textContent.trim().replace(/\s+/g,' '));});out.push(vals.join('\t'));});var ta=document.createElement('textarea');ta.value=out.join('\r\n');document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta);var b=document.getElementById('copy');var old=b.innerHTML;b.innerHTML='Copiado';setTimeout(function(){b.innerHTML=old},1800);}
				setTimeout(filtrarDoc,100);
				(function(){var tip;function ensure(){if(tip)return tip;tip=document.createElement('div');tip.className='float-tip';document.body.appendChild(tip);return tip;}function place(e){if(!tip)return;var pad=18,w=tip.offsetWidth||360,h=tip.offsetHeight||120,x=e.clientX+pad,y=e.clientY+pad;if(x+w>window.innerWidth-8)x=e.clientX-w-pad;if(y+h>window.innerHeight-8)y=e.clientY-h-pad;tip.style.left=Math.max(8,x)+'px';tip.style.top=Math.max(8,y)+'px';}function bind(){document.querySelectorAll('[data-tip]').forEach(function(el){if(el.getAttribute('data-tip-bound'))return;el.setAttribute('data-tip-bound','1');el.addEventListener('mouseenter',function(e){var t=ensure();t.innerHTML=el.getAttribute('data-tip')||'';t.classList.add('on');place(e);});el.addEventListener('mousemove',place);el.addEventListener('mouseleave',function(){if(tip)tip.classList.remove('on');});});}if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',bind);}else{setTimeout(bind,50);}})();
				</script>
				"
				VAR vRowsHTML =
				    CONCATENATEX (
				        vDetalheTop,
				        VAR vProdutoAttr = SUBSTITUTE ( [__Produto], "'", "&#39;" )
				        VAR vJourneyAttr = SUBSTITUTE ( [__Journey], "'", "&#39;" )
				        VAR vJobAttr = SUBSTITUTE ( [__Job], "'", "&#39;" )
				        VAR vCodigoTxt = [__Codigo] & ""
				        VAR vCodigoAttr = SUBSTITUTE ( vCodigoTxt, "'", "&#39;" )
				        VAR vEtapaAttr = SUBSTITUTE ( [__Etapa], "'", "&#39;" )
				        VAR vStatusAttr = SUBSTITUTE ( [__Status], "'", "&#39;" )
				        VAR vDataTxt = IF ( ISBLANK ( [__Data] ), "-", FORMAT ( [__Data], "dd/MM/yyyy HH:mm" ) )
				        RETURN
				            "<tr class='linha' data-prod='" & vProdutoAttr & "' data-journey='" & vJourneyAttr & "' data-job='" & vJobAttr & "' data-codigo='" & vCodigoAttr & "' data-etapa='" & vEtapaAttr & "' data-status='" & vStatusAttr & "'>"
				                & "<td class='prod' title='" & vProdutoAttr & "'>" & [__Produto] & "</td>"
				                & "<td class='journey'>" & [__Journey] & "</td>"
				                & "<td class='job'>" & [__Job] & "</td>"
				                & "<td class='codigo'>" & vCodigoTxt & "</td>"
				                & "<td class='date'>" & vDataTxt & "</td>"
				                & "<td><span class='chip " & IF ( [__Status] = "Ativo", "ativo", "inativo" ) & "'>" & [__Status] & "</span></td>"
				                & "<td><span class='chip etapa'>" & [__Etapa] & "</span></td>"
				            & "</tr>",
				        "",
				        [__Data], DESC,
				        [__Produto], ASC,
				        [__Job], ASC
				    )
				VAR vTipJourneys = "<b>JOURNEYS (JORNADAS PAI)</b><br/>Quantidade total de jornadas pai no período e filtros ativos.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys</code><br/><b>Colunas Usadas:</b> <code>CODIGO</code>, <code>JOB</code>, <code>DATA_CADASTRO</code>, <code>FIM</code><br/><b>Regra de Cálculo:</b> Conta as linhas da tabela de jornadas filtradas pela coluna <code>DATA_CADASTRO</code> no slicer de período. Se filtros de produto, job ou etapa estiverem ativos (tabela de jobs filhos), a listagem restringe-se apenas aos journeys vinculados a esses jobs correspondentes."
				VAR vTipJourneysAtivos = "<b>JOURNEYS ATIVOS (FIM = 1)</b><br/>Quantidade de jornadas pai consideradas ativas no recorte selecionado.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys</code><br/><b>Colunas Usadas:</b> <code>CODIGO</code>, <code>JOB</code>, <code>DATA_CADASTRO</code>, <code>FIM</code><br/><b>Regra de Cálculo:</b> Filtra as jornadas do período pelo critério <code>vw_powerbi_journeys[FIM] = 1</code>. Respeita os filtros cruzados de produtos, jobs e etapas aplicados no painel."
				VAR vTipJobs = "<b>JOBS (TRABALHOS FILHOS)</b><br/>Quantidade total de jobs filhos associados a jornadas no recorte selecionado.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code><br/><b>Colunas Usadas:</b> <code>CODIGO</code>, <code>JOB</code>, <code>DATA_CADASTRO</code>, <code>CODIGO_PRODUTO</code>, <code>GppNome</code>, <code>FIM</code><br/><b>Regra de Cálculo:</b> Conta os jobs cujos pais (jornadas) estão no período de cadastro selecionado. Os jobs são cruzados com os filtros de produto e etapa aplicados."
				VAR vTipJobsAtivos = "<b>JOBS ATIVOS (FIM = 1)</b><br/>Quantidade de jobs filhos com status ativo no recorte selecionado.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code><br/><b>Colunas Usadas:</b> <code>CODIGO</code>, <code>JOB</code>, <code>DATA_CADASTRO</code>, <code>FIM</code><br/><b>Regra de Cálculo:</b> Filtra a lista de jobs do recorte pelo critério <code>vw_powerbi_journeys_filhos_novos[FIM] = 1</code>. A etapa atual mostrada na distribuição do produto é baseada apenas nestes jobs ativos."
				VAR vTipLinhas = "<b>LINHAS EXIBIDAS</b><br/>Quantidade total de jobs filhos retornados sob os filtros atuais e exibidos na tabela abaixo.<br/><br/><b>Origem:</b> Total de registros avaliados em tempo de execução no modelo sem o limite de paginação visual."
				VAR vTipHeaderProd = "<b>PRODUTO (LINHA)</b><br/>Agrupamento dos jobs filhos por produto.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code><br/><b>Coluna:</b> <code>GppNome</code>"
				VAR vTipHeaderJourney = "<b>JOURNEY (JORNADA PAI)</b><br/>Identificador da jornada pai do job.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys</code><br/><b>Coluna:</b> <code>JOB</code>"
				VAR vTipHeaderJob = "<b>JOB (IDENTIFICADOR DO JOB)</b><br/>Identificador único do job filho.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code><br/><b>Coluna:</b> <code>JOB</code>"
				VAR vTipHeaderCodigo = "<b>CÓDIGO DO JOB</b><br/>Código numérico chave do job filho.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code><br/><b>Coluna:</b> <code>CODIGO</code>"
				VAR vTipHeaderCadastro = "<b>DATA DE CADASTRO</b><br/>Data e hora de registro do job filho.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code><br/><b>Coluna:</b> <code>DATA_CADASTRO</code>"
				VAR vTipHeaderStatus = "<b>STATUS DO JOB</b><br/>Indica se o job está ativo ou inativo com base na regra oficial.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code><br/><b>Regra:</b> Ativo se <code>FIM = 1</code>, Inativo se <code>FIM &lt;&gt; 1</code>"
				VAR vTipHeaderEtapa = "<b>ETAPA ATUAL</b><br/>Menor área atual do job ativo.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_menor_area_novos</code><br/><b>Colunas:</b> <code>ParNome</code>, <code>PmvJob</code>"
				RETURN
				    vCSS
				        & "<div class='wrap'>"
				            & "<div class='head'><div><div class='title'>Detalhamento Journey x Jobs</div><div class='subtitle'>Detalhamento por produto, journey, job, status e etapa atual.</div></div><div class='period'>" & vPeriodo & "</div></div>"
				            & "<div class='kpis'>"
				                & "<div class='kpi primary' data-tip='" & vTipJourneys & "'><div class='kpi-content'><div class='kpi-label'>Clientes (Journeys)</div><div class='kpi-value'>" & FORMAT ( vJourneys, vIntFormat ) & "</div><div class='kpi-note'>Volume total de contratos</div></div><div class='kpi-side-badge'><div class='badge-val'>" & FORMAT ( vPctAtivosJourneys, "0.0%" ) & "</div><div class='badge-lbl'>Ativos</div></div></div>"
				                & "<div class='kpi attention' data-tip='" & vTipJourneysAtivos & "'><div class='kpi-content'><div class='kpi-label'>Clientes Ativos</div><div class='kpi-value'>" & FORMAT ( vJourneysAtivos, vIntFormat ) & "</div><div class='kpi-note'>Operação vigente em andamento</div></div><div class='kpi-side-badge'><div class='badge-val'>" & FORMAT ( vInativosJourneys, vIntFormat ) & "</div><div class='badge-lbl'>Históricos</div></div></div>"
				                & "<div class='kpi primary' data-tip='" & vTipJobs & "'><div class='kpi-content'><div class='kpi-label'>Serviços (Jobs)</div><div class='kpi-value'>" & FORMAT ( vJobs, vIntFormat ) & "</div><div class='kpi-note'>Subprodutos solicitados</div></div><div class='kpi-side-badge'><div class='badge-val'>" & FORMAT ( vCrossSell, "0.0" ) & "</div><div class='badge-lbl'>Jobs/Cliente</div></div></div>"
				                & "<div class='kpi attention' data-tip='" & vTipJobsAtivos & "'><div class='kpi-content'><div class='kpi-label'>Serviços Ativos</div><div class='kpi-value'>" & FORMAT ( vJobsAtivos, vIntFormat ) & "</div><div class='kpi-note'>Carga de trabalho em execução</div></div><div class='kpi-side-badge'><div class='badge-val'>" & FORMAT ( vPctAtivosJobs, "0.0%" ) & "</div><div class='badge-lbl'>Operando</div></div></div>"
				                & "<div class='kpi' data-tip='" & vTipLinhas & "'><div class='kpi-content'><div class='kpi-label'>Linhas Exibidas</div><div class='kpi-value'><span id='vis' data-total='" & FORMAT ( vTotalRows, vIntFormat ) & "'>" & FORMAT ( vTotalRows, vIntFormat ) & "</span></div><div class='kpi-note'>Registros na tabela abaixo</div></div><div class='kpi-side-badge'><div class='badge-val'>Tabela</div><div class='badge-lbl'>Operacional</div></div></div>"
				            & "</div>"
				            & "<div class='controls doc-filters'><div class='doc-filter'><label>Busca geral</label><input id='q' class='search' oninput='filtrarDoc()' placeholder='Buscar em todas as colunas'></div><div class='doc-filter'><label>Produto</label><input id='fDocProduto' oninput='filtrarDoc()' placeholder='Produto'></div><div class='doc-filter'><label>Journey</label><input id='fDocJourney' oninput='filtrarDoc()' placeholder='Journey'></div><div class='doc-filter'><label>Job</label><input id='fDocJob' oninput='filtrarDoc()' placeholder='Job'></div><div class='doc-filter'><label>Código</label><input id='fDocCodigo' oninput='filtrarDoc()' placeholder='Código'></div><div class='doc-filter'><label>Etapa</label><input id='fDocEtapa' oninput='filtrarDoc()' placeholder='Etapa'></div><div class='doc-filter'><label>Status</label><select id='fDocStatus' onchange='filtrarDoc()'><option value=''>Todos</option><option value='Ativo'>Ativo</option><option value='Inativo'>Inativo</option></select></div><div class='doc-actions'><button class='btn' onclick='limparFiltrosDoc()'>Limpar</button><button id='copy' class='btn' onclick='copiarTabela()'>Copiar</button></div></div>"
				            & "<div class='table-wrap'><table><thead><tr><th data-tip='" & vTipHeaderProd & "'>Produto</th><th data-tip='" & vTipHeaderJourney & "'>Journey</th><th data-tip='" & vTipHeaderJob & "'>Job</th><th data-tip='" & vTipHeaderCodigo & "'>Código</th><th data-tip='" & vTipHeaderCadastro & "'>Cadastro</th><th data-tip='" & vTipHeaderStatus & "'>Status</th><th data-tip='" & vTipHeaderEtapa & "'>Etapa Atual</th></tr></thead><tbody>" & IF ( ISBLANK ( vRowsHTML ), "<tr><td colspan='7'>Nenhum registro encontrado.</td></tr>", vRowsHTML ) & "</tbody></table><div id='docNoMatch' class='empty' style='display:none'>Nenhum registro encontrado para os filtros internos.</div></div>"
				            & "<div class='foot'>Exibindo " & FORMAT ( vRowsVisiveis, vIntFormat ) & " de " & FORMAT ( vTotalRows, vIntFormat ) & " linhas. Se o total for maior que o limite, use slicers para reduzir o recorte.</div>"
				        & "</div>"
			```
		displayFolder: HTML
		lineageTag: 7cc4cf4f-59eb-4360-8f7e-9a14c4534d03

	/// Visual principal com 4 cards e tabela de produtos usando as views novas.
	measure 'HTML Macro Oportunidades x Jobs | Tela Principal' = ```
				VAR vIntFormat = "#,##0"
				VAR vPctFormat = "0.0%"
				VAR vTopProdutos = 40
				VAR vTopDetalhes = 12
				VAR vCalendarStart = MIN ( 'dCalendar'[Date] )
				VAR vCalendarEnd = MAX ( 'dCalendar'[Date] )
				VAR vHasCalendarFilter = COUNTROWS ( 'dCalendar' ) < COUNTROWS ( ALL ( 'dCalendar' ) )
				VAR vHasJobFilter =
				    ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[JOB] )
				        || ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[CODIGO] )
				        || ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[CODIGO_PRODUTO] )
				        || ISFILTERED ( 'vw_powerbi_journeys_filhos_novos'[GppNome] )
				VAR vJourneysPeriod =
				    SELECTCOLUMNS (
				        FILTER (
				            ALLSELECTED ( 'vw_powerbi_journeys' ),
				            NOT vHasCalendarFilter
				                || (
				                    'vw_powerbi_journeys'[DATA_CADASTRO] >= vCalendarStart
				                        && 'vw_powerbi_journeys'[DATA_CADASTRO] < vCalendarEnd + 1
				                )
				        ),
				        "__JourneyCodigo", 'vw_powerbi_journeys'[CODIGO],
				        "__JourneyJob", 'vw_powerbi_journeys'[JOB],
				        "__Fim", 'vw_powerbi_journeys'[FIM],
				        "__Data", 'vw_powerbi_journeys'[DATA_CADASTRO]
				    )
				VAR vJobsPeriod =
				    ADDCOLUMNS (
				        SELECTCOLUMNS (
				            FILTER (
				                ALLSELECTED ( 'vw_powerbi_journeys_filhos_novos' ),
				                NOT vHasCalendarFilter
				                    || (
				                        'vw_powerbi_journeys_filhos_novos'[DATA_CADASTRO] >= vCalendarStart
				                            && 'vw_powerbi_journeys_filhos_novos'[DATA_CADASTRO] < vCalendarEnd + 1
				                    )
				            ),
				            "__Codigo", 'vw_powerbi_journeys_filhos_novos'[CODIGO],
				            "__Job", 'vw_powerbi_journeys_filhos_novos'[JOB],
				            "__Data", 'vw_powerbi_journeys_filhos_novos'[DATA_CADASTRO],
				            "__ProdutoCodigo", 'vw_powerbi_journeys_filhos_novos'[CODIGO_PRODUTO],
				            "__Produto", COALESCE ( 'vw_powerbi_journeys_filhos_novos'[GppNome], "Sem produto" ),
				            "__Fim", 'vw_powerbi_journeys_filhos_novos'[FIM]
				        ),
				        "__ParentJob", VAR j = [__Job] RETURN LEFT ( j, SEARCH ( "-", j & "-", 1, LEN ( j ) + 1 ) - 1 )
				    )
				VAR vAreas =
				    SELECTCOLUMNS (
				        ALLSELECTED ( 'vw_powerbi_journeys_menor_area_novos' ),
				        "__PmvJob", 'vw_powerbi_journeys_menor_area_novos'[PmvJob],
				        "__Etapa", COALESCE ( 'vw_powerbi_journeys_menor_area_novos'[ParNome], "SEM ETAPA" )
				    )
				VAR vHasEtapaFilter =
				    ISFILTERED ( 'vw_powerbi_journeys_menor_area_novos'[ParNome] )
				        || ISFILTERED ( 'vw_powerbi_journeys_menor_area_novos'[PmvArea] )
				        || ISFILTERED ( 'vw_powerbi_journeys_menor_area_novos'[PmvJob] )
				VAR vAreaJobCodes = DISTINCT ( SELECTCOLUMNS ( vAreas, "__Codigo", [__PmvJob] ) )
				VAR vJobsPeriodEtapa = FILTER ( vJobsPeriod, NOT vHasEtapaFilter || [__Codigo] IN vAreaJobCodes )
				VAR vJobParents = DISTINCT ( SELECTCOLUMNS ( vJobsPeriodEtapa, "__JourneyJob", [__ParentJob] ) )
				VAR vJourneysBase = FILTER ( vJourneysPeriod, NOT ( vHasJobFilter || vHasEtapaFilter ) || [__JourneyJob] IN vJobParents )
				VAR vJourneyKeys = DISTINCT ( SELECTCOLUMNS ( vJourneysBase, "__ParentJob", [__JourneyJob] ) )
				VAR vJobsBase = FILTER ( vJobsPeriodEtapa, [__ParentJob] IN vJourneyKeys )
				VAR vJourneys = COUNTROWS ( vJourneysBase )
				VAR vJourneysAtivos = COUNTROWS ( FILTER ( vJourneysBase, [__Fim] = 1 ) )
				VAR vJobsTotais = COUNTROWS ( vJobsBase )
				VAR vJobsAtivos = COUNTROWS ( FILTER ( vJobsBase, [__Fim] = 1 ) )
				VAR vPctAtivosJourneys = DIVIDE ( vJourneysAtivos, vJourneys, 0 )
				VAR vInativosJourneys = vJourneys - vJourneysAtivos
				VAR vCrossSell = DIVIDE ( vJobsTotais, vJourneys, 0 )
				VAR vPctAtivosJobs = DIVIDE ( vJobsAtivos, vJobsTotais, 0 )
				VAR vPeriodo =
				    IF (
				        vHasCalendarFilter,
				        FORMAT ( vCalendarStart, "dd/MM/yyyy" ) & " a " & FORMAT ( vCalendarEnd, "dd/MM/yyyy" ),
				        "Todo o período"
				    )
				VAR vProdutos = SUMMARIZE ( vJobsBase, [__ProdutoCodigo], [__Produto] )
				VAR vProductSummary =
				    ADDCOLUMNS (
				        vProdutos,
				        "__Jobs", VAR p = [__ProdutoCodigo] RETURN COUNTROWS ( FILTER ( vJobsBase, [__ProdutoCodigo] = p ) ),
				        "__Ativos", VAR p = [__ProdutoCodigo] RETURN COUNTROWS ( FILTER ( vJobsBase, [__ProdutoCodigo] = p && [__Fim] = 1 ) ),
				        "__Cadastro", VAR p = [__ProdutoCodigo] VAR jobsP = SELECTCOLUMNS ( FILTER ( vJobsBase, [__ProdutoCodigo] = p && [__Fim] = 1 ), "__PmvJob", [__Codigo] ) RETURN COUNTROWS ( FILTER ( vAreas, [__PmvJob] IN jobsP && [__Etapa] = "CADASTRO" ) ),
				        "__Procuracao", VAR p = [__ProdutoCodigo] VAR jobsP = SELECTCOLUMNS ( FILTER ( vJobsBase, [__ProdutoCodigo] = p && [__Fim] = 1 ), "__PmvJob", [__Codigo] ) RETURN COUNTROWS ( FILTER ( vAreas, [__PmvJob] IN jobsP && [__Etapa] = "PROCURAÇÃO ELETRÔNICA" ) ),
				        "__Checklist", VAR p = [__ProdutoCodigo] VAR jobsP = SELECTCOLUMNS ( FILTER ( vJobsBase, [__ProdutoCodigo] = p && [__Fim] = 1 ), "__PmvJob", [__Codigo] ) RETURN COUNTROWS ( FILTER ( vAreas, [__PmvJob] IN jobsP && [__Etapa] = "CHECKLIST" ) ),
				        "__Operacao", VAR p = [__ProdutoCodigo] VAR jobsP = SELECTCOLUMNS ( FILTER ( vJobsBase, [__ProdutoCodigo] = p && [__Fim] = 1 ), "__PmvJob", [__Codigo] ) RETURN COUNTROWS ( FILTER ( vAreas, [__PmvJob] IN jobsP && [__Etapa] = "OPERAÇÃO" ) ),
				        "__Reuniao", VAR p = [__ProdutoCodigo] VAR jobsP = SELECTCOLUMNS ( FILTER ( vJobsBase, [__ProdutoCodigo] = p && [__Fim] = 1 ), "__PmvJob", [__Codigo] ) RETURN COUNTROWS ( FILTER ( vAreas, [__PmvJob] IN jobsP && [__Etapa] = "REUNIÃO TÉCNICA" ) ),
				        "__Fim", VAR p = [__ProdutoCodigo] VAR jobsP = SELECTCOLUMNS ( FILTER ( vJobsBase, [__ProdutoCodigo] = p && [__Fim] = 1 ), "__PmvJob", [__Codigo] ) RETURN COUNTROWS ( FILTER ( vAreas, [__PmvJob] IN jobsP && [__Etapa] = "FIM" ) )
				    )
				VAR vProductTop = TOPN ( vTopProdutos, vProductSummary, [__Jobs], DESC, [__Ativos], DESC, [__Produto], ASC )
				VAR vCSS =
				"
				<style>
				:root{--bg:#060A0F;--panel:#0E1720;--panel2:#121F2A;--line:rgba(255,255,255,.08);--gold:#F4D9A9;--gold2:#D5AE77;--teal:#8BE0D1;--text:#F4F7FA;--muted:#A8B4C0;--dim:#6D7A86;--red:#FF9C93;--green:#7BEEA6;--blue:#9CCBFF}.diag-wrap{font-family:'Segoe UI',Arial,sans-serif;width:100%;height:calc(100vh - 2px);box-sizing:border-box;color:var(--text);background:radial-gradient(circle at 0% 0%,rgba(213,174,119,.22),transparent 34%),radial-gradient(circle at 100% 0%,rgba(139,224,209,.14),transparent 30%),linear-gradient(135deg,#101A24 0%,#060A0F 100%);border:1px solid rgba(213,174,119,.32);border-radius:22px;overflow:auto;box-shadow:0 24px 70px rgba(0,0,0,.46)}.diag-wrap::-webkit-scrollbar{width:14px;height:12px}.diag-wrap::-webkit-scrollbar-track{background:#060A0F;border-radius:999px}.diag-wrap::-webkit-scrollbar-thumb{background:linear-gradient(180deg,rgba(244,217,169,.78),rgba(139,224,209,.44));border:3px solid #060A0F;border-radius:999px}.sticky{position:relative!important;z-index:2;background:rgba(8,13,19,.985);border-bottom:1px solid rgba(213,174,119,.22);box-shadow:0 12px 24px rgba(0,0,0,.24);overflow:visible}.diag-head{padding:16px 26px 22px;overflow:visible}.slicer-space{height:auto;min-height:76px;margin-bottom:14px;border-radius:18px;border:0;background:transparent;box-shadow:none;padding:12px 0;display:flex;justify-content:flex-end;align-items:center}.detailbar{width:430px;display:flex;justify-content:stretch;align-items:center}.detail-pill{height:38px;width:100%;display:flex;align-items:center;justify-content:center;border-radius:11px;border:1px solid rgba(213,174,119,.42);background:linear-gradient(135deg,rgba(213,174,119,.16),rgba(139,224,209,.08));color:var(--gold);font-size:12px;font-weight:1000;letter-spacing:.08em;text-transform:uppercase;box-shadow:inset 0 1px 0 rgba(255,255,255,.05),0 10px 20px rgba(0,0,0,.16)}.detail-pill span{color:var(--teal);margin-left:7px}.kpis{display:grid;grid-template-columns:repeat(4,minmax(210px,1fr));gap:12px;overflow:visible}.kpi{position:relative;min-width:0;padding:15px 20px 14px;border-radius:18px;background:linear-gradient(155deg,rgba(18,31,42,.98),rgba(9,15,21,.96));border:1px solid rgba(255,255,255,.10);box-shadow:0 18px 34px rgba(0,0,0,.25),inset 0 1px 0 rgba(255,255,255,.06);overflow:visible;display:flex;align-items:center;justify-content:space-between;gap:12px}.kpi:before{content:'';position:absolute;left:18px;top:0;width:56px;height:5px;border-radius:0 0 10px 10px;background:linear-gradient(90deg,var(--gold),var(--teal))}.kpi.primary{border-color:rgba(213,174,119,.46);background:linear-gradient(155deg,rgba(213,174,119,.18),rgba(18,31,42,.98) 38%,rgba(9,15,21,.96))}.kpi.attention{border-color:rgba(139,224,209,.32);background:linear-gradient(155deg,rgba(139,224,209,.13),rgba(18,31,42,.98) 38%,rgba(9,15,21,.96))}.kpi-content{min-width:0;flex:1;display:flex;flex-direction:column;align-items:flex-start}.kpi-label{color:var(--muted);font-size:11.5px;font-weight:1000;letter-spacing:.09em;text-transform:uppercase}.kpi-value{margin-top:10px;color:var(--gold);font-size:34px;font-weight:1000;line-height:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.kpi-note{margin-top:8px;color:var(--dim);font-size:12px;font-weight:850;line-height:1.25}.kpi-side-badge{display:flex;flex-direction:column;align-items:center;justify-content:center;padding:10px 12px;border-radius:12px;background:linear-gradient(135deg,rgba(213,174,119,.08),rgba(139,224,209,.04));border:1px solid rgba(213,174,119,.18);min-width:96px;text-align:center;transition:all .15s ease}.kpi-side-badge .badge-val{color:var(--gold);font-size:17px;font-weight:1000;line-height:1.15}.kpi-side-badge .badge-lbl{color:var(--muted);font-size:9.5px;font-weight:1000;text-transform:uppercase;letter-spacing:.05em;margin-top:4px}.kpi:hover .kpi-side-badge{background:linear-gradient(135deg,rgba(213,174,119,.16),rgba(139,224,209,.07));border-color:var(--gold2);transform:scale(1.03)}.table-head,.row-grid{display:grid;grid-template-columns:340px repeat(8,minmax(105px,.9fr))!important;min-width:1280px!important}.rows{min-width:1280px!important}.table-head{position:sticky!important;top:0!important;z-index:65;background:linear-gradient(180deg,#0F1923 0%,#0A121A 100%);border-bottom:1px solid rgba(213,174,119,.18);box-shadow:0 14px 26px rgba(0,0,0,.35);overflow:visible}.table-head div{padding:13px 10px;color:var(--gold2);font-size:12.8px;line-height:1.16;font-weight:1000;text-transform:uppercase;letter-spacing:.09em;text-align:center;border-right:1px solid rgba(255,255,255,.035);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.table-head div:first-child{text-align:left;padding-left:24px}.diag-row{border-bottom:1px solid rgba(255,255,255,.055);position:relative;z-index:1;overflow:visible}.diag-row summary{list-style:none;cursor:pointer}.diag-row summary::-webkit-details-marker{display:none}.row-grid{align-items:stretch;background:linear-gradient(90deg,rgba(11,18,25,.92) 0%,rgba(6,13,20,.96) 100%)}.row-grid:hover{background:linear-gradient(90deg,rgba(18,27,35,.96) 0%,rgba(7,15,23,.98) 100%)}.prod-cell{position:relative;min-height:92px;padding:10px 14px;display:flex;flex-direction:column;justify-content:center;align-items:flex-start;min-width:0}.prod-title{color:#FFF7EC;font-size:18px;font-weight:1000;line-height:1.16;margin-bottom:7px}.prod-sub{margin-top:0;color:#AEB9C4;font-size:12.5px;line-height:1.28;font-weight:800}.prod-progress{margin-top:10px;width:100%;height:6px;border-radius:999px;background:rgba(255,255,255,.08);overflow:hidden;box-shadow:inset 0 1px 0 rgba(255,255,255,.05)}.prod-progress span{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,#F4D9A9 0%,#8BE0D1 100%)}.metric{position:relative;display:flex;flex-direction:column;justify-content:center;align-items:center;min-height:92px;text-align:center;padding:8px 6px;gap:4px;border-left:1px solid rgba(255,255,255,.06);background:transparent;min-width:0}.metric:hover{background:rgba(255,255,255,.02);box-shadow:inset 0 0 0 1px rgba(255,255,255,.03)}.metric b{color:var(--text);font-size:21px;line-height:1.05;font-weight:1000;white-space:nowrap}.metric small{margin-top:0;color:#95A2AF;font-size:10.6px;line-height:1.18;font-weight:950;text-transform:uppercase;letter-spacing:.04em}.metric.active b{color:#8BE0D1}.metric.cad b{color:#A8B4C0}.metric.proc b{color:#9CCBFF}.metric.check b{color:#F4D9A9}.metric.oper b{color:#FFCF87}.metric.reu b{color:#8BE0D1}.metric.fim b{color:#B4BBC4}.details{display:grid;grid-template-columns:1fr 1fr;gap:18px;padding:14px 16px 16px;background:rgba(2,7,12,.44);border-top:1px solid rgba(213,174,119,.16)}.card{border:1px solid rgba(213,174,119,.18);background:rgba(255,255,255,.04);border-radius:18px;padding:16px;min-width:0}.card-title{color:var(--gold);font-size:12px;font-weight:1000;letter-spacing:.06em;text-transform:uppercase;margin-bottom:13px}.stage-line{display:grid;grid-template-columns:155px 1fr 70px 68px;align-items:center;gap:10px;min-height:36px;border-bottom:1px solid rgba(255,255,255,.055);font-size:14px;font-weight:850}.bar{height:9px;border-radius:999px;background:rgba(255,255,255,.08);overflow:hidden}.bar span{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,var(--gold2),var(--teal))}.num{text-align:right;font-weight:1000;color:#fff}.pcttxt{text-align:right;color:var(--muted);font-size:10.5px;font-weight:950}.det-head,.det-row{display:grid;grid-template-columns:1fr 1fr 1fr;gap:9px;align-items:center}.det-head{color:var(--gold2);font-size:11.5px;font-weight:1000;text-transform:uppercase;letter-spacing:.055em;padding-bottom:9px;border-bottom:1px solid rgba(213,174,119,.18)}.det-row{min-height:38px;color:#E8EEF5;font-size:13.5px;font-weight:820;border-bottom:1px solid rgba(255,255,255,.05)}.det-row div{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chip{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:5px 9px;font-size:11px;font-weight:1000;text-transform:uppercase;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.05);color:#8BE0D1}.empty{margin:24px;padding:34px;border:1px dashed rgba(213,174,119,.30);border-radius:18px;color:var(--muted);text-align:center;font-size:18px;font-weight:900}.foot{padding:12px 24px 26px;color:var(--dim);font-size:13px;font-weight:800}.det-rows-scroll{max-height:240px;overflow-y:auto;overflow-x:hidden;padding-right:4px}@media(max-width:1000px){.kpis{grid-template-columns:repeat(4,minmax(210px,1fr));overflow-x:auto}.details{grid-template-columns:1fr}.table-head,.row-grid{grid-template-columns:300px repeat(8,minmax(98px,.9fr))!important;min-width:1160px!important}.rows{min-width:1160px!important}.detailbar{width:360px}.slicer-space{min-height:96px}}
				[data-tip]{position:relative;cursor:help}.kpi[data-tip]:hover,.metric[data-tip]:hover,.prod-cell[data-tip]:hover,.table-head div[data-tip]:hover,.stage-line[data-tip]:hover{outline:1px solid rgba(244,217,169,.22);outline-offset:-1px}.float-tip{position:fixed;z-index:2147483647;display:none;max-width:500px;min-width:280px;padding:16px 18px;border-radius:15px;background:linear-gradient(160deg,rgba(7,12,18,.99),rgba(15,27,36,.99));border:1px solid rgba(244,217,169,.45);color:#F4F7FA;font-family:'Segoe UI',Arial,sans-serif;font-size:15px;font-weight:800;line-height:1.5;text-align:left;box-shadow:0 18px 40px rgba(0,0,0,.48),0 0 0 1px rgba(139,224,209,.08),inset 0 1px 0 rgba(255,255,255,.07);pointer-events:none;white-space:normal}.float-tip.on{display:block}.float-tip b{color:#F4D9A9}.float-tip code{color:#8BE0D1;font-family:Consolas,'Courier New',monospace;font-size:.95em}
				</style>
				<script>
				(function(){var tip;function ensure(){if(tip)return tip;tip=document.createElement('div');tip.className='float-tip';document.body.appendChild(tip);return tip;}function place(e){if(!tip)return;var pad=18,w=tip.offsetWidth||360,h=tip.offsetHeight||120,x=e.clientX+pad,y=e.clientY+pad;if(x+w>window.innerWidth-8)x=e.clientX-w-pad;if(y+h>window.innerHeight-8)y=e.clientY-h-pad;tip.style.left=Math.max(8,x)+'px';tip.style.top=Math.max(8,y)+'px';}function bind(){document.querySelectorAll('[data-tip]').forEach(function(el){if(el.getAttribute('data-tip-bound'))return;el.setAttribute('data-tip-bound','1');el.addEventListener('mouseenter',function(e){var t=ensure();t.innerHTML=el.getAttribute('data-tip')||'';t.classList.add('on');place(e);});el.addEventListener('mousemove',place);el.addEventListener('mouseleave',function(){if(tip)tip.classList.remove('on');});});}if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',bind);}else{setTimeout(bind,50);}})();
				</script>
				"
				VAR vTipJourneys = "<b>JOURNEYS (JORNADAS PAI)</b><br/>Quantidade total de jornadas pai no período e filtros ativos.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys</code><br/><b>Colunas Usadas:</b> <code>CODIGO</code>, <code>JOB</code>, <code>DATA_CADASTRO</code>, <code>FIM</code><br/><b>Regra de Cálculo:</b> Conta as linhas da tabela de jornadas filtradas pela coluna <code>DATA_CADASTRO</code> no slicer de período. Se filtros de produto, job ou etapa estiverem ativos (tabela de jobs filhos), a listagem restringe-se apenas aos journeys vinculados a esses jobs correspondentes."
				VAR vTipJourneysAtivos = "<b>JOURNEYS ATIVOS (FIM = 1)</b><br/>Quantidade de jornadas pai consideradas ativas no recorte selecionado.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys</code><br/><b>Colunas Usadas:</b> <code>CODIGO</code>, <code>JOB</code>, <code>DATA_CADASTRO</code>, <code>FIM</code><br/><b>Regra de Cálculo:</b> Filtra as jornadas do período pelo critério <code>vw_powerbi_journeys[FIM] = 1</code>. Respeita os filtros cruzados de produtos, jobs e etapas aplicados no painel."
				VAR vTipJobs = "<b>JOBS (TRABALHOS FILHOS)</b><br/>Quantidade total de jobs filhos associados a jornadas no recorte selecionado.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code><br/><b>Colunas Usadas:</b> <code>CODIGO</code>, <code>JOB</code>, <code>DATA_CADASTRO</code>, <code>CODIGO_PRODUTO</code>, <code>GppNome</code>, <code>FIM</code><br/><b>Regra de Cálculo:</b> Conta os jobs cujos pais (jornadas) estão no período de cadastro selecionado. Os jobs são cruzados com os filtros de produto e etapa aplicados."
				VAR vTipJobsAtivos = "<b>JOBS ATIVOS (FIM = 1)</b><br/>Quantidade de jobs filhos com status ativo no recorte selecionado.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code><br/><b>Colunas Usadas:</b> <code>CODIGO</code>, <code>JOB</code>, <code>DATA_CADASTRO</code>, <code>FIM</code><br/><b>Regra de Cálculo:</b> Filtra a lista de jobs do recorte pelo critério <code>vw_powerbi_journeys_filhos_novos[FIM] = 1</code>. A etapa atual mostrada na distribuição do produto é baseada apenas nestes jobs ativos."
				VAR vTipHeaderProd = "<b>PRODUTO (LINHA)</b><br/>Agrupamento dos jobs filhos por produto.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code><br/><b>Coluna:</b> <code>GppNome</code>"
				VAR vTipHeaderJobs = "<b>JOBS DO PRODUTO</b><br/>Total de jobs filhos vinculados a este produto no período selecionado.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_filhos_novos</code>"
				VAR vTipHeaderAtivos = "<b>ATIVOS DO PRODUTO</b><br/>Total de jobs filhos ativos do produto.<br/><br/><b>Regra:</b> <code>FIM = 1</code> na tabela <code>vw_powerbi_journeys_filhos_novos</code>"
				VAR vTipHeaderCad = "<b>ETAPA ATUAL: CADASTRO</b><br/>Jobs ativos do produto cuja menor área atual é Cadastro.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_menor_area_novos</code><br/><b>Coluna:</b> <code>ParNome</code> = 'CADASTRO'"
				VAR vTipHeaderProc = "<b>ETAPA ATUAL: PROCURAÇÃO ELETRÔNICA</b><br/>Jobs ativos do produto parados na etapa Procuração Eletrônica.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_menor_area_novos</code><br/><b>Coluna:</b> <code>ParNome</code> = 'PROCURAÇÃO ELETRÔNICA'"
				VAR vTipHeaderCheck = "<b>ETAPA ATUAL: CHECKLIST</b><br/>Jobs ativos do produto na etapa Checklist.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_menor_area_novos</code><br/><b>Coluna:</b> <code>ParNome</code> = 'CHECKLIST'"
				VAR vTipHeaderOper = "<b>ETAPA ATUAL: OPERAÇÃO</b><br/>Jobs ativos do produto na etapa Operação.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_menor_area_novos</code><br/><b>Coluna:</b> <code>ParNome</code> = 'OPERAÇÃO'"
				VAR vTipHeaderReu = "<b>ETAPA ATUAL: REUNIÃO TÉCNICA</b><br/>Jobs ativos do produto na etapa Reunião Técnica.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_menor_area_novos</code><br/><b>Coluna:</b> <code>ParNome</code> = 'REUNIÃO TÉCNICA'"
				VAR vTipHeaderFim = "<b>ETAPA ATUAL: FIM</b><br/>Jobs ativos do produto na etapa Fim (finalizados).<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_menor_area_novos</code><br/><b>Coluna:</b> <code>ParNome</code> = 'FIM'"
				VAR vCards =
				    "<div class='kpis'>"
				        & "<div class='kpi primary' data-tip='" & vTipJourneys & "'><div class='kpi-content'><div class='kpi-label'>Clientes (Journeys)</div><div class='kpi-value'>" & FORMAT ( vJourneys, vIntFormat ) & "</div><div class='kpi-note'>Volume total de contratos</div></div><div class='kpi-side-badge'><div class='badge-val'>" & FORMAT ( vPctAtivosJourneys, "0.0%" ) & "</div><div class='badge-lbl'>Ativos</div></div></div>"
				        & "<div class='kpi attention' data-tip='" & vTipJourneysAtivos & "'><div class='kpi-content'><div class='kpi-label'>Clientes Ativos</div><div class='kpi-value'>" & FORMAT ( vJourneysAtivos, vIntFormat ) & "</div><div class='kpi-note'>Operação vigente em andamento</div></div><div class='kpi-side-badge'><div class='badge-val'>" & FORMAT ( vInativosJourneys, vIntFormat ) & "</div><div class='badge-lbl'>Históricos</div></div></div>"
				        & "<div class='kpi primary' data-tip='" & vTipJobs & "'><div class='kpi-content'><div class='kpi-label'>Serviços (Jobs)</div><div class='kpi-value'>" & FORMAT ( vJobsTotais, vIntFormat ) & "</div><div class='kpi-note'>Subprodutos solicitados</div></div><div class='kpi-side-badge'><div class='badge-val'>" & FORMAT ( vCrossSell, "0.0" ) & "</div><div class='badge-lbl'>Jobs/Cliente</div></div></div>"
				        & "<div class='kpi attention' data-tip='" & vTipJobsAtivos & "'><div class='kpi-content'><div class='kpi-label'>Serviços Ativos</div><div class='kpi-value'>" & FORMAT ( vJobsAtivos, vIntFormat ) & "</div><div class='kpi-note'>Carga de trabalho em execução</div></div><div class='kpi-side-badge'><div class='badge-val'>" & FORMAT ( vPctAtivosJobs, "0.0%" ) & "</div><div class='badge-lbl'>Operando</div></div></div>"
				    & "</div>"
				VAR vHead =
				    "<div class='table-head'>"
				        & "<div data-tip='" & vTipHeaderProd & "'>Produto</div>"
				        & "<div data-tip='" & vTipHeaderJobs & "'>Jobs</div>"
				        & "<div data-tip='" & vTipHeaderAtivos & "'>Ativos</div>"
				        & "<div data-tip='" & vTipHeaderCad & "'>Cadastro</div>"
				        & "<div data-tip='" & vTipHeaderProc & "'>Procur.</div>"
				        & "<div data-tip='" & vTipHeaderCheck & "'>Checklist</div>"
				        & "<div data-tip='" & vTipHeaderOper & "'>Operação</div>"
				        & "<div data-tip='" & vTipHeaderReu & "'>Reunião</div>"
				        & "<div data-tip='" & vTipHeaderFim & "'>Fim</div>"
				    & "</div>"
				VAR vRows =
				    CONCATENATEX (
				        vProductTop,
				        VAR p = [__Produto]
				        VAR pTip = SUBSTITUTE ( p, "'", "&#39;" )
				        VAR pc = [__ProdutoCodigo]
				        VAR vJobs = [__Jobs]
				        VAR vAtivos = [__Ativos]
				        VAR vCad = [__Cadastro]
				        VAR vProc = [__Procuracao]
				        VAR vCheck = [__Checklist]
				        VAR vOper = [__Operacao]
				        VAR vReu = [__Reuniao]
				        VAR vFim = [__Fim]
				        VAR vPctAtivos = DIVIDE ( vAtivos, vJobs, 0 )
				        VAR vTotalEtapas = vCad + vProc + vCheck + vOper + vReu + vFim
				        VAR vStageTable =
				            UNION (
				                ROW ( "Ordem", 1, "Etapa", "Cadastro", "Qtd", vCad, "Class", "cad" ),
				                ROW ( "Ordem", 2, "Etapa", "Procuração", "Qtd", vProc, "Class", "proc" ),
				                ROW ( "Ordem", 3, "Etapa", "Checklist", "Qtd", vCheck, "Class", "check" ),
				                ROW ( "Ordem", 4, "Etapa", "Operação", "Qtd", vOper, "Class", "oper" ),
				                ROW ( "Ordem", 5, "Etapa", "Reunião Técnica", "Qtd", vReu, "Class", "reu" ),
				                ROW ( "Ordem", 6, "Etapa", "Fim", "Qtd", vFim, "Class", "fim" )
				            )
				        VAR vStageCells =
				            "<div class='metric'><b>" & FORMAT ( vJobs, vIntFormat ) & "</b><small>jobs</small></div>"
				                & "<div class='metric active'><b>" & FORMAT ( vAtivos, vIntFormat ) & "</b><small>ativos</small></div>"
				                & CONCATENATEX (
				                    vStageTable,
				                    VAR q = [Qtd]
				                    VAR pct = DIVIDE ( q, vTotalEtapas, 0 )
				                    VAR cellTip = "<b>ETAPA: " & [Etapa] & "</b><br/>Jobs nesta etapa: <b>" & FORMAT ( q, vIntFormat ) & "</b> ativos.<br/>Representatividade no produto: <b>" & FORMAT ( pct, vPctFormat ) & "</b>.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_menor_area_novos</code><br/><b>Vínculo:</b> <code>PmvJob</code> = <code>CODIGO</code> do Job Filho.<br/><b>Coluna:</b> <code>ParNome</code>"
				                    RETURN "<div class='metric " & [Class] & "' data-tip='" & cellTip & "'><b>" & IF ( q = 0, "-", FORMAT ( q, vIntFormat ) ) & "</b><small>" & FORMAT ( pct, vPctFormat ) & "</small></div>",
				                    "",
				                    [Ordem], ASC
				                )
				        VAR vJobsProduto =
				            ADDCOLUMNS (
				                FILTER ( vJobsBase, [__ProdutoCodigo] = pc ),
				                "__Etapa", VAR c = [__Codigo] RETURN COALESCE ( MAXX ( FILTER ( vAreas, [__PmvJob] = c ), [__Etapa] ), IF ( [__Fim] = 1, "SEM ETAPA", "INATIVO" ) )
				            )
				        VAR vPrimeiros = TOPN ( vTopDetalhes, vJobsProduto, [__Data], ASC, [__Job], ASC )
				        VAR vUltimos = TOPN ( vTopDetalhes, vJobsProduto, [__Data], DESC, [__Job], DESC )
				        VAR vPrimeirosHTML =
				            CONCATENATEX (
				                vPrimeiros,
				                "<div class='det-row'><div>" & [__Job] & "</div><div><span class='chip'>" & [__Etapa] & "</span></div><div>" & FORMAT ( [__Data], "dd/MM/yyyy" ) & "</div></div>",
				                "",
				                [__Data], ASC
				            )
				        VAR vUltimosHTML =
				            CONCATENATEX (
				                vUltimos,
				                "<div class='det-row'><div>" & [__Job] & "</div><div><span class='chip'>" & [__Etapa] & "</span></div><div>" & FORMAT ( [__Data], "dd/MM/yyyy" ) & "</div></div>",
				                "",
				                [__Data], DESC
				            )
				        VAR vStageLines =
				            CONCATENATEX (
				                vStageTable,
				                VAR q = [Qtd]
				                VAR pct = DIVIDE ( q, vTotalEtapas, 0 )
				                VAR lineTip = "<b>ETAPA: " & [Etapa] & "</b><br/>Quantidade: <b>" & FORMAT ( q, vIntFormat ) & "</b> jobs ativos.<br/>Participação: <b>" & FORMAT ( pct, vPctFormat ) & "</b>.<br/><br/><b>Tabela Origem:</b> <code>vw_powerbi_journeys_menor_area_novos</code><br/><b>Coluna:</b> <code>ParNome</code>"
				                RETURN "<div class='stage-line' data-tip='" & lineTip & "'><div>" & [Etapa] & "</div><div class='bar'><span style='width:" & FORMAT ( ROUND ( pct * 100, 0 ), "0" ) & "%'></span></div><div class='num'>" & FORMAT ( q, vIntFormat ) & "</div><div class='pcttxt'>" & FORMAT ( pct, vPctFormat ) & "</div></div>",
				                "",
				                [Ordem], ASC
				            )
				        RETURN
				            "<details class='diag-row'><summary><div class='row-grid'>"
				                & "<div class='prod-cell' data-tip='<b>PRODUTO:</b> " & pTip & "<br/><br/><b>Total Jobs:</b> " & FORMAT ( vJobs, vIntFormat ) & " (tabela <code>vw_powerbi_journeys_filhos_novos</code>)<br/><b>Jobs Ativos:</b> " & FORMAT ( vAtivos, vIntFormat ) & " (regra <code>FIM = 1</code>)<br/><b>Percentual Ativo:</b> " & FORMAT ( vPctAtivos, vPctFormat ) & "<br/><b>Origem:</b> agrupamento por <code>vw_powerbi_journeys_filhos_novos[GppNome]</code>.'><div class='prod-title'>" & p & "</div><div class='prod-sub'>" & FORMAT ( vJobs, vIntFormat ) & " jobs · " & FORMAT ( vAtivos, vIntFormat ) & " ativos</div><div class='prod-progress'><span style='width:" & FORMAT ( ROUND ( vPctAtivos * 100, 0 ), "0" ) & "%'></span></div></div>"
				                & vStageCells
				            & "</div></summary><div class='details'>"
				                & "<div class='card'><div class='card-title'>Distribuição por etapa</div>" & vStageLines & "</div>"
				                & "<div class='card'><div class='card-title'>Primeiros e últimos jobs</div><div class='det-head'><div>Job</div><div>Etapa</div><div>Cadastro</div></div><div class='det-rows-scroll'>" & vPrimeirosHTML & vUltimosHTML & "</div></div>"
				            & "</div></details>",
				        "",
				        [__Jobs], DESC,
				        [__Produto], ASC
				    )
				VAR vNota = "Período: " & vPeriodo & ". Ativo nas novas views = FIM 1."
				RETURN
				    vCSS
				        & "<div class='diag-wrap'>"
				        & "<div class='sticky'><div class='diag-head'><div class='slicer-space'><div class='detailbar'><div class='detail-pill'>Abrir detalhamento <span>›</span></div></div></div>" & vCards & "</div></div>"
				        & vHead
				        & "<div class='rows'>" & IF ( ISBLANK ( vRows ), "<div class='empty'>Nenhum produto encontrado para os filtros atuais.</div>", vRows ) & "</div>"
				        & "<div class='foot'>" & vNota & "</div>"
				        & "</div>"
			```
		displayFolder: HTML
		lineageTag: b0000702-d1ag-ba5e-b010-ba5e00000702

	column Column
		formatString: 0
		lineageTag: 2ec931fb-c2e0-4926-ad68-5e513c5ba130
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition medidas_html = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 1fcf0b6930bb4e10a61b1c725afbbaf7

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

