table medidas_html
	lineageTag: f371007f-daa0-4acf-919c-58dc35ff6b74

	/// Cabeçalho executivo da DRE Gerencial TAX.
	measure Titulo_Diagnostico_HTML_2026_Novo_Estilo_DOCUMENTACAO = ```
			
			VAR vYearFixed = YEAR ( TODAY () )
			VAR vDateFormat = "dd/mm/yyyy"
			
			VAR vBase2026 =
			    FILTER (
			        ALL ( 'JOBS_Produto' ),
			        NOT ISBLANK ( 'JOBS_Produto'[JOB] )
			            && YEAR ( 'JOBS_Produto'[DATA_CADASTRO] ) = vYearFixed
			            && CONTAINSSTRING (
			                UPPER ( COALESCE ( 'JOBS_Produto'[NOME_PRODUTO], "" ) ),
			                "DIAGN"
			            )
			    )
			
			VAR vCalendarFilterStart =
			    MIN ( dCalendar[Date] )
			
			VAR vCalendarFilterEnd =
			    MAX ( dCalendar[Date] )
			
			VAR vHasCalendarFilter =
			    ISFILTERED ( dCalendar[Date] )
			        || ISFILTERED ( dCalendar[YearMonth] )
			        || ISFILTERED ( dCalendar[MonthNumber] )
			        || ISFILTERED ( dCalendar[Quarter] )
			
			VAR vBaseContext =
			    FILTER (
			        vBase2026,
			        'JOBS_Produto'[DATA_CADASTRO]
			            >= IF (
			                vHasCalendarFilter,
			                vCalendarFilterStart,
			                DATE ( vYearFixed, 1, 1 )
			            )
			            && 'JOBS_Produto'[DATA_CADASTRO]
			                <= IF (
			                    vHasCalendarFilter,
			                    vCalendarFilterEnd,
			                    DATE ( vYearFixed, 12, 31 )
			                )
			    )
			
			VAR vMinData =
			    MINX ( vBaseContext, 'JOBS_Produto'[DATA_CADASTRO] )
			
			VAR vMaxData =
			    MAXX ( vBaseContext, 'JOBS_Produto'[DATA_CADASTRO] )
			
			VAR vUltimoMovimento =
			    MAXX ( vBaseContext, 'JOBS_Produto'[TRIBUTO_DATA_ENTRADA] )
			
			VAR vPeriodo =
			    IF (
			        ISBLANK ( vMinData ) || ISBLANK ( vMaxData ),
			        "Período não definido",
			        FORMAT ( vMinData, vDateFormat ) & " a " & FORMAT ( vMaxData, vDateFormat )
			    )
			
			VAR vUltimoMovimentoTxt =
			    IF (
			        ISBLANK ( vUltimoMovimento ),
			        "Sem data",
			        FORMAT ( vUltimoMovimento, vDateFormat )
			    )
			
			VAR vDataAtual =
			    FORMAT ( NOW (), "dd/mm/yyyy HH:mm" )
			
			VAR vCSS =
			"
			<style>
			    * {
			        margin: 0;
			        padding: 0;
			        box-sizing: border-box;
			    }
			
			    .diag-title-shell {
			        width: 1910px;
			        min-width: 1910px;
			        max-width: 1910px;
			        height: 165px;
			        min-height: 165px;
			        max-height: 165px;
			        overflow: hidden;
			        font-family: 'Segoe UI', Arial, sans-serif;
			        color: #E8EEF5;
			        border-radius: 18px;
			        border: 1px solid rgba(213,174,119,.36);
			        background:
			            radial-gradient(circle at 0% 0%, rgba(213,174,119,.22), transparent 33%),
			            radial-gradient(circle at 92% 18%, rgba(139,224,209,.13), transparent 28%),
			            linear-gradient(135deg, #060B10 0%, #0B141B 46%, #10201F 100%);
			        box-shadow:
			            0 16px 38px rgba(0,0,0,.50),
			            inset 0 1px 0 rgba(255,255,255,.05);
			        position: relative;
			    }
			
			    .diag-title-shell:before {
			        content: '';
			        position: absolute;
			        left: 0;
			        top: 0;
			        bottom: 0;
			        width: 8px;
			        background: linear-gradient(180deg,#F4D9A9,#D5AE77,#8BE0D1);
			        opacity: .92;
			    }
			
			    .diag-title-grid {
			        position: relative;
			        z-index: 2;
			        width: 100%;
			        height: 100%;
			        display: grid;
			        grid-template-columns: 150px minmax(0,1fr) 430px;
			        align-items: center;
			        gap: 24px;
			        padding: 18px 26px 18px 34px;
			    }
			
			    .brand-panel {
			        height: 100%;
			        min-width: 0;
			        display: flex;
			        align-items: center;
			        justify-content: center;
			    }
			
			    .logo-card {
			        width: 118px;
			        height: 82px;
			        border-radius: 16px;
			        display: flex;
			        align-items: center;
			        justify-content: center;
			        padding: 10px;
			        background:
			            radial-gradient(circle at 28% 12%, rgba(213,174,119,.18), transparent 36%),
			            #030506;
			        border: 1px solid rgba(213,174,119,.40);
			        box-shadow:
			            0 12px 24px rgba(0,0,0,.34),
			            inset 0 1px 0 rgba(255,255,255,.06);
			        overflow: hidden;
			    }
			
			    .logo-text {
			        width: 100%;
			        height: 100%;
			        display: flex;
			        align-items: center;
			        justify-content: center;
			        gap: 0;
			        color: #FFFFFF;
			        font-family: Georgia, 'Times New Roman', serif;
			        font-size: 13px;
			        font-weight: 700;
			        line-height: 1;
			        letter-spacing: -0.05em;
			        text-align: center;
			        white-space: nowrap;
			        overflow: hidden;
			    }
			
			    .logo-text .studio {
			        color: #D5AE77;
			        margin-left: 1px;
			    }
			
			    .center-panel {
			        min-width: 0;
			        height: 100%;
			        display: flex;
			        flex-direction: column;
			        align-items: center;
			        justify-content: center;
			        gap: 8px;
			        text-align: center;
			        position: relative;
			    }
			
			    .center-panel:before,
			    .center-panel:after {
			        content: '';
			        width: 88px;
			        height: 1px;
			        background: linear-gradient(
			            90deg,
			            transparent,
			            rgba(213,174,119,.65),
			            transparent
			        );
			    }
			
			    .title-kicker {
			        color: #8BE0D1;
			        font-size: 10px;
			        font-weight: 950;
			        letter-spacing: .22em;
			        text-transform: uppercase;
			        line-height: 1;
			        white-space: nowrap;
			    }
			
			    .main-title {
			        color: #FFFFFF;
			        font-size: 38px;
			        font-weight: 950;
			        letter-spacing: .09em;
			        text-transform: uppercase;
			        line-height: 1;
			        white-space: nowrap;
			        overflow: hidden;
			        text-overflow: ellipsis;
			        text-shadow: 0 4px 16px rgba(0,0,0,.72);
			    }
			
			    .main-title .gold {
			        color: #F4D9A9;
			    }
			
			    .subline {
			        max-width: 100%;
			        color: #D5AE77;
			        font-size: 11px;
			        font-weight: 950;
			        letter-spacing: .10em;
			        text-transform: uppercase;
			        white-space: nowrap;
			        overflow: hidden;
			        text-overflow: ellipsis;
			    }
			
			    .right-panel {
			        height: 100%;
			        display: grid;
			        grid-template-columns: 168px minmax(0,1fr) 68px;
			        align-items: center;
			        gap: 14px;
			        min-width: 0;
			    }
			
			    .doc-title-button {
			        position: relative;
			        min-height: 44px;
			        display: inline-flex;
			        align-items: center;
			        justify-content: center;
			        padding: 12px 17px;
			        border-radius: 14px;
			        color: #081018;
			        border: 1px solid rgba(244,217,169,.72);
			        background: linear-gradient(135deg,#F4D9A9 0%,#D5AE77 48%,#8BE0D1 100%);
			        box-shadow:
			            0 14px 28px rgba(213,174,119,.24),
			            0 0 0 1px rgba(255,255,255,.08) inset,
			            0 0 22px rgba(139,224,209,.18);
			        font-size: 11px;
			        font-weight: 950;
			        letter-spacing: .10em;
			        text-transform: uppercase;
			        white-space: nowrap;
			        overflow: hidden;
			    }
			
			    .doc-title-button:before {
			        content: 'i';
			        display: inline-flex;
			        align-items: center;
			        justify-content: center;
			        width: 21px;
			        height: 21px;
			        margin-right: 8px;
			        border-radius: 50%;
			        background: rgba(8,16,24,.18);
			        border: 1px solid rgba(8,16,24,.24);
			        color: #081018;
			        font-size: 12px;
			        font-weight: 950;
			        font-style: italic;
			        line-height: 1;
			    }
			
			    .doc-title-button:after {
			        content: '';
			        position: absolute;
			        inset: -1px;
			        border-radius: 14px;
			        background: linear-gradient(90deg, transparent, rgba(255,255,255,.45), transparent);
			        transform: translateX(-125%);
			        animation: shineDoc 3.8s ease-in-out infinite;
			    }
			
			    @keyframes shineDoc {
			        0% { transform: translateX(-125%); }
			        48% { transform: translateX(-125%); }
			        72% { transform: translateX(125%); }
			        100% { transform: translateX(125%); }
			    }
			
			    .update-box {
			        display: flex;
			        flex-direction: column;
			        align-items: flex-end;
			        justify-content: center;
			        gap: 10px;
			        min-width: 0;
			    }
			
			    .update-line {
			        display: flex;
			        flex-direction: column;
			        align-items: flex-end;
			        gap: 3px;
			        min-width: 0;
			    }
			
			    .update-label {
			        color: #F4D9A9;
			        font-size: 9px;
			        font-weight: 950;
			        letter-spacing: .08em;
			        text-transform: uppercase;
			        white-space: nowrap;
			    }
			
			    .update-value {
			        color: #E8EEF5;
			        font-size: 12px;
			        font-weight: 900;
			        white-space: nowrap;
			        overflow: hidden;
			        text-overflow: ellipsis;
			        max-width: 160px;
			        text-align: right;
			    }
			
			    .avatar {
			        position: relative;
			        width: 62px;
			        height: 62px;
			        border-radius: 50%;
			        display: flex;
			        align-items: center;
			        justify-content: center;
			        color: #F4D9A9;
			        font-size: 18px;
			        font-weight: 950;
			        letter-spacing: .05em;
			        background:
			            linear-gradient(
			                145deg,
			                rgba(213,174,119,.14),
			                rgba(255,255,255,.035)
			            );
			        border: 1px solid rgba(213,174,119,.58);
			        box-shadow:
			            0 0 0 5px rgba(213,174,119,.06),
			            inset 0 1px 0 rgba(255,255,255,.10);
			    }
			
			    .avatar:after {
			        content: '';
			        position: absolute;
			        right: 2px;
			        bottom: 5px;
			        width: 9px;
			        height: 9px;
			        border-radius: 50%;
			        background: #21E66D;
			        box-shadow: 0 0 12px rgba(33,230,109,.75);
			        border: 2px solid #10201F;
			    }
			</style>
			"
			
			VAR vHTML =
			    "<div class='diag-title-shell'>"
			        & "<div class='diag-title-grid'>"
			
			            & "<div class='brand-panel'>"
			                & "<div class='logo-card'>"
			                    & "<div class='logo-text'>"
			                        & "<span>GRUPO</span><span class='studio'>STUDIO</span>"
			                    & "</div>"
			                & "</div>"
			            & "</div>"
			
			            & "<div class='center-panel'>"
			                & "<div class='title-kicker'>Grupo Studio · Monitoramento Operacional</div>"
			                & "<div class='main-title'>Diagnóstico <span class='gold'>- Journey</span></div>"
			                & "<div class='subline'>"
			                    & "Etapas, status e oportunidades | "
			                    & vPeriodo
			                & "</div>"
			            & "</div>"
			
			            & "<div class='right-panel'>"
			                & "<div class='doc-title-button'>Documentação</div>"
			                & "<div class='update-box'>"
			                    & "<div class='update-line'>"
			                        & "<span class='update-label'>Atualizado em</span>"
			                        & "<span class='update-value'>" & vDataAtual & "</span>"
			                    & "</div>"
			                    & "<div class='update-line'>"
			                        & "<span class='update-label'>Último movimento</span>"
			                        & "<span class='update-value'>" & vUltimoMovimentoTxt & "</span>"
			                    & "</div>"
			                & "</div>"
			                & "<div class='avatar'>GS</div>"
			            & "</div>"
			
			        & "</div>"
			    & "</div>"
			
			RETURN
			    vCSS & vHTML
			
			```
		displayFolder: 10 | HTML e Visual
		lineageTag: c4874ca8-7357-4c3e-b3e5-6180c4491f86

	/// Documentacao executiva e tecnica atualizada da DRE Gerencial TAX. Reflete a primeira aba atual: 4 cards premium, periodo dinamico, linhas, expansoes, regras oficiais, IRPJ/CSLL informativo e pontos de atencao.
	measure DOCUMENTACAO_DIAGNOSTICO_JOURNEY_HTML_V4_FORMAL_TODO_PERIODO = ```
			VAR vIntFormat = "#,##0"
						VAR vPctFormat = "0.0%"
						VAR vDateFormat = "dd/mm/yyyy"
						VAR vAtualizadoEm = FORMAT ( NOW (), "dd/mm/yyyy HH:mm" )
						
						VAR vBaseJourney = 'JOBS_Produto'
						
						VAR vJobStatusRaw =
						    ADDCOLUMNS (
						        SUMMARIZE ( vBaseJourney, 'JOBS_Produto'[JOB] ),
						        "__OpenRows",
						            VAR vJobKey = 'JOBS_Produto'[JOB]
						            RETURN
						                COUNTROWS (
						                    FILTER (
						                        vBaseJourney,
						                        'JOBS_Produto'[JOB] = vJobKey
						                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
						                    )
						                ),
						        "__FimRows",
						            VAR vJobKey = 'JOBS_Produto'[JOB]
						            RETURN
						                COUNTROWS (
						                    FILTER (
						                        vBaseJourney,
						                        'JOBS_Produto'[JOB] = vJobKey
						                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) = "FIM"
						                    )
						                ),
						        "__StageOpen",
						            VAR vJobKey = 'JOBS_Produto'[JOB]
						            RETURN
						                MAXX (
						                    FILTER (
						                        vBaseJourney,
						                        'JOBS_Produto'[JOB] = vJobKey
						                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
						                    ),
						                    VAR vArea = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
						                    RETURN
						                        SWITCH (
						                            TRUE (),
						                            vArea = "CHECKLIST", 1,
						                            vArea = "OPERAÇÃO", 2,
						                            vArea = "OPERACAO", 2,
						                            vArea = "PROCURAÇÃO ELETRÔNICA", 3,
						                            vArea = "PROCURACAO ELETRONICA", 3,
						                            0
						                        )
						                )
						    )
						
						VAR vJobStatus =
						    ADDCOLUMNS (
						        vJobStatusRaw,
						        "__Stage",
						            IF (
						                [__OpenRows] = 0 && [__FimRows] > 0,
						                4,
						                COALESCE ( [__StageOpen], 0 )
						            ),
						        "__Status",
						            IF (
						                [__OpenRows] = 0 && [__FimRows] > 0,
						                "Finalizado",
						                "Ativo"
						            )
						    )
						
						VAR vRegistros = COUNTROWS ( vBaseJourney )
						VAR vJobs = COUNTROWS ( vJobStatus )
						VAR vJobsAtivos = COUNTROWS ( FILTER ( vJobStatus, [__Status] = "Ativo" ) )
						VAR vJobsFinalizados = COUNTROWS ( FILTER ( vJobStatus, [__Status] = "Finalizado" ) )
						VAR vJobsChecklist = COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 1 ) )
						VAR vJobsOperacao = COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 2 ) )
						VAR vJobsProcuracao = COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 3 ) )
						VAR vJobsFim = COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 4 ) )
						VAR vJobsSemEtapa = COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 0 ) )
						VAR vJobsPassaram = COUNTROWS ( FILTER ( vJobStatus, [__Stage] >= 2 ) )
						
						VAR vClientes =
						    COUNTROWS (
						        SUMMARIZE (
						            FILTER ( vBaseJourney, NOT ISBLANK ( 'JOBS_Produto'[NOME_CLIENTE] ) ),
						            'JOBS_Produto'[NOME_CLIENTE]
						        )
						    )
						
						VAR vCNPJs =
						    COUNTROWS (
						        SUMMARIZE (
						            FILTER ( vBaseJourney, NOT ISBLANK ( 'JOBS_Produto'[CNPJ_CLIENTE] ) ),
						            'JOBS_Produto'[CNPJ_CLIENTE]
						        )
						    )
						
						VAR vCNPJBlank =
						    COUNTROWS (
						        FILTER ( vBaseJourney, ISBLANK ( 'JOBS_Produto'[CNPJ_CLIENTE] ) )
						    )
						
						VAR vProdutos =
						    COUNTROWS (
						        SUMMARIZE (
						            FILTER ( vBaseJourney, NOT ISBLANK ( 'JOBS_Produto'[NOME_PRODUTO] ) ),
						            'JOBS_Produto'[NOME_PRODUTO]
						        )
						    )
						
						VAR vSubprodutos =
						    COUNTROWS (
						        SUMMARIZE (
						            FILTER ( vBaseJourney, NOT ISBLANK ( 'JOBS_Produto'[NOME_SUBPRODUTO] ) ),
						            'JOBS_Produto'[NOME_SUBPRODUTO]
						        )
						    )
						
						VAR vOportunidadesDisp =
						    COUNTROWS (
						        SUMMARIZE (
						            FILTER ( vBaseJourney, NOT ISBLANK ( 'JOBS_Produto'[NOME_TRIBUTO] ) ),
						            'JOBS_Produto'[NOME_TRIBUTO]
						        )
						    )
						
						VAR vOportunidadesPass =
						    COUNTROWS (
						        SUMMARIZE (
						            FILTER (
						                vBaseJourney,
						                NOT ISBLANK ( 'JOBS_Produto'[NOME_TRIBUTO] )
						                    && (
						                        VAR vAreaPass = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
						                        RETURN
						                            vAreaPass IN {
						                                "OPERAÇÃO",
						                                "OPERACAO",
						                                "PROCURAÇÃO ELETRÔNICA",
						                                "PROCURACAO ELETRONICA",
						                                "FIM"
						                            }
						                    )
						            ),
						            'JOBS_Produto'[NOME_TRIBUTO]
						        )
						    )
						
						VAR vPctAtivo = DIVIDE ( vJobsAtivos, vJobs , 0 )
						VAR vPctFinalizado = DIVIDE ( vJobsFinalizados, vJobs , 0 )
						VAR vPctPassaram = DIVIDE ( vJobsPassaram, vJobs , 0 )
						VAR vPctOportPass = DIVIDE ( vOportunidadesPass, vOportunidadesDisp , 0 )
						VAR vPctCNPJBlank = DIVIDE ( vCNPJBlank, vRegistros , 0 )
						VAR vDiasMed = MEDIANX ( vBaseJourney, 'JOBS_Produto'[DIAS] )
						
						VAR vMinCadastro = MINX ( vBaseJourney, 'JOBS_Produto'[DATA_CADASTRO] )
						VAR vMaxCadastro = MAXX ( vBaseJourney, 'JOBS_Produto'[DATA_CADASTRO] )
						VAR vUltimoMovimento =
						    MAXX (
						        vBaseJourney,
						        COALESCE ( 'JOBS_Produto'[TRIBUTO_DATA_ENTRADA], 'JOBS_Produto'[DATA_CADASTRO] )
						    )
						
						VAR vPeriodo =
						    IF (
						        ISBLANK ( vMinCadastro ) || ISBLANK ( vMaxCadastro ),
						        "Todo período",
						        FORMAT ( vMinCadastro, "mmm/yyyy" ) & " a " & FORMAT ( vMaxCadastro, "mmm/yyyy" )
						    )
						
						VAR vUltimoMovimentoTxt =
						    IF (
						        ISBLANK ( vUltimoMovimento ),
						        "Sem registros",
						        FORMAT ( vUltimoMovimento, "dd/MM/yyyy" )
						    )
						
						VAR vStatusExecutivo =
						    SWITCH (
						        TRUE (),
						        vPctPassaram >= 0.70, "Excelente",
						        vPctPassaram >= 0.50, "Bom",
						        vPctPassaram >= 0.30, "Atenção",
						        "Crítico"
						    )
						
						VAR vRiscoTexto =
						    SWITCH (
						        TRUE (),
						        vPctPassaram >= 0.70, "Carteira com alto índice de avanço operacional. Excelente saúde operacional.",
						        vPctPassaram >= 0.50, "Mais da metade dos jobs avançaram para execução. Ritmo adequado.",
						        vPctPassaram >= 0.30, "Necessário acelerar avanço de etapas iniciais (Checklist).",
						        "Gargalo severo identificado nas etapas iniciais. Risco de atraso nas entregas."
						    )
						
						VAR vStageTable =
						    UNION (
						        ROW ( "Ordem", 1, "Etapa", "Checklist", "Qtd", vJobsChecklist, "Pct", DIVIDE ( vJobsChecklist, vJobs, 0 ), "Cor", "warn" ),
						        ROW ( "Ordem", 2, "Etapa", "Operação", "Qtd", vJobsOperacao, "Pct", DIVIDE ( vJobsOperacao, vJobs, 0 ), "Cor", "good" ),
						        ROW ( "Ordem", 3, "Etapa", "Procuração Eletrônica", "Qtd", vJobsProcuracao, "Pct", DIVIDE ( vJobsProcuracao, vJobs, 0 ), "Cor", "info" ),
						        ROW ( "Ordem", 4, "Etapa", "Fim (Finalizados)", "Qtd", vJobsFim, "Pct", DIVIDE ( vJobsFim, vJobs, 0 ), "Cor", "good" ),
						        ROW ( "Ordem", 5, "Etapa", "Sem etapa mapeada", "Qtd", vJobsSemEtapa, "Pct", DIVIDE ( vJobsSemEtapa, vJobs, 0 ), "Cor", "bad" )
						    )
						
						VAR vStageHTML =
						    CONCATENATEX (
						        vStageTable,
						        VAR vBar = MAX ( 2, ROUND ( COALESCE ( [Pct], 0 ) * 100, 0 ) )
						        RETURN
						            "<div class='stage-line " & [Cor] & "'>"
						                & "<div class='stage-name'>" & [Etapa] & "</div>"
						                & "<div class='stage-bar'><span style='width:" & FORMAT ( vBar, "0" ) & "%'></span></div>"
						                & "<div class='stage-qtd'>" & FORMAT ( [Qtd], vIntFormat ) & "</div>"
						                & "<div class='stage-pct'>" & FORMAT ( [Pct], vPctFormat ) & "</div>"
						            & "</div>",
						        "",
						        [Ordem], ASC
						    )
			
						VAR vHonorariosEncontrados =
						    SUMX (
						        SUMMARIZE ( vBaseJourney, 'JOBS_Produto'[JOB] ),
						        CALCULATE ( MAX ( 'JOBS_Produto'[JOB_HONORARIOS_ENCONTRADOS] ) )
						    )
						VAR vHonorariosAgendados =
						    SUMX (
						        SUMMARIZE ( vBaseJourney, 'JOBS_Produto'[JOB] ),
						        CALCULATE ( MAX ( 'JOBS_Produto'[JOB_HONORARIOS_AGENDADOS] ) )
						    )
						VAR vPctHonorariosAgendados =
						    DIVIDE ( vHonorariosAgendados, vHonorariosEncontrados, 0 )
						
						VAR vCSS =
						"
						<style>
						.doc-page{
						    width:1910px;
						    height:1070px;
						    box-sizing:border-box;
						    padding:20px;
						    font-family:'Segoe UI',Arial,sans-serif;
						    background:
						        radial-gradient(circle at 0% 0%,rgba(213,174,119,.18),transparent 32%),
						        radial-gradient(circle at 94% 7%,rgba(139,224,209,.12),transparent 30%),
						        linear-gradient(180deg,#101923 0%,#0B1219 100%);
						    color:#E8EEF5;
						    overflow:hidden;
						}
						.doc-shell{
						    width:100%;
						    height:100%;
						    display:grid;
						    grid-template-columns:390px 1fr;
						    gap:16px;
						}
						.doc-sidebar{
						    height:100%;
						    box-sizing:border-box;
						    border-radius:20px;
						    border:1px solid rgba(213,174,119,.28);
						    background:linear-gradient(180deg,rgba(213,174,119,.15),rgba(255,255,255,.025));
						    box-shadow:0 18px 42px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.05);
						    padding:24px 20px 20px;
						    overflow-y:auto;
						    overflow-x:hidden;
						    scrollbar-width:none;
						    position:relative;
						}
						.doc-sidebar::-webkit-scrollbar{display:none}
						.doc-sidebar:before{
						    content:'';
						    position:absolute;
						    left:0;
						    top:0;
						    bottom:0;
						    width:7px;
						    background:linear-gradient(180deg,#F4D9A9,#D5AE77,#8BE0D1);
						}
						.brand-kicker{
						    font-size:12.5px;
						    text-transform:uppercase;
						    letter-spacing:1.7px;
						    color:#8BE0D1;
						    font-weight:950;
						    margin-bottom:10px;
						}
						.brand-title{
						    color:#F4D9A9;
						    font-size:37.5px;
						    line-height:1.02;
						    font-weight:950;
						    letter-spacing:.02em;
						    margin-bottom:10px;
						    text-transform:uppercase;
						    text-shadow:0 8px 18px rgba(0,0,0,.35);
						}
						.brand-sub{
						    font-size:15.6px;
						    line-height:1.48;
						    color:#B7C2CD;
						    margin-bottom:14px;
						}
						.side-card{
						    border:1px solid rgba(255,255,255,.09);
						    background:rgba(255,255,255,.04);
						    border-radius:15px;
						    padding:12px;
						    margin-bottom:10px;
						}
						.side-card.highlight{
						    background:linear-gradient(135deg,rgba(213,174,119,.17),rgba(255,255,255,.035));
						    border-color:rgba(213,174,119,.30);
						}
						.side-label{
						    display:block;
						    font-size:11.9px;
						    color:#8796A5;
						    text-transform:uppercase;
						    letter-spacing:.85px;
						    font-weight:950;
						    margin-bottom:5px;
						}
						.side-value{
						    display:block;
						    font-size:17.5px;
						    color:#F0F5FA;
						    font-weight:900;
						    line-height:1.25;
						}
						.side-value.big{
						    color:#F4D9A9;
						    font-size:27.5px;
						}
						.side-small{
						    color:#AEB8C2;
						    font-size:13.4px;
						    line-height:1.4;
						    margin-top:5px;
						}
						.nav-title{
						    margin-top:14px;
						    margin-bottom:9px;
						    font-size:12.5px;
						    text-transform:uppercase;
						    letter-spacing:.95px;
						    color:#D5AE77;
						    font-weight:950;
						}
						.nav-list{
						    display:flex;
						    flex-direction:column;
						    gap:6px;
						}
						.nav-pill{
						    font-size:13.5px;
						    color:#DCE5EE;
						    border:1px solid rgba(213,174,119,.16);
						    background:rgba(255,255,255,.04);
						    border-radius:999px;
						    padding:7px 10px;
						    font-weight:850;
						    line-height:1;
						}
						.nav-pill.active{
						    color:#8BE0D1;
						    border-color:rgba(139,224,209,.30);
						    background:rgba(139,224,209,.08);
						}
						.doc-main{
						    height:100%;
						    background:linear-gradient(180deg,#121C25 0%,#0D151D 100%);
						    border:1px solid rgba(213,174,119,.20);
						    border-radius:20px;
						    box-shadow:0 18px 42px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.05);
						    overflow:hidden;
						    display:flex;
						    flex-direction:column;
						}
						.doc-header{
						    padding:17px 20px 15px;
						    border-bottom:1px solid rgba(213,174,119,.16);
						    display:flex;
						    align-items:flex-start;
						    justify-content:space-between;
						    gap:18px;
						    background:linear-gradient(90deg,rgba(255,255,255,.03),rgba(213,174,119,.035));
						}
						.doc-header h1{
						    margin:0;
						    color:#F4D9A9;
						    font-size:33.8px;
						    line-height:1.08;
						    font-weight:950;
						    letter-spacing:.3px;
						    text-transform:uppercase;
						}
						.doc-header p{
						    margin:7px 0 0;
						    color:#B7C2CD;
						    font-size:16px;
						    line-height:1.4;
						    max-width:1120px;
						}
						.doc-actions{
						    display:flex;
						    flex-direction:column;
						    align-items:flex-end;
						    gap:9px;
						    flex-shrink:0;
						}
						.back-report-fake{
						    display:inline-flex;
						    align-items:center;
						    justify-content:center;
						    gap:8px;
						    min-height:36px;
						    padding:9px 15px;
						    border-radius:999px;
						    background:linear-gradient(135deg,rgba(213,174,119,.18),rgba(139,224,209,.10));
						    border:1px solid rgba(213,174,119,.38);
						    color:#F4D9A9;
						    font-size:13.1px;
						    font-weight:950;
						    letter-spacing:.65px;
						    text-transform:uppercase;
						    white-space:nowrap;
						    box-shadow:0 10px 22px rgba(213,174,119,.10),inset 0 1px 0 rgba(255,255,255,.07);
						}
						.back-report-fake:before{
						    content:'←';
						    width:18px;
						    height:18px;
						    display:inline-flex;
						    align-items:center;
						    justify-content:center;
						    border-radius:50%;
						    background:rgba(213,174,119,.14);
						    border:1px solid rgba(213,174,119,.34);
						    color:#8BE0D1;
						    font-size:15px;
						    font-weight:950;
						    line-height:1;
						}
						.badge-wrap{
						    display:flex;
						    justify-content:flex-end;
						    align-items:center;
						    flex-wrap:wrap;
						    gap:6px;
						}
						.badge{
						    display:inline-flex;
						    border-radius:999px;
						    border:1px solid rgba(213,174,119,.30);
						    background:rgba(213,174,119,.08);
						    color:#F4D9A9;
						    font-size:12.5px;
						    font-weight:950;
						    text-transform:uppercase;
						    letter-spacing:.6px;
						    padding:5px 10px;
						    white-space:nowrap;
						}
						.badge.teal{
						    color:#8BE0D1;
						    border-color:rgba(139,224,209,.34);
						    background:rgba(139,224,209,.08);
						}
						.doc-scroll{
						    flex:1 1 auto;
						    min-height:0;
						    overflow-y:auto;
						    overflow-x:hidden;
						    padding:18px 20px 20px;
						    box-sizing:border-box;
						    scrollbar-width:thin;
						    scrollbar-color:rgba(213,174,119,.60) rgba(8,14,20,.95);
						}
						.doc-scroll::-webkit-scrollbar{width:12px}
						.doc-scroll::-webkit-scrollbar-track{
						    background:rgba(8,14,20,.96);
						    border-left:1px solid rgba(213,174,119,.10);
						}
						.doc-scroll::-webkit-scrollbar-thumb{
						    background:linear-gradient(180deg,rgba(213,174,119,.78),rgba(109,84,51,.86));
						    border:3px solid rgba(8,14,20,.96);
						    border-radius:999px;
						}
						.metric-grid{
						    display:grid;
						    grid-template-columns:repeat(6,1fr);
						    gap:11px;
						    margin-bottom:14px;
						}
						.metric{
						    position:relative;
						    min-height:124px;
						    padding:15px 13px 13px;
						    border-radius:18px;
						    background:linear-gradient(160deg,rgba(18,28,37,.96),rgba(11,18,25,.94));
						    border:1px solid rgba(255,255,255,.10);
						    box-shadow:0 16px 28px rgba(0,0,0,.22),inset 0 1px 0 rgba(255,255,255,.06);
						    overflow:hidden;
						}
						.metric:before{
						    content:'';
						    position:absolute;
						    left:14px;
						    top:0;
						    width:42px;
						    height:4px;
						    border-radius:0 0 10px 10px;
						    background:linear-gradient(90deg,#F4D9A9,#8BE0D1);
						}
						.metric.primary{
						    background:linear-gradient(155deg,rgba(213,174,119,.20),rgba(18,28,37,.96) 36%,rgba(11,18,25,.96));
						    border-color:rgba(213,174,119,.40);
						}
						.metric.attention{
						    background:linear-gradient(155deg,rgba(139,224,209,.08),rgba(18,28,37,.96) 34%,rgba(11,18,25,.96));
						    border-color:rgba(139,224,209,.30);
						}
						.m-label{
						    display:block;
						    color:#AEB9C4;
						    font-size:12.5px;
						    letter-spacing:.08em;
						    text-transform:uppercase;
						    font-weight:950;
						    margin-bottom:8px;
						}
						.m-value{
						    display:block;
						    color:#F4D9A9;
						    font-size:32.5px;
						    font-weight:950;
						    line-height:1.05;
						    white-space:nowrap;
						    overflow:hidden;
						    text-overflow:ellipsis;
						}
						.m-note{
						    display:block;
						    color:#8B98A6;
						    font-size:13.8px;
						    line-height:1.28;
						    margin-top:7px;
						    font-weight:850;
						}
						.insight-strip{
						    display:grid;
						    grid-template-columns:repeat(4,1fr);
						    gap:10px;
						    margin-bottom:14px;
						}
						.insight{
						    border-radius:14px;
						    border:1px solid rgba(255,255,255,.09);
						    background:rgba(255,255,255,.035);
						    padding:11px 12px;
						    border-left:4px solid rgba(174,185,196,.48);
						}
						.insight.good{border-left-color:#8BE0D1}
						.insight.warn{border-left-color:#F4D9A9}
						.insight.bad{border-left-color:#FFB0A8}
						.insight-label{
						    display:block;
						    color:#8796A5;
						    font-size:11.9px;
						    font-weight:950;
						    letter-spacing:.08em;
						    text-transform:uppercase;
						    margin-bottom:5px;
						}
						.insight-text{
						    display:block;
						    color:#DCE5EE;
						    font-size:14.1px;
						    font-weight:850;
						    line-height:1.32;
						}
						.doc-section{
						    border:1px solid rgba(213,174,119,.19);
						    background:rgba(255,255,255,.027);
						    border-radius:17px;
						    margin-bottom:12px;
						    overflow:hidden;
						}
						.doc-section summary{
						    cursor:pointer;
						    list-style:none;
						    display:flex;
						    align-items:center;
						    justify-content:space-between;
						    gap:12px;
						    padding:14px 15px;
						    background:linear-gradient(90deg,rgba(213,174,119,.17),rgba(213,174,119,.035));
						    border-bottom:1px solid rgba(213,174,119,.13);
						}
						.doc-section summary::-webkit-details-marker{display:none}
						.summary-left{
						    display:flex;
						    align-items:center;
						    gap:10px;
						    min-width:0;
						}
						.summary-index{
						    display:inline-flex;
						    align-items:center;
						    justify-content:center;
						    width:28px;
						    height:28px;
						    border-radius:50%;
						    background:rgba(213,174,119,.19);
						    border:1px solid rgba(213,174,119,.30);
						    color:#F4D9A9;
						    font-size:12.5px;
						    font-weight:950;
						}
						.summary-title{
						    color:#F4D9A9;
						    font-size:17.5px;
						    font-weight:950;
						    text-transform:uppercase;
						    letter-spacing:.45px;
						}
						.summary-action{
						    color:#B7C2CD;
						    font-size:12.2px;
						    font-weight:950;
						    text-transform:uppercase;
						    letter-spacing:.5px;
						    border:1px solid rgba(255,255,255,.10);
						    background:rgba(255,255,255,.04);
						    border-radius:999px;
						    padding:5px 9px;
						    white-space:nowrap;
						}
						.section-body{padding:15px}
						.two-col{display:grid;grid-template-columns:1fr 1fr;gap:10px}
						.three-col{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}
						.doc-table{
						    width:100%;
						    border-collapse:separate;
						    border-spacing:0;
						    table-layout:fixed;
						    overflow:hidden;
						    border-radius:13px;
						    border:1px solid rgba(255,255,255,.08);
						    margin-bottom:10px;
						}
						.doc-table th{
						    background:#111A22;
						    color:#D5AE77;
						    font-size:12.5px;
						    font-weight:950;
						    text-transform:uppercase;
						    letter-spacing:.55px;
						    text-align:left;
						    padding:10px;
						    border-bottom:1px solid rgba(213,174,119,.30);
						}
						.doc-table td{
						    color:#DCE5EE;
						    font-size:14px;
						    line-height:1.45;
						    padding:9px 10px;
						    border-bottom:1px solid rgba(255,255,255,.055);
						    vertical-align:top;
						}
						.doc-table tr:last-child td{border-bottom:none}
						.doc-table td strong{color:#F4D9A9}
						.tag{
						    display:inline-flex;
						    border:1px solid rgba(213,174,119,.26);
						    background:rgba(213,174,119,.07);
						    color:#F4D9A9;
						    border-radius:999px;
						    padding:3px 7px;
						    font-size:11.2px;
						    font-weight:950;
						    text-transform:uppercase;
						    letter-spacing:.35px;
						    white-space:nowrap;
						}
						.tag.good{color:#8BE0D1;border-color:rgba(139,224,209,.35);background:rgba(139,224,209,.09)}
						.tag.info{color:#AEB9C4;border-color:rgba(255,255,255,.14);background:rgba(255,255,255,.05)}
						.tag.warn{color:#F4D9A9;border-color:rgba(213,174,119,.35);background:rgba(213,174,119,.09)}
						.tag.bad{color:#FFB0A8;border-color:rgba(217,93,93,.35);background:rgba(217,93,93,.09)}
						.callout{
						    border-left:4px solid rgba(213,174,119,.82);
						    background:rgba(213,174,119,.06);
						    border-radius:13px;
						    padding:12px 13px;
						    color:#DCE5EE;
						    font-size:14.2px;
						    line-height:1.5;
						    margin:10px 0;
						}
						.callout.tech{
						    border-left-color:#8BE0D1;
						    background:rgba(139,224,209,.055);
						}
						.callout.warn{
						    border-left-color:#F4D9A9;
						    background:rgba(244,217,169,.065);
						}
						.callout.bad{
						    border-left-color:#FFB0A8;
						    background:rgba(217,93,93,.065);
						}
						.stage-box{
						    display:grid;
						    grid-template-columns:1fr;
						    gap:8px;
						}
						.stage-line{
						    display:grid;
						    grid-template-columns:210px minmax(190px,1fr) 86px 86px;
						    gap:10px;
						    align-items:center;
						    padding:8px 9px;
						    border-radius:11px;
						    background:rgba(255,255,255,.035);
						    border:1px solid rgba(255,255,255,.07);
						}
						.stage-name{color:#DCE5EE;font-size:14.1px;font-weight:850}
						.stage-bar{height:9px;border-radius:999px;background:rgba(255,255,255,.07);overflow:hidden}
						.stage-bar span{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,#D5AE77,#8BE0D1)}
						.stage-qtd,.stage-pct{color:#AEB9C4;font-size:13.8px;font-weight:900;text-align:right}
						.footer-doc{
						    font-size:13.4px;
						    color:#8796A5;
						    line-height:1.38;
						    padding:10px 2px 2px;
						}
						</style>
						"
						
						VAR vHTML =
						"<div class='doc-page'>
						    <div class='doc-shell'>
						        <aside class='doc-sidebar'>
						            <div class='brand-kicker'>Power BI · Documentação</div>
						            <div class='brand-title'>Diagnóstico<br><span style='color:#8BE0D1'>Journey</span></div>
						            <div class='brand-sub'>Documentação oficial alinhada para a Diretoria Executiva (visão de valor, andamento) e para a Equipe Técnica (regras, performance, manutenção e escalabilidade).</div>
						
						            <div class='side-card highlight'>
						                <span class='side-label'>Status executivo</span>
						                <span class='side-value big'>" & vStatusExecutivo & "</span>
						                <div class='side-small'>" & vRiscoTexto & "</div>
						            </div>
			
						            <div class='side-card highlight' style='border-color:rgba(139,224,209,.38); background:linear-gradient(135deg,rgba(139,224,209,.12),rgba(255,255,255,.03));'>
						                <span class='side-label' style='color:#8BE0D1'>Honorários Agendados</span>
						                <span class='side-value big' style='color:#8BE0D1'>R$ " & FORMAT ( vHonorariosAgendados, vIntFormat ) & "</span>
						                <div class='side-small'>Encontrados: R$ " & FORMAT ( vHonorariosEncontrados, vIntFormat ) & " <br> Taxa de agendamento: " & FORMAT ( vPctHonorariosAgendados, vPctFormat ) & " do total.</div>
						            </div>
						
						            <div class='side-card'>
						                <span class='side-label'>Período exibido</span>
						                <span class='side-value'>" & vPeriodo & "</span>
						                <div class='side-small'>Sem filtro fixo de ano. O padrão é todo o período disponível; o usuário escolhe o recorte pelo slicer de data. A regra de base desta documentação foi alinhada à medida principal para evitar divergência de valores.</div>
						            </div>
						
						            <div class='side-card'>
						                <span class='side-label'>Último movimento</span>
						                <span class='side-value'>" & vUltimoMovimentoTxt & "</span>
						                <div class='side-small'>Baseado em TRIBUTO_DATA_ENTRADA, com fallback em DATA_CADASTRO quando necessário.</div>
						            </div>
						
						            <div class='side-card'>
						                <span class='side-label'>Atualização</span>
						                <span class='side-value'>" & vAtualizadoEm & "</span>
						                <div class='side-small'>Atualizado automaticamente pela medida HTML no refresh/abertura do relatório.</div>
						            </div>
						
						            <div class='nav-title'>Guia executivo e técnico</div>
						            <div class='nav-list'>
						                <div class='nav-pill active'>01. O que mudou agora</div>
						                <div class='nav-pill'>02. Como usar</div>
						                <div class='nav-pill'>03. Perguntas respondidas</div>
						                <div class='nav-pill'>04. Layout final</div>
						                <div class='nav-pill'>05. KPIs</div>
						                <div class='nav-pill'>06. Etapas e status</div>
						                <div class='nav-pill'>07. Slicers</div>
						                <div class='nav-pill'>08. Calendário</div>
						                <div class='nav-pill'>09. Aba Detalhamento</div>
						                <div class='nav-pill'>10. Dados</div>
						                <div class='nav-pill'>11. Manutenção</div>
						                <div class='nav-pill'>12. QA</div>
						                <div class='nav-pill'>13. Performance</div>
						                <div class='nav-pill'>14. Roadmap</div>
						            </div>
						        </aside>
						
						        <main class='doc-main'>
						            <div class='doc-header'>
						                <div>
						                    <h1>Documentação · Diagnóstico - Journey</h1>
						                    <p>Versão executiva e técnica integrada. Detalhamento completo das regras operacionais, visão financeira com honorários agendados, regras de performance de carregamento e arquitetura de medidas.</p>
						                </div>
						                <div class='doc-actions'>
						                    <div class='back-report-fake'>Voltar ao relatório</div>
						                    <div class='badge-wrap'>
						                        <span class='badge'>Diretoria</span>
						                        <span class='badge'>Técnico</span>
						                        <span class='badge teal'>Journey</span>
						                        <span class='badge'>Todo período</span>
						                    </div>
						                </div>
						            </div>
						
						            <div class='doc-scroll'>
						
						                <div class='metric-grid'>
						                    <div class='metric primary'><span class='m-label'>Jobs listados</span><span class='m-value'>" & FORMAT ( vJobs, vIntFormat ) & "</span><span class='m-note'>Jobs no período</span></div>
						                    <div class='metric'><span class='m-label'>Ativos</span><span class='m-value'>" & FORMAT ( vJobsAtivos, vIntFormat ) & "</span><span class='m-note'>" & FORMAT ( vPctAtivo, vPctFormat ) & " da carteira</span></div>
						                    <div class='metric'><span class='m-label'>Finalizados</span><span class='m-value'>" & FORMAT ( vJobsFinalizados, vIntFormat ) & "</span><span class='m-note'>" & FORMAT ( vPctFinalizado, vPctFormat ) & " em FIM</span></div>
						                    <div class='metric attention'><span class='m-label'>Passaram etapa</span><span class='m-value'>" & FORMAT ( vJobsPassaram, vIntFormat ) & "</span><span class='m-note'>" & FORMAT ( vPctPassaram, vPctFormat ) & " em Operação/Proc/FIM</span></div>
						                    <div class='metric'><span class='m-label'>Oportunidades</span><span class='m-value'>" & FORMAT ( vOportunidadesDisp, vIntFormat ) & "</span><span class='m-note'>" & FORMAT ( vOportunidadesPass, vIntFormat ) & " com passagem</span></div>
						                    <div class='metric'><span class='m-label'>Dias mediano</span><span class='m-value'>" & FORMAT ( vDiasMed, "#,##0" ) & "</span><span class='m-note'>Tempo operacional mediano</span></div>
						                </div>
			
						                <div class='metric-grid' style='grid-template-columns: repeat(3, 1fr); margin-bottom: 14px;'>
						                    <div class='metric' style='border-color:rgba(213,174,119,.3);'><span class='m-label' style='color:#D5AE77'>Honorários Encontrados</span><span class='m-value' style='color:#D5AE77'>R$ " & FORMAT ( vHonorariosEncontrados, vIntFormat ) & "</span><span class='m-note'>Soma distinta máxima por JOB</span></div>
						                    <div class='metric' style='border-color:rgba(139,224,209,.3);'><span class='m-label' style='color:#8BE0D1'>Honorários Agendados</span><span class='m-value' style='color:#8BE0D1'>R$ " & FORMAT ( vHonorariosAgendados, vIntFormat ) & "</span><span class='m-note'>Planejado operacionalmente</span></div>
						                    <div class='metric' style='border-color:rgba(139,224,209,.3);'><span class='m-label' style='color:#8BE0D1'>Eficiência de Agendamento</span><span class='m-value' style='color:#8BE0D1'>" & FORMAT ( vPctHonorariosAgendados, vPctFormat ) & "</span><span class='m-note'>Agendados sobre Encontrados</span></div>
						                </div>
						
						                <div class='insight-strip'>
						                    <div class='insight " & IF ( vPctPassaram >= 0.40, "good", "warn" ) & "'><span class='insight-label'>Andamento</span><span class='insight-text'>" & vStatusExecutivo & " no recorte atual.</span></div>
						                    <div class='insight " & IF ( vPctAtivo >= 0.80, "warn", "good" ) & "'><span class='insight-label'>Carteira</span><span class='insight-text'>" & FORMAT ( vPctAtivo, vPctFormat ) & " dos jobs permanecem ativos.</span></div>
						                    <div class='insight " & IF ( vPctOportPass >= 0.50, "good", "warn" ) & "'><span class='insight-label'>Oportunidades</span><span class='insight-text'>" & FORMAT ( vPctOportPass, vPctFormat ) & " das oportunidades tiveram passagem.</span></div>
						                    <div class='insight " & IF ( vPctCNPJBlank > 0, "warn", "good" ) & "'><span class='insight-label'>Chave futura</span><span class='insight-text'>" & FORMAT ( vCNPJBlank, vIntFormat ) & " linhas sem CNPJ no recorte.</span></div>
						                </div>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>01</span><span class='summary-title'>O que mudou na versão atual</span></div><span class='summary-action'>Atualização</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Mudança</th><th>Antes</th><th>Agora</th><th>Impacto</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>Escopo de Produtos</strong></td><td>Apenas produtos diagnósticos (`IsDiagnostico = TRUE`).</td><td><strong>Todos os produtos da base</strong> (filtro `IsDiagnostico` removido de todas as medidas).</td><td>Permite analisar qualquer produto (ex: Revisão Previdenciária) sem cards ficarem vazios.</td></tr>
						                                <tr><td><strong>Expansão de Produto</strong></td><td>Lista job por job ocupando muito espaço e gerando lentidão.</td><td><strong>Tabela widescreen comparativa</strong> com os totais macros da base.</td><td>Compara de forma clara e limpa o produto com a média geral da empresa.</td></tr>
						                                <tr><td><strong>Alinhamento do Detalhamento</strong></td><td>Cards operacionais e rodapé travados em `750` listados.</td><td><strong>Contagem dinâmica e real</strong> (`_totalJobs` ex: 2.074 em abril/2026).</td><td>Os cards mostram o total real do período e o rodapé mostra `750 de 2.074 no período`.</td></tr>
						                                <tr><td><strong>Recorte de Período</strong></td><td>Filtro fixo de ano na medida.</td><td>Totalmente dinâmico pelo slicer.</td><td>Liberdade para navegar de forma retroativa ou futura conforme a dCalendar.</td></tr>
						                                <tr><td><strong>Valores com Honorários</strong></td><td>Não integrados na documentação e cards operacionais.</td><td><strong>Medidas exclusivas de Honorários</strong> integradas à barra executiva.</td><td>Soma distinta do máximo de honorários por JOB no período para Encontrados e Agendados.</td></tr>
						                                <tr><td><strong>Bolhas de Status</strong></td><td>Exibia status poluídos na principal.</td><td>Removidas.</td><td>Foco nas métricas de representatividade de forma limpa.</td></tr>
						                            </tbody>
						                        </table>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>02</span><span class='summary-title'>Como usar o dashboard no dia a dia</span></div><span class='summary-action'>Usuário</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Passo</th><th>O que fazer</th><th>Resultado esperado</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>1</strong></td><td>Abra a aba principal.</td><td>Veja o panorama macro da carteira de Jobs Journey e a visão financeira de honorários.</td></tr>
						                                <tr><td><strong>2</strong></td><td>Selecione um período no slicer de data.</td><td>Todos os cards (inclusive Detalhamento e Documentação) passam a respeitar o recorte de período.</td></tr>
						                                <tr><td><strong>3</strong></td><td>Use os filtros de Produto, Cliente e Etapa.</td><td>Analise carteiras específicas de forma focada para reuniões ou comitês.</td></tr>
						                                <tr><td><strong>4</strong></td><td>Clique para expandir um produto na tabela.</td><td>Veja a comparação widescreen do produto com o total da empresa de forma limpa.</td></tr>
						                                <tr><td><strong>5</strong></td><td>Navegue para a aba Detalhamento.</td><td>Consulte o job por job, busque na barra global ou colunas e copie a tabela para o Excel.</td></tr>
						                                <tr><td><strong>6</strong></td><td>Acesse a aba Documentação.</td><td>Entenda as regras operacionais, de cálculo e detalhes de manutenção técnica.</td></tr>
						                            </tbody>
						                        </table>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>03</span><span class='summary-title'>Perguntas que o dashboard responde</span></div><span class='summary-action'>Diretoria</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Pergunta</th><th>Onde olhar</th><th>Como interpretar</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>Qual o tamanho da carteira de jobs no período?</strong></td><td>Card ""Jobs listados"".</td><td>Volume total de diagnósticos/jobs Journey ativos ou finalizados.</td></tr>
						                                <tr><td><strong>Quantos jobs ainda demandam gestão operacional?</strong></td><td>Card ""Ativos"" ou coluna ""Ativos"".</td><td>Total de jobs que possuem pelo menos uma linha fora da etapa FIM.</td></tr>
						                                <tr><td><strong>Qual o volume de honorários identificados no período?</strong></td><td>Card ""Honorários Encontrados"".</td><td>Volume total bruto de honorários identificados nos jobs mapeados.</td></tr>
						                                <tr><td><strong>Qual o valor financeiro já planejado/agendado?</strong></td><td>Card ""Honorários Agendados"".</td><td>Soma distinta por job dos valores com status de agendamento.</td></tr>
						                                <tr><td><strong>Como o produto X performa comparado com a média geral?</strong></td><td>Tabela principal (clique de expansão).</td><td>Mapeia eficiência em %, mediana de dias e volumetria comparativa direta.</td></tr>
						                            </tbody>
						                        </table>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>04</span><span class='summary-title'>Layout final das páginas</span></div><span class='summary-action'>Layout</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Página</th><th>Conteúdo</th><th>Finalidade</th><th>Botão</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>JOBS - PRODUTOS (Principal)</strong></td><td>Visão executiva macro, cards principais de volume/financeiro, tabela por produto com expansão widescreen comparativa.</td><td>Apresentação executiva e tomada de decisão estratégica.</td><td>Detalhamento (no topo da tabela) e Documentação (no título).</td></tr>
						                                <tr><td><strong>DETALHAMENTO</strong></td><td>Tabela detalhada job por job com busca global, filtros por coluna e botão de copiar para Excel (DOM limitado a 750 linhas).</td><td>Análise operacional de pendências e exportação de relatórios rápidos.</td><td>Voltar (ao lado do título).</td></tr>
						                                <tr><td><strong>DOCUMENTAÇÃO</strong></td><td>Esta página, com a documentação unificada executiva e técnica, glossário de KPIs e guia de performance.</td><td>Rastreabilidade técnica, auditoria de regras e onboarding de novos usuários.</td><td>Voltar ao relatório (ao lado do título).</td></tr>
						                            </tbody>
						                        </table>
						                        <div class='callout tech'>
						                            Os botões desenhados em HTML são visuais. A navegação real deve ser feita com botões nativos transparentes do Power BI posicionados por cima.
						                        </div>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>05</span><span class='summary-title'>KPIs e definição de cada card</span></div><span class='summary-action'>KPIs</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Card</th><th>Regra de cálculo</th><th>Como ler</th><th>Cuidado</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>Jobs listados</strong></td><td>Distinct count de JOB no recorte Journey.</td><td>Total de jobs Journey no período selecionado.</td><td>Respeita dinamicamente os slicers e o período de data.</td></tr>
						                                <tr><td><strong>Ativos</strong></td><td>Job com pelo menos uma linha diferente de FIM.</td><td>Diagnósticos operacionais que ainda requerem acompanhamento.</td><td>Um único subproduto fora de FIM mantém o job ativo.</td></tr>
						                                <tr><td><strong>Finalizados</strong></td><td>Job com todas as sub-linhas na etapa FIM.</td><td>Carteira de jobs operacionalmente encerrados.</td><td>Depende de todas as linhas do JOB estarem com NOME_AREA = ""FIM"".</td></tr>
						                                <tr><td><strong>Honorários Encontrados</strong></td><td>Soma distinta do valor máximo de JOB_HONORARIOS_ENCONTRADOS por JOB.</td><td>Volume total financeiro mapeado de honorários brutos no período.</td><td>Distinct count por JOB evita duplicidades causadas por subprodutos.</td></tr>
						                                <tr><td><strong>Honorários Agendados</strong></td><td>Soma distinta do valor máximo de JOB_HONORARIOS_AGENDADOS por JOB.</td><td>Volume total financeiro com agendamento concluído.</td><td>Distinct count por JOB protege contra duplicidades operacionais.</td></tr>
						                                <tr><td><strong>Dias mediano</strong></td><td>Mediana do campo DIAS na base.</td><td>Tempo médio típico que um job consome no fluxo.</td><td>A mediana é usada no lugar da média para neutralizar outliers extremos.</td></tr>
						                            </tbody>
						                        </table>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>06</span><span class='summary-title'>Regras de etapa, status e ação sugerida</span></div><span class='summary-action'>Regra</span></summary>
						                    <div class='section-body'>
						                        <div class='three-col'>
						                            <div class='callout'><strong>Ativo:</strong> existe pelo menos uma linha do job fora de FIM.</div>
						                            <div class='callout'><strong>Finalizado:</strong> todas as linhas do job estão em FIM.</div>
						                            <div class='callout'><strong>Passou:</strong> o job chegou em Operação, Procuração Eletrônica ou FIM (Stage >= 2).</div>
						                        </div>
						                        <div class='stage-box'>" & vStageHTML & "</div>
						                        <table class='doc-table' style='margin-top:10px'>
						                            <thead><tr><th>Etapa</th><th>Significado operacional</th><th>Ação sugerida na aba Detalhamento</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>Checklist</strong></td><td>Fase inicial de documentação, triagem e verificação preliminar.</td><td>Priorizar avanço.</td></tr>
						                                <tr><td><strong>Operação</strong></td><td>Execução técnica e operacional dos trabalhos de auditoria.</td><td>Acompanhar operação.</td></tr>
						                                <tr><td><strong>Procuração Eletrônica</strong></td><td>Aguardando liberação de procuração fiscal ou assinatura digital.</td><td>Acompanhar procuração.</td></tr>
						                                <tr><td><strong>Fim</strong></td><td>Finalizado, auditoria encerrada operacionalmente.</td><td>Finalizado.</td></tr>
						                                <tr><td><strong>Sem etapa mapeada</strong></td><td>Registros vazios ou fora do padrão em NOME_AREA.</td><td>Verificar base.</td></tr>
						                            </tbody>
						                        </table>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>07</span><span class='summary-title'>Slicers e interatividade</span></div><span class='summary-action'>Interação</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Slicer</th><th>Campo Técnico</th><th>Sincronização (syncGroup)</th><th>Função</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>Período</strong></td><td>`dCalendar[YearMonthName]`</td><td>`YearMonthName` (Completo)</td><td>Controla a janela temporal ativa das análises macros e detalhadas.</td></tr>
						                                <tr><td><strong>Área / Etapa</strong></td><td>`JOBS_Produto[NOME_AREA]`</td><td>`NOME_AREA` (Completo)</td><td>Filtra o relatório por etapas operacionais gargalos.</td></tr>
						                                <tr><td><strong>Cliente</strong></td><td>`JOBS_Produto[NOME_CLIENTE]`</td><td>`NOME_CLIENTE` (Completo)</td><td>Permite análise individualizada de contas operacionais.</td></tr>
							                                <tr><td><strong>Produto</strong></td><td>`DIM_PRODUTOS_IMAGEM_TAX[ProdutoImagem]`</td><td>Lista TAX da imagem</td><td>Filtra a visão principal para os produtos governados da imagem.</td></tr>
						                                <tr><td><strong>Usuário Responsável</strong></td><td>`JOBS_Produto[usunome]`</td><td>`usunome` (Completo)</td><td>Filtra a carteira por responsável direto do job.</td></tr>
						                            </tbody>
						                        </table>
						                        <div class='callout warn'>
						                            <strong>Nota sobre Camadas:</strong> No painel de Seleção do Power BI Desktop, garanta que os Slicers transparentes fiquem na camada mais alta. Se a medida HTML sobrepor um slicer, o clique nele será bloqueado.
						                        </div>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>08</span><span class='summary-title'>Calendário e relacionamentos</span></div><span class='summary-action'>Modelo</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Item</th><th>Configuração recomendada</th><th>Por quê</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>Tabela dCalendar</strong></td><td>Gerada dinamicamente entre o menor e maior `DATA_CADASTRO` da base.</td><td>Assegura consistência de período temporal.</td></tr>
						                                <tr><td><strong>Relacionamento Ativo</strong></td><td>`dCalendar[Date] (1) → JOBS_Produto[DATA_CADASTRO] (*)`</td><td>Data de criação do job é a âncora principal de recorte de safra.</td></tr>
						                                <tr><td><strong>Cardinalidade & Direção</strong></td><td>Um para muitos (1:*) / Única (dCalendar filtra JOBS_Produto).</td><td>Mantém integridade transacional de modelagem em estrela (Star Schema).</td></tr>
						                            </tbody>
						                        </table>
						                        <div class='callout tech'>
						                            <strong>Aviso Técnico:</strong> Caso surja a necessidade de analisar safras operacionais por `TRIBUTO_DATA_ENTRADA`, crie relacionamentos inativos e invoque-os nas medidas específicas usando a função `USERELATIONSHIP`. Nunca altere o relacionamento ativo principal.
						                        </div>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>09</span><span class='summary-title'>Aba Detalhamento & Limite de Performance</span></div><span class='summary-action'>Operação</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Elemento</th><th>O que faz</th><th>Como interpretar / Usar</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>Jobs listados (Card)</strong></td><td>Exibe o total real filtrado (`_totalJobs` ex: 2.074).</td><td>Alinhado 100% com a tela principal, respeitando slicers e períodos.</td></tr>
						                                <tr><td><strong>Tabela física (DOM)</strong></td><td>Carrega no máximo as **750 linhas mais recentes**.</td><td>Controle de segurança técnico (`vLimiteLinhas = 750`) para evitar lentidão e travamentos no Power BI.</td></tr>
						                                <tr><td><strong>Nota de Truncamento</strong></td><td>`TOTAL VISÍVEL APÓS FILTROS: 750 DE 2.074 NO PERÍODO`</td><td>Significa que 2.074 jobs atendem aos seus filtros, e os 750 mais relevantes estão carregados no navegador. Use slicers para afunilar a busca se precisar exportar dados específicos.</td></tr>
						                                <tr><td><strong>Busca Global & Colunas</strong></td><td>Pesquisa e filtra dinamicamente as linhas carregadas no visual.</td><td>Filtro instantâneo rodando via JavaScript no navegador (super rápido).</td></tr>
						                                <tr><td><strong>Copiar tabela</strong></td><td>Copia todas as linhas filtradas (visíveis) em formato tabulado.</td><td>Pronto para colar diretamente no Microsoft Excel (`Ctrl + V`).</td></tr>
						                            </tbody>
						                        </table>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>10</span><span class='summary-title'>Dados, campos e qualidade da base</span></div><span class='summary-action'>Dados</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Campo Original</th><th>Tipo / Regra</th><th>Uso / Importância Técnica</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>JOB</strong></td><td>Inteiro / ID do Job</td><td>Chave primária de agrupamento de diagnósticos. Linhas sem ID são excluídas.</td></tr>
						                                <tr><td><strong>DATA_CADASTRO</strong></td><td>Date / Anchored</td><td>Âncora de safra ativa ligada à dCalendar.</td></tr>
						                                <tr><td><strong>TRIBUTO_DATA_ENTRADA</strong></td><td>Date / Fallback</td><td>Usado para identificar a data do último movimento operacional.</td></tr>
						                                <tr><td><strong>JOB_HONORARIOS_ENCONTRADOS</strong></td><td>Currency</td><td>Valor bruto mapeado (soma distinta do máximo por JOB).</td></tr>
						                                <tr><td><strong>JOB_HONORARIOS_AGENDADOS</strong></td><td>Currency</td><td>Valor planejado operacionalmente (soma distinta do máximo por JOB).</td></tr>
						                                <tr><td><strong>CNPJ_CLIENTE / CNPJ_KEY</strong></td><td>Text</td><td>Cruzamento futuro com faturamento. No recorte atual existem " & FORMAT ( vCNPJBlank, vIntFormat ) & " registros sem CNPJ.</td></tr>
						                            </tbody>
						                        </table>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>11</span><span class='summary-title'>Medidas e objetos técnicos</span></div><span class='summary-action'>Técnico</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Medida DAX (medidas_html)</th><th>Função Principal</th><th>Recomendações de Manutenção</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>'HTML Diagnóstico Journey | Visual Principal'</strong></td><td>Gera o painel principal executivo, cards de KPI e a tabela por produto com expansão widescreen comparativa.</td><td>Alterar se precisar modificar o layout da grid principal, regras de comparação ou os cards de topo.</td></tr>
						                                <tr><td><strong>HTML_DETALHAMENTO_DIAGNOSTICO_JOURNEY_SEM_ESPACO_OCIOSO</strong></td><td>Gera o painel operacional de detalhamento com barra de busca JavaScript, filtros por coluna e limite de 750 linhas.</td><td>Alterar se precisar mudar campos visíveis na tabela job por job, alterar o script de busca ou regras de ação.</td></tr>
						                                <tr><td><strong>DOCUMENTACAO_DIAGNOSTICO_JOURNEY_HTML_V4_FORMAL_TODO_PERIODO</strong></td><td>Esta medida. Gera a página completa de documentação executiva e técnica.</td><td>Manter atualizada sempre que houver alteração de regras de negócio, tabelas ou novas features de escala.</td></tr>
						                                <tr><td><strong>Diagnóstico | Honorários Encontrados / Agendados</strong></td><td>Medidas base em DAX que realizam a soma distinta máxima por JOB no contexto atual.</td><td>Garantir que usem `MAX` por JOB encapsulado em `SUMX(SUMMARIZE(...))` para evitar duplicidades de subprodutos.</td></tr>
						                            </tbody>
						                        </table>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>12</span><span class='summary-title'>Checklist de validação técnica (QA)</span></div><span class='summary-action'>QA</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Validação</th><th>O que testar</th><th>Procedimento</th><th>Severidade</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>Sincronização de Slicers</strong></td><td>Mudança de filtro na principal se reflete na detalhada.</td><td>Mude o mês na tela principal para abril/2026. Navegue para detalhamento e confirme o total de 2.074.</td><td><span class='tag bad'>Alto</span></td></tr>
						                                <tr><td><strong>Suporte a Produtos Gerais</strong></td><td>Selecionar produto não-diagnóstico.</td><td>Filtre por Revisão Previdenciária. Confirme que os cards calculam normalmente e não ficam em branco.</td><td><span class='tag bad'>Alto</span></td></tr>
						                                <tr><td><strong>Soma distinta de Honorários</strong></td><td>Duplicidade por subproduto.</td><td>Valide se jobs com múltiplos subprodutos não duplicam a soma dos honorários encontrados.</td><td><span class='tag bad'>Alto</span></td></tr>
						                                <tr><td><strong>Desempenho de Renderização</strong></td><td>Consumo excessivo de RAM no navegador.</td><td>Valide se a tabela detalhada carrega instantaneamente. O limite de 750 linhas assegura isso.</td><td><span class='tag warn'>Médio</span></td></tr>
						                            </tbody>
						                        </table>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>13</span><span class='summary-title'>Performance e limites do HTML Content</span></div><span class='summary-action'>Performance</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Risco / Limite</th><th>Motivo Técnico</th><th>Estratégia de Mitigação Atual</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>Consumo excessivo de DOM</strong></td><td>O visual HTML renderiza todas as tags passadas via DAX. Milhares de elementos expansíveis travam o navegador.</td><td>Mover a listagem detalhada para uma página própria com paginação/limite de 750 registros mais relevantes.</td></tr>
						                                <tr><td><strong>Sobreposição de Camadas</strong></td><td>O visual HTML captura cliques do mouse em toda a sua área retangular.</td><td>Slicers nativos transparentes são colocados na camada mais alta (`Trazer para frente` no painel de Seleção).</td></tr>
						                                <tr><td><strong>Estouro de Buffer no DAX</strong></td><td>Medidas HTML com concatenações gigantes podem estourar a memória do Analysis Services.</td><td>A tabela widescreen da principal agrupa produtos por linha, e a detalhada limita a base física de rows para 750.</td></tr>
						                            </tbody>
						                        </table>
						                    </div>
						                </details>
						
						                <details class='doc-section' open>
						                    <summary><div class='summary-left'><span class='summary-index'>14</span><span class='summary-title'>Roadmap recomendado de escalabilidade</span></div><span class='summary-action'>Roadmap</span></summary>
						                    <div class='section-body'>
						                        <table class='doc-table'>
						                            <thead><tr><th>Prioridade</th><th>Ação Recomendada</th><th>Justificativa / Benefício</th></tr></thead>
						                            <tbody>
						                                <tr><td><strong>Alta</strong></td><td>Padronizar CNPJ de Clientes</td><td>Ajustar a fonte de dados para garantir que a chave do CNPJ tenha exatamente 14 dígitos (evitando inconsistências de cruzamento).</td></tr>
						                                <tr><td><strong>Média</strong></td><td>Centralizar Variáveis de Status</td><td>Criar uma tabela calculada centralizando as chaves e status de Jobs para reduzir o overhead de repetição de variáveis em DAX.</td></tr>
						                                <tr><td><strong>Média</strong></td><td>Implementar Drillthrough de CNPJ</td><td>Criar uma tela de detalhamento individual por CNPJ/Cliente, permitindo auditorias financeiras e operacionais focadas.</td></tr>
						                                <tr><td><strong>Baixa</strong></td><td>Exportação Direta Automatizada</td><td>Desenvolver fluxo automatizado por Power Automate para baixar toda a base consolidada sem a barreira de performance de 750 linhas.</td></tr>
						                            </tbody>
						                        </table>
						                        <div class='footer-doc'>
						                            Recorte atual: " & vPeriodo & ". Registros base: " & FORMAT ( vRegistros, vIntFormat ) & ". Jobs identificados: " & FORMAT ( vJobs, vIntFormat ) & ". Ativos: " & FORMAT ( vJobsAtivos, vIntFormat ) & ". Finalizados: " & FORMAT ( vJobsFinalizados, vIntFormat ) & ". Clientes distintos: " & FORMAT ( vClientes, vIntFormat ) & ". CNPJs válidos: " & FORMAT ( vCNPJs, vIntFormat ) & ". Produtos: " & FORMAT ( vProdutos, vIntFormat ) & ". Subprodutos: " & FORMAT ( vSubprodutos, vIntFormat ) & ". Oportunidades: " & FORMAT ( vOportunidadesDisp, vIntFormat ) & ". Atualizado em " & vAtualizadoEm & ".
						                        </div>
						                    </div>
						                </details>
						
						            </div>
						        </main>
						    </div>
						</div>"
						
						RETURN
						    vCSS & vHTML
			```
		displayFolder: 11 | Documentação
		lineageTag: f12039a5-a0eb-4967-9a5c-c2c27638806e

	measure HTML_DETALHAMENTO_DIAGNOSTICO_JOURNEY_SEM_ESPACO_OCIOSO = ```
			
			VAR vLimiteLinhas = 750
			VAR vIntFormat = "#,##0"
			VAR vPctFormat = "0.0%"
			
			VAR _css =
			"
			<style>
			:root{
			    --bg:#080b10;
			    --panel:rgba(14,18,24,.965);
			    --panel-2:#0e1218;
			    --border:rgba(213,174,119,.16);
			    --border-soft:rgba(255,255,255,.055);
			    --gold:#F4D9A9;
			    --gold-2:#D5AE77;
			    --teal:#8BE0D1;
			    --text:#ffffff;
			    --text-2:#AEB9C4;
			    --text-3:#6E7A86;
			    --green:#4ade80;
			    --red:#FFB0A8;
			    --warn:#F4D9A9;
			    --hover:rgba(213,174,119,.08);
			    --font:'Segoe UI',system-ui,sans-serif;
			}
			html,body{
			    margin:0;
			    padding:0;
			    width:100vw;
			    height:100vh;
			    background:var(--bg);
			    font-family:var(--font);
			    color:var(--text);
			    overflow:hidden;
			}
			*{box-sizing:border-box}
			.painel{
			    height:calc(100vh - 20px);
			    margin:10px;
			    padding:24px;
			    display:flex;
			    flex-direction:column;
			    border-radius:18px;
			    border:1px solid var(--border);
			    background:
			        radial-gradient(circle at 0% 0%,rgba(213,174,119,.16),transparent 28%),
			        radial-gradient(circle at 92% 4%,rgba(139,224,209,.10),transparent 28%),
			        linear-gradient(180deg,#101923 0%,#0B1219 100%);
			    box-shadow:0 18px 48px rgba(0,0,0,.48),inset 0 1px 0 rgba(255,255,255,.05);
			}
			.cabecalho{
			    display:flex;
			    justify-content:space-between;
			    align-items:center;
			    gap:18px;
			    flex-shrink:0;
			    padding-bottom:15px;
			    margin-bottom:14px;
			    border-bottom:1px solid var(--border);
			}
			.cabecalho-esquerda{
			    display:flex;
			    align-items:center;
			    gap:16px;
			    min-width:0;
			}
			.btn-voltar,.btn-copiar{
			    display:flex;
			    align-items:center;
			    justify-content:center;
			    gap:7px;
			    min-height:38px;
			    border-radius:10px;
			    padding:9px 15px;
			    border:1px solid var(--border);
			    background:rgba(213,174,119,.08);
			    color:var(--gold);
			    cursor:pointer;
			    font-family:var(--font);
			    font-size:13.8px;
			    font-weight:950;
			    letter-spacing:.08em;
			    text-transform:uppercase;
			    white-space:nowrap;
			    transition:all .2s ease;
			}
			.btn-voltar:hover,.btn-copiar:hover{
			    background:rgba(213,174,119,.15);
			    border-color:var(--gold-2);
			    color:#fff;
			    box-shadow:0 0 16px rgba(213,174,119,.16);
			}
			.titulo{
			    display:flex;
			    align-items:center;
			    gap:11px;
			    color:var(--gold);
			    font-size:30px;
			    font-weight:950;
			    letter-spacing:.10em;
			    text-transform:uppercase;
			    white-space:nowrap;
			    overflow:hidden;
			    text-overflow:ellipsis;
			}
			.titulo:before{
			    content:'';
			    display:inline-block;
			    width:7px;
			    height:28px;
			    border-radius:6px;
			    background:linear-gradient(180deg,var(--gold),var(--gold-2),var(--teal));
			    box-shadow:0 0 18px rgba(213,174,119,.22);
			}
			.controles{
			    display:flex;
			    align-items:center;
			    justify-content:flex-end;
			    gap:12px;
			    flex-shrink:0;
			}
			.busca-global{
			    width:370px;
			    border-radius:10px;
			    border:1px solid var(--border);
			    outline:none;
			    background:rgba(213,174,119,.055);
			    color:#fff;
			    font-family:var(--font);
			    font-size:15.6px;
			    padding:13px 18px;
			    transition:all .25s ease;
			}
			.busca-global:focus{
			    width:430px;
			    border-color:var(--gold-2);
			    background:rgba(213,174,119,.09);
			    box-shadow:0 0 0 3px rgba(213,174,119,.06);
			}
			.resumo{
			    display:grid;
			    grid-template-columns:repeat(6,1fr);
			    gap:10px;
			    flex-shrink:0;
			    margin-bottom:13px;
			}
			.kpi{
			    min-height:92px;
			    position:relative;
			    overflow:hidden;
			    border-radius:15px;
			    border:1px solid rgba(255,255,255,.09);
			    background:linear-gradient(155deg,rgba(18,28,37,.96),rgba(11,18,25,.94));
			    padding:14px 13px 12px;
			    box-shadow:0 14px 26px rgba(0,0,0,.20),inset 0 1px 0 rgba(255,255,255,.05);
			}
			.kpi.primary{
			    border-color:rgba(213,174,119,.38);
			    background:linear-gradient(155deg,rgba(213,174,119,.18),rgba(18,28,37,.96) 34%,rgba(11,18,25,.96));
			}
			.kpi:before{
			    content:'';
			    position:absolute;
			    left:13px;
			    top:0;
			    width:42px;
			    height:4px;
			    border-radius:0 0 9px 9px;
			    background:linear-gradient(90deg,var(--gold),var(--teal));
			}
			.kpi-label{
			    display:block;
			    color:var(--text-2);
			    font-size:10.8px;
			    font-weight:950;
			    letter-spacing:.08em;
			    text-transform:uppercase;
			    margin-bottom:7px;
			}
			.kpi-value{
			    display:block;
			    color:var(--gold);
			    font-size:28.8px;
			    font-weight:950;
			    line-height:1.05;
			    white-space:nowrap;
			    overflow:hidden;
			    text-overflow:ellipsis;
			}
			.kpi-note{
			    display:block;
			    color:var(--text-3);
			    font-size:13px;
			    font-weight:850;
			    margin-top:6px;
			    white-space:nowrap;
			    overflow:hidden;
			    text-overflow:ellipsis;
			}
			.table-wrapper{
			    flex:1 1 auto;
			    min-height:0;
			    overflow-y:auto;
			    overflow-x:hidden;
			    padding-right:8px;
			    position:relative;
			}
			.table-wrapper::-webkit-scrollbar{width:8px;height:0}
			.table-wrapper::-webkit-scrollbar-track{background:rgba(255,255,255,.025);border-radius:999px}
			.table-wrapper::-webkit-scrollbar-thumb{background:rgba(213,174,119,.38);border-radius:999px}
			.table-wrapper::-webkit-scrollbar-thumb:hover{background:rgba(213,174,119,.62)}
			.tabela{
			    width:100%;
			    min-width:0;
			    max-width:100%;
			    table-layout:fixed;
			    border-collapse:collapse;
			}
			.tabela th{
			    position:sticky;
			    top:0;
			    z-index:5;
			    padding:12px 8px;
			    background:#0e1218;
			    color:var(--gold-2);
			    border-bottom:1px solid rgba(213,174,119,.28);
			    box-shadow:0 1px 0 var(--border);
			    text-align:left;
			    font-size:11.7px;
			    font-weight:950;
			    text-transform:uppercase;
			    letter-spacing:.09em;
			}
			.tabela td{
			    padding:12px 8px;
			    color:#fff;
			    border-bottom:1px solid var(--border-soft);
			    font-size:14px;
			    line-height:1.32;
			    vertical-align:middle;
			    transition:background .18s ease;
			}
			.tabela tr:hover td{background:var(--hover)}
			.tabela tr:hover td:first-child{
			    border-left:3px solid var(--gold-2);
			    padding-left:9px;
			    color:var(--gold);
			}
			.col-filter{
			    width:100%;
			    margin-top:7px;
			    padding:7px 8px;
			    border-radius:6px;
			    border:1px solid var(--border);
			    background:rgba(0,0,0,.28);
			    color:#fff;
			    outline:none;
			    font-family:var(--font);
			    font-size:11.8px;
			    font-weight:700;
			}
			.col-filter:focus{
			    border-color:var(--gold-2);
			    background:rgba(213,174,119,.08);
			}
			.col-filter::placeholder{color:var(--text-3)}
			.td-job{
			    display:flex;
			    align-items:center;
			    gap:10px;
			    font-weight:950;
			    color:#F8EFE1;
			    white-space:nowrap;
			    overflow:hidden;
			    text-overflow:ellipsis;
			}
			.td-job-text{
			    min-width:0;
			    overflow:hidden;
			    text-overflow:ellipsis;
			}
			.td-cliente,.td-produto,.td-ops{
			    max-width:310px;
			    white-space:nowrap;
			    overflow:hidden;
			    text-overflow:ellipsis;
			}
			.td-cnpj{
			    white-space:nowrap;
			    color:#DCE5EE;
			    overflow:hidden;
			    text-overflow:ellipsis;
			}
			.chip{
			    display:inline-flex;
			    align-items:center;
			    justify-content:center;
			    border-radius:999px;
			    padding:5px 8px;
			    font-size:11.9px;
			    font-weight:950;
			    letter-spacing:.04em;
			    text-transform:uppercase;
			    white-space:nowrap;
			    border:1px solid rgba(255,255,255,.10);
			    background:rgba(255,255,255,.045);
			    color:var(--text-2);
			}
			.chip-check,.chip-priorizar{
			    color:var(--red);
			    border-color:rgba(255,176,168,.32);
			    background:rgba(217,93,93,.10);
			}
			.chip-oper,.chip-acompanhar{
			    color:var(--gold);
			    border-color:rgba(213,174,119,.34);
			    background:rgba(213,174,119,.10);
			}
			.chip-proc,.chip-ok{
			    color:var(--teal);
			    border-color:rgba(139,224,209,.34);
			    background:rgba(139,224,209,.09);
			}
			.chip-fim{
			    color:var(--green);
			    border-color:rgba(74,222,128,.34);
			    background:rgba(74,222,128,.08);
			}
			.num{
			    text-align:center;
			    font-weight:950;
			    color:var(--gold);
			}
			.date-cell{
			    text-align:center;
			    color:#DCE5EE;
			    white-space:nowrap;
			    overflow:hidden;
			    text-overflow:ellipsis;
			}
			.days{
			    text-align:center;
			    font-weight:950;
			    color:var(--gold);
			    white-space:nowrap;
			    overflow:hidden;
			    text-overflow:ellipsis;
			}
			
			.expand-btn{
			    user-select:none;
			    width:24px;
			    height:24px;
			    display:inline-flex;
			    align-items:center;
			    justify-content:center;
			    border-radius:10px;
			    border:1px solid rgba(213,174,119,.34);
			    background:rgba(213,174,119,.08);
			    color:var(--gold);
			    font-size:12px;
			    font-weight:950;
			    cursor:pointer;
			    transition:all .18s ease;
			}
			.expand-btn:hover{
			    background:rgba(213,174,119,.16);
			    border-color:var(--gold-2);
			    box-shadow:0 0 14px rgba(213,174,119,.16);
			}
			.expand-btn.open{
			    color:#081018;
			    background:linear-gradient(135deg,var(--gold),var(--gold-2),var(--teal));
			    border-color:rgba(244,217,169,.72);
			    transform:rotate(90deg);
			}
			.linha-detalhe[data-expanded='1'] td{
			    background:rgba(213,174,119,.055);
			}
			.linha-extra{
			    display:none;
			}
			.linha-extra td{
			    padding:0!important;
			    background:rgba(4,8,12,.58)!important;
			    border-bottom:1px solid rgba(213,174,119,.18)!important;
			}
			.job-extra-panel{
			    padding:18px 20px 20px 64px;
			    border-left:3px solid rgba(213,174,119,.42);
			    background:
			        radial-gradient(circle at 0% 0%,rgba(213,174,119,.10),transparent 30%),
			        linear-gradient(180deg,rgba(12,20,28,.92),rgba(6,11,16,.96));
			}
			.job-extra-top{
			    display:flex;
			    align-items:flex-start;
			    justify-content:space-between;
			    flex-wrap:wrap;
			    gap:14px;
			    margin-bottom:14px;
			}
			.job-extra-title{
			    color:var(--gold);
			    font-size:18px;
			    font-weight:950;
			    letter-spacing:.04em;
			    text-transform:uppercase;
			}
			.job-extra-subtitle{
			    margin-top:5px;
			    color:var(--text-2);
			    font-size:13.5px;
			    font-weight:850;
			    line-height:1.35;
			}
			.job-extra-kpis{
			    display:flex;
			    gap:8px;
			    flex-wrap:wrap;
			    justify-content:flex-start;
			}
			.extra-pill{
			    display:inline-flex;
			    align-items:center;
			    gap:5px;
			    padding:7px 10px;
			    border-radius:999px;
			    border:1px solid rgba(255,255,255,.10);
			    background:rgba(255,255,255,.045);
			    color:var(--text-2);
			    font-size:12px;
			    font-weight:900;
			    white-space:nowrap;
			}
			.extra-pill strong{
			    color:var(--gold);
			    font-weight:950;
			}
			.extra-pill.good{
			    color:var(--teal);
			    border-color:rgba(139,224,209,.30);
			    background:rgba(139,224,209,.08);
			}
			.extra-pill.warn{
			    color:var(--gold);
			    border-color:rgba(213,174,119,.30);
			    background:rgba(213,174,119,.08);
			}
			.extra-grid{
			    display:grid;
			    grid-template-columns:repeat(4,minmax(130px,1fr));
			    gap:10px;
			    margin-bottom:12px;
			}
			.extra-card{
			    min-width:0;
			    border:1px solid rgba(255,255,255,.08);
			    background:rgba(255,255,255,.035);
			    border-radius:14px;
			    padding:12px 12px;
			}
			.extra-card span{
			    display:block;
			    color:var(--text-3);
			    font-size:11px;
			    font-weight:950;
			    letter-spacing:.07em;
			    text-transform:uppercase;
			    margin-bottom:6px;
			}
			.extra-card b{
			    display:block;
			    color:#F0F5FA;
			    font-size:14px;
			    font-weight:900;
			    white-space:nowrap;
			    overflow:hidden;
			    text-overflow:ellipsis;
			}
			.extra-section{
			    border:1px solid rgba(255,255,255,.08);
			    background:rgba(255,255,255,.025);
			    border-radius:14px;
			    padding:12px;
			    margin-top:10px;
			}
			.extra-section-title{
			    color:var(--gold-2);
			    font-size:12px;
			    font-weight:950;
			    letter-spacing:.08em;
			    text-transform:uppercase;
			    margin-bottom:10px;
			}
			.extra-chip-wrap{
			    display:flex;
			    gap:8px;
			    flex-wrap:wrap;
			}
			.area-detail-chip,.detail-opp{
			    display:inline-flex;
			    align-items:center;
			    gap:7px;
			    padding:7px 10px;
			    border-radius:999px;
			    border:1px solid rgba(255,255,255,.10);
			    background:rgba(255,255,255,.045);
			    color:#DCE5EE;
			    font-size:12px;
			    font-weight:850;
			}
			.detail-opp.passed{
			    color:var(--teal);
			    border-color:rgba(139,224,209,.30);
			    background:rgba(139,224,209,.08);
			}
			.detail-opp.open{
			    color:var(--gold);
			    border-color:rgba(213,174,119,.26);
			    background:rgba(213,174,119,.07);
			}
			.detail-opp em{
			    color:var(--text-3);
			    font-style:normal;
			    font-size:10.5px;
			    font-weight:950;
			    text-transform:uppercase;
			}
			.job-extra-search{
			    display:none;
			}
			
			.tabela tfoot td{
			    position:sticky;
			    bottom:-1px;
			    z-index:5;
			    background:#0e1218;
			    border-top:2px solid var(--gold-2);
			    border-bottom:none;
			    color:var(--gold);
			    font-size:15px;
			    font-weight:950;
			    letter-spacing:.06em;
			    text-transform:uppercase;
			}
			.count-destaque{
			    display:inline-flex;
			    align-items:center;
			    justify-content:center;
			    min-width:44px;
			    margin-left:8px;
			    padding:5px 10px;
			    border-radius:8px;
			    border:1px solid var(--gold-2);
			    background:rgba(213,174,119,.18);
			    color:#fff;
			    font-size:20px;
			    font-weight:950;
			}
			.empty{
			    text-align:center;
			    padding:46px!important;
			    color:var(--text-3)!important;
			    font-size:17.5px!important;
			}
			
			@media(max-width:1500px){
			    .tabela th{font-size:10.5px;padding:10px 6px}
			    .tabela td{font-size:12.8px;padding:10px 6px}
			    .chip{font-size:9.6px;padding:4px 6px}
			    .col-filter{font-size:10.5px;padding:6px 6px}
			    .td-cliente,.td-produto,.td-ops{max-width:100%}
			    .extra-grid{grid-template-columns:repeat(2,minmax(130px,1fr))}
			}
			
			</style>
			"
			
			VAR _js =
			"
			<script>
			function safeText(selector,row){
			    var el=row.querySelector(selector);
			    return el ? el.textContent.toLowerCase() : '';
			}
			
			function filtrarTabela(){
			    var qG=document.getElementById('buscaGlobal').value.toLowerCase();
			    var qJ=document.getElementById('buscaColJob').value.toLowerCase();
			    var qE=document.getElementById('buscaColEtapa').value.toLowerCase();
			    var qC=document.getElementById('buscaColCliente').value.toLowerCase();
			    var qP=document.getElementById('buscaColProduto').value.toLowerCase();
			    var rows=document.querySelectorAll('.linha-detalhe');
			    var count=0;
			    for(var i=0;i<rows.length;i++){
			        var detail=rows[i].nextElementSibling;
			        var detailText=(detail && detail.classList.contains('linha-extra')) ? detail.textContent.toLowerCase() : '';
			        var tJ=safeText('.td-job',rows[i]);
			        var tE=safeText('.td-etapa',rows[i]);
			        var tA=safeText('.td-acao',rows[i]);
			        var tC=safeText('.td-cliente',rows[i]);
			        var tCNPJ=safeText('.td-cnpj',rows[i]);
			        var tP=safeText('.td-produto',rows[i]);
			        var tOps=safeText('.td-ops',rows[i]);
			        var matchG=(qG===''||tJ.indexOf(qG)>-1||tE.indexOf(qG)>-1||tA.indexOf(qG)>-1||tC.indexOf(qG)>-1||tCNPJ.indexOf(qG)>-1||tP.indexOf(qG)>-1||tOps.indexOf(qG)>-1||detailText.indexOf(qG)>-1);
			        var matchCols=(tJ.indexOf(qJ)>-1&&tE.indexOf(qE)>-1&&tC.indexOf(qC)>-1&&tP.indexOf(qP)>-1);
			        if(matchG&&matchCols){
			            rows[i].style.display='';
			            if(detail && detail.classList.contains('linha-extra')){
			                detail.style.display=(rows[i].dataset.expanded==='1')?'table-row':'none';
			            }
			            count++;
			        }else{
			            rows[i].style.display='none';
			            if(detail && detail.classList.contains('linha-extra')){detail.style.display='none';}
			        }
			    }
			    var countEl=document.getElementById('totalJobsCount');
			    if(countEl){countEl.textContent=count;}
			}
			function toggleJob(btn){
			    var row=btn.closest('tr');
			    if(!row){return;}
			    var detail=row.nextElementSibling;
			    if(!detail || !detail.classList.contains('linha-extra')){return;}
			    var open=row.dataset.expanded==='1';
			    row.dataset.expanded=open?'0':'1';
			    btn.classList.toggle('open',!open);
			    detail.style.display=open?'none':'table-row';
			}
			setTimeout(filtrarTabela,100);
			function copiarTabela(){
			    var btn=document.getElementById('btnCopiar');
			    var originalText=btn.innerHTML;
			    btn.innerHTML='&#8982; Copiando...';
			    var textToCopy='';
			    var ths=document.querySelectorAll('.tabela thead th');
			    for(var i=0;i<ths.length;i++){
			        var span=ths[i].querySelector('span');
			        var thText=span?span.textContent.trim():ths[i].textContent.trim();
			        textToCopy+=thText+(i===ths.length-1?'\n':'\t');
			    }
			    var rows=document.querySelectorAll('.linha-detalhe');
			    var copiedCount=0;
			    for(var r=0;r<rows.length;r++){
			        if(rows[r].style.display!=='none'){
			            var tds=rows[r].querySelectorAll('td');
			            for(var j=0;j<tds.length;j++){
			                var cellText=tds[j].textContent.trim().replace(/\s+/g,' '); if(j===0){cellText=cellText.replace(/^▶\s*/, '');} textToCopy+=cellText+(j===tds.length-1?'\n':'\t');
			            }
			            copiedCount++;
			        }
			    }
			    try{
			        var textArea=document.createElement('textarea');
			        textArea.value=textToCopy;
			        textArea.style.position='fixed';
			        textArea.style.opacity='0';
			        document.body.appendChild(textArea);
			        textArea.focus();
			        textArea.select();
			        var successful=document.execCommand('copy');
			        document.body.removeChild(textArea);
			        if(successful){
			            btn.innerHTML='&#10004; Copiado ('+copiedCount+' linhas)';
			            btn.style.borderColor='var(--green)';
			            btn.style.color='var(--green)';
			            setTimeout(function(){
			                btn.innerHTML=originalText;
			                btn.style.borderColor='var(--border)';
			                btn.style.color='var(--gold)';
			            },3000);
			        }else{throw new Error('copy failed');}
			    }catch(err){
			        btn.innerHTML='&#10060; Erro ao copiar';
			        setTimeout(function(){btn.innerHTML=originalText;},3000);
			    }
			}
			</script>
			"
			
			VAR _base = 'JOBS_Produto'
			
			VAR _jobsStage =
			    ADDCOLUMNS (
			        SUMMARIZE ( _base, 'JOBS_Produto'[JOB] ),
			        "__Stage",
			            VAR vJobKey = 'JOBS_Produto'[JOB]
			            VAR vJobRows =
			                SELECTCOLUMNS (
			                    FILTER ( _base, 'JOBS_Produto'[JOB] = vJobKey ),
			                    "@S",
			                        VAR vArea = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
			                        RETURN
			                            SWITCH (
			                                TRUE (),
			                                vArea = "CHECKLIST", 1,
			                                vArea = "OPERAÇÃO", 2,
			                                vArea = "OPERACAO", 2,
			                                vArea = "PROCURAÇÃO ELETRÔNICA", 3,
			                                vArea = "PROCURACAO ELETRONICA", 3,
			                                vArea = "FIM", 4,
			                                0
			                            )
			                )
			            VAR vMaxAll = MAXX ( vJobRows, [@S] )
			            VAR vMaxOpen = MAXX ( FILTER ( vJobRows, [@S] < 4 ), [@S] )
			            RETURN
			                IF ( vMaxAll = 4 && ISBLANK ( vMaxOpen ), 4, COALESCE ( vMaxOpen, 0 ) )
			    )
			
			VAR _jobsBase =
			    ADDCOLUMNS (
			        _jobsStage,
			
			        "__Cliente",
			            VAR _job = 'JOBS_Produto'[JOB]
			            RETURN
			                COALESCE (
			                    MAXX (
			                        FILTER ( _base, 'JOBS_Produto'[JOB] = _job && NOT ISBLANK ( 'JOBS_Produto'[NOME_CLIENTE] ) ),
			                        'JOBS_Produto'[NOME_CLIENTE]
			                    ),
			                    "Sem cliente"
			                ),
			
			        "__CNPJ",
			            VAR _job = 'JOBS_Produto'[JOB]
			            RETURN
			                COALESCE (
			                    MAXX (
			                        FILTER ( _base, 'JOBS_Produto'[JOB] = _job && NOT ISBLANK ( 'JOBS_Produto'[CNPJ_CLIENTE] ) ),
			                        'JOBS_Produto'[CNPJ_CLIENTE] & ""
			                    ),
			                    "Sem CNPJ"
			                ),
			
			        "__Produto",
			            VAR _job = 'JOBS_Produto'[JOB]
			            RETURN
			                COALESCE (
			                    MAXX (
			                        FILTER ( _base, 'JOBS_Produto'[JOB] = _job && NOT ISBLANK ( 'JOBS_Produto'[NOME_PRODUTO] ) ),
			                        'JOBS_Produto'[NOME_PRODUTO]
			                    ),
			                    "Sem produto"
			                ),
			
			        "__Subproduto",
			            VAR _job = 'JOBS_Produto'[JOB]
			            RETURN
			                COALESCE (
			                    MAXX (
			                        FILTER ( _base, 'JOBS_Produto'[JOB] = _job && NOT ISBLANK ( 'JOBS_Produto'[NOME_SUBPRODUTO] ) ),
			                        'JOBS_Produto'[NOME_SUBPRODUTO]
			                    ),
			                    "Sem subproduto"
			                ),
			
			        "__DataCadastro",
			            VAR _job = 'JOBS_Produto'[JOB]
			            RETURN
			                MINX ( FILTER ( _base, 'JOBS_Produto'[JOB] = _job ), 'JOBS_Produto'[DATA_CADASTRO] ),
			
			        "__UltimoMovimento",
			            VAR _job = 'JOBS_Produto'[JOB]
			            RETURN
			                MAXX (
			                    FILTER ( _base, 'JOBS_Produto'[JOB] = _job ),
			                    COALESCE ( 'JOBS_Produto'[TRIBUTO_DATA_ENTRADA], 'JOBS_Produto'[DATA_CADASTRO] )
			                ),
			
			        "__Dias",
			            VAR _job = 'JOBS_Produto'[JOB]
			            RETURN
			                MAXX ( FILTER ( _base, 'JOBS_Produto'[JOB] = _job ), 'JOBS_Produto'[DIAS] ),
			
			        "__StageSort", [__Stage],
			
			        "__EtapaAtual",
			            SWITCH (
			                [__Stage],
			                1, "Checklist",
			                2, "Operação",
			                3, "Procuração",
			                4, "Fim",
			                "Sem etapa"
			            ),
			
			        "__Status",
			            IF ( [__Stage] = 4, "Finalizado", "Ativo" ),
			
			        "__Acao",
			            SWITCH (
			                [__Stage],
			                4, "Finalizado",
			                1, "Priorizar avanço",
			                2, "Acompanhar operação",
			                3, "Acompanhar procuração",
			                "Verificar base"
			            ),
			
			        "__OportDisp",
			            VAR _job = 'JOBS_Produto'[JOB]
			            RETURN
			                COUNTROWS (
			                    SUMMARIZE (
			                        FILTER ( _base, 'JOBS_Produto'[JOB] = _job && NOT ISBLANK ( 'JOBS_Produto'[NOME_TRIBUTO] ) ),
			                        'JOBS_Produto'[NOME_TRIBUTO]
			                    )
			                ),
			
			        "__OportPass",
			            VAR _job = 'JOBS_Produto'[JOB]
			            VAR _jobRows =
			                FILTER (
			                    _base,
			                    'JOBS_Produto'[JOB] = _job
			                        && NOT ISBLANK ( 'JOBS_Produto'[NOME_TRIBUTO] )
			                        && (
			                            VAR _areaPass = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
			                            RETURN
			                                _areaPass IN {
			                                    "OPERAÇÃO",
			                                    "OPERACAO",
			                                    "PROCURAÇÃO ELETRÔNICA",
			                                    "PROCURACAO ELETRONICA",
			                                    "FIM"
			                                }
			                        )
			                )
			            RETURN
			                COUNTROWS ( SUMMARIZE ( _jobRows, 'JOBS_Produto'[NOME_TRIBUTO] ) ),
			
			        "__OportunidadesLista",
			            VAR _job = 'JOBS_Produto'[JOB]
			            VAR _jobRows = FILTER ( _base, 'JOBS_Produto'[JOB] = _job )
			            VAR _topOps =
			                TOPN (
			                    5,
			                    ADDCOLUMNS (
			                        SUMMARIZE (
			                            FILTER ( _jobRows, NOT ISBLANK ( 'JOBS_Produto'[NOME_TRIBUTO] ) ),
			                            'JOBS_Produto'[NOME_TRIBUTO]
			                        ),
			                        "__Passou",
			                            VAR _trib = 'JOBS_Produto'[NOME_TRIBUTO]
			                            RETURN
			                                COUNTROWS (
			                                    FILTER (
			                                        _jobRows,
			                                        COALESCE ( 'JOBS_Produto'[NOME_TRIBUTO], "" ) = COALESCE ( _trib, "" )
			                                            && (
			                                                VAR _areaPass = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
			                                                RETURN
			                                                    _areaPass IN {
			                                                        "OPERAÇÃO",
			                                                        "OPERACAO",
			                                                        "PROCURAÇÃO ELETRÔNICA",
			                                                        "PROCURACAO ELETRONICA",
			                                                        "FIM"
			                                                    }
			                                            )
			                                    )
			                                )
			                    ),
			                    [__Passou], DESC,
			                    'JOBS_Produto'[NOME_TRIBUTO], ASC
			                )
			            RETURN
			                COALESCE (
			                    CONCATENATEX (
			                        _topOps,
			                        'JOBS_Produto'[NOME_TRIBUTO] & IF ( [__Passou] > 0, " ✓", "" ),
			                        " · ",
			                        [__Passou], DESC
			                    ),
			                    "Sem oportunidades"
			                )
			    )
			
			VAR _totalJobs = COUNTROWS ( _jobsBase )
			VAR _jobsAtivos = COUNTROWS ( FILTER ( _jobsBase, [__Status] = "Ativo" ) )
			VAR _jobsFinalizados = COUNTROWS ( FILTER ( _jobsBase, [__Status] = "Finalizado" ) )
			VAR _jobsPassaram = COUNTROWS ( FILTER ( _jobsBase, [__StageSort] >= 2 ) )
			VAR _pctPassaram = DIVIDE ( _jobsPassaram, _totalJobs , 0 )
			VAR _oportDispTotal =
			    COUNTROWS (
			        SUMMARIZE (
			            FILTER ( _base, NOT ISBLANK ( 'JOBS_Produto'[NOME_TRIBUTO] ) ),
			            'JOBS_Produto'[NOME_TRIBUTO]
			        )
			    )
			VAR _oportPassTotal =
			    COUNTROWS (
			        SUMMARIZE (
			            FILTER (
			                _base,
			                NOT ISBLANK ( 'JOBS_Produto'[NOME_TRIBUTO] )
			                    && (
			                        VAR _areaPass = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
			                        RETURN
			                            _areaPass IN {
			                                "OPERAÇÃO",
			                                "OPERACAO",
			                                "PROCURAÇÃO ELETRÔNICA",
			                                "PROCURACAO ELETRONICA",
			                                "FIM"
			                            }
			                    )
			            ),
			            'JOBS_Produto'[NOME_TRIBUTO]
			        )
			    )
			
			VAR _jobsDetalhe =
			    TOPN (
			        vLimiteLinhas,
			        _jobsBase,
			        [__Status], ASC,
			        [__StageSort], ASC,
			        [__Dias], DESC,
			        [__DataCadastro], DESC,
			        'JOBS_Produto'[JOB], ASC
			    )
			
			VAR _qtdListada = COUNTROWS ( _jobsDetalhe )
			
			VAR _opcoesProduto =
			    CONCATENATEX (
			        SUMMARIZE ( _base, 'JOBS_Produto'[NOME_PRODUTO] ),
			        "<option value='" & SUBSTITUTE ( COALESCE ( 'JOBS_Produto'[NOME_PRODUTO], "" ), "'", "&#39;" ) & "'></option>",
			        "",
			        'JOBS_Produto'[NOME_PRODUTO], ASC
			    )
			
			VAR _opcoesEtapa =
			    "<option value='Checklist'></option>"
			        & "<option value='Operação'></option>"
			        & "<option value='Procuração'></option>"
			        & "<option value='Fim'></option>"
			        & "<option value='Sem etapa'></option>"
			
			VAR _linhas =
			    CONCATENATEX (
			        _jobsDetalhe,
			        VAR _stage = [__StageSort]
			        VAR _etapaClass =
			            SWITCH (
			                TRUE (),
			                _stage = 1, "chip-check",
			                _stage = 2, "chip-oper",
			                _stage = 3, "chip-proc",
			                _stage = 4, "chip-fim",
			                "chip"
			            )
			        VAR _acao = [__Acao]
			        VAR _acaoClass =
			            SWITCH (
			                TRUE (),
			                _acao = "Finalizado", "chip-fim",
			                _acao = "Priorizar avanço", "chip-priorizar",
			                _acao = "Acompanhar operação", "chip-acompanhar",
			                _acao = "Acompanhar procuração", "chip-ok",
			                "chip"
			            )
			        VAR _jobKey = 'JOBS_Produto'[JOB]
			        VAR _jobRows =
			            FILTER ( _base, 'JOBS_Produto'[JOB] = _jobKey )
			        VAR _qtdLinhas =
			            COUNTROWS ( _jobRows )
			        VAR _modeloProduto =
			            COALESCE (
			                MAXX (
			                    FILTER ( _jobRows, NOT ISBLANK ( 'JOBS_Produto'[MODELO_PRODUTO] ) ),
			                    'JOBS_Produto'[MODELO_PRODUTO]
			                ),
			                "Sem modelo produto"
			            )
			        VAR _modeloNegocio =
			            COALESCE (
			                MAXX (
			                    FILTER ( _jobRows, NOT ISBLANK ( 'JOBS_Produto'[MODELO_NEGOCIO] ) ),
			                    'JOBS_Produto'[MODELO_NEGOCIO]
			                ),
			                "Sem modelo negócio"
			            )
			        VAR _areasResumo =
			            CONCATENATEX (
			                ADDCOLUMNS (
			                    SUMMARIZE ( _jobRows, 'JOBS_Produto'[NOME_AREA] ),
			                    "__QtdArea",
			                        VAR _areaKey = 'JOBS_Produto'[NOME_AREA]
			                        RETURN
			                            COUNTROWS (
			                                FILTER (
			                                    _jobRows,
			                                    COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) = COALESCE ( _areaKey, "" )
			                                )
			                            )
			                ),
			                "<span class='area-detail-chip'>" & COALESCE ( 'JOBS_Produto'[NOME_AREA], "Sem área" ) & " · " & FORMAT ( [__QtdArea], vIntFormat ) & "</span>",
			                "",
			                [__QtdArea], DESC
			            )
			        VAR _opsDetalhe =
			            COALESCE (
			                CONCATENATEX (
			                    TOPN (
			                        6,
			                        ADDCOLUMNS (
			                            SUMMARIZE (
			                                FILTER ( _jobRows, NOT ISBLANK ( 'JOBS_Produto'[NOME_TRIBUTO] ) ),
			                                'JOBS_Produto'[NOME_TRIBUTO]
			                            ),
			                            "__Passou",
			                                VAR _trib = 'JOBS_Produto'[NOME_TRIBUTO]
			                                RETURN
			                                    COUNTROWS (
			                                        FILTER (
			                                            _jobRows,
			                                            COALESCE ( 'JOBS_Produto'[NOME_TRIBUTO], "" ) = COALESCE ( _trib, "" )
			                                                && (
			                                                    VAR _areaPass = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
			                                                    RETURN
			                                                        _areaPass IN {
			                                                            "OPERAÇÃO",
			                                                            "OPERACAO",
			                                                            "PROCURAÇÃO ELETRÔNICA",
			                                                            "PROCURACAO ELETRONICA",
			                                                            "FIM"
			                                                        }
			                                                )
			                                        )
			                                    )
			                        ),
			                        [__Passou], DESC,
			                        'JOBS_Produto'[NOME_TRIBUTO], ASC
			                    ),
			                    "<span class='detail-opp " & IF ( [__Passou] > 0, "passed", "open" ) & "'>"
			                        & 'JOBS_Produto'[NOME_TRIBUTO]
			                        & "<em>" & IF ( [__Passou] > 0, "passou", "disp." ) & "</em>"
			                    & "</span>",
			                    "",
			                    [__Passou], DESC
			                ),
			                "<span class='detail-opp open'>Sem oportunidades<em>disp.</em></span>"
			            )
			        RETURN
			            "<tr class='linha-detalhe' data-expanded='0'>"
			                & "<td class='td-job'><span class='expand-btn' onclick='toggleJob(this)' title='Expandir detalhes do job'>▶</span><span class='td-job-text'>" & 'JOBS_Produto'[JOB] & "</span></td>"
			                & "<td class='td-etapa'><span class='chip " & _etapaClass & "'>" & [__EtapaAtual] & "</span></td>"
			                & "<td class='td-acao'><span class='chip " & _acaoClass & "'>" & [__Acao] & "</span></td>"
			                & "<td class='td-cliente'>" & [__Cliente] & "</td>"
			                & "<td class='td-cnpj'>" & [__CNPJ] & "</td>"
			                & "<td class='td-produto'>" & [__Produto] & "<br><span style='color:var(--text-3);font-size:13px'>" & [__Subproduto] & "</span></td>"
			                & "<td class='td-ops'>" & [__OportunidadesLista] & "</td>"
			                & "<td class='num'>" & FORMAT ( [__OportDisp], vIntFormat ) & "</td>"
			                & "<td class='num'>" & FORMAT ( [__OportPass], vIntFormat ) & "</td>"
			                & "<td class='date-cell'>" & IF ( ISBLANK ( [__DataCadastro] ), "-", FORMAT ( [__DataCadastro], "dd/MM/yyyy" ) ) & "</td>"
			                & "<td class='date-cell'>" & IF ( ISBLANK ( [__UltimoMovimento] ), "-", FORMAT ( [__UltimoMovimento], "dd/MM/yyyy" ) ) & "</td>"
			                & "<td class='days'>" & FORMAT ( [__Dias], "#,##0" ) & "</td>"
			            & "</tr>"
			            & "<tr class='linha-extra'>"
			                & "<td colspan='12'>"
			                    & "<div class='job-extra-panel'>"
			                        & "<div class='job-extra-top'>"
			                            & "<div>"
			                                & "<div class='job-extra-title'>Job " & 'JOBS_Produto'[JOB] & " · " & [__Cliente] & "</div>"
			                                & "<div class='job-extra-subtitle'>CNPJ: " & [__CNPJ] & " · Produto: " & [__Produto] & " · Subproduto: " & [__Subproduto] & "</div>"
			                            & "</div>"
			                            & "<div class='job-extra-kpis'>"
			                                & "<span class='extra-pill warn'><strong>" & FORMAT ( _qtdLinhas, vIntFormat ) & "</strong> linhas</span>"
			                                & "<span class='extra-pill warn'><strong>" & FORMAT ( [__OportDisp], vIntFormat ) & "</strong> oportunidades</span>"
			                                & "<span class='extra-pill good'><strong>" & FORMAT ( [__OportPass], vIntFormat ) & "</strong> passaram</span>"
			                                & "<span class='extra-pill'><strong>" & FORMAT ( [__Dias], "#,##0" ) & "</strong> dias</span>"
			                            & "</div>"
			                        & "</div>"
			                        & "<div class='extra-grid'>"
			                            & "<div class='extra-card'><span>Etapa atual</span><b>" & [__EtapaAtual] & "</b></div>"
			                            & "<div class='extra-card'><span>Status</span><b>" & [__Status] & "</b></div>"
			                            & "<div class='extra-card'><span>Ação sugerida</span><b>" & [__Acao] & "</b></div>"
			                            & "<div class='extra-card'><span>Cadastro</span><b>" & IF ( ISBLANK ( [__DataCadastro] ), "-", FORMAT ( [__DataCadastro], "dd/MM/yyyy" ) ) & "</b></div>"
			                            & "<div class='extra-card'><span>Último movimento</span><b>" & IF ( ISBLANK ( [__UltimoMovimento] ), "-", FORMAT ( [__UltimoMovimento], "dd/MM/yyyy" ) ) & "</b></div>"
			                            & "<div class='extra-card'><span>Modelo produto</span><b>" & _modeloProduto & "</b></div>"
			                            & "<div class='extra-card'><span>Modelo negócio</span><b>" & _modeloNegocio & "</b></div>"
			                            & "<div class='extra-card'><span>Cliente</span><b>" & [__Cliente] & "</b></div>"
			                        & "</div>"
			                        & "<div class='extra-section'>"
			                            & "<div class='extra-section-title'>Distribuição de etapas dentro do job</div>"
			                            & "<div class='extra-chip-wrap'>" & _areasResumo & "</div>"
			                        & "</div>"
			                        & "<div class='extra-section'>"
			                            & "<div class='extra-section-title'>Oportunidades do job</div>"
			                            & "<div class='extra-chip-wrap'>" & _opsDetalhe & "</div>"
			                        & "</div>"
			& "</div>"
			                & "</td>"
			            & "</tr>",
			        "",
			        [__Status], ASC,
			        [__StageSort], ASC,
			        [__Dias], DESC,
			        [__DataCadastro], DESC
			    )
			
			VAR _avisoLimite =
			    IF (
			        _totalJobs > vLimiteLinhas,
			        " · exibindo " & FORMAT ( vLimiteLinhas, vIntFormat ) & " de " & FORMAT ( _totalJobs, vIntFormat ) & " jobs; use slicers para reduzir o recorte",
			        ""
			    )
			
			VAR _html =
			    "<html><head><meta charset='UTF-8'>" & _css & "</head><body>"
			        & "<div class='painel'>"
			            & "<div class='cabecalho'>"
			                & "<div class='cabecalho-esquerda'>"
			                    & "<button class='btn-voltar'>&#8592; Voltar</button>"
			                    & "<div class='titulo'>Detalhamento Diagnóstico - Journey</div>"
			                & "</div>"
			                & "<div class='controles'>"
			                    & "<input class='busca-global' id='buscaGlobal' type='text' placeholder='Busca nos jobs carregados: use slicers do Power BI para buscar na base completa...' oninput='filtrarTabela()'>"
			                    & "<button id='btnCopiar' class='btn-copiar' onclick='copiarTabela()' title='Copia a tabela filtrada para colar no Excel'>&#128203; Copiar tabela</button>"
			                & "</div>"
			            & "</div>"
			
			            & "<div class='resumo'>"
			                & "<div class='kpi primary'><span class='kpi-label'>Jobs listados</span><span class='kpi-value'>" & FORMAT ( _totalJobs, vIntFormat ) & "</span><span class='kpi-note'>Todo período" & _avisoLimite & "</span></div>"
			                & "<div class='kpi'><span class='kpi-label'>Ativos</span><span class='kpi-value'>" & FORMAT ( _jobsAtivos, vIntFormat ) & "</span><span class='kpi-note'>Ainda fora de FIM</span></div>"
			                & "<div class='kpi'><span class='kpi-label'>Finalizados</span><span class='kpi-value'>" & FORMAT ( _jobsFinalizados, vIntFormat ) & "</span><span class='kpi-note'>Todos em FIM</span></div>"
			                & "<div class='kpi'><span class='kpi-label'>Passaram etapa</span><span class='kpi-value'>" & FORMAT ( _jobsPassaram, vIntFormat ) & "</span><span class='kpi-note'>" & FORMAT ( _pctPassaram, vPctFormat ) & " da carteira</span></div>"
			                & "<div class='kpi'><span class='kpi-label'>Oport. disp.</span><span class='kpi-value'>" & FORMAT ( _oportDispTotal, vIntFormat ) & "</span><span class='kpi-note'>Distinto no período</span></div>"
			                & "<div class='kpi'><span class='kpi-label'>Oport. passaram</span><span class='kpi-value'>" & FORMAT ( _oportPassTotal, vIntFormat ) & "</span><span class='kpi-note'>Operação / Procuração / FIM</span></div>"
			            & "</div>"
			
			            & "<div class='table-wrapper'>"
			                & "<table class='tabela'>"
			                    & "<thead>"
			                        & "<tr>"
			                            & "<th style='width:9%'><div style='display:flex;flex-direction:column'><span>Job</span><input id='buscaColJob' class='col-filter' type='text' placeholder='Filtrar...' oninput='filtrarTabela()'></div></th>"
			                            & "<th style='width:8%'><div style='display:flex;flex-direction:column'><span>Etapa atual</span><input id='buscaColEtapa' class='col-filter' type='text' list='listaEtapas' placeholder='Buscar...' oninput='filtrarTabela()'><datalist id='listaEtapas'>" & _opcoesEtapa & "</datalist></div></th>"
			                            & "<th style='width:9%'><span>Ação sugerida</span></th>"
			                            & "<th style='width:15%'><div style='display:flex;flex-direction:column'><span>Cliente</span><input id='buscaColCliente' class='col-filter' type='text' placeholder='Filtrar...' oninput='filtrarTabela()'></div></th>"
			                            & "<th style='width:8%'><span>CNPJ</span></th>"
			                            & "<th style='width:14%'><div style='display:flex;flex-direction:column'><span>Produto / Subproduto</span><input id='buscaColProduto' class='col-filter' type='text' list='listaProdutos' placeholder='Filtrar...' oninput='filtrarTabela()'><datalist id='listaProdutos'>" & _opcoesProduto & "</datalist></div></th>"
			                            & "<th style='width:15%'><span>Oportunidades</span></th>"
			                            & "<th style='width:4%;text-align:center'><span>Disp.</span></th>"
			                            & "<th style='width:5%;text-align:center'><span>Passaram</span></th>"
			                            & "<th style='width:5%;text-align:center'><span>Cadastro</span></th>"
			                            & "<th style='width:5%;text-align:center'><span>Últ. mov.</span></th>"
			                            & "<th style='width:3%;text-align:center'><span>Dias</span></th>"
			                        & "</tr>"
			                    & "</thead>"
			                    & "<tbody id='tbodyDetalhe'>"
			                        & IF (
			                            ISBLANK ( _linhas ),
			                            "<tr><td colspan='12' class='empty'>Nenhum registro encontrado com os filtros atuais.</td></tr>",
			                            _linhas
			                        )
			                    & "</tbody>"
			                    & "<tfoot>"
			                        & "<tr>"
			                            & "<td colspan='12' style='text-align:right'>"
			                                & "Total visível após filtros: <span class='count-destaque' id='totalJobsCount'>0</span> de " & FORMAT ( _totalJobs, vIntFormat ) & " no período"
			                            & "</td>"
			                        & "</tr>"
			                    & "</tfoot>"
			                & "</table>"
			            & "</div>"
			        & "</div>"
			        & _js
			    & "</body></html>"
			
			RETURN
			    _html
			
			```
		displayFolder: 10 | HTML e Visual
		lineageTag: 7cc4cf4f-59eb-4360-8f7e-9a14c4534d03

	/// 01 BASE - Medidas fundamentais de contagem e periodo
	/// Contagem total de linhas da base de diagnostico no contexto atual.
	measure 'Diagnóstico | Registros' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    COUNTROWS ( vBaseDiag )
			```
		displayFolder: 01 Base
		lineageTag: b0000101-d1ag-ba5e-b010-ba5e00000101

	/// Contagem distinta de jobs (JOB) na base de diagnostico no contexto atual.
	measure 'Diagnóstico | Jobs' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    COUNTROWS ( SUMMARIZE ( vBaseDiag, 'JOBS_Produto'[JOB] ) )
			```
		displayFolder: 01 Base
		lineageTag: b0000102-d1ag-ba5e-b010-ba5e00000102

	/// Contagem distinta de empresas (NOME_CLIENTE) na base de diagnostico.
	measure 'Diagnóstico | Empresas' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    COUNTROWS (
				        SUMMARIZE (
				            FILTER ( vBaseDiag, NOT ISBLANK ( 'JOBS_Produto'[NOME_CLIENTE] ) ),
				            'JOBS_Produto'[NOME_CLIENTE]
				        )
				    )
			```
		displayFolder: 01 Base
		lineageTag: b0000103-d1ag-ba5e-b010-ba5e00000103

	/// Contagem distinta de CNPJs (CNPJ_CLIENTE) na base de diagnostico.
	measure 'Diagnóstico | CNPJs' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    COUNTROWS (
				        SUMMARIZE (
				            FILTER ( vBaseDiag, NOT ISBLANK ( 'JOBS_Produto'[CNPJ_CLIENTE] ) ),
				            'JOBS_Produto'[CNPJ_CLIENTE]
				        )
				    )
			```
		displayFolder: 01 Base
		lineageTag: b0000104-d1ag-ba5e-b010-ba5e00000104

	/// Data mais antiga de cadastro na base de diagnostico no contexto atual.
	measure 'Diagnóstico | Período Inicial' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    MINX ( vBaseDiag, 'JOBS_Produto'[DATA_CADASTRO] )
			```
		displayFolder: 01 Base
		lineageTag: b0000105-d1ag-ba5e-b010-ba5e00000105

	/// Data mais recente de cadastro na base de diagnostico no contexto atual.
	measure 'Diagnóstico | Período Final' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    MAXX ( vBaseDiag, 'JOBS_Produto'[DATA_CADASTRO] )
			```
		displayFolder: 01 Base
		lineageTag: b0000106-d1ag-ba5e-b010-ba5e00000106

	/// Periodo formatado como texto (dd/mm/yyyy a dd/mm/yyyy).
	measure 'Diagnóstico | Período Texto' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				VAR vMinData = MINX ( vBaseDiag, 'JOBS_Produto'[DATA_CADASTRO] )
				VAR vMaxData = MAXX ( vBaseDiag, 'JOBS_Produto'[DATA_CADASTRO] )
				RETURN
				    IF (
				        ISBLANK ( vMinData ) || ISBLANK ( vMaxData ),
				        "Sem dados no periodo",
				        FORMAT ( vMinData, "dd/mm/yyyy" ) & " a " & FORMAT ( vMaxData, "dd/mm/yyyy" )
				    )
			```
		displayFolder: 01 Base
		lineageTag: b0000107-d1ag-ba5e-b010-ba5e00000107

	/// Data do ultimo movimento (TRIBUTO_DATA_ENTRADA) na base de diagnostico.
	measure 'Diagnóstico | Último Movimento' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    MAXX (
				        vBaseDiag,
				        COALESCE ( 'JOBS_Produto'[TRIBUTO_DATA_ENTRADA], 'JOBS_Produto'[DATA_CADASTRO] )
				    )
			```
		displayFolder: 01 Base
		lineageTag: b0000108-d1ag-ba5e-b010-ba5e00000108

	/// Indica se ha filtro ativo no calendario (slicer de data).
	measure 'Diagnóstico | Contexto Calendário' = ```
				VAR vHasCalendarFilter =
				    ISFILTERED ( 'dCalendar'[Date] )
				        || ISFILTERED ( 'dCalendar'[Year] )
				        || ISFILTERED ( 'dCalendar'[YearMonth] )
				        || ISFILTERED ( 'dCalendar'[YearMonthName] )
				        || ISFILTERED ( 'dCalendar'[QuarterName] )
				        || ISFILTERED ( 'dCalendar'[MonthName] )
				RETURN
				    IF ( vHasCalendarFilter, "Periodo filtrado pelo slicer", "Todo periodo" )
			```
		displayFolder: 01 Base
		lineageTag: b0000109-d1ag-ba5e-b010-ba5e00000109

	/// 02 STATUS JOBS - Medidas de status e etapa dos jobs
	/// Status detalhado dos jobs: tabela virtual com Stage e Status por job.
	/// Retorna 1 se houver jobs ativos, 0 caso contrario (medida auxiliar interna).
	measure 'Diagnóstico | Job Status Base' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    COUNTROWS ( vBaseDiag )
			```
		displayFolder: 02 Status Jobs
		lineageTag: b0000200-d1ag-ba5e-b010-ba5e00000200

	/// Jobs ativos: possuem pelo menos uma linha fora de FIM.
	measure 'Diagnóstico | Jobs Ativos' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				VAR vJobStatusRaw =
				    ADDCOLUMNS (
				        SUMMARIZE ( vBaseDiag, 'JOBS_Produto'[JOB] ),
				        "__OpenRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
				                    )
				                ),
				        "__FimRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) = "FIM"
				                    )
				                )
				    )
				VAR vJobStatus =
				    ADDCOLUMNS (
				        vJobStatusRaw,
				        "__Status",
				            IF (
				                [__OpenRows] = 0 && [__FimRows] > 0,
				                "Finalizado",
				                "Ativo"
				            )
				    )
				RETURN
				    COUNTROWS ( FILTER ( vJobStatus, [__Status] = "Ativo" ) )
			```
		displayFolder: 02 Status Jobs
		lineageTag: b0000201-d1ag-ba5e-b010-ba5e00000201

	/// Jobs finalizados: todas as linhas do job estao em FIM.
	measure 'Diagnóstico | Jobs Finalizados' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				VAR vJobStatusRaw =
				    ADDCOLUMNS (
				        SUMMARIZE ( vBaseDiag, 'JOBS_Produto'[JOB] ),
				        "__OpenRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
				                    )
				                ),
				        "__FimRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) = "FIM"
				                    )
				                )
				    )
				VAR vJobStatus =
				    ADDCOLUMNS (
				        vJobStatusRaw,
				        "__Status",
				            IF (
				                [__OpenRows] = 0 && [__FimRows] > 0,
				                "Finalizado",
				                "Ativo"
				            )
				    )
				RETURN
				    COUNTROWS ( FILTER ( vJobStatus, [__Status] = "Finalizado" ) )
			```
		displayFolder: 02 Status Jobs
		lineageTag: b0000202-d1ag-ba5e-b010-ba5e00000202

	/// Jobs na etapa Checklist (etapa 1).
	measure 'Diagnóstico | Jobs Checklist' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				VAR vJobStatusRaw =
				    ADDCOLUMNS (
				        SUMMARIZE ( vBaseDiag, 'JOBS_Produto'[JOB] ),
				        "__OpenRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
				                    )
				                ),
				        "__FimRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) = "FIM"
				                    )
				                ),
				        "__StageOpen",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                MAXX (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
				                    ),
				                    VAR vArea = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
				                    RETURN
				                        SWITCH (
				                            TRUE (),
				                            vArea = "CHECKLIST", 1,
				                            vArea = "OPERAÇÃO", 2,
				                            vArea = "OPERACAO", 2,
				                            vArea = "PROCURAÇÃO ELETRÔNICA", 3,
				                            vArea = "PROCURACAO ELETRONICA", 3,
				                            0
				                        )
				                )
				    )
				VAR vJobStatus =
				    ADDCOLUMNS (
				        vJobStatusRaw,
				        "__Stage",
				            IF (
				                [__OpenRows] = 0 && [__FimRows] > 0,
				                4,
				                COALESCE ( [__StageOpen], 0 )
				            )
				    )
				RETURN
				    COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 1 ) )
			```
		displayFolder: 02 Status Jobs
		lineageTag: b0000203-d1ag-ba5e-b010-ba5e00000203

	/// Jobs na etapa Operacao (etapa 2).
	measure 'Diagnóstico | Jobs Operação' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				VAR vJobStatusRaw =
				    ADDCOLUMNS (
				        SUMMARIZE ( vBaseDiag, 'JOBS_Produto'[JOB] ),
				        "__OpenRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
				                    )
				                ),
				        "__FimRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) = "FIM"
				                    )
				                ),
				        "__StageOpen",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                MAXX (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
				                    ),
				                    VAR vArea = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
				                    RETURN
				                        SWITCH (
				                            TRUE (),
				                            vArea = "CHECKLIST", 1,
				                            vArea = "OPERAÇÃO", 2,
				                            vArea = "OPERACAO", 2,
				                            vArea = "PROCURAÇÃO ELETRÔNICA", 3,
				                            vArea = "PROCURACAO ELETRONICA", 3,
				                            0
				                        )
				                )
				    )
				VAR vJobStatus =
				    ADDCOLUMNS (
				        vJobStatusRaw,
				        "__Stage",
				            IF (
				                [__OpenRows] = 0 && [__FimRows] > 0,
				                4,
				                COALESCE ( [__StageOpen], 0 )
				            )
				    )
				RETURN
				    COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 2 ) )
			```
		displayFolder: 02 Status Jobs
		lineageTag: b0000204-d1ag-ba5e-b010-ba5e00000204

	/// Jobs na etapa Procuracao Eletronica (etapa 3).
	measure 'Diagnóstico | Jobs Procuração' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				VAR vJobStatusRaw =
				    ADDCOLUMNS (
				        SUMMARIZE ( vBaseDiag, 'JOBS_Produto'[JOB] ),
				        "__OpenRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
				                    )
				                ),
				        "__FimRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) = "FIM"
				                    )
				                ),
				        "__StageOpen",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                MAXX (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
				                    ),
				                    VAR vArea = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
				                    RETURN
				                        SWITCH (
				                            TRUE (),
				                            vArea = "CHECKLIST", 1,
				                            vArea = "OPERAÇÃO", 2,
				                            vArea = "OPERACAO", 2,
				                            vArea = "PROCURAÇÃO ELETRÔNICA", 3,
				                            vArea = "PROCURACAO ELETRONICA", 3,
				                            0
				                        )
				                )
				    )
				VAR vJobStatus =
				    ADDCOLUMNS (
				        vJobStatusRaw,
				        "__Stage",
				            IF (
				                [__OpenRows] = 0 && [__FimRows] > 0,
				                4,
				                COALESCE ( [__StageOpen], 0 )
				            )
				    )
				RETURN
				    COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 3 ) )
			```
		displayFolder: 02 Status Jobs
		lineageTag: b0000205-d1ag-ba5e-b010-ba5e00000205

	/// Jobs na etapa Fim (etapa 4).
	measure 'Diagnóstico | Jobs Fim' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				VAR vJobStatusRaw =
				    ADDCOLUMNS (
				        SUMMARIZE ( vBaseDiag, 'JOBS_Produto'[JOB] ),
				        "__OpenRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
				                    )
				                ),
				        "__FimRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) = "FIM"
				                    )
				                ),
				        "__StageOpen",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                MAXX (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
				                    ),
				                    VAR vArea = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
				                    RETURN
				                        SWITCH (
				                            TRUE (),
				                            vArea = "CHECKLIST", 1,
				                            vArea = "OPERAÇÃO", 2,
				                            vArea = "OPERACAO", 2,
				                            vArea = "PROCURAÇÃO ELETRÔNICA", 3,
				                            vArea = "PROCURACAO ELETRONICA", 3,
				                            0
				                        )
				                )
				    )
				VAR vJobStatus =
				    ADDCOLUMNS (
				        vJobStatusRaw,
				        "__Stage",
				            IF (
				                [__OpenRows] = 0 && [__FimRows] > 0,
				                4,
				                COALESCE ( [__StageOpen], 0 )
				            )
				    )
				RETURN
				    COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 4 ) )
			```
		displayFolder: 02 Status Jobs
		lineageTag: b0000206-d1ag-ba5e-b010-ba5e00000206

	/// Jobs que passaram de etapa (etapa >= 2: ja estao em Operacao, Procuracao ou Fim).
	measure 'Diagnóstico | Jobs Passaram Etapa' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				VAR vJobStatusRaw =
				    ADDCOLUMNS (
				        SUMMARIZE ( vBaseDiag, 'JOBS_Produto'[JOB] ),
				        "__OpenRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
				                    )
				                ),
				        "__FimRows",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                COUNTROWS (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) = "FIM"
				                    )
				                ),
				        "__StageOpen",
				            VAR vJobKey = 'JOBS_Produto'[JOB]
				            RETURN
				                MAXX (
				                    FILTER (
				                        vBaseDiag,
				                        'JOBS_Produto'[JOB] = vJobKey
				                            && UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) ) <> "FIM"
				                    ),
				                    VAR vArea = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
				                    RETURN
				                        SWITCH (
				                            TRUE (),
				                            vArea = "CHECKLIST", 1,
				                            vArea = "OPERAÇÃO", 2,
				                            vArea = "OPERACAO", 2,
				                            vArea = "PROCURAÇÃO ELETRÔNICA", 3,
				                            vArea = "PROCURACAO ELETRONICA", 3,
				                            0
				                        )
				                )
				    )
				VAR vJobStatus =
				    ADDCOLUMNS (
				        vJobStatusRaw,
				        "__Stage",
				            IF (
				                [__OpenRows] = 0 && [__FimRows] > 0,
				                4,
				                COALESCE ( [__StageOpen], 0 )
				            )
				    )
				RETURN
				    COUNTROWS ( FILTER ( vJobStatus, [__Stage] >= 2 ) )
			```
		displayFolder: 02 Status Jobs
		lineageTag: b0000207-d1ag-ba5e-b010-ba5e00000207

	/// Percentual de jobs ativos em relacao ao total.
	measure 'Diagnóstico | % Ativos' = ```
				DIVIDE ( [Diagnóstico | Jobs Ativos], [Diagnóstico | Jobs] , 0 )
			```
		formatString: 0.0%
		displayFolder: 02 Status Jobs
		lineageTag: b0000208-d1ag-ba5e-b010-ba5e00000208
		dataCategory: Percentage

	/// Percentual de jobs que passaram de etapa (etapa >= 2) em relacao ao total.
	measure 'Diagnóstico | % Passaram Etapa' = ```
				DIVIDE ( [Diagnóstico | Jobs Passaram Etapa], [Diagnóstico | Jobs] , 0 )
			```
		formatString: 0.0%
		displayFolder: 02 Status Jobs
		lineageTag: b0000209-d1ag-ba5e-b010-ba5e00000209
		dataCategory: Percentage

	/// 03 OPORTUNIDADES - Medidas de oportunidades (tributos)
	/// Oportunidades disponibilizadas: contagem distinta de NOME_TRIBUTO na base.
	measure 'Diagnóstico | Oportunidades Disponibilizadas' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    COUNTROWS (
				        SUMMARIZE (
				            FILTER ( vBaseDiag, NOT ISBLANK ( 'JOBS_Produto'[NOME_TRIBUTO] ) ),
				            'JOBS_Produto'[NOME_TRIBUTO]
				        )
				    )
			```
		displayFolder: 03 Oportunidades
		lineageTag: b0000301-d1ag-ba5e-b010-ba5e00000301

	/// Oportunidades que passaram: tributos cujas linhas estao em Operacao, Procuracao ou Fim.
	measure 'Diagnóstico | Oportunidades Passaram' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    COUNTROWS (
				        SUMMARIZE (
				            FILTER (
				                vBaseDiag,
				                NOT ISBLANK ( 'JOBS_Produto'[NOME_TRIBUTO] )
				                    && (
				                        VAR vArea = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
				                        RETURN
				                            vArea IN {
				                                "OPERAÇÃO",
				                                "OPERACAO",
				                                "PROCURAÇÃO ELETRÔNICA",
				                                "PROCURACAO ELETRONICA",
				                                "FIM"
				                            }
				                    )
				            ),
				            'JOBS_Produto'[NOME_TRIBUTO]
				        )
				    )
			```
		displayFolder: 03 Oportunidades
		lineageTag: b0000302-d1ag-ba5e-b010-ba5e00000302

	/// Percentual de oportunidades que passaram em relacao as disponibilizadas.
	measure 'Diagnóstico | % Oportunidades Passaram' = ```
				DIVIDE ( [Diagnóstico | Oportunidades Passaram], [Diagnóstico | Oportunidades Disponibilizadas] , 0 )
			```
		formatString: 0.0%
		displayFolder: 03 Oportunidades
		lineageTag: b0000303-d1ag-ba5e-b010-ba5e00000303
		dataCategory: Percentage

	/// 04 CARDS - HTML dos 3 cards KPI principais conforme lógica PROJECT_QBERT_JOBS/QBERT. Jobs e Ativos usam MAP_PRODUTOS_ESTEIRA_TAX.
	measure 'HTML Bloco | Cards' =
			VAR vFmt = "#,##0"
			VAR vJourney = [Journey QBERT | Total Journey]
			VAR vJobs = [Journey QBERT | Total Jobs]
			VAR vAtivos = [Journey QBERT | Jobs Ativos]
			VAR vJourneyCard =
			    "<div class='kpi-card primary' data-tip='Total de Journey: PROJECT_QBERT_JOBS com CODIGO_PRODUTO = 360, FIM = 1 e DATA_CADASTRO no período selecionado.'>"
			        & "<span class='tip-arrow'></span>"
			        & "<div class='kpi-label'>Total Journey</div>"
			        & "<div class='kpi-value'>" & FORMAT ( vJourney, vFmt ) & "</div>"
			        & "<div class='kpi-caption'>Produto 360 finalizado</div>"
			    & "</div>"
			VAR vJobsCard =
			    "<div class='kpi-card primary' data-tip='Total de Jobs: filhos cujo PAI está nos Journey 360 finalizados do período e cujo CODIGO_PRODUTO está no mapa da esteira TAX.'>"
			        & "<span class='tip-arrow'></span>"
			        & "<div class='kpi-label'>Total Jobs</div>"
			        & "<div class='kpi-value'>" & FORMAT ( vJobs, vFmt ) & "</div>"
			        & "<div class='kpi-caption'>Filhos da esteira TAX</div>"
			    & "</div>"
			VAR vAtivosCard =
			    "<div class='kpi-card attention' data-tip='Jobs ativos: filhos dos Journey 360 do período, restritos à esteira TAX, com FIM diferente de 1.'>"
			        & "<span class='tip-arrow'></span>"
			        & "<div class='kpi-label'>Ativos</div>"
			        & "<div class='kpi-value'>" & FORMAT ( vAtivos, vFmt ) & "</div>"
			        & "<div class='kpi-caption'>Esteira TAX sem FIM = 1</div>"
			    & "</div>"
			RETURN
			    "<div class='diag-kpis qbert-kpis'>"
			        & vJourneyCard
			        & vJobsCard
			        & vAtivosCard
			    & "</div>"
		displayFolder: 04 Cards
		lineageTag: b0000410-d1ag-ba5e-b010-ba5e00000410

	/// 05 TABELA PRINCIPAL - HTML da tabela e linhas de produtos
	/// Cabecalho fixo da tabela principal com as 9 colunas.
	measure 'HTML Tabela | Cabeçalho' = ```
				    "<div class='table-head'>"
				        & "<div>Produto</div>"
				        & "<div>Diag.</div>"
				        & "<div>Ativos</div>"
				        & "<div>Checklist</div>"
				        & "<div>Operacao</div>"
				        & "<div>Procur.</div>"
				        & "<div>Fim</div>"
				        & "<div>Passaram</div>"
				        & "<div>Dias</div>"
				    & "</div>"
			```
		displayFolder: 05 Tabela Principal
		lineageTag: b0000501-d1ag-ba5e-b010-ba5e00000501

	/// Linhas da tabela: uma linha expansivel por produto diagnostico com etapas e resumo macro.
	/// Esta medida contem a logica principal de agrupamento por produto e geracao HTML.
	measure 'HTML Tabela | Linhas Produtos' = ```
					VAR vIntFormat = "#,##0"
					VAR vPctFormat = "0.0%"
					VAR vTopProdutos = 35
					VAR vTopDetalhes = 12
					VAR vProdutoSelecionado =
					    HASONEVALUE ( 'DIM_PRODUTOS_IMAGEM_TAX'[ProdutoImagem] )
					VAR vProdutosSelecionados =
					    VALUES ( 'DIM_PRODUTOS_IMAGEM_TAX'[ProdutoImagem] )
			
					-- Base governada: somente produtos da imagem da esteira TAX.
					VAR vBaseDiag =
					    CALCULATETABLE (
					        FILTER ( 'JOBS_Produto', NOT ISBLANK ( 'JOBS_Produto'[ProdutoImagemTax] ) ),
					        TREATAS ( vProdutosSelecionados, 'JOBS_Produto'[ProdutoImagemTax] )
					    )
			
					-- Job stage: single FILTER per job (was 3 separate scans = 67% reduction)
					VAR vJobStageCalc =
					    ADDCOLUMNS (
					        SUMMARIZE ( vBaseDiag, 'JOBS_Produto'[JOB] ),
					        "__Stage",
					            VAR vJobKey = 'JOBS_Produto'[JOB]
					            VAR vJobRows =
					                SELECTCOLUMNS (
					                    FILTER ( vBaseDiag, 'JOBS_Produto'[JOB] = vJobKey ),
					                    "@S",
					                        VAR vArea = UPPER ( COALESCE ( 'JOBS_Produto'[NOME_AREA], "" ) )
					                        RETURN
					                            SWITCH (
					                                TRUE (),
					                                vArea = "CHECKLIST", 1,
					                                vArea = "OPERAÇÃO", 2,
					                                vArea = "OPERACAO", 2,
					                                vArea = "PROCURAÇÃO ELETRÔNICA", 3,
					                                vArea = "PROCURACAO ELETRONICA", 3,
					                                vArea = "FIM", 4,
					                                0
					                            )
					                )
					            VAR vMaxAll = MAXX ( vJobRows, [@S] )
					            VAR vMaxOpen = MAXX ( FILTER ( vJobRows, [@S] < 4 ), [@S] )
					            RETURN
					                IF ( vMaxAll = 4 && ISBLANK ( vMaxOpen ), 4, COALESCE ( vMaxOpen, 0 ) )
					    )
			
					-- Derive status without re-scanning vBaseDiag
					VAR vJobStatus =
					    ADDCOLUMNS (
					        vJobStageCalc,
					        "__Status", IF ( [__Stage] = 4, "Finalizado", "Ativo" )
					    )
			
					VAR vJobs = COUNTROWS ( vJobStatus )
			
					-- Totais gerais para comparativo na expansao
					VAR vTotalAtivos     = COUNTROWS ( FILTER ( vJobStatus, [__Status] = "Ativo" ) )
					VAR vTotalChecklist  = COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 1 ) )
					VAR vTotalOperacao   = COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 2 ) )
					VAR vTotalProcuracao = COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 3 ) )
					VAR vTotalFim        = COUNTROWS ( FILTER ( vJobStatus, [__Stage] = 4 ) )
					VAR vTotalPassaram   = COUNTROWS ( FILTER ( vJobStatus, [__Stage] >= 2 ) )
					VAR vTotalReg        = COUNTROWS ( vBaseDiag )
					VAR vTotalOport      = COUNTROWS ( SUMMARIZE ( FILTER ( vBaseDiag, NOT ISBLANK ( 'JOBS_Produto'[NOME_TRIBUTO] ) ), 'JOBS_Produto'[NOME_TRIBUTO] ) )
					VAR vTotalDiasMed    = MEDIANX ( vBaseDiag, 'JOBS_Produto'[DIAS] )
			
					-- Product aggregates: single FILTER per product (was 3 separate ADDCOLUMNS + vProdutoBase = 83% reduction)
					VAR vAllProdutos = SUMMARIZE ( vBaseDiag, 'JOBS_Produto'[ProdutoImagemTax] )
			
					VAR vProdutoValidos =
					    FILTER (
					        ADDCOLUMNS (
					            vAllProdutos,
					            "__Registros",
					                VAR vP = 'JOBS_Produto'[ProdutoImagemTax]
					                VAR vPRows = FILTER ( vBaseDiag, 'JOBS_Produto'[ProdutoImagemTax] = vP )
					                RETURN
					                    COUNTROWS ( vPRows ),
					            "__Jobs",
					                VAR vP = 'JOBS_Produto'[ProdutoImagemTax]
					                VAR vPRows = FILTER ( vBaseDiag, 'JOBS_Produto'[ProdutoImagemTax] = vP )
					                RETURN
					                    COUNTROWS ( SUMMARIZE ( vPRows, 'JOBS_Produto'[JOB] ) ),
					            "__OportDisp",
					                VAR vP = 'JOBS_Produto'[ProdutoImagemTax]
					                VAR vPRows = FILTER ( vBaseDiag, 'JOBS_Produto'[ProdutoImagemTax] = vP )
					                RETURN
					                    COUNTROWS ( SUMMARIZE ( vPRows, 'JOBS_Produto'[NOME_TRIBUTO] ) ),
					            "__DiasMed",
					                VAR vP = 'JOBS_Produto'[ProdutoImagemTax]
					                VAR vPRows = FILTER ( vBaseDiag, 'JOBS_Produto'[ProdutoImagemTax] = vP )
					                RETURN
					                    MEDIANX ( vPRows, 'JOBS_Produto'[DIAS] )
					        ),
					        [__Jobs] > 0
					    )
			
					VAR vProdutoTop =
					    TOPN (
					        vTopProdutos,
					        vProdutoValidos,
					        [__Jobs], DESC,
					        [__Registros], DESC,
					        'JOBS_Produto'[ProdutoImagemTax], ASC
					    )
			
					VAR vMaxJobsProduto =
					    MAXX ( vProdutoTop, [__Jobs] )
			
					-- Job-to-product mapping
					VAR vJobProduto =
					    SUMMARIZE (
					        vBaseDiag,
					        'JOBS_Produto'[JOB],
					        'JOBS_Produto'[ProdutoImagemTax]
					    )
			
					-- Pre-compute subproduto stats
					VAR vSubprodutoJobs =
					    ADDCOLUMNS (
					        SUMMARIZE (
					            vBaseDiag,
					            'JOBS_Produto'[ProdutoImagemTax],
					            'JOBS_Produto'[NOME_SUBPRODUTO]
					        ),
					        "__Jobs",
					            VAR vP = 'JOBS_Produto'[ProdutoImagemTax]
					            VAR vS = 'JOBS_Produto'[NOME_SUBPRODUTO]
					            RETURN
					                COUNTROWS (
					                    SUMMARIZE (
					                    FILTER (
					                        vBaseDiag,
					                        'JOBS_Produto'[ProdutoImagemTax] = vP
					                            && 'JOBS_Produto'[NOME_SUBPRODUTO] = vS
					                        ),
					                        'JOBS_Produto'[JOB]
					                    )
					                )
					    )
			
					VAR vRowsHTML =
					    CONCATENATEX (
					        vProdutoTop,
					        VAR vProdutoKey = 'JOBS_Produto'[ProdutoImagemTax]
					        VAR vProduto = COALESCE ( vProdutoKey, "Sem produto" )
			
					        -- Pre-computed values from row context
					        VAR vReg = [__Registros]
					        VAR vOportDisp = [__OportDisp]
					        VAR vDiasProduto = [__DiasMed]
			
					        -- Filter job status by product via mapping table
					        VAR vGroupStatus =
					            FILTER (
					                vJobStatus,
					                'JOBS_Produto'[JOB]
					                        IN SELECTCOLUMNS (
					                            FILTER ( vJobProduto, 'JOBS_Produto'[ProdutoImagemTax] = vProdutoKey ),
					                            "@job",
					                        'JOBS_Produto'[JOB]
					                    )
					            )
			
					        VAR vJob = COUNTROWS ( vGroupStatus )
					        VAR vAtivo = COUNTROWS ( FILTER ( vGroupStatus, [__Status] = "Ativo" ) )
					        VAR vFim = COUNTROWS ( FILTER ( vGroupStatus, [__Stage] = 4 ) )
					        VAR vChecklist = COUNTROWS ( FILTER ( vGroupStatus, [__Stage] = 1 ) )
					        VAR vOperacao = COUNTROWS ( FILTER ( vGroupStatus, [__Stage] = 2 ) )
					        VAR vProcuracao = COUNTROWS ( FILTER ( vGroupStatus, [__Stage] = 3 ) )
					        VAR vPassaram = COUNTROWS ( FILTER ( vGroupStatus, [__Stage] >= 2 ) )
					        VAR vShare = DIVIDE ( vJob, vJobs , 0 )
					        VAR vBar = MAX ( 4, ROUND ( DIVIDE ( vJob, vMaxJobsProduto , 0 ) * 100, 0 ) )
					        VAR vPassouPct = DIVIDE ( vPassaram, vJob , 0 )
			
					        VAR vStageTable =
					            UNION (
					                ROW ( "Etapa", "Checklist", "Qtd", vChecklist, "Pct", DIVIDE ( vChecklist, vJob , 0 ), "Ordem", 1 ),
					                ROW ( "Etapa", "Operacao", "Qtd", vOperacao, "Pct", DIVIDE ( vOperacao, vJob , 0 ), "Ordem", 2 ),
					                ROW ( "Etapa", "Procuracao Eletronica", "Qtd", vProcuracao, "Pct", DIVIDE ( vProcuracao, vJob , 0 ), "Ordem", 3 ),
					                ROW ( "Etapa", "Fim", "Qtd", vFim, "Pct", DIVIDE ( vFim, vJob , 0 ), "Ordem", 4 )
					            )
			
					        VAR vStageHTML =
					            CONCATENATEX (
					                vStageTable,
					                VAR vPct = [Pct]
					                VAR vPctBar = MAX ( 2, ROUND ( COALESCE ( vPct, 0 ) * 100, 0 ) )
					                RETURN
					                    "<div class='detail-line'>"
					                        & "<div class='detail-name'>" & [Etapa] & "</div>"
					                        & "<div class='detail-bar'><span style='width:" & FORMAT ( vPctBar, "0" ) & "%'></span></div>"
					                        & "<div class='detail-num'>" & FORMAT ( [Qtd], vIntFormat ) & "</div>"
					                        & "<div class='detail-pct'>" & FORMAT ( vPct, vPctFormat ) & "</div>"
					                    & "</div>",
					                "",
					                [Ordem], ASC
					            )
			
					        -- Subproduto table
					        VAR vSubprodutoTable =
					            TOPN (
					                vTopDetalhes,
					                FILTER (
					                    vSubprodutoJobs,
					                    COALESCE ( 'JOBS_Produto'[ProdutoImagemTax], "" ) = COALESCE ( vProdutoKey, "" )
					                ),
					                [__Jobs], DESC,
					                'JOBS_Produto'[NOME_SUBPRODUTO], ASC
					            )
			
					        VAR vSubprodutoHTML =
					            CONCATENATEX (
					                vSubprodutoTable,
					                "<span class='pill'>"
					                    & COALESCE ( 'JOBS_Produto'[NOME_SUBPRODUTO], "Sem subproduto" )
					                    & " · "
					                    & FORMAT ( [__Jobs], vIntFormat )
					                    & " jobs"
					                & "</span>",
					                "",
					                [__Jobs], DESC
					            )
			
					        RETURN
					            "<details class='diag-row'>"
					                & "<summary>"
					                    & "<div class='row-grid'>"
					                        & "<div class='main-cell'>"
					                            & "<div class='title-line'>"
					                                & "<span class='row-title'>" & vProduto & "</span>"
					                            & "</div>"
					                            & "<div class='row-sub'>"
					                                & FORMAT ( vReg, vIntFormat ) & " linhas · "
					                                & FORMAT ( vOportDisp, vIntFormat ) & " oportunidades disponibilizadas · "
					                                & FORMAT ( vShare, vPctFormat ) & " dos diagnosticos"
					                            & "</div>"
					                            & "<div class='progress'><span style='width:" & FORMAT ( vBar, "0" ) & "%'></span></div>"
					                        & "</div>"
					                        & "<div class='metric'><b>" & FORMAT ( vJob, vIntFormat ) & "</b><small>diagnosticos</small></div>"
					                        & "<div class='metric'><b>" & FORMAT ( vAtivo, vIntFormat ) & "</b><small>ativos</small></div>"
					                        & "<div class='metric'><b>" & FORMAT ( vChecklist, vIntFormat ) & "</b><small>checklist</small></div>"
					                        & "<div class='metric'><b>" & FORMAT ( vOperacao, vIntFormat ) & "</b><small>operacao</small></div>"
					                        & "<div class='metric'><b>" & FORMAT ( vProcuracao, vIntFormat ) & "</b><small>procuracao</small></div>"
					                        & "<div class='metric'><b>" & FORMAT ( vFim, vIntFormat ) & "</b><small>fim</small></div>"
					                        & "<div class='metric highlight'><b>" & FORMAT ( vPassouPct, vPctFormat ) & "</b><small>passaram</small></div>"
					                        & "<div class='metric'><b>" & FORMAT ( vDiasProduto, "#,##0" ) & "</b><small>dias med.</small></div>"
					                    & "</div>"
					                & "</summary>"
					                & "<div class='detail-box'>"
					                    & "<div class='detail-card wide'>"
					                        & "<div class='detail-title'>Comparativo: produto vs total do periodo</div>"
					                        & "<div class='cmp-head'>"
					                            & "<div>Metrica</div><div>Produto</div><div>Total</div><div>% do Total</div><div></div>"
					                        & "</div>"
					                        & "<div class='cmp-row'><div class='cmp-name'>Jobs</div><div class='cmp-val'>" & FORMAT ( vJob, vIntFormat ) & "</div><div class='cmp-val'>" & FORMAT ( vJobs, vIntFormat ) & "</div><div class='cmp-pct'>" & FORMAT ( DIVIDE ( vJob, vJobs, 0 ), vPctFormat ) & "</div><div class='cmp-bar'><span style='width:" & FORMAT ( MAX ( 2, ROUND ( DIVIDE ( vJob, vJobs, 0 ) * 100, 0 ) ), "0" ) & "%'></span></div></div>"
					                        & "<div class='cmp-row'><div class='cmp-name'>Ativos</div><div class='cmp-val'>" & FORMAT ( vAtivo, vIntFormat ) & "</div><div class='cmp-val'>" & FORMAT ( vTotalAtivos, vIntFormat ) & "</div><div class='cmp-pct'>" & FORMAT ( DIVIDE ( vAtivo, vTotalAtivos, 0 ), vPctFormat ) & "</div><div class='cmp-bar'><span style='width:" & FORMAT ( MAX ( 2, ROUND ( DIVIDE ( vAtivo, vTotalAtivos, 0 ) * 100, 0 ) ), "0" ) & "%'></span></div></div>"
					                        & "<div class='cmp-row'><div class='cmp-name'>Checklist</div><div class='cmp-val'>" & FORMAT ( vChecklist, vIntFormat ) & "</div><div class='cmp-val'>" & FORMAT ( vTotalChecklist, vIntFormat ) & "</div><div class='cmp-pct'>" & FORMAT ( DIVIDE ( vChecklist, vTotalChecklist, 0 ), vPctFormat ) & "</div><div class='cmp-bar'><span style='width:" & FORMAT ( MAX ( 2, ROUND ( DIVIDE ( vChecklist, vTotalChecklist, 0 ) * 100, 0 ) ), "0" ) & "%'></span></div></div>"
					                        & "<div class='cmp-row'><div class='cmp-name'>Operacao</div><div class='cmp-val'>" & FORMAT ( vOperacao, vIntFormat ) & "</div><div class='cmp-val'>" & FORMAT ( vTotalOperacao, vIntFormat ) & "</div><div class='cmp-pct'>" & FORMAT ( DIVIDE ( vOperacao, vTotalOperacao, 0 ), vPctFormat ) & "</div><div class='cmp-bar'><span style='width:" & FORMAT ( MAX ( 2, ROUND ( DIVIDE ( vOperacao, vTotalOperacao, 0 ) * 100, 0 ) ), "0" ) & "%'></span></div></div>"
					                        & "<div class='cmp-row'><div class='cmp-name'>Procuracao</div><div class='cmp-val'>" & FORMAT ( vProcuracao, vIntFormat ) & "</div><div class='cmp-val'>" & FORMAT ( vTotalProcuracao, vIntFormat ) & "</div><div class='cmp-pct'>" & FORMAT ( DIVIDE ( vProcuracao, vTotalProcuracao, 0 ), vPctFormat ) & "</div><div class='cmp-bar'><span style='width:" & FORMAT ( MAX ( 2, ROUND ( DIVIDE ( vProcuracao, vTotalProcuracao, 0 ) * 100, 0 ) ), "0" ) & "%'></span></div></div>"
					                        & "<div class='cmp-row'><div class='cmp-name'>Fim</div><div class='cmp-val'>" & FORMAT ( vFim, vIntFormat ) & "</div><div class='cmp-val'>" & FORMAT ( vTotalFim, vIntFormat ) & "</div><div class='cmp-pct'>" & FORMAT ( DIVIDE ( vFim, vTotalFim, 0 ), vPctFormat ) & "</div><div class='cmp-bar'><span style='width:" & FORMAT ( MAX ( 2, ROUND ( DIVIDE ( vFim, vTotalFim, 0 ) * 100, 0 ) ), "0" ) & "%'></span></div></div>"
					                        & "<div class='cmp-row'><div class='cmp-name'>Passaram etapa</div><div class='cmp-val'>" & FORMAT ( vPassaram, vIntFormat ) & "</div><div class='cmp-val'>" & FORMAT ( vTotalPassaram, vIntFormat ) & "</div><div class='cmp-pct'>" & FORMAT ( DIVIDE ( vPassaram, vTotalPassaram, 0 ), vPctFormat ) & "</div><div class='cmp-bar'><span style='width:" & FORMAT ( MAX ( 2, ROUND ( DIVIDE ( vPassaram, vTotalPassaram, 0 ) * 100, 0 ) ), "0" ) & "%'></span></div></div>"
					                        & "<div class='cmp-row'><div class='cmp-name'>Registros (linhas)</div><div class='cmp-val'>" & FORMAT ( vReg, vIntFormat ) & "</div><div class='cmp-val'>" & FORMAT ( vTotalReg, vIntFormat ) & "</div><div class='cmp-pct'>" & FORMAT ( DIVIDE ( vReg, vTotalReg, 0 ), vPctFormat ) & "</div><div class='cmp-bar'><span style='width:" & FORMAT ( MAX ( 2, ROUND ( DIVIDE ( vReg, vTotalReg, 0 ) * 100, 0 ) ), "0" ) & "%'></span></div></div>"
					                        & "<div class='cmp-row'><div class='cmp-name'>Oportunidades</div><div class='cmp-val'>" & FORMAT ( vOportDisp, vIntFormat ) & "</div><div class='cmp-val'>" & FORMAT ( vTotalOport, vIntFormat ) & "</div><div class='cmp-pct'>" & FORMAT ( DIVIDE ( vOportDisp, vTotalOport, 0 ), vPctFormat ) & "</div><div class='cmp-bar'><span style='width:" & FORMAT ( MAX ( 2, ROUND ( DIVIDE ( vOportDisp, vTotalOport, 0 ) * 100, 0 ) ), "0" ) & "%'></span></div></div>"
					                        & "<div class='cmp-row'><div class='cmp-name'>Dias mediana</div><div class='cmp-val'>" & FORMAT ( vDiasProduto, "#,##0" ) & "</div><div class='cmp-val'>" & FORMAT ( vTotalDiasMed, "#,##0" ) & "</div><div class='cmp-pct cmp-neutral'>" & IF ( vDiasProduto <= vTotalDiasMed, "≤ geral", "> geral" ) & "</div><div class='cmp-bar'><span style='width:" & FORMAT ( MIN ( 100, MAX ( 2, ROUND ( DIVIDE ( vDiasProduto, MAX ( vTotalDiasMed, 1 ), 0 ) * 100, 0 ) ) ), "0" ) & "%'></span></div></div>"
					                    & "</div>"
					                    & "<div class='detail-card wide'>"
					                        & "<div class='detail-title'>Subprodutos</div>"
					                        & "<div class='pill-wrap'>"
					                            & vSubprodutoHTML
					                        & "</div>"
					                        & "<div class='pill-wrap' style='margin-top:12px'>"
					                            & "<span class='pill pass'>Para ver job, cliente, CNPJ, oportunidades e datas linha a linha, use a aba Detalhamento.</span>"
					                        & "</div>"
					                    & "</div>"
					                & "</div>"
					            & "</details>",
					        "",
					        [__Jobs], DESC
					    )
			
					RETURN
					    vRowsHTML
			```
		displayFolder: 05 Tabela Principal
		lineageTag: b0000502-d1ag-ba5e-b010-ba5e00000502

	/// 06 ESTILO HTML - CSS completo do visual
	/// CSS completo do dashboard Diagnostico Journey com fundo escuro, paleta dourado/teal, scroll customizado, cards, tabela, tooltips e responsivo.
	measure 'HTML CSS | Completo' = ```
					"<style>
			.diag-wrap{
			    font-family:'Segoe UI',Arial,sans-serif;
			    width:100%;
			    height:calc(100vh - 2px);
			    box-sizing:border-box;
			    color:#E8EEF5;
			    background:radial-gradient(circle at top left,rgba(213,174,119,.18),transparent 32%),linear-gradient(135deg,#101923 0%,#0B1219 100%);
			    border:1px solid rgba(213,174,119,.28);
			    border-radius:18px;
			    overflow:auto;
			    box-shadow:0 18px 48px rgba(0,0,0,.34);
			}
			
			.diag-wrap{
			    scrollbar-width:thin;
			    scrollbar-color:rgba(213,174,119,.48) rgba(6,11,16,.96);
			}
			.diag-wrap::-webkit-scrollbar{
			    width:13px;
			    height:10px;
			}
			.diag-wrap::-webkit-scrollbar-track{
			    background:linear-gradient(180deg,#060B10 0%,#0B1219 100%);
			    border-left:1px solid rgba(213,174,119,.10);
			    border-radius:999px;
			}
			.diag-wrap::-webkit-scrollbar-thumb{
			    background:
			        linear-gradient(180deg,rgba(213,174,119,.58),rgba(17,28,35,.96));
			    border:3px solid #060B10;
			    border-radius:999px;
			    box-shadow:inset 0 1px 0 rgba(255,255,255,.08);
			}
			.diag-wrap::-webkit-scrollbar-thumb:hover{
			    background:
			        linear-gradient(180deg,rgba(244,217,169,.70),rgba(213,174,119,.40));
			}
			.diag-wrap::-webkit-scrollbar-corner{
			    background:#060B10;
			}
			
			.sticky{position:sticky;top:0;z-index:60;background:rgba(11,18,25,.98);border-bottom:1px solid rgba(213,174,119,.18);box-shadow:0 16px 30px rgba(0,0,0,.36);overflow:visible}
			.diag-head{padding:20px 24px 28px;overflow:visible}
			.slicer-space{height:64px;width:100%;margin-bottom:8px;display:flex;align-items:flex-start;justify-content:flex-end;padding-top:2px}
			.doc-button{position:relative;display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:12px 20px 12px 18px;border-radius:14px;color:#081018;border:1px solid rgba(244,217,169,.72);background:linear-gradient(135deg,#F4D9A9 0%,#D5AE77 48%,#8BE0D1 100%);box-shadow:0 14px 28px rgba(213,174,119,.24),0 0 0 1px rgba(255,255,255,.08) inset,0 0 22px rgba(139,224,209,.18);font-size:13px;font-weight:950;letter-spacing:.10em;text-transform:uppercase;white-space:nowrap;overflow:hidden}
			.doc-button:before{content:'\25A6';display:inline-flex;align-items:center;justify-content:center;width:22px;height:22px;margin-right:9px;border-radius:8px;background:rgba(8,16,24,.18);border:1px solid rgba(8,16,24,.22);font-size:12px;line-height:1;color:#081018;font-weight:950}
			.doc-button:after{content:'';position:absolute;inset:-1px;border-radius:14px;background:linear-gradient(90deg,transparent,rgba(255,255,255,.45),transparent);transform:translateX(-120%);animation:shineDetalhe 3.6s ease-in-out infinite}
			@keyframes shineDetalhe{0%{transform:translateX(-120%)}48%{transform:translateX(-120%)}72%{transform:translateX(120%)}100%{transform:translateX(120%)}}
			.diag-kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:18px;margin-top:0;position:relative;z-index:90;overflow:visible}
			.kpi-card{position:relative;min-width:0;padding:21px 18px 18px;border-radius:20px;background:linear-gradient(160deg,rgba(18,28,37,.96),rgba(11,18,25,.94));border:1px solid rgba(255,255,255,.10);overflow:visible;box-shadow:0 18px 32px rgba(0,0,0,.24),inset 0 1px 0 rgba(255,255,255,.06);transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}
			.kpi-card.primary{background:linear-gradient(155deg,rgba(213,174,119,.18),rgba(18,28,37,.96) 36%,rgba(11,18,25,.96));border-color:rgba(213,174,119,.42)}
			.kpi-card.attention{background:linear-gradient(155deg,rgba(139,224,209,.08),rgba(18,28,37,.96) 34%,rgba(11,18,25,.96));border-color:rgba(139,224,209,.30)}
			.kpi-card:before{content:'';position:absolute;left:16px;top:0;width:46px;height:4px;border-radius:0 0 10px 10px;background:linear-gradient(90deg,#F4D9A9,#8BE0D1);opacity:.92}
			.kpi-card:hover{transform:translateY(-2px);border-color:rgba(213,174,119,.34);box-shadow:0 22px 40px rgba(0,0,0,.28),0 0 0 1px rgba(213,174,119,.08),inset 0 1px 0 rgba(255,255,255,.08)}
			.kpi-card[data-tip]:hover:after{content:attr(data-tip);position:absolute;left:14px;right:14px;top:calc(100% + 12px);padding:11px 12px;border-radius:12px;background:linear-gradient(160deg,rgba(7,13,18,.98),rgba(12,22,29,.98));border:1px solid rgba(213,174,119,.34);color:#E8EEF5;font-size:11.5px;font-weight:820;line-height:1.35;box-shadow:0 16px 32px rgba(0,0,0,.34);z-index:999;white-space:normal;pointer-events:none}
			.kpi-card[data-tip]:hover:before{opacity:1}
			.kpi-card[data-tip]:hover .tip-arrow{position:absolute;left:28px;top:calc(100% + 5px);width:14px;height:14px;background:linear-gradient(160deg,rgba(7,13,18,.98),rgba(12,22,29,.98));border-left:1px solid rgba(213,174,119,.34);border-top:1px solid rgba(213,174,119,.34);transform:rotate(45deg);opacity:0;z-index:998;pointer-events:none}
			.tip-arrow{position:absolute;left:28px;bottom:calc(100% + 4px);width:14px;height:14px;background:linear-gradient(160deg,rgba(7,13,18,.98),rgba(12,22,29,.98));border-left:1px solid rgba(213,174,119,.34);border-top:1px solid rgba(213,174,119,.34);transform:rotate(45deg);opacity:0;z-index:29;pointer-events:none}
			.kpi-label{color:#AEB9C4;font-size:12px;font-weight:950;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
			.kpi-value{margin-top:10px;color:#F4D9A9;font-size:32px;font-weight:950;line-height:1.05;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
			.kpi-caption{margin-top:9px;color:#8B98A6;font-size:13px;font-weight:850;line-height:1.25}
			.kpi-total{color:#8B98A6;font-size:22px;font-weight:850}
			.exec-strip{display:none}
			.exec-alert{display:inline-flex;align-items:center;min-height:34px;padding:8px 13px;border-radius:11px;font-size:12px;font-weight:950;letter-spacing:.04em;text-transform:uppercase;border:1px solid rgba(255,255,255,.10);background:rgba(255,255,255,.045);color:#C7D0DA}
			.exec-alert.good{color:#8BE0D1;border-color:rgba(139,224,209,.30);background:rgba(139,224,209,.08)}
			.exec-alert.attention{color:#F4D9A9;border-color:rgba(213,174,119,.32);background:rgba(213,174,119,.09)}
			.exec-alert.danger{color:#FFB0A8;border-color:rgba(217,93,93,.34);background:rgba(217,93,93,.10)}
			.exec-alert.neutral{color:#AEB9C4;border-color:rgba(255,255,255,.12);background:rgba(255,255,255,.04)}
			.table-head{display:grid;grid-template-columns:minmax(520px,1.95fr) repeat(8,minmax(112px,.56fr));min-width:1520px;background:#121C25;border-bottom:1px solid rgba(213,174,119,.20)}
			.table-head div{padding:16px 12px;color:#D5AE77;font-size:13px;font-weight:950;text-transform:uppercase;letter-spacing:.07em;text-align:center}
			.table-head div:first-child{text-align:left;padding-left:20px}
			.rows{min-width:1520px}
			.diag-row{border-bottom:1px solid rgba(255,255,255,.055)}
			.diag-row summary{list-style:none;cursor:pointer}
			.diag-row summary::-webkit-details-marker{display:none}
			.row-grid{display:grid;grid-template-columns:minmax(520px,1.95fr) repeat(8,minmax(112px,.56fr));align-items:stretch;transition:all .18s ease}
			.row-grid:hover{background:rgba(213,174,119,.08)}
			.main-cell{padding:18px 18px;border-right:1px solid rgba(255,255,255,.05)}
			.title-line{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
			.row-title{color:#F8EFE1;font-size:18px;font-weight:950;line-height:1.2}
			.row-sub{margin-top:8px;color:#9FAAB5;font-size:14px;font-weight:820}
			.progress{margin-top:12px;height:9px;border-radius:999px;background:rgba(255,255,255,.07);overflow:hidden}
			.progress span{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,#D5AE77,#8BE0D1)}
			.metric{display:flex;flex-direction:column;justify-content:center;align-items:center;gap:6px;min-height:96px;padding:12px 8px;text-align:center;border-left:1px solid rgba(255,255,255,.05)}
			.metric b{color:#E8EEF5;font-size:21px;font-weight:950}
			.metric small{color:#8B98A6;font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.05em}
			.metric.highlight b{color:#F4D9A9}
			.badge{display:inline-flex;align-items:center;padding:6px 10px;border-radius:999px;font-size:11px;font-weight:950;text-transform:uppercase;letter-spacing:.04em;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.055)}
			.badge.good{color:#8BE0D1;border-color:rgba(139,224,209,.30);background:rgba(139,224,209,.08)}
			.badge.attention{color:#F4D9A9;border-color:rgba(213,174,119,.34);background:rgba(213,174,119,.10)}
			.badge.danger{color:#FFB0A8;border-color:rgba(217,93,93,.34);background:rgba(217,93,93,.10)}
			.badge.neutral{color:#AEB9C4}
			.detail-box{display:grid;grid-template-columns:1fr;gap:24px;padding:28px 32px 32px 40px;background:rgba(4,9,14,.38);border-top:1px solid rgba(213,174,119,.08)}
			.detail-card{min-width:0;padding:28px;border-radius:18px;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.08)}
			.detail-card.wide{grid-column:span 2}
			.detail-title{color:#F4D9A9;font-size:16px;font-weight:950;letter-spacing:.08em;text-transform:uppercase;margin-bottom:18px}
			.detail-line{display:grid;grid-template-columns:minmax(190px,1fr) minmax(200px,1fr) 90px 72px;align-items:center;gap:10px;margin-bottom:8px}
			.detail-name{color:#DCE5EE;font-size:14px;font-weight:850}
			.detail-bar{height:10px;border-radius:999px;overflow:hidden;background:rgba(255,255,255,.07)}
			.detail-bar span{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,#D5AE77,#F4D9A9)}
			.detail-num,.detail-pct{color:#AEB9C4;font-size:13px;font-weight:900;text-align:right}
			.pill-wrap{display:flex;flex-wrap:wrap;gap:12px}
			.pill{display:inline-flex;align-items:center;padding:12px 16px;border-radius:999px;color:#DCE5EE;background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.10);font-size:16px;font-weight:850}
			.pill.disp{border-color:rgba(213,174,119,.24);background:rgba(213,174,119,.07)}
			.pill.pass{border-color:rgba(139,224,209,.26);background:rgba(139,224,209,.07);color:#DFFCF7}
			.pill.empty{color:#AEB9C4}
			.client-wrap{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}
			.client-line{display:grid;grid-template-columns:minmax(0,1fr) 138px 76px;gap:8px;align-items:center;padding:8px 9px;border-radius:11px;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.07)}
			.client-name{min-width:0;color:#DCE5EE;font-size:13px;font-weight:850;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
			.client-cnpj,.client-qtd{color:#9FAAB5;font-size:12px;font-weight:850;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:right}
			.diag-note{display:none}
			.cmp-head,.cmp-row{display:grid;grid-template-columns:minmax(220px,1.6fr) 130px 130px 110px minmax(300px,2.5fr);align-items:center;gap:16px;padding:8px 10px}
			.cmp-head{border-bottom:2px solid rgba(213,174,119,.22);margin-bottom:6px}
			.cmp-head div{color:#D5AE77;font-size:14px;font-weight:950;text-transform:uppercase;letter-spacing:.06em}
			.cmp-name{color:#DCE5EE;font-size:18px;font-weight:850}
			.cmp-val{color:#AEB9C4;font-size:18px;font-weight:900;text-align:right}
			.cmp-pct{color:#F4D9A9;font-size:18px;font-weight:950;text-align:right}
			.cmp-pct.cmp-neutral{color:#8B98A6;font-size:15px;font-weight:850}
			.cmp-bar{height:14px;border-radius:999px;background:rgba(255,255,255,.07);overflow:hidden}
			.cmp-bar span{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,#D5AE77,#8BE0D1)}
			.cmp-row:hover{background:rgba(213,174,119,.06);border-radius:10px}
			@media(max-width:900px){.diag-kpis{grid-template-columns:repeat(6,minmax(210px,1fr));overflow-x:auto}.detail-box{grid-template-columns:1fr}.detail-card.wide{grid-column:span 1}.client-wrap{grid-template-columns:1fr}}
			</style>"
			```
		displayFolder: 06 Estilo HTML
		lineageTag: b0000601-d1ag-ba5e-b010-ba5e00000601

	/// 07 LAYOUT FINAL - Medida principal que monta o visual completo
	/// Topo com espaco para slicers e botao Detalhamento.
	measure 'HTML Layout | Topo Slicers' = ```
				    "<div class='slicer-space'><div class='doc-button'>Detalhamento</div></div>"
			```
		displayFolder: 07 Layout Final
		lineageTag: b0000701-d1ag-ba5e-b010-ba5e00000701

	/// Visual principal refatorado que monta CSS + Cards + Tabela com logica modular.
	/// Esta e a nova medida final que substitui a medida original monolítica.
	measure 'HTML Diagnóstico Journey | Visual Principal' =
			VAR vCSS = [HTML CSS | Completo]
				VAR vCards = [HTML Bloco | Cards]
				VAR vTabelaHead = [HTML Tabela | Cabeçalho]
				VAR vLinhas = [HTML Tabela | Linhas Produtos]
				VAR vTopo = [HTML Layout | Topo Slicers]
				RETURN
				    vCSS
				        & "<div class='diag-wrap'>"
				        &     "<div class='sticky'>"
				        &         "<div class='diag-head'>"
				        &             vTopo
				        &             vCards
				        &         "</div>"
				        &         vTabelaHead
				        &     "</div>"
				        &     "<div class='rows'>" & vLinhas & "</div>"
				        & "</div>"
		displayFolder: 07 Layout Final
		lineageTag: b0000702-d1ag-ba5e-b010-ba5e00000702

	/// 08 DEBUG E VALIDACAO - Medidas para conferencia entre versao antiga e nova
	/// Debug: Contagem total de registros na base de diagnostico.
	measure 'Diagnóstico Debug | Total Base' = ```
				[Diagnóstico | Registros]
			```
		displayFolder: 08 Debug e Validação
		lineageTag: b0000801-d1ag-ba5e-b010-ba5e00000801

	/// Debug: Total de produtos distintos na base de diagnostico.
	measure 'Diagnóstico Debug | Total Produtos' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    COUNTROWS (
				        SUMMARIZE (
				            FILTER ( vBaseDiag, NOT ISBLANK ( 'JOBS_Produto'[NOME_PRODUTO] ) ),
				            'JOBS_Produto'[NOME_PRODUTO]
				        )
				    )
			```
		displayFolder: 08 Debug e Validação
		lineageTag: b0000802-d1ag-ba5e-b010-ba5e00000802

	/// Debug: Confere contagem de empresas (NOME_CLIENTE distintos).
	measure 'Diagnóstico Debug | Conferência Empresas' = ```
				[Diagnóstico | Empresas]
			```
		displayFolder: 08 Debug e Validação
		lineageTag: b0000803-d1ag-ba5e-b010-ba5e00000803

	/// Debug: Confere contagem de jobs.
	measure 'Diagnóstico Debug | Conferência Jobs' = ```
				[Diagnóstico | Jobs]
			```
		displayFolder: 08 Debug e Validação
		lineageTag: b0000804-d1ag-ba5e-b010-ba5e00000804

	/// Debug: Confere contagem de oportunidades disponibilizadas.
	measure 'Diagnóstico Debug | Conferência Oportunidades' = ```
				[Diagnóstico | Oportunidades Disponibilizadas]
			```
		displayFolder: 08 Debug e Validação
		lineageTag: b0000805-d1ag-ba5e-b010-ba5e00000805

	/// 03B HONORARIOS - Medidas de honorários por job
	/// Honorarios encontrados: soma distinta por JOB para evitar duplicidade.
	measure 'Diagnóstico | Honorários Encontrados' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    SUMX (
				        SUMMARIZE ( vBaseDiag, 'JOBS_Produto'[JOB] ),
				        CALCULATE ( MAX ( 'JOBS_Produto'[JOB_HONORARIOS_ENCONTRADOS] ) )
				    )
			```
		formatString: R$ #,##0
		displayFolder: 03B Honorarios
		lineageTag: b0000311-d1ag-ba5e-b010-ba5e00000311

	/// Honorarios agendados: soma distinta por JOB.
	measure 'Diagnóstico | Honorários Agendados' = ```
				VAR vBaseDiag = 'JOBS_Produto'
				RETURN
				    SUMX (
				        SUMMARIZE ( vBaseDiag, 'JOBS_Produto'[JOB] ),
				        CALCULATE ( MAX ( 'JOBS_Produto'[JOB_HONORARIOS_AGENDADOS] ) )
				    )
			```
		formatString: R$ #,##0
		displayFolder: 03B Honorarios
		lineageTag: b0000312-d1ag-ba5e-b010-ba5e00000312

	/// Percentual de honorarios agendados sobre encontrados.
	measure 'Diagnóstico | % Honorários Agendados' = ```
				DIVIDE ( [Diagnóstico | Honorários Agendados], [Diagnóstico | Honorários Encontrados], 0 )
			```
		formatString: 0.0%
		displayFolder: 03B Honorarios
		lineageTag: b0000313-d1ag-ba5e-b010-ba5e00000313
		dataCategory: Percentage

	/// Total de Journey: COUNT(CODIGO) em PROJECT_QBERT_JOBS/QBERT para CODIGO_PRODUTO=360, FIM=1 e período selecionado.
	measure 'Journey QBERT | Total Journey' =
			VAR vMesesSelecionados =
			    VALUES ( 'dCalendar'[YearMonth] )
			RETURN
			    COUNTROWS (
			        FILTER (
			            ALL ( 'QBERT_JOBS_JOURNEY' ),
			            'QBERT_JOBS_JOURNEY'[CODIGO_PRODUTO] = 360
			                && 'QBERT_JOBS_JOURNEY'[FIM] = 1
			                && CONTAINS (
			                    vMesesSelecionados,
			                    'dCalendar'[YearMonth],
			                    YEAR ( 'QBERT_JOBS_JOURNEY'[DATA_CADASTRO] ) * 100
			                        + MONTH ( 'QBERT_JOBS_JOURNEY'[DATA_CADASTRO] )
			                )
			        )
			    )
		formatString: #,##0
		displayFolder: 04 Cards | QBERT
		lineageTag: 142b60b8-a65b-43f9-b8ba-e00e3955028b

	/// Total de Jobs: COUNT(CODIGO) dos filhos cujo PAI está nos Journey 360 finalizados do período selecionado e CODIGO_PRODUTO está no mapa governado MAP_PRODUTOS_ESTEIRA_TAX.
	measure 'Journey QBERT | Total Jobs' =
			VAR vMesesSelecionados =
			    VALUES ( 'dCalendar'[YearMonth] )
			VAR vProdutosEsteiraTax =
			    SELECTCOLUMNS (
			        FILTER (
			            ALL ( 'MAP_PRODUTOS_ESTEIRA_TAX' ),
			            'MAP_PRODUTOS_ESTEIRA_TAX'[AtivoFiltro]
			                && NOT ISBLANK ( 'MAP_PRODUTOS_ESTEIRA_TAX'[CodigoProduto] )
			        ),
			        "@CodigoProduto", 'MAP_PRODUTOS_ESTEIRA_TAX'[CodigoProduto]
			    )
			VAR vPaisJourney =
			    SELECTCOLUMNS (
			        FILTER (
			            ALL ( 'QBERT_JOBS_JOURNEY' ),
			            'QBERT_JOBS_JOURNEY'[CODIGO_PRODUTO] = 360
			                && 'QBERT_JOBS_JOURNEY'[FIM] = 1
			                && CONTAINS (
			                    vMesesSelecionados,
			                    'dCalendar'[YearMonth],
			                    YEAR ( 'QBERT_JOBS_JOURNEY'[DATA_CADASTRO] ) * 100
			                        + MONTH ( 'QBERT_JOBS_JOURNEY'[DATA_CADASTRO] )
			                )
			        ),
			        "@CodigoPai", 'QBERT_JOBS_JOURNEY'[CODIGO]
			    )
			RETURN
			    COUNTROWS (
			        FILTER (
			            ALL ( 'QBERT_JOBS_JOURNEY' ),
			            NOT ISBLANK ( 'QBERT_JOBS_JOURNEY'[CODIGO] )
			                && 'QBERT_JOBS_JOURNEY'[PAI] IN vPaisJourney
			                && 'QBERT_JOBS_JOURNEY'[CODIGO_PRODUTO] IN vProdutosEsteiraTax
			        )
			    )
		formatString: #,##0
		displayFolder: 04 Cards | QBERT
		lineageTag: 3e0d1714-b681-4c61-b78c-863f7916c025

	/// Jobs ativos: filhos dos Journey 360 finalizados do período selecionado, restritos ao mapa governado MAP_PRODUTOS_ESTEIRA_TAX, com FIM diferente de 1.
	measure 'Journey QBERT | Jobs Ativos' =
			VAR vMesesSelecionados =
			    VALUES ( 'dCalendar'[YearMonth] )
			VAR vProdutosEsteiraTax =
			    SELECTCOLUMNS (
			        FILTER (
			            ALL ( 'MAP_PRODUTOS_ESTEIRA_TAX' ),
			            'MAP_PRODUTOS_ESTEIRA_TAX'[AtivoFiltro]
			                && NOT ISBLANK ( 'MAP_PRODUTOS_ESTEIRA_TAX'[CodigoProduto] )
			        ),
			        "@CodigoProduto", 'MAP_PRODUTOS_ESTEIRA_TAX'[CodigoProduto]
			    )
			VAR vPaisJourney =
			    SELECTCOLUMNS (
			        FILTER (
			            ALL ( 'QBERT_JOBS_JOURNEY' ),
			            'QBERT_JOBS_JOURNEY'[CODIGO_PRODUTO] = 360
			                && 'QBERT_JOBS_JOURNEY'[FIM] = 1
			                && CONTAINS (
			                    vMesesSelecionados,
			                    'dCalendar'[YearMonth],
			                    YEAR ( 'QBERT_JOBS_JOURNEY'[DATA_CADASTRO] ) * 100
			                        + MONTH ( 'QBERT_JOBS_JOURNEY'[DATA_CADASTRO] )
			                )
			        ),
			        "@CodigoPai", 'QBERT_JOBS_JOURNEY'[CODIGO]
			    )
			RETURN
			    COUNTROWS (
			        FILTER (
			            ALL ( 'QBERT_JOBS_JOURNEY' ),
			            NOT ISBLANK ( 'QBERT_JOBS_JOURNEY'[CODIGO] )
			                && 'QBERT_JOBS_JOURNEY'[PAI] IN vPaisJourney
			                && 'QBERT_JOBS_JOURNEY'[CODIGO_PRODUTO] IN vProdutosEsteiraTax
			                && COALESCE ( 'QBERT_JOBS_JOURNEY'[FIM], 0 ) <> 1
			        )
			    )
		formatString: #,##0
		displayFolder: 04 Cards | QBERT
		lineageTag: 1bdef7ff-7b2c-4f9b-bf88-d8af9ff2ebf7

	column Column
		formatString: 0
		lineageTag: 2ec931fb-c2e0-4926-ad68-5e513c5ba130
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition medidas_html = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 1fcf0b6930bb4e10a61b1c725afbbaf7

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

