table medidas_html
	lineageTag: f371007f-daa0-4acf-919c-58dc35ff6b74

	/// Cabeçalho executivo do dashboard Journey, com dados de oportunidades e jobs por CNPJ.
	measure Titulo_Diagnostico_HTML_2026_Novo_Estilo_DOCUMENTACAO = ```
					VAR vCalendarStart = MIN ( 'dCalendar'[Date] )
					VAR vCalendarEnd = MAX ( 'dCalendar'[Date] )
					VAR vHasCalendarFilter =
						ISFILTERED ( 'dCalendar'[Date] )
							|| ISFILTERED ( 'dCalendar'[YearMonthName] )
							|| ISFILTERED ( 'dCalendar'[YearMonth] )
							|| ISFILTERED ( 'dCalendar'[MonthNumber] )
							|| ISFILTERED ( 'dCalendar'[Year] )
					VAR vDateFormat = "dd/mm/yyyy"
					VAR vMinData = MINX ( CONTRATOS_OPORTUNIDADES, CONTRATOS_OPORTUNIDADES[data_contrato] )
					VAR vMaxData = MAXX ( CONTRATOS_OPORTUNIDADES, CONTRATOS_OPORTUNIDADES[data_contrato] )
					VAR vPeriodo =
						IF (
							ISBLANK ( vMinData ) || ISBLANK ( vMaxData ),
							"Período não definido",
							FORMAT ( vMinData, vDateFormat ) & " a " & FORMAT ( vMaxData, vDateFormat )
						)
					VAR vTotalProdutos = DISTINCTCOUNT ( CONTRATOS_OPORTUNIDADES[oportunidade] )
					VAR vJobsCO = DISTINCTCOUNT ( CONTRATOS_OPORTUNIDADES[job] )
					VAR vEstimativaTotal = SUM ( CONTRATOS_OPORTUNIDADES[estimativa] )
					VAR vDataAtual = FORMAT ( NOW (), "dd/mm/yyyy HH:mm" )
					VAR vCSS =
					"
					<style>
					*{margin:0;padding:0;box-sizing:border-box}
					.diag-title-shell{width:1910px;min-width:1910px;max-width:1910px;height:165px;min-height:165px;max-height:165px;overflow:hidden;font-family:'Segoe UI',Arial,sans-serif;color:#E8EEF5;border-radius:18px;border:1px solid rgba(213,174,119,.36);background:radial-gradient(circle at 0% 0%,rgba(213,174,119,.22),transparent 33%),radial-gradient(circle at 92% 18%,rgba(139,224,209,.13),transparent 28%),linear-gradient(135deg,#060B10 0%,#0B141B 46%,#10201F 100%);box-shadow:0 16px 38px rgba(0,0,0,.50),inset 0 1px 0 rgba(255,255,255,.05);position:relative}
					.diag-title-shell:before{content:'';position:absolute;left:0;top:0;bottom:0;width:8px;background:linear-gradient(180deg,#F4D9A9,#D5AE77,#8BE0D1);opacity:.92}
					.diag-title-grid{position:relative;z-index:2;width:100%;height:100%;display:grid;grid-template-columns:150px minmax(0,1fr) 430px;align-items:center;gap:24px;padding:18px 26px 18px 34px}
					.brand-panel{height:100%;min-width:0;display:flex;align-items:center;justify-content:center}
					.logo-card{width:118px;height:82px;border-radius:16px;display:flex;align-items:center;justify-content:center;padding:10px;background:radial-gradient(circle at 28% 12%,rgba(213,174,119,.18),transparent 36%),#030506;border:1px solid rgba(213,174,119,.40);box-shadow:0 12px 24px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.06);overflow:hidden}
					.logo-text{width:100%;height:100%;display:flex;align-items:center;justify-content:center;color:#fff;font-family:Georgia,'Times New Roman',serif;font-size:13px;font-weight:700;line-height:1;letter-spacing:-.05em;text-align:center;white-space:nowrap;overflow:hidden}
					.logo-text .studio{color:#D5AE77;margin-left:1px}
					.center-panel{min-width:0;height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;text-align:center;position:relative}
					.center-panel:before,.center-panel:after{content:'';width:88px;height:1px;background:linear-gradient(90deg,transparent,rgba(213,174,119,.65),transparent)}
					.title-kicker{color:#8BE0D1;font-size:10px;font-weight:950;letter-spacing:.22em;text-transform:uppercase;line-height:1;white-space:nowrap}
					.main-title{color:#fff;font-size:38px;font-weight:950;letter-spacing:.09em;text-transform:uppercase;line-height:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-shadow:0 4px 16px rgba(0,0,0,.72)}
					.main-title .gold{color:#F4D9A9}
					.subline{max-width:100%;color:#D5AE77;font-size:11px;font-weight:950;letter-spacing:.10em;text-transform:uppercase;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
					.right-panel{height:100%;display:grid;grid-template-columns:168px minmax(0,1fr) 68px;align-items:center;gap:14px;min-width:0}
					.doc-title-button{position:relative;min-height:44px;display:inline-flex;align-items:center;justify-content:center;padding:12px 17px;border-radius:14px;color:#081018;border:1px solid rgba(244,217,169,.72);background:linear-gradient(135deg,#F4D9A9 0%,#D5AE77 48%,#8BE0D1 100%);box-shadow:0 14px 28px rgba(213,174,119,.24),0 0 0 1px rgba(255,255,255,.08) inset,0 0 22px rgba(139,224,209,.18);font-size:11px;font-weight:950;letter-spacing:.10em;text-transform:uppercase;white-space:nowrap;overflow:hidden}
					.doc-title-button:before{content:'i';display:inline-flex;align-items:center;justify-content:center;width:21px;height:21px;margin-right:8px;border-radius:50%;background:rgba(8,16,24,.18);border:1px solid rgba(8,16,24,.24);color:#081018;font-size:12px;font-weight:950;font-style:italic;line-height:1}
					.update-box{display:flex;flex-direction:column;align-items:flex-end;justify-content:center;gap:10px;min-width:0}
					.update-line{display:flex;flex-direction:column;align-items:flex-end;gap:3px;min-width:0}
					.update-label{color:#F4D9A9;font-size:9px;font-weight:950;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap}
					.update-value{color:#E8EEF5;font-size:12px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:160px;text-align:right}
					.avatar{position:relative;width:62px;height:62px;border-radius:50%;display:flex;align-items:center;justify-content:center;color:#F4D9A9;font-size:18px;font-weight:950;letter-spacing:.05em;background:linear-gradient(145deg,rgba(213,174,119,.14),rgba(255,255,255,.035));border:1px solid rgba(213,174,119,.58);box-shadow:0 0 0 5px rgba(213,174,119,.06),inset 0 1px 0 rgba(255,255,255,.10)}
					.avatar:after{content:'';position:absolute;right:2px;bottom:5px;width:9px;height:9px;border-radius:50%;background:#21E66D;box-shadow:0 0 12px rgba(33,230,109,.75);border:2px solid #10201F}
					</style>
					"
					VAR vHTML =
						"<div class='diag-title-shell'><div class='diag-title-grid'>"
							& "<div class='brand-panel'><div class='logo-card'><div class='logo-text'><span>GRUPO</span><span class='studio'>STUDIO</span></div></div></div>"
							& "<div class='center-panel'><div class='title-kicker'>Grupo Studio · Diagnóstico TAX</div><div class='main-title'>Oportunidades <span class='gold'>- Journey</span></div><div class='subline'>" & FORMAT ( vTotalProdutos, "#,##0" ) & " produtos · " & FORMAT ( vJobsCO, "#,##0" ) & " empresas | " & vPeriodo & "</div></div>"
							& "<div class='right-panel'><div class='doc-title-button'>Documentação</div><div class='update-box'><div class='update-line'><span class='update-label'>Atualizado em</span><span class='update-value'>" & vDataAtual & "</span></div><div class='update-line'><span class='update-label'>Créd. Estimado</span><span class='update-value'>" & FORMAT ( vEstimativaTotal, "R$ #,##0" ) & "</span></div></div><div class='avatar'>GS</div></div>"
						& "</div></div>"
					RETURN
						vCSS & vHTML
			```
		displayFolder: HTML
		lineageTag: c4874ca8-7357-4c3e-b3e5-6180c4491f86

	/// Documentação executiva da refatoração com CONTRATOS_OPORTUNIDADES como base de produtos.
	measure DOCUMENTACAO_DIAGNOSTICO_JOURNEY_HTML_V4_FORMAL_TODO_PERIODO = ```
					VAR vTotalProdutos = DISTINCTCOUNT ( CONTRATOS_OPORTUNIDADES[oportunidade] )
					VAR vTotalOportunidades = COUNTROWS ( CONTRATOS_OPORTUNIDADES )
					VAR vCNPJsRecorte =
						FILTER (
							VALUES ( CONTRATOS_OPORTUNIDADES[CNPJ_JOIN] ),
							NOT ISBLANK ( CONTRATOS_OPORTUNIDADES[CNPJ_JOIN] )
						)
					VAR vTotalCNPJs = COUNTROWS ( vCNPJsRecorte )
					VAR vTotalJobs =
						CALCULATE (
							DISTINCTCOUNT ( JOBS_PRODUTO_AREA[JOB] ),
							TREATAS ( vCNPJsRecorte, JOBS_PRODUTO_AREA[CNPJ_JOIN] )
						)
					VAR vTotalEstimativa = SUM ( CONTRATOS_OPORTUNIDADES[estimativa] )
					VAR vPeriodoInicial = MINX ( CONTRATOS_OPORTUNIDADES, CONTRATOS_OPORTUNIDADES[data_contrato] )
					VAR vPeriodoFinal = MAXX ( CONTRATOS_OPORTUNIDADES, CONTRATOS_OPORTUNIDADES[data_contrato] )
					VAR vPeriodo =
						IF (
							ISBLANK ( vPeriodoInicial ) || ISBLANK ( vPeriodoFinal ),
							"Sem dados no recorte",
							FORMAT ( vPeriodoInicial, "dd/MM/yyyy" ) & " a " & FORMAT ( vPeriodoFinal, "dd/MM/yyyy" )
						)
					VAR vAtualizado = FORMAT ( NOW (), "dd/mm/yyyy HH:mm" )
					VAR vCSS =
					"
					<style>
					.doc-page{width:1910px;height:1070px;box-sizing:border-box;padding:20px;font-family:'Segoe UI',Arial,sans-serif;background:radial-gradient(circle at 0% 0%,rgba(213,174,119,.18),transparent 32%),radial-gradient(circle at 94% 7%,rgba(139,224,209,.12),transparent 30%),linear-gradient(180deg,#101923 0%,#0B1219 100%);color:#E8EEF5;overflow:hidden}
					.doc-shell{width:100%;height:100%;display:grid;grid-template-columns:390px 1fr;gap:16px}
					.doc-sidebar{height:100%;box-sizing:border-box;border-radius:20px;border:1px solid rgba(213,174,119,.28);background:linear-gradient(180deg,rgba(213,174,119,.15),rgba(255,255,255,.025));box-shadow:0 18px 42px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.05);padding:24px 20px 20px;overflow:hidden;position:relative}
					.doc-sidebar:before{content:'';position:absolute;left:0;top:0;bottom:0;width:7px;background:linear-gradient(180deg,#F4D9A9,#D5AE77,#8BE0D1)}
					.brand-kicker{font-size:12.5px;text-transform:uppercase;letter-spacing:1.7px;color:#8BE0D1;font-weight:950;margin-bottom:10px}
					.brand-title{color:#F4D9A9;font-size:37.5px;line-height:1.02;font-weight:950;letter-spacing:.02em;margin-bottom:10px;text-transform:uppercase;text-shadow:0 8px 18px rgba(0,0,0,.35)}
					.brand-sub{font-size:15.6px;line-height:1.48;color:#B7C2CD;margin-bottom:14px}
					.side-card{border:1px solid rgba(255,255,255,.09);background:rgba(255,255,255,.04);border-radius:15px;padding:12px;margin-bottom:10px}
					.side-card.highlight{background:linear-gradient(135deg,rgba(213,174,119,.17),rgba(255,255,255,.035));border-color:rgba(213,174,119,.30)}
					.side-label{display:block;font-size:11.9px;color:#8796A5;text-transform:uppercase;letter-spacing:.85px;font-weight:950;margin-bottom:5px}
					.side-value{display:block;font-size:17.5px;color:#F0F5FA;font-weight:900;line-height:1.25}
					.side-value.big{color:#F4D9A9;font-size:27.5px}
					.side-small{color:#AEB8C2;font-size:13.4px;line-height:1.4;margin-top:5px}
					.nav-title{margin-top:14px;margin-bottom:9px;font-size:12.5px;text-transform:uppercase;letter-spacing:.95px;color:#D5AE77;font-weight:950}
					.nav-list{display:flex;flex-direction:column;gap:6px}.nav-pill{font-size:13.5px;color:#DCE5EE;border:1px solid rgba(213,174,119,.16);background:rgba(255,255,255,.04);border-radius:999px;padding:7px 10px;font-weight:850;line-height:1}.nav-pill.active{color:#8BE0D1;border-color:rgba(139,224,209,.30);background:rgba(139,224,209,.08)}
					.doc-main{height:100%;background:linear-gradient(180deg,#121C25 0%,#0D151D 100%);border:1px solid rgba(213,174,119,.20);border-radius:20px;box-shadow:0 18px 42px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.05);overflow:hidden;display:flex;flex-direction:column}
					.doc-header{padding:17px 20px 15px;border-bottom:1px solid rgba(213,174,119,.16);display:flex;align-items:flex-start;justify-content:space-between;gap:18px;background:linear-gradient(90deg,rgba(255,255,255,.03),rgba(213,174,119,.035))}
					.doc-header h1{margin:0;color:#F4D9A9;font-size:33.8px;line-height:1.08;font-weight:950;letter-spacing:.3px;text-transform:uppercase}.doc-header p{margin:7px 0 0;color:#B7C2CD;font-size:16px;line-height:1.4;max-width:1120px}
					.badge-wrap{display:flex;justify-content:flex-end;align-items:center;flex-wrap:wrap;gap:6px}.badge{display:inline-flex;border-radius:999px;border:1px solid rgba(213,174,119,.30);background:rgba(213,174,119,.08);color:#F4D9A9;font-size:12.5px;font-weight:950;text-transform:uppercase;letter-spacing:.6px;padding:5px 10px;white-space:nowrap}.badge.teal{color:#8BE0D1;border-color:rgba(139,224,209,.34);background:rgba(139,224,209,.08)}
					.doc-scroll{flex:1 1 auto;min-height:0;overflow-y:auto;overflow-x:hidden;padding:18px 20px 20px;box-sizing:border-box;scrollbar-width:thin;scrollbar-color:rgba(213,174,119,.60) rgba(8,14,20,.95)}
					.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:11px;margin-bottom:14px}.metric{position:relative;min-height:124px;padding:15px 13px 13px;border-radius:18px;background:linear-gradient(160deg,rgba(18,28,37,.96),rgba(11,18,25,.94));border:1px solid rgba(255,255,255,.10);box-shadow:0 16px 28px rgba(0,0,0,.22),inset 0 1px 0 rgba(255,255,255,.06);overflow:hidden}.metric:before{content:'';position:absolute;left:14px;top:0;width:42px;height:4px;border-radius:0 0 10px 10px;background:linear-gradient(90deg,#F4D9A9,#8BE0D1)}.metric.primary{background:linear-gradient(155deg,rgba(213,174,119,.20),rgba(18,28,37,.96) 36%,rgba(11,18,25,.96));border-color:rgba(213,174,119,.40)}.m-label{display:block;color:#AEB9C4;font-size:12.5px;letter-spacing:.08em;text-transform:uppercase;font-weight:950;margin-bottom:8px}.m-value{display:block;color:#F4D9A9;font-size:32.5px;font-weight:950;line-height:1.05;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.m-note{display:block;color:#8B98A6;font-size:13.8px;line-height:1.28;margin-top:7px;font-weight:850}
					.doc-section{border:1px solid rgba(213,174,119,.19);background:rgba(255,255,255,.027);border-radius:17px;margin-bottom:12px;overflow:hidden}.doc-section summary{cursor:pointer;list-style:none;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 15px;background:linear-gradient(90deg,rgba(213,174,119,.17),rgba(213,174,119,.035));border-bottom:1px solid rgba(213,174,119,.13)}.summary-left{display:flex;align-items:center;gap:10px;min-width:0}.summary-index{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:50%;background:rgba(213,174,119,.19);border:1px solid rgba(213,174,119,.30);color:#F4D9A9;font-size:12.5px;font-weight:950}.summary-title{color:#F4D9A9;font-size:17.5px;font-weight:950;text-transform:uppercase;letter-spacing:.45px}.summary-action{color:#B7C2CD;font-size:12.2px;font-weight:950;text-transform:uppercase;letter-spacing:.5px;border:1px solid rgba(255,255,255,.10);background:rgba(255,255,255,.04);border-radius:999px;padding:5px 9px;white-space:nowrap}.section-body{padding:15px}
					.doc-table{width:100%;border-collapse:separate;border-spacing:0;table-layout:fixed;overflow:hidden;border-radius:13px;border:1px solid rgba(255,255,255,.08);margin-bottom:10px}.doc-table th{background:#111A22;color:#D5AE77;font-size:12.5px;font-weight:950;text-transform:uppercase;letter-spacing:.55px;text-align:left;padding:10px;border-bottom:1px solid rgba(213,174,119,.30)}.doc-table td{color:#DCE5EE;font-size:14px;line-height:1.45;padding:9px 10px;border-bottom:1px solid rgba(255,255,255,.055);vertical-align:top}.doc-table tr:last-child td{border-bottom:none}.doc-table td strong{color:#F4D9A9}.callout{border-left:4px solid rgba(213,174,119,.82);background:rgba(213,174,119,.06);border-radius:13px;padding:12px 13px;color:#DCE5EE;font-size:14.2px;line-height:1.5;margin:10px 0}.callout.tech{border-left-color:#8BE0D1;background:rgba(139,224,209,.055)}.footer-doc{font-size:13.4px;color:#8796A5;line-height:1.38;padding:10px 2px 2px}
					</style>
					"
					VAR vHTML =
					"<div class='doc-page'><div class='doc-shell'><aside class='doc-sidebar'>"
						& "<div class='brand-kicker'>Power BI · Documentação</div><div class='brand-title'>Oportunidades<br><span style='color:#8BE0D1'>x Jobs</span></div>"
						& "<div class='brand-sub'>Guia executivo e técnico do painel. A pergunta central é: das oportunidades contratadas no período selecionado, onde estão os jobs desses CNPJs agora?</div>"
						& "<div class='side-card highlight'><span class='side-label'>Modelo atual</span><span class='side-value big'>dCalendar + dCNPJ</span><div class='side-small'>Calendário e CNPJ são as dimensões de controle. As duas fatos não se relacionam diretamente.</div></div>"
						& "<div class='side-card'><span class='side-label'>Bases usadas</span><span class='side-value'>CO + Jobs</span><div class='side-small'>CONTRATOS_OPORTUNIDADES define o universo comercial. JOBS_PRODUTO_AREA mostra a posição operacional atual dos jobs.</div></div>"
						& "<div class='side-card'><span class='side-label'>Período exibido</span><span class='side-value'>" & vPeriodo & "</span><div class='side-small'>O período filtra somente CONTRATOS_OPORTUNIDADES[data_contrato] via dCalendar.</div></div>"
						& "<div class='side-card'><span class='side-label'>Atualização</span><span class='side-value'>" & vAtualizado & "</span><div class='side-small'>Horário gerado no cálculo da medida HTML.</div></div>"
						& "<div class='nav-title'>Conteúdo</div><div class='nav-list'><div class='nav-pill active'>01. Visão executiva</div><div class='nav-pill'>02. Modelo</div><div class='nav-pill'>03. Regras de cálculo</div><div class='nav-pill'>04. Manutenção</div></div>"
					& "</aside><main class='doc-main'><div class='doc-header'><div><h1>Documentação · Oportunidades x Jobs</h1><p>Esta página explica a lógica do relatório para a diretoria e registra os pontos técnicos necessários para evolução, manutenção e auditoria do modelo semântico.</p></div><div class='badge-wrap'><span class='badge'>Diretoria</span><span class='badge'>Técnico</span><span class='badge teal'>CNPJ como ponte</span></div></div><div class='doc-scroll'>"
						& "<div class='metric-grid'><div class='metric primary'><span class='m-label'>Produtos</span><span class='m-value'>" & FORMAT ( vTotalProdutos, "#,##0" ) & "</span><span class='m-note'>CONTRATOS_OPORTUNIDADES[oportunidade]</span></div><div class='metric'><span class='m-label'>Oportunidades</span><span class='m-value'>" & FORMAT ( vTotalOportunidades, "#,##0" ) & "</span><span class='m-note'>Linhas comerciais analisadas</span></div><div class='metric'><span class='m-label'>CNPJs</span><span class='m-value'>" & FORMAT ( vTotalCNPJs, "#,##0" ) & "</span><span class='m-note'>Dimensão comum dCNPJ</span></div><div class='metric'><span class='m-label'>Jobs</span><span class='m-value'>" & FORMAT ( vTotalJobs, "#,##0" ) & "</span><span class='m-note'>Jobs distintos na base operacional</span></div></div>"
						& "<details class='doc-section' open><summary><div class='summary-left'><span class='summary-index'>01</span><span class='summary-title'>Visão executiva do projeto</span></div><span class='summary-action'>Diretoria</span></summary><div class='section-body'><table class='doc-table'><thead><tr><th>Tema</th><th>Definição para negócio</th><th>Efeito no painel</th></tr></thead><tbody><tr><td><strong>Objetivo</strong></td><td>Conectar oportunidades contratadas com a situação operacional dos jobs vinculados aos mesmos CNPJs.</td><td>Permite acompanhar se uma oportunidade virou job, onde ela está na esteira e se há gargalo.</td></tr><tr><td><strong>Período</strong></td><td>O período selecionado representa data de contrato da oportunidade, não data operacional do job.</td><td>O usuário pergunta pelas oportunidades do período e enxerga o status atual dos jobs desses CNPJs.</td></tr><tr><td><strong>Produto</strong></td><td>Produto é a oportunidade comercial registrada em CONTRATOS_OPORTUNIDADES[oportunidade].</td><td>As linhas da tela principal agrupam por produto e recalculam com os slicers nativos.</td></tr><tr><td><strong>Status atual</strong></td><td>JOBS_PRODUTO_AREA é histórica; por isso o painel usa a última movimentação por JOB para classificar a etapa atual.</td><td>Evita tratar área antiga como status atual e reduz distorções de funil.</td></tr></tbody></table><div class='callout'>Leitura recomendada: primeiro selecione Período, Produto, Cliente ou CNPJ nos slicers nativos. Depois use o botão Detalhamento para abrir a página analítica com filtros internos por coluna.</div></div></details>"
						& "<details class='doc-section' open><summary><div class='summary-left'><span class='summary-index'>02</span><span class='summary-title'>Modelo semântico e relacionamentos</span></div><span class='summary-action'>Modelo</span></summary><div class='section-body'><table class='doc-table'><thead><tr><th>Objeto</th><th>Função</th><th>Regra técnica</th></tr></thead><tbody><tr><td><strong>CONTRATOS_OPORTUNIDADES</strong></td><td>Fato comercial. Contém job, id_solucao, cnpj, razao_social, oportunidade, data_contrato e estimativa.</td><td>Recebe CNPJ_JOIN calculado a partir de cnpj normalizado para 14 dígitos.</td></tr><tr><td><strong>JOBS_PRODUTO_AREA</strong></td><td>Fato operacional histórica. Contém JOB, CNPJ_CLIENTE, NOME_AREA, datas de movimentação, responsável, equipe e honorários.</td><td>Recebe CNPJ_JOIN calculado a partir de CNPJ_CLIENTE normalizado para 14 dígitos.</td></tr><tr><td><strong>dCNPJ</strong></td><td>Dimensão comum de CNPJ. Une todos os CNPJs válidos presentes nas duas fatos.</td><td>Relaciona 1:* com as duas fatos em direção single. Não existe relacionamento direto entre as fatos.</td></tr><tr><td><strong>dCalendar</strong></td><td>Calendário único do relatório.</td><td>Relaciona 1:* somente com CONTRATOS_OPORTUNIDADES[data_contrato]. Não filtra datas operacionais da JOBS_PRODUTO_AREA.</td></tr></tbody></table><div class='callout tech'>Topologia aceita: dCalendar 1:* CONTRATOS_OPORTUNIDADES; dCNPJ 1:* CONTRATOS_OPORTUNIDADES; dCNPJ 1:* JOBS_PRODUTO_AREA. Não usar many-to-many, bidirecional ou relacionamento direto ativo entre CONTRATOS_OPORTUNIDADES e JOBS_PRODUTO_AREA.</div></div></details>"
						& "<details class='doc-section' open><summary><div class='summary-left'><span class='summary-index'>03</span><span class='summary-title'>Filtros, páginas e comportamento esperado</span></div><span class='summary-action'>Uso</span></summary><div class='section-body'><table class='doc-table'><thead><tr><th>Recurso</th><th>Como funciona</th><th>Observação</th></tr></thead><tbody><tr><td><strong>Slicers nativos</strong></td><td>Período, Produto, Cliente e CNPJ ficam fora da medida HTML, como visuais nativos do relatório.</td><td>São os filtros oficiais para recalcular cards e medidas, respeitando o modelo semântico.</td></tr><tr><td><strong>Tela principal</strong></td><td>Mostra KPIs e uma linha por produto. Ao expandir um produto, exibe primeiros jobs e últimos jobs relacionados.</td><td>Primeiros jobs ajudam a identificar itens parados há mais tempo; últimos jobs mostram movimentações recentes.</td></tr><tr><td><strong>Botão Detalhamento</strong></td><td>É um bloco visual dentro da medida principal, coberto por botão transparente nativo para navegação.</td><td>A medida não navega sozinha; a navegação real fica no visual nativo do Power BI.</td></tr><tr><td><strong>Aba Detalhamento</strong></td><td>Mostra linhas operacionais com filtros internos de busca geral, produto, cliente, CNPJ, job, etapa e área.</td><td>Filtros internos só escondem/exibem linhas já retornadas pela medida; slicers nativos continuam sendo o recorte principal.</td></tr></tbody></table></div></details>"
						& "<details class='doc-section' open><summary><div class='summary-left'><span class='summary-index'>04</span><span class='summary-title'>Regras de cálculo e classificação</span></div><span class='summary-action'>DAX</span></summary><div class='section-body'><table class='doc-table'><thead><tr><th>Regra</th><th>Descrição</th><th>Onde ajustar</th></tr></thead><tbody><tr><td><strong>CNPJ_JOIN</strong></td><td>Converte CNPJ em texto, remove ponto, barra, hífen, espaço e espaço invisível, completa zeros à esquerda e mantém 14 dígitos.</td><td>Colunas calculadas CNPJ_JOIN nas duas tabelas fato.</td></tr><tr><td><strong>Universo de análise</strong></td><td>O recorte começa nas oportunidades filtradas por dCalendar e slicers nativos.</td><td>Blocos vCO_Raw, vCO_Select e vCO_Base das medidas HTML.</td></tr><tr><td><strong>Status atual do job</strong></td><td>Para cada JOB, a medida pega a última linha pela maior data entre TRIBUTO_DATA_ENTRADA e DATA_CADASTRO.</td><td>Blocos de tabela virtual vJobs_Status nas medidas.</td></tr><tr><td><strong>Etapa atual</strong></td><td>A etapa é classificada por NOME_AREA: procuração, checklist, operação, reunião técnica, diagnóstico, créditos, finalizado, cancelado ou cadastro/outros.</td><td>SWITCH/CONTAINSSTRING dentro das medidas HTML.</td></tr><tr><td><strong>Honorários</strong></td><td>Honorários estimados vêm de CONTRATOS_OPORTUNIDADES[estimativa]. Honorários encontrados vêm de JOBS_PRODUTO_AREA[JOB_HONORARIOS_ENCONTRADOS].</td><td>Blocos de métricas financeiras da medida principal.</td></tr></tbody></table><div class='callout tech'>Como JOBS_PRODUTO_AREA é histórica, não criar slicer de área diretamente em NOME_AREA sem transformar a base para uma linha atual por JOB. Se precisar de filtro nativo de área, criar antes uma dimensão/tabela JOBS_STATUS_ATUAL.</div></div></details>"
						& "<details class='doc-section' open><summary><div class='summary-left'><span class='summary-index'>05</span><span class='summary-title'>Manutenção técnica</span></div><span class='summary-action'>TMDL</span></summary><div class='section-body'><table class='doc-table'><thead><tr><th>Artefato</th><th>Local</th><th>Quando mexer</th></tr></thead><tbody><tr><td><strong>Medidas HTML</strong></td><td>Jobs_Produtos.SemanticModel/definition/tables/medidas_html.tmdl</td><td>Alterar layout, textos, filtros internos, regras de etapa e tabelas expandidas.</td></tr><tr><td><strong>Modelo</strong></td><td>Jobs_Produtos.SemanticModel/definition/model.tmdl e relationships.tmdl</td><td>Validar relacionamentos, calendário único, auto date/time desativado e ausência de relações diretas entre fatos.</td></tr><tr><td><strong>Tabelas fato</strong></td><td>CONTRATOS_OPORTUNIDADES.tmdl e JOBS_PRODUTO_AREA.tmdl</td><td>Manter CNPJ_JOIN e tipos de dados esperados. Não criar objeto permanente no banco.</td></tr><tr><td><strong>Visuais nativos</strong></td><td>Jobs_Produtos.Report/definition/pages/.../visuals/visual.json</td><td>Ajustar slicers nativos, botões transparentes de navegação e posicionamento dos visuais.</td></tr></tbody></table><div class='callout tech'>Validações mínimas após alteração: carregar a pasta TMDL, validar as medidas HTML com uma consulta DAX simples usando LEN, verificar se os JSONs dos visuais abrem como JSON válido e conferir se não há filtros persistidos indevidos nos slicers.</div></div></details>"
						& "<details class='doc-section' open><summary><div class='summary-left'><span class='summary-index'>06</span><span class='summary-title'>Cuidados e limites conhecidos</span></div><span class='summary-action'>Governança</span></summary><div class='section-body'><div class='callout'>O relatório não responde quantos jobs foram criados dentro do mesmo período operacional. Ele responde onde estão agora os jobs dos CNPJs que tiveram oportunidade no período selecionado.</div><div class='callout tech'>Não reativar LocalDateTable_* nem DateTableTemplate_*. O calendário oficial é dCalendar. Se o Power BI recriar tabelas automáticas, revisar a anotação __PBI_TimeIntelligenceEnabled = 0 e remover variações automáticas das colunas de data.</div><div class='callout tech'>Não relacionar dCalendar com JOBS_PRODUTO_AREA[TRIBUTO_DATA_ENTRADA] nem JOBS_PRODUTO_AREA[DATA_CADASTRO] para esta tela. Isso esconderia jobs atuais por data operacional e quebraria a análise executiva.</div><div class='footer-doc'>Recorte atual: " & vPeriodo & ". Produtos: " & FORMAT ( vTotalProdutos, "#,##0" ) & ". Oportunidades: " & FORMAT ( vTotalOportunidades, "#,##0" ) & ". CNPJs: " & FORMAT ( vTotalCNPJs, "#,##0" ) & ". Jobs: " & FORMAT ( vTotalJobs, "#,##0" ) & ". Estimativa: " & FORMAT ( vTotalEstimativa, "R$ #,##0" ) & ". Atualizado em " & vAtualizado & ".</div></div></details>"
					& "</div></main></div></div>"
					RETURN
						vCSS & vHTML
			```
		displayFolder: HTML
		lineageTag: f12039a5-a0eb-4967-9a5c-c2c27638806e

	/// Detalhamento operacional com CONTRATOS_OPORTUNIDADES como fonte de jobs e etapas via PQBJ.
	measure 'HTML Macro Oportunidades x Jobs | Aba Documentação' = ```
			
			VAR vIntFormat = "#,##0"
			VAR vMoneyFormat = "R$ #,##0"
			VAR vLimiteLinhas = 3000
			
			VAR vCalendarStart = MIN ( 'dCalendar'[Date] )
			VAR vCalendarEnd = MAX ( 'dCalendar'[Date] )
			VAR vHasCalendarFilter =
			    COUNTROWS ( 'dCalendar' ) < COUNTROWS ( ALL ( 'dCalendar' ) )
			
			VAR vPeriodo =
			    IF (
			        vHasCalendarFilter,
			        FORMAT ( vCalendarStart, "dd/MM/yyyy" ) & " a " & FORMAT ( vCalendarEnd, "dd/MM/yyyy" ),
			        "Todo o período"
			    )
			
			/* =========================================================================
			   1) OPORTUNIDADES
			   ========================================================================= */
			VAR vCO_Raw =
			    FILTER (
			        ALLSELECTED ( CONTRATOS_OPORTUNIDADES ),
			        NOT vHasCalendarFilter
			            || (
			                CONTRATOS_OPORTUNIDADES[data_contrato] >= vCalendarStart
			                    && CONTRATOS_OPORTUNIDADES[data_contrato] < vCalendarEnd + 1
			            )
			    )
			
			VAR vCO_Select =
			    SELECTCOLUMNS (
			        vCO_Raw,
			        "__JobCO", CONTRATOS_OPORTUNIDADES[job],
			        "__IdSolucao", CONTRATOS_OPORTUNIDADES[id_solucao],
			        "__CNPJ", CONTRATOS_OPORTUNIDADES[CNPJ_JOIN],
			        "__ClienteCO", COALESCE ( CONTRATOS_OPORTUNIDADES[razao_social], "Sem cliente" ),
			        "__Produto", TRIM ( SUBSTITUTE ( COALESCE ( CONTRATOS_OPORTUNIDADES[oportunidade], "Sem produto" ), "_", " " ) ),
			        "__DataContrato", CONTRATOS_OPORTUNIDADES[data_contrato],
			        "__Estimativa", COALESCE ( CONTRATOS_OPORTUNIDADES[estimativa], 0 )
			    )
			
			VAR vCO_Base =
			    ADDCOLUMNS (
			        SUMMARIZE ( vCO_Select, [__JobCO], [__IdSolucao], [__CNPJ] ),
			        "__Produto",
			            VAR j = [__JobCO]
			            VAR s = [__IdSolucao]
			            VAR c = [__CNPJ]
			            RETURN MAXX ( FILTER ( vCO_Select, [__JobCO] = j && [__IdSolucao] = s && [__CNPJ] = c ), [__Produto] ),
			        "__ClienteCO",
			            VAR j = [__JobCO]
			            VAR s = [__IdSolucao]
			            VAR c = [__CNPJ]
			            RETURN MAXX ( FILTER ( vCO_Select, [__JobCO] = j && [__IdSolucao] = s && [__CNPJ] = c ), [__ClienteCO] ),
			        "__DataContrato",
			            VAR j = [__JobCO]
			            VAR s = [__IdSolucao]
			            VAR c = [__CNPJ]
			            RETURN MINX ( FILTER ( vCO_Select, [__JobCO] = j && [__IdSolucao] = s && [__CNPJ] = c ), [__DataContrato] ),
			        "__Estimativa",
			            VAR j = [__JobCO]
			            VAR s = [__IdSolucao]
			            VAR c = [__CNPJ]
			            RETURN MAXX ( FILTER ( vCO_Select, [__JobCO] = j && [__IdSolucao] = s && [__CNPJ] = c ), [__Estimativa] )
			    )
			
			VAR vCNPJsOportunidade =
			    DISTINCT ( SELECTCOLUMNS ( vCO_Base, "__CNPJ", [__CNPJ] ) )
			
			/* =========================================================================
			   2) JOBS ATUAIS
			   ========================================================================= */
			VAR vHasAreaFilter = ISFILTERED ( 'JOBS_PRODUTO_AREA'[NOME_AREA] )
			VAR vAreasSelecionadas = VALUES ( 'JOBS_PRODUTO_AREA'[NOME_AREA] )
			
			VAR vJobs_Select =
			    SELECTCOLUMNS (
			        FILTER (
			            CALCULATETABLE (
			                ALLSELECTED ( 'JOBS_PRODUTO_AREA' ),
			                REMOVEFILTERS ( 'JOBS_PRODUTO_AREA'[NOME_AREA] )
			            ),
			            NOT ISBLANK ( 'JOBS_PRODUTO_AREA'[JOB] )
			        ),
			        "__JOB", 'JOBS_PRODUTO_AREA'[JOB],
			        "__BaseJob", 'JOBS_PRODUTO_AREA'[BASE_JOB_ID],
			        "__CNPJ", 'JOBS_PRODUTO_AREA'[CNPJ_JOIN],
			        "__Cliente", COALESCE ( 'JOBS_PRODUTO_AREA'[NOME_CLIENTE], "Sem cliente" ),
			        "__Area", COALESCE ( 'JOBS_PRODUTO_AREA'[NOME_AREA], "Sem área" ),
			        "__ProdutoOp", COALESCE ( 'JOBS_PRODUTO_AREA'[NOME_PRODUTO], "Sem produto operacional" ),
			        "__SubprodutoOp", COALESCE ( 'JOBS_PRODUTO_AREA'[NOME_SUBPRODUTO], "Sem subproduto" ),
			        "__TributoOp", COALESCE ( 'JOBS_PRODUTO_AREA'[NOME_TRIBUTO], "Sem tributo" ),
			        "__Responsavel", COALESCE ( 'JOBS_PRODUTO_AREA'[RESPONSAVEL], "Sem responsável" ),
			        "__Equipe", COALESCE ( 'JOBS_PRODUTO_AREA'[NOME_EQUIPE], "Sem equipe" ),
			        "__DataCadastro", 'JOBS_PRODUTO_AREA'[DATA_CADASTRO],
			        "__Mov", COALESCE ( 'JOBS_PRODUTO_AREA'[TRIBUTO_DATA_ENTRADA], 'JOBS_PRODUTO_AREA'[DATA_CADASTRO] ),
			        "__ValorTributo", COALESCE ( 'JOBS_PRODUTO_AREA'[VALOR_TRIBUTO], 0 ),
			        "__HonorEnc", COALESCE ( 'JOBS_PRODUTO_AREA'[JOB_HONORARIOS_ENCONTRADOS], 0 ),
			        "__HonorAge", COALESCE ( 'JOBS_PRODUTO_AREA'[JOB_HONORARIOS_AGENDADOS], 0 )
			    )
			
			VAR vJobs_LastMove =
			    GROUPBY (
			        vJobs_Select,
			        [__JOB],
			        "__Mov", MAXX ( CURRENTGROUP (), [__Mov] )
			    )
			
			VAR vJobs_LatestRows =
			    NATURALINNERJOIN ( vJobs_LastMove, vJobs_Select )
			
			VAR vJobs_Atual =
			    GROUPBY (
			        vJobs_LatestRows,
			        [__JOB],
			        "__CNPJ", MAXX ( CURRENTGROUP (), [__CNPJ] ),
			        "__BaseJob", MAXX ( CURRENTGROUP (), [__BaseJob] ),
			        "__Cliente", MAXX ( CURRENTGROUP (), [__Cliente] ),
			        "__Area", MAXX ( CURRENTGROUP (), [__Area] ),
			        "__ProdutoOp", MAXX ( CURRENTGROUP (), [__ProdutoOp] ),
			        "__SubprodutoOp", MAXX ( CURRENTGROUP (), [__SubprodutoOp] ),
			        "__TributoOp", MAXX ( CURRENTGROUP (), [__TributoOp] ),
			        "__Responsavel", MAXX ( CURRENTGROUP (), [__Responsavel] ),
			        "__Equipe", MAXX ( CURRENTGROUP (), [__Equipe] ),
			        "__DataCadastro", MAXX ( CURRENTGROUP (), [__DataCadastro] ),
			        "__UltMov", MAXX ( CURRENTGROUP (), [__Mov] ),
			        "__ValorTributo", SUMX ( CURRENTGROUP (), [__ValorTributo] ),
			        "__HonorEnc", SUMX ( CURRENTGROUP (), [__HonorEnc] ),
			        "__HonorAge", SUMX ( CURRENTGROUP (), [__HonorAge] )
			    )
			
			VAR vJobs_Status0 =
			    ADDCOLUMNS (
			        vJobs_Atual,
			        "__Etapa",
			            VAR a = UPPER ( COALESCE ( [__Area], "" ) )
			            RETURN
			                SWITCH (
			                    TRUE (),
			                    CONTAINSSTRING ( a, "DISTRATO" )
			                        || CONTAINSSTRING ( a, "NÃO FATURADO" )
			                        || CONTAINSSTRING ( a, "NAO FATURADO" )
			                        || CONTAINSSTRING ( a, "NÃO APROVADO" )
			                        || CONTAINSSTRING ( a, "NAO APROVADO" )
			                        || CONTAINSSTRING ( a, "NÃO APRESENTADO" )
			                        || CONTAINSSTRING ( a, "NAO APRESENTADO" ), "CANCELADO / PERDIDO",
			                    CONTAINSSTRING ( a, "CRÉDIT" )
			                        || CONTAINSSTRING ( a, "CREDIT" )
			                        || CONTAINSSTRING ( a, "COMPENSA" )
			                        || CONTAINSSTRING ( a, "LIQUID" ), "CRÉDITOS",
			                    CONTAINSSTRING ( a, "FIM" )
			                        || CONTAINSSTRING ( a, "FATUR" ), "FINALIZADO / FATURADO",
			                    CONTAINSSTRING ( a, "DIAGN" )
			                        || CONTAINSSTRING ( a, "ENTREGA" ), "DIAGNÓSTICO",
			                    CONTAINSSTRING ( a, "REUNIÃO" )
			                        || CONTAINSSTRING ( a, "REUNIAO" ), "REUNIÃO TEC",
			                    CONTAINSSTRING ( a, "OPER" )
			                        || CONTAINSSTRING ( a, "PLANILH" )
			                        || CONTAINSSTRING ( a, "RETIFIC" )
			                        || CONTAINSSTRING ( a, "REVISÃO" )
			                        || CONTAINSSTRING ( a, "REVISAO" )
			                        || CONTAINSSTRING ( a, "JURÍD" )
			                        || CONTAINSSTRING ( a, "JURID" )
			                        || CONTAINSSTRING ( a, "MANIPULA" ), "OPERAÇÃO",
			                    CONTAINSSTRING ( a, "CHECKLIST" )
			                        || CONTAINSSTRING ( a, "QUALIDADE" )
			                        || CONTAINSSTRING ( a, "VALIDA" ), "CHECKLIST",
			                    CONTAINSSTRING ( a, "PROCURA" ), "PROCURAÇÃO",
			                    "CADASTRO / OUTROS"
			                )
			    )
			
			VAR vJobs_StatusBase =
			    ADDCOLUMNS (
			        vJobs_Status0,
			        "__Ativo",
			            IF (
			                [__Etapa] = "CRÉDITOS"
			                    || [__Etapa] = "FINALIZADO / FATURADO"
			                    || [__Etapa] = "CANCELADO / PERDIDO",
			                0,
			                1
			            )
			    )
			
			VAR vCO_Keys = DISTINCT ( SELECTCOLUMNS ( vCO_Base, "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			VAR vJobs_Status =
			    FILTER (
			        vJobs_StatusBase,
			        [__CNPJ] & "|" & [__BaseJob] IN vCO_Keys
			            && (
			                NOT vHasAreaFilter
			                    || [__Area] IN vAreasSelecionadas
			                    || [__Etapa] IN vAreasSelecionadas
			            )
			    )
			
			VAR vJobs_UnfilteredForArea =
			    FILTER (
			        vJobs_StatusBase,
			        [__CNPJ] & "|" & [__BaseJob] IN vCO_Keys
			    )
			
			VAR vJobsKeys =
			    DISTINCT ( SELECTCOLUMNS ( vJobs_UnfilteredForArea, "__Key", [__CNPJ] & "|" & [__BaseJob] ) )
			
			/* =========================================================================
			   3) DETALHE: OPORTUNIDADE x JOBS DO CNPJ
			   ========================================================================= */
			VAR vRowsComJob =
			    SELECTCOLUMNS (
			        ADDCOLUMNS (
			            vJobs_Status,
			            "__Produto",
			                VAR c = [__CNPJ]
			                VAR j = [__BaseJob]
			                RETURN COALESCE ( MAXX ( FILTER ( vCO_Base, [__CNPJ] = c && [__JobCO] = j ), [__Produto] ), [__ProdutoOp] ),
			            "__ClienteCO",
			                VAR c = [__CNPJ]
			                VAR j = [__BaseJob]
			                RETURN COALESCE ( MAXX ( FILTER ( vCO_Base, [__CNPJ] = c && [__JobCO] = j ), [__ClienteCO] ), [__Cliente] ),
			            "__JobCO", [__BaseJob],
			            "__DataContrato",
			                VAR c = [__CNPJ]
			                VAR j = [__BaseJob]
			                RETURN MINX ( FILTER ( vCO_Base, [__CNPJ] = c && [__JobCO] = j ), [__DataContrato] ),
			            "__Estimativa",
			                VAR c = [__CNPJ]
			                VAR j = [__BaseJob]
			                RETURN COALESCE ( SUMX ( FILTER ( vCO_Base, [__CNPJ] = c && [__JobCO] = j ), [__Estimativa] ), 0 ),
			            "__StatusMatch", "Com job",
			            "__Falha",
			                SWITCH (
			                    [__Etapa],
			                    "PROCURAÇÃO", "Cobrar procuração",
			                    "CHECKLIST", "Cobrar checklist",
			                    "OPERAÇÃO", "Cobrar operação",
			                    "REUNIÃO TEC", "Cobrar reunião técnica",
			                    "DIAGNÓSTICO", "Cobrar diagnóstico",
			                    "CRÉDITOS", "Acompanhar créditos",
			                    "FINALIZADO / FATURADO", "Acompanhar faturamento",
			                    "CANCELADO / PERDIDO", "Validar cancelado/perdido",
			                    "Verificar cadastro/outros"
			                )
			        ),
			        "__Produto", [__Produto],
			        "__ClienteCO", [__ClienteCO],
			        "__CNPJ", [__CNPJ],
			        "__JobCO", [__JobCO],
			        "__DataContrato", [__DataContrato],
			        "__Estimativa", [__Estimativa],
			        "__JOB", [__JOB],
			        "__ClienteJob", [__Cliente],
			        "__Etapa", [__Etapa],
			        "__Area", [__Area],
			        "__Responsavel", [__Responsavel],
			        "__Equipe", [__Equipe],
			        "__UltMov", [__UltMov],
			        "__ValorTributo", [__ValorTributo],
			        "__HonorEnc", [__HonorEnc],
			        "__HonorAge", [__HonorAge],
			        "__StatusMatch", [__StatusMatch],
			        "__Falha", [__Falha]
			    )
			
			VAR vRowsSemJob =
			    SELECTCOLUMNS (
			        FILTER ( vCO_Base, NOT [__CNPJ] & "|" & [__JobCO] IN vJobsKeys ),
			        "__Produto", [__Produto],
			        "__ClienteCO", [__ClienteCO],
			        "__CNPJ", [__CNPJ],
			        "__JobCO", [__JobCO],
			        "__DataContrato", [__DataContrato],
			        "__Estimativa", [__Estimativa],
			        "__JOB", BLANK (),
			        "__ClienteJob", BLANK (),
			        "__Etapa", "SEM JOB",
			        "__Area", "Sem job encontrado",
			        "__Responsavel", "Sem responsável",
			        "__Equipe", "Sem equipe",
			        "__UltMov", BLANK (),
			        "__ValorTributo", 0,
			        "__HonorEnc", 0,
			        "__HonorAge", 0,
			        "__StatusMatch", "Sem job",
			        "__Falha", "Sem job para o CNPJ da oportunidade"
			    )
			
			VAR vDetalheAll =
			    UNION ( vRowsComJob, vRowsSemJob )
			
			VAR vDetalheTop =
			    TOPN (
			        vLimiteLinhas,
			        vDetalheAll,
			        [__DataContrato], ASC,
			        [__Produto], ASC,
			        [__Etapa], ASC,
			        [__ClienteCO], ASC
			    )
			
			VAR vTotalRows = COUNTROWS ( vDetalheAll )
			VAR vRowsVisiveis = COUNTROWS ( vDetalheTop )
			VAR vEmpresas = COUNTROWS ( DISTINCT ( SELECTCOLUMNS ( vDetalheAll, "__CNPJ", [__CNPJ] ) ) )
			VAR vOportunidades = COUNTROWS ( vCO_Base )
			VAR vJobs = COUNTROWS ( DISTINCT ( SELECTCOLUMNS ( FILTER ( vDetalheAll, NOT ISBLANK ( [__JOB] ) ), "__JOB", [__JOB] ) ) )
			VAR vSemJob = COUNTROWS ( FILTER ( vDetalheAll, [__Etapa] = "SEM JOB" ) )
			
			/* =========================================================================
			   4) HTML
			   ========================================================================= */
			VAR vCSS =
			"
			<style>
			:root{--bg:#050A0F;--panel:#0E1720;--panel2:#111D27;--line:rgba(255,255,255,.075);--gold:#F4D9A9;--gold2:#D5AE77;--teal:#8BE0D1;--text:#F4F7FA;--muted:#A8B4C0;--dim:#6D7A86;--red:#FF9C93;--green:#7BEEA6;--blue:#9CCBFF}
			html,body{margin:0;padding:0;background:var(--bg);color:var(--text);font-family:'Segoe UI',Arial,sans-serif;overflow:hidden}
			.wrap{height:calc(100vh - 2px);box-sizing:border-box;padding:16px;border-radius:20px;border:1px solid rgba(213,174,119,.28);background:radial-gradient(circle at 0 0,rgba(213,174,119,.15),transparent 30%),radial-gradient(circle at 100% 0,rgba(139,224,209,.09),transparent 28%),linear-gradient(135deg,#101A24,#050A0F);box-shadow:0 22px 60px rgba(0,0,0,.45);display:flex;flex-direction:column}
			.head{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:12px}.title{color:var(--gold);font-size:24px;font-weight:1000;letter-spacing:.07em;text-transform:uppercase}.subtitle{color:var(--muted);font-size:12.5px;font-weight:850;margin-top:5px}.period{color:var(--teal);font-size:12.5px;font-weight:1000;border:1px solid rgba(139,224,209,.32);background:rgba(139,224,209,.08);border-radius:999px;padding:8px 12px;white-space:nowrap}
			.kpis{display:grid;grid-template-columns:repeat(5,minmax(145px,1fr));gap:10px;margin-bottom:12px}.kpi{position:relative;padding:13px 13px 12px;border-radius:15px;background:linear-gradient(155deg,rgba(18,31,42,.98),rgba(9,15,21,.96));border:1px solid rgba(255,255,255,.10);box-shadow:0 12px 24px rgba(0,0,0,.24);overflow:hidden;transition:transform .15s ease,border-color .15s ease,box-shadow .15s ease}.kpi:before{content:'';position:absolute;left:14px;top:0;width:42px;height:4px;border-radius:0 0 10px 10px;background:linear-gradient(90deg,var(--gold),var(--teal))}.kpi:hover{transform:translateY(-3px);border-color:rgba(244,217,169,.42);box-shadow:0 18px 34px rgba(0,0,0,.32)}.kpi span{display:block;color:var(--muted);font-size:10.5px;font-weight:1000;text-transform:uppercase;letter-spacing:.08em}.kpi b{display:block;color:var(--gold);font-size:27px;font-weight:1000;margin-top:5px;line-height:1}
			.controls{display:flex;gap:10px;margin-bottom:12px}.search{flex:1;border:1px solid rgba(213,174,119,.24);background:#071018;color:#fff;border-radius:12px;padding:11px 14px;font-size:14px;font-weight:800;outline:none;box-shadow:inset 0 1px 0 rgba(255,255,255,.04);transition:border-color .15s ease,box-shadow .15s ease}.search:focus{border-color:rgba(139,224,209,.62);box-shadow:0 0 0 3px rgba(139,224,209,.08),inset 0 1px 0 rgba(255,255,255,.06)}.btn{border:1px solid rgba(213,174,119,.34);background:rgba(213,174,119,.10);color:var(--gold);border-radius:12px;padding:10px 15px;font-size:12px;font-weight:1000;letter-spacing:.06em;text-transform:uppercase;cursor:pointer;transition:transform .15s ease,background .15s ease}.btn:hover{transform:translateY(-2px);background:rgba(213,174,119,.18)}
			.table-wrap{flex:1;min-height:0;overflow:auto;border:1px solid rgba(213,174,119,.16);border-radius:16px;background:rgba(255,255,255,.022);box-shadow:inset 0 1px 0 rgba(255,255,255,.035)}.table-wrap::-webkit-scrollbar{width:12px;height:12px}.table-wrap::-webkit-scrollbar-track{background:#071018}.table-wrap::-webkit-scrollbar-thumb{background:linear-gradient(180deg,rgba(244,217,169,.78),rgba(139,224,209,.44));border:3px solid #071018;border-radius:999px}
			table{border-collapse:collapse;width:100%;min-width:1120px;table-layout:fixed}th{position:sticky;top:0;z-index:4;background:linear-gradient(180deg,#111D27,#0B141D);color:var(--gold2);font-size:11px;font-weight:1000;text-transform:uppercase;letter-spacing:.075em;padding:12px 10px;text-align:left;border-bottom:1px solid rgba(213,174,119,.25);white-space:nowrap}th:nth-child(1){width:27%}th:nth-child(2){width:25%}th:nth-child(3){width:13%}th:nth-child(4){width:10%}th:nth-child(5){width:12%}th:nth-child(6){width:13%}
			td{font-size:12.5px;font-weight:820;color:#EEF3F8;padding:11px 10px;border-bottom:1px solid rgba(255,255,255,.055);vertical-align:middle;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}tr{transition:background .14s ease,transform .14s ease}tr:hover td{background:rgba(213,174,119,.075)}tr:hover{transform:translateX(2px)}td.prod{font-weight:1000;color:#FFF2DE}td.client{color:#E8EEF5}td.cnpj{font-family:Consolas,'Courier New',monospace;color:#B9C7D5;font-size:12px}td.date{font-family:Consolas,'Courier New',monospace;color:#B9C7D5;font-size:12px;text-align:center}td.job{font-weight:1000;color:var(--gold);text-align:center}td.area{color:#CAD4DF}.chip{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:6px 10px;font-size:10.5px;font-weight:1000;text-transform:uppercase;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.055);min-width:94px}.proc{color:#9CCBFF;border-color:rgba(156,203,255,.22)}.check{color:#F4D9A9;border-color:rgba(244,217,169,.25)}.oper{color:#FFCF87;border-color:rgba(255,207,135,.23)}.reu{color:#8BE0D1;border-color:rgba(139,224,209,.25)}.diag{color:#B9F0FF;border-color:rgba(185,240,255,.22)}			.cred{color:#7BEEA6;border-color:rgba(123,238,166,.24)}.fim{color:#B4BBC4;border-color:rgba(180,187,196,.22)}.bad{color:var(--red);border-color:rgba(255,156,147,.25)}.foot{margin-top:9px;color:var(--dim);font-size:11.5px;font-weight:850}
			
			/* v4 - fontes maiores para melhor leitura */
			.wrap{padding:18px!important}
			.title{font-size:30px!important}
			.subtitle{font-size:16px!important;line-height:1.25!important}
			.period{font-size:15px!important;padding:10px 14px!important}
			.kpis{gap:12px!important;margin-bottom:14px!important}
			.kpi{padding:16px 16px 15px!important;border-radius:17px!important}
			.kpi span{font-size:13px!important}
			.kpi b{font-size:36px!important;margin-top:7px!important}
			.controls{margin-bottom:14px!important}
			.search{font-size:17px!important;height:46px!important;padding:0 16px!important}
			.btn{font-size:15px!important;height:46px!important;padding:0 18px!important}
			table{min-width:1280px!important}
			th{font-size:14px!important;padding:15px 13px!important;letter-spacing:.07em!important}
			td{font-size:16px!important;padding:15px 13px!important;line-height:1.25!important}
			td.cnpj,td.date{font-size:15px!important}
			td.job{font-size:16px!important}
			.chip{font-size:13px!important;padding:8px 12px!important;min-width:120px!important}
			.foot{font-size:14px!important;margin-top:11px!important}
			.table-wrap{border-radius:18px!important}
			
			/* v5 - filtros por coluna e sem rolagem horizontal */
			.controls.doc-filters{display:grid!important;grid-template-columns:1.25fr repeat(6,minmax(0,1fr)) auto!important;gap:9px!important;margin-bottom:12px!important;align-items:end!important}
			.doc-filter{display:flex;flex-direction:column;gap:5px;min-width:0}.doc-filter label{color:var(--gold2);font-size:11px;font-weight:1000;letter-spacing:.075em;text-transform:uppercase}.doc-filter input,.doc-filter select{height:42px;width:100%;box-sizing:border-box;border:1px solid rgba(213,174,119,.28);background:#071018;color:#F4F7FA;border-radius:11px;padding:0 11px;font-size:13px;font-weight:850;outline:none;box-shadow:inset 0 1px 0 rgba(255,255,255,.04)}.doc-filter input:focus,.doc-filter select:focus{border-color:rgba(139,224,209,.62);box-shadow:0 0 0 3px rgba(139,224,209,.08),inset 0 1px 0 rgba(255,255,255,.06)}.doc-actions{display:flex;gap:8px;align-items:end;justify-content:flex-end}.doc-actions .btn{height:42px!important;font-size:12px!important;padding:0 13px!important;white-space:nowrap}
			.table-wrap{overflow-y:auto!important;overflow-x:hidden!important}
			table{width:100%!important;min-width:0!important;table-layout:fixed!important}
			th:nth-child(1){width:18%!important}th:nth-child(2){width:18%!important}th:nth-child(3){width:13%!important}th:nth-child(4){width:11%!important}th:nth-child(5){width:12%!important}th:nth-child(6){width:14%!important}th:nth-child(7){width:14%!important}
			th,td{box-sizing:border-box!important}.table-wrap::-webkit-scrollbar:horizontal{height:0!important;display:none!important}
			@media(max-width:1200px){.controls.doc-filters{grid-template-columns:repeat(4,minmax(0,1fr))!important}.doc-actions{justify-content:flex-start}}
			
			</style>
			<script>
			function normDoc(s){
			 try{return (s||'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
			 catch(e){return (s||'').toString().toLowerCase();}
			}
			function valDoc(id){var el=document.getElementById(id);return el?normDoc(el.value):'';}
			function filtrarDoc(){
			 var q=valDoc('q');
			 var fProd=valDoc('fDocProduto');
			 var fCliente=valDoc('fDocCliente');
			 var fCnpj=valDoc('fDocCnpj');
			 var fJob=valDoc('fDocJob');
			 var fEtapa=valDoc('fDocEtapa');
			 var fArea=valDoc('fDocArea');
			 var rows=document.querySelectorAll('.linha');
			 var n=0;
			 rows.forEach(function(r){
			   var ok=true;
			   var txt=normDoc(r.textContent);
			   if(q && txt.indexOf(q)===-1) ok=false;
			   if(fProd && normDoc(r.getAttribute('data-prod')).indexOf(fProd)===-1) ok=false;
			   if(fCliente && normDoc(r.getAttribute('data-cliente')).indexOf(fCliente)===-1) ok=false;
			   if(fCnpj && normDoc(r.getAttribute('data-cnpj')).indexOf(fCnpj)===-1) ok=false;
			   if(fJob && normDoc(r.getAttribute('data-job')).indexOf(fJob)===-1) ok=false;
			   if(fEtapa && normDoc(r.getAttribute('data-etapa')).indexOf(fEtapa)===-1) ok=false;
			   if(fArea && normDoc(r.getAttribute('data-area')).indexOf(fArea)===-1) ok=false;
			   r.style.display=ok?'':'none';
			   if(ok)n++;
			 });
			 var hasFilter = (q || fProd || fCliente || fCnpj || fJob || fEtapa || fArea);
			 var el=document.getElementById('vis');
			 if(el) el.textContent = hasFilter ? n : el.getAttribute('data-total');
			 var empty=document.getElementById('docNoMatch'); if(empty) empty.style.display=n===0?'block':'none';
			}
			function limparFiltrosDoc(){
			 ['q','fDocProduto','fDocCliente','fDocCnpj','fDocJob','fDocEtapa','fDocArea'].forEach(function(id){var el=document.getElementById(id); if(el) el.value='';});
			 filtrarDoc();
			}
			function copiarTabela(){
			 var rows=document.querySelectorAll('tr');
			 var out=[];
			 rows.forEach(function(r){
			   if(r.className==='linha' && r.style.display==='none') return;
			   var cells=r.querySelectorAll('th,td');
			   var vals=[];
			   cells.forEach(function(c){
			     var val = c.textContent.trim().replace(/\s+/g,' ');
			     if ((c.classList && c.classList.contains('cnpj')) || c.className === 'cnpj') {
			       var clean = val.replace(/\D/g, '');
			       if (clean.length > 0) {
			         if (clean.length < 14) {
			           clean = clean.padStart(14, '0');
			         }
			         val = clean.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/, '$1.$2.$3/$4-$5');
			       }
			     }
			     vals.push(val);
			   });
			   out.push(vals.join('\t'));
			 });
			 var ta=document.createElement('textarea'); ta.value=out.join('\r\n'); document.body.appendChild(ta); ta.select(); document.execCommand('copy'); document.body.removeChild(ta);
			 var b=document.getElementById('copy'); var old=b.innerHTML; b.innerHTML='Copiado'; setTimeout(function(){b.innerHTML=old},1800);
			}
			setTimeout(filtrarDoc,100);
			</script>
			"
			
			VAR vRowsHTML =
			    CONCATENATEX (
			        vDetalheTop,
			        VAR cls =
			            SWITCH (
			                [__Etapa],
			                "PROCURAÇÃO", "proc",
			                "CHECKLIST", "check",
			                "OPERAÇÃO", "oper",
			                "REUNIÃO TEC", "reu",
			                "DIAGNÓSTICO", "diag",
			                "CRÉDITOS", "cred",
			                "FINALIZADO / FATURADO", "fim",
			                "SEM JOB", "bad",
			                "bad"
			            )
			        VAR vJobTxt = IF ( ISBLANK ( [__JOB] ), "-", [__JOB] )
			        VAR vDataTxt = IF ( ISBLANK ( [__DataContrato] ), "-", FORMAT ( [__DataContrato], "dd/MM/yyyy" ) )
			        VAR vProdAttr = SUBSTITUTE ( [__Produto], "'", "&#39;" )
			        VAR vClienteAttr = SUBSTITUTE ( [__ClienteCO], "'", "&#39;" )
			        VAR vCnpjAttr = SUBSTITUTE ( [__CNPJ], "'", "&#39;" )
			        VAR vJobAttr = SUBSTITUTE ( vJobTxt, "'", "&#39;" )
			        VAR vEtapaAttr = SUBSTITUTE ( [__Etapa], "'", "&#39;" )
			        VAR vAreaAttr = SUBSTITUTE ( [__Area], "'", "&#39;" )
			        RETURN
			            "<tr class='linha' data-prod='" & vProdAttr & "' data-cliente='" & vClienteAttr & "' data-cnpj='" & vCnpjAttr & "' data-job='" & vJobAttr & "' data-etapa='" & vEtapaAttr & "' data-area='" & vAreaAttr & "'>"
			                & "<td class='prod' title='" & [__Produto] & "'>" & [__Produto] & "</td>"
			                & "<td class='client' title='" & [__ClienteCO] & "'>" & [__ClienteCO] & "</td>"
			                & "<td class='cnpj'>" & [__CNPJ] & "</td>"
			                & "<td class='date'>" & vDataTxt & "</td>"
			                & "<td class='job'>" & vJobTxt & "</td>"
			                & "<td><span class='chip " & cls & "'>" & [__Etapa] & "</span></td>"
			                & "<td class='area' title='" & [__Area] & "'>" & [__Area] & "</td>"
			            & "</tr>",
			        "",
			        [__DataContrato], ASC,
			        [__Produto], ASC,
			        [__Etapa], ASC,
			        [__ClienteCO], ASC
			    )
			
			RETURN
			    vCSS
			        & "<div class='wrap'>"
			            & "<div class='head'><div><div class='title'>Documentação Oportunidades x Jobs</div><div class='subtitle'>Detalhamento enxuto por oportunidade, CNPJ, job operacional e etapa atual.</div></div><div class='period'>" & vPeriodo & "</div></div>"
			            & "<div class='kpis'><div class='kpi'><span>Empresas</span><b>" & FORMAT ( vEmpresas, vIntFormat ) & "</b></div><div class='kpi'><span>Oportunidades</span><b>" & FORMAT ( vOportunidades, vIntFormat ) & "</b></div><div class='kpi'><span>Jobs</span><b>" & FORMAT ( vJobs, vIntFormat ) & "</b></div><div class='kpi'><span>Sem Job</span><b>" & FORMAT ( vSemJob, vIntFormat ) & "</b></div><div class='kpi'><span>Linhas</span><b><span id='vis' data-total='" & FORMAT ( vTotalRows, vIntFormat ) & "'>" & FORMAT ( vTotalRows, vIntFormat ) & "</span></b></div></div>"
			            & "<div class='controls doc-filters'><div class='doc-filter'><label>Busca geral</label><input id='q' class='search' oninput='filtrarDoc()' placeholder='Buscar em todas as colunas'></div><div class='doc-filter'><label>Produto</label><input id='fDocProduto' oninput='filtrarDoc()' placeholder='Produto'></div><div class='doc-filter'><label>Cliente</label><input id='fDocCliente' oninput='filtrarDoc()' placeholder='Cliente'></div><div class='doc-filter'><label>CNPJ</label><input id='fDocCnpj' oninput='filtrarDoc()' placeholder='CNPJ'></div><div class='doc-filter'><label>Job</label><input id='fDocJob' oninput='filtrarDoc()' placeholder='Job'></div><div class='doc-filter'><label>Etapa</label><select id='fDocEtapa' onchange='filtrarDoc()'><option value=''>Todas</option><option value='PROCURAÇÃO'>Procuração</option><option value='CHECKLIST'>Checklist</option><option value='OPERAÇÃO'>Operação</option><option value='REUNIÃO TEC'>Reunião Tec</option><option value='DIAGNÓSTICO'>Diagnóstico</option><option value='CRÉDITOS'>Créditos</option><option value='FINALIZADO / FATURADO'>Finalizado</option><option value='SEM JOB'>Sem Job</option></select></div><div class='doc-filter'><label>Área</label><input id='fDocArea' oninput='filtrarDoc()' placeholder='Área atual'></div><div class='doc-actions'><button class='btn' onclick='limparFiltrosDoc()'>Limpar</button><button id='copy' class='btn' onclick='copiarTabela()'>Copiar</button></div></div>"
			            & "<div class='table-wrap'><table><thead><tr>"
			                & "<th>Produto</th><th>Cliente</th><th>CNPJ</th><th>Data</th><th>Job Oper.</th><th>Etapa</th><th>Área Atual</th>"
			            & "</tr></thead><tbody>" & IF ( ISBLANK ( vRowsHTML ), "<tr><td colspan='7'>Nenhum registro encontrado.</td></tr>", vRowsHTML ) & "</tbody></table><div id='docNoMatch' class='empty' style='display:none'>Nenhum registro encontrado para os filtros internos.</div></div>"
			            & "<div class='foot'>Exibindo " & FORMAT ( vRowsVisiveis, vIntFormat ) & " de " & FORMAT ( vTotalRows, vIntFormat ) & " linhas. Se o total for maior que o limite, use slicers para reduzir o recorte.</div>"
			        & "</div>"
			
			```
		displayFolder: HTML
		lineageTag: 7cc4cf4f-59eb-4360-8f7e-9a14c4534d03

	/// Visual principal com 8 colunas: PRODUTOS + 7 etapas. Journey 360 como base para stages e cards.
	measure 'HTML Macro Oportunidades x Jobs | Tela Principal' = ```
			
			VAR vIntFormat = "#,##0"
			VAR vPctFormat = "0.0%"
			VAR vMoneyFormat = "R$ #,##0"
			VAR vTopProdutos = 40
			VAR vTopDetalhes = 12
			
			VAR vCalendarStart = MIN ( 'dCalendar'[Date] )
			VAR vCalendarEnd = MAX ( 'dCalendar'[Date] )
			VAR vHasCalendarFilter =
			    COUNTROWS ( 'dCalendar' ) < COUNTROWS ( ALL ( 'dCalendar' ) )
			
			VAR vPeriodo =
			    IF (
			        vHasCalendarFilter,
			        FORMAT ( vCalendarStart, "dd/MM/yyyy" ) & " a " & FORMAT ( vCalendarEnd, "dd/MM/yyyy" ),
			        "Todo o período"
			    )
			
			/* =========================================================================
			   1) BASE DE OPORTUNIDADES
			   Fonte: CONTRATOS_OPORTUNIDADES
			   Produto da tela: CONTRATOS_OPORTUNIDADES[oportunidade]
			   ========================================================================= */
			VAR vCO_Raw =
			    FILTER (
			        ALLSELECTED ( CONTRATOS_OPORTUNIDADES ),
			        NOT vHasCalendarFilter
			            || (
			                CONTRATOS_OPORTUNIDADES[data_contrato] >= vCalendarStart
			                    && CONTRATOS_OPORTUNIDADES[data_contrato] < vCalendarEnd + 1
			            )
			    )
			
			VAR vCO_Select =
			    SELECTCOLUMNS (
			        vCO_Raw,
			        "__JobCO", CONTRATOS_OPORTUNIDADES[job],
			        "__IdSolucao", CONTRATOS_OPORTUNIDADES[id_solucao],
			        "__CNPJ", CONTRATOS_OPORTUNIDADES[CNPJ_JOIN],
			        "__ClienteCO", COALESCE ( CONTRATOS_OPORTUNIDADES[razao_social], "Sem cliente" ),
			        "__Produto", TRIM ( SUBSTITUTE ( COALESCE ( CONTRATOS_OPORTUNIDADES[oportunidade], "Sem produto" ), "_", " " ) ),
			        "__DataContrato", CONTRATOS_OPORTUNIDADES[data_contrato],
			        "__Estimativa", COALESCE ( CONTRATOS_OPORTUNIDADES[estimativa], 0 )
			    )
			
			/* Uma oportunidade = job + id_solucao + CNPJ */
			VAR vCO_Base =
			    ADDCOLUMNS (
			        SUMMARIZE ( vCO_Select, [__JobCO], [__IdSolucao], [__CNPJ] ),
			        "__Produto",
			            VAR j = [__JobCO]
			            VAR s = [__IdSolucao]
			            VAR c = [__CNPJ]
			            RETURN MAXX ( FILTER ( vCO_Select, [__JobCO] = j && [__IdSolucao] = s && [__CNPJ] = c ), [__Produto] ),
			        "__ClienteCO",
			            VAR j = [__JobCO]
			            VAR s = [__IdSolucao]
			            VAR c = [__CNPJ]
			            RETURN MAXX ( FILTER ( vCO_Select, [__JobCO] = j && [__IdSolucao] = s && [__CNPJ] = c ), [__ClienteCO] ),
			        "__DataContrato",
			            VAR j = [__JobCO]
			            VAR s = [__IdSolucao]
			            VAR c = [__CNPJ]
			            RETURN MINX ( FILTER ( vCO_Select, [__JobCO] = j && [__IdSolucao] = s && [__CNPJ] = c ), [__DataContrato] ),
			        "__Estimativa",
			            VAR j = [__JobCO]
			            VAR s = [__IdSolucao]
			            VAR c = [__CNPJ]
			            RETURN MAXX ( FILTER ( vCO_Select, [__JobCO] = j && [__IdSolucao] = s && [__CNPJ] = c ), [__Estimativa] )
			    )
			
			VAR vCNPJsOportunidade =
			    DISTINCT ( SELECTCOLUMNS ( vCO_Base, "__CNPJ", [__CNPJ] ) )
			
			VAR vHasCOFilter =
			    vHasCalendarFilter
			        || ISFILTERED ( CONTRATOS_OPORTUNIDADES[oportunidade] )
			        || ISFILTERED ( CONTRATOS_OPORTUNIDADES[razao_social] )
			        || ISFILTERED ( CONTRATOS_OPORTUNIDADES[cnpj] )
			        || ISFILTERED ( CONTRATOS_OPORTUNIDADES[job] )
			        || ISFILTERED ( CONTRATOS_OPORTUNIDADES[id_solucao] )
			        || ISFILTERED ( dCNPJ[CNPJ_JOIN] )
			        || ISFILTERED ( CONTRATOS_OPORTUNIDADES[CNPJ_JOIN] )
			
			/* =========================================================================
			   2) BASE DE JOBS COMPLETA
			   Fonte: JOBS_PRODUTO_AREA
			   Regra: status atual = última linha por JOB
			   ========================================================================= */
			VAR vHasAreaFilter = ISFILTERED ( 'JOBS_PRODUTO_AREA'[NOME_AREA] )
			VAR vAreasSelecionadas = VALUES ( 'JOBS_PRODUTO_AREA'[NOME_AREA] )
			
			VAR vJobs_Select =
			    SELECTCOLUMNS (
			        FILTER (
			            CALCULATETABLE (
			                ALLSELECTED ( 'JOBS_PRODUTO_AREA' ),
			                REMOVEFILTERS ( 'JOBS_PRODUTO_AREA'[NOME_AREA] )
			            ),
			            NOT ISBLANK ( 'JOBS_PRODUTO_AREA'[JOB] )
			        ),
			        "__JOB", 'JOBS_PRODUTO_AREA'[JOB],
			        "__BaseJob", 'JOBS_PRODUTO_AREA'[BASE_JOB_ID],
			        "__CNPJ", 'JOBS_PRODUTO_AREA'[CNPJ_JOIN],
			        "__Cliente", COALESCE ( 'JOBS_PRODUTO_AREA'[NOME_CLIENTE], "Sem cliente" ),
			        "__Area", COALESCE ( 'JOBS_PRODUTO_AREA'[NOME_AREA], "Sem área" ),
			        "__ProdutoOp", COALESCE ( 'JOBS_PRODUTO_AREA'[NOME_PRODUTO], "Sem produto operacional" ),
			        "__SubprodutoOp", COALESCE ( 'JOBS_PRODUTO_AREA'[NOME_SUBPRODUTO], "Sem subproduto" ),
			        "__TributoOp", COALESCE ( 'JOBS_PRODUTO_AREA'[NOME_TRIBUTO], "Sem tributo" ),
			        "__Responsavel", COALESCE ( 'JOBS_PRODUTO_AREA'[RESPONSAVEL], "Sem responsável" ),
			        "__Equipe", COALESCE ( 'JOBS_PRODUTO_AREA'[NOME_EQUIPE], "Sem equipe" ),
			        "__DataCadastro", 'JOBS_PRODUTO_AREA'[DATA_CADASTRO],
			        "__Mov", COALESCE ( 'JOBS_PRODUTO_AREA'[TRIBUTO_DATA_ENTRADA], 'JOBS_PRODUTO_AREA'[DATA_CADASTRO] ),
			        "__ValorTributo", COALESCE ( 'JOBS_PRODUTO_AREA'[VALOR_TRIBUTO], 0 ),
			        "__HonorEnc", COALESCE ( 'JOBS_PRODUTO_AREA'[JOB_HONORARIOS_ENCONTRADOS], 0 ),
			        "__HonorAge", COALESCE ( 'JOBS_PRODUTO_AREA'[JOB_HONORARIOS_AGENDADOS], 0 )
			    )
			
			VAR vJobs_LastMove =
			    GROUPBY (
			        vJobs_Select,
			        [__JOB],
			        "__Mov", MAXX ( CURRENTGROUP (), [__Mov] )
			    )
			
			VAR vJobs_LatestRows =
			    NATURALINNERJOIN ( vJobs_LastMove, vJobs_Select )
			
			VAR vJobs_Atual =
			    GROUPBY (
			        vJobs_LatestRows,
			        [__JOB],
			        "__CNPJ", MAXX ( CURRENTGROUP (), [__CNPJ] ),
			        "__BaseJob", MAXX ( CURRENTGROUP (), [__BaseJob] ),
			        "__Cliente", MAXX ( CURRENTGROUP (), [__Cliente] ),
			        "__Area", MAXX ( CURRENTGROUP (), [__Area] ),
			        "__ProdutoOp", MAXX ( CURRENTGROUP (), [__ProdutoOp] ),
			        "__SubprodutoOp", MAXX ( CURRENTGROUP (), [__SubprodutoOp] ),
			        "__TributoOp", MAXX ( CURRENTGROUP (), [__TributoOp] ),
			        "__Responsavel", MAXX ( CURRENTGROUP (), [__Responsavel] ),
			        "__Equipe", MAXX ( CURRENTGROUP (), [__Equipe] ),
			        "__DataCadastro", MAXX ( CURRENTGROUP (), [__DataCadastro] ),
			        "__UltMov", MAXX ( CURRENTGROUP (), [__Mov] ),
			        "__ValorTributo", SUMX ( CURRENTGROUP (), [__ValorTributo] ),
			        "__HonorEnc", SUMX ( CURRENTGROUP (), [__HonorEnc] ),
			        "__HonorAge", SUMX ( CURRENTGROUP (), [__HonorAge] )
			    )
			
			VAR vJobs_Status0 =
			    ADDCOLUMNS (
			        vJobs_Atual,
			        "__Etapa",
			            VAR a = UPPER ( COALESCE ( [__Area], "" ) )
			            RETURN
			                SWITCH (
			                    TRUE (),
			                    CONTAINSSTRING ( a, "DISTRATO" )
			                        || CONTAINSSTRING ( a, "NÃO FATURADO" )
			                        || CONTAINSSTRING ( a, "NAO FATURADO" )
			                        || CONTAINSSTRING ( a, "NÃO APROVADO" )
			                        || CONTAINSSTRING ( a, "NAO APROVADO" )
			                        || CONTAINSSTRING ( a, "NÃO APRESENTADO" )
			                        || CONTAINSSTRING ( a, "NAO APRESENTADO" ), "CANCELADO / PERDIDO",
			                    CONTAINSSTRING ( a, "CRÉDIT" )
			                        || CONTAINSSTRING ( a, "CREDIT" )
			                        || CONTAINSSTRING ( a, "COMPENSA" )
			                        || CONTAINSSTRING ( a, "LIQUID" ), "CRÉDITOS",
			                    CONTAINSSTRING ( a, "FIM" )
			                        || CONTAINSSTRING ( a, "FATUR" ), "FINALIZADO / FATURADO",
			                    CONTAINSSTRING ( a, "DIAGN" )
			                        || CONTAINSSTRING ( a, "ENTREGA" ), "DIAGNÓSTICO",
			                    CONTAINSSTRING ( a, "REUNIÃO" )
			                        || CONTAINSSTRING ( a, "REUNIAO" ), "REUNIÃO TEC",
			                    CONTAINSSTRING ( a, "OPER" )
			                        || CONTAINSSTRING ( a, "PLANILH" )
			                        || CONTAINSSTRING ( a, "RETIFIC" )
			                        || CONTAINSSTRING ( a, "REVISÃO" )
			                        || CONTAINSSTRING ( a, "REVISAO" )
			                        || CONTAINSSTRING ( a, "JURÍD" )
			                        || CONTAINSSTRING ( a, "JURID" )
			                        || CONTAINSSTRING ( a, "MANIPULA" ), "OPERAÇÃO",
			                    CONTAINSSTRING ( a, "CHECKLIST" )
			                        || CONTAINSSTRING ( a, "QUALIDADE" )
			                        || CONTAINSSTRING ( a, "VALIDA" ), "CHECKLIST",
			                    CONTAINSSTRING ( a, "PROCURA" ), "PROCURAÇÃO",
			                    "CADASTRO / OUTROS"
			                )
			    )
			
			VAR vJobs_StatusBase =
			    ADDCOLUMNS (
			        vJobs_Status0,
			        "__Ativo",
			            IF (
			                [__Etapa] = "CRÉDITOS"
			                    || [__Etapa] = "FINALIZADO / FATURADO"
			                    || [__Etapa] = "CANCELADO / PERDIDO",
			                0,
			                1
			            )
			    )
			
			VAR vJobs_Status =
			    FILTER (
			        vJobs_StatusBase,
			        NOT vHasAreaFilter
			            || [__Area] IN vAreasSelecionadas
			            || [__Etapa] IN vAreasSelecionadas
			    )
			
			/* Cards: JOBS partem sempre dos CNPJs das oportunidades no recorte atual. */
			VAR vCO_Keys = DISTINCT ( SELECTCOLUMNS ( vCO_Base, "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			VAR vJobs_Cards =
			    FILTER (
			        vJobs_Status,
			        [__CNPJ] & "|" & [__BaseJob] IN vCO_Keys
			    )
			
			VAR vEmpresas = COUNTROWS ( DISTINCT ( SELECTCOLUMNS ( vCO_Base, "__CNPJ", [__CNPJ] ) ) )
			VAR vJobsTotais = COUNTROWS ( vJobs_Cards )
			VAR vJobsAtivos = COUNTROWS ( FILTER ( vJobs_Cards, [__Ativo] = 1 ) )
			VAR vOportunidades = COUNTROWS ( vCO_Base )
			
			/* =========================================================================
			   3) RESUMO POR PRODUTO / OPORTUNIDADE
			   ========================================================================= */
			VAR vProdutos =
			    SUMMARIZE ( vCO_Base, [__Produto] )
			
			VAR vProductSummary =
			    ADDCOLUMNS (
			        vProdutos,
			        "__Empresas",
			            VAR p = [__Produto]
			            RETURN COUNTROWS ( DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__CNPJ", [__CNPJ] ) ) ),
			        "__Oportunidades",
			            VAR p = [__Produto]
			            RETURN COUNTROWS ( FILTER ( vCO_Base, [__Produto] = p ) ),
			        "__Estimativa",
			            VAR p = [__Produto]
			            RETURN SUMX ( FILTER ( vCO_Base, [__Produto] = p ), [__Estimativa] ),
			        "__Jobs",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN COUNTROWS ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys ) ),
			        "__Ativos",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN COUNTROWS ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys && [__Ativo] = 1 ) ),
			        "__CadastroOutros",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN COUNTROWS ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys && [__Etapa] = "CADASTRO / OUTROS" ) ),
			        "__Procuracao",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN COUNTROWS ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys && [__Etapa] = "PROCURAÇÃO" ) ),
			        "__Checklist",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN COUNTROWS ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys && [__Etapa] = "CHECKLIST" ) ),
			        "__Operacao",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN COUNTROWS ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys && [__Etapa] = "OPERAÇÃO" ) ),
			        "__Reuniao",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN COUNTROWS ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys && [__Etapa] = "REUNIÃO TEC" ) ),
			        "__Diagnostico",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN COUNTROWS ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys && [__Etapa] = "DIAGNÓSTICO" ) ),
			        "__Creditos",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN COUNTROWS ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys && [__Etapa] = "CRÉDITOS" ) ),
			        "__Finalizado",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN COUNTROWS ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys && [__Etapa] = "FINALIZADO / FATURADO" ) ),
			        "__Cancelado",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN COUNTROWS ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys && [__Etapa] = "CANCELADO / PERDIDO" ) ),
			        "__CreditosValor",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN SUMX ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys ), [__ValorTributo] ),
			        "__HonorEstimado",
			            VAR p = [__Produto]
			            RETURN SUMX ( FILTER ( vCO_Base, [__Produto] = p ), [__Estimativa] ),
			        "__HonorEncontrado",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            RETURN SUMX ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys ), [__HonorEnc] ),
			        "__SemJob",
			            VAR p = [__Produto]
			            VAR keys = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__Key", [__CNPJ] & "|" & [__JobCO] ) )
			            VAR keysJobs = DISTINCT ( SELECTCOLUMNS ( FILTER ( vJobs_Status, [__CNPJ] & "|" & [__BaseJob] IN keys ), "__Key", [__CNPJ] & "|" & [__BaseJob] ) )
			            RETURN COUNTROWS ( FILTER ( FILTER ( vCO_Base, [__Produto] = p ), NOT [__CNPJ] & "|" & [__JobCO] IN keysJobs ) )
			    )
			
			VAR vProductTop =
			    TOPN (
			        vTopProdutos,
			        vProductSummary,
			        [__SemJob], DESC,
			        [__Oportunidades], DESC,
			        [__Jobs], DESC,
			        [__Produto], ASC
			    )
			
			
			/* =========================================================================
			   4) FILTROS INTERNOS DO HTML
			   ========================================================================= */
			VAR vProdutoOptions =
			    CONCATENATEX (
			        vProductTop,
			        "<option value='" & SUBSTITUTE ( LOWER ( [__Produto] ), "'", "" ) & "'>" & [__Produto] & "</option>",
			        "",
			        [__Produto], ASC
			    )
			
			VAR vPeriodTable =
			    DISTINCT (
			        SELECTCOLUMNS (
			            vCO_Base,
			            "__YM", FORMAT ( [__DataContrato], "yyyy-MM" ),
			            "__Label", FORMAT ( [__DataContrato], "[$-pt-BR]mmm/yyyy" )
			        )
			    )
			
			VAR vPeriodOptions =
			    CONCATENATEX (
			        vPeriodTable,
			        "<option value='" & [__YM] & "'>" & [__Label] & "</option>",
			        "",
			        [__YM], ASC
			    )
			
			/* =========================================================================
			   5) HTML / ESTILO
			   ========================================================================= */
			VAR vCSS =
			"
			<style>
			:root{--bg:#060A0F;--panel:#0E1720;--panel2:#121F2A;--line:rgba(255,255,255,.08);--gold:#F4D9A9;--gold2:#D5AE77;--teal:#8BE0D1;--text:#F4F7FA;--muted:#A8B4C0;--dim:#6D7A86;--red:#FF9C93;--green:#7BEEA6;--blue:#9CCBFF}
			.diag-wrap{font-family:'Segoe UI',Arial,sans-serif;width:100%;height:calc(100vh - 2px);box-sizing:border-box;color:var(--text);background:radial-gradient(circle at 0% 0%,rgba(213,174,119,.22),transparent 34%),radial-gradient(circle at 100% 0%,rgba(139,224,209,.14),transparent 30%),linear-gradient(135deg,#101A24 0%,#060A0F 100%);border:1px solid rgba(213,174,119,.32);border-radius:22px;overflow:auto;box-shadow:0 24px 70px rgba(0,0,0,.46)}
			.diag-wrap::-webkit-scrollbar{width:14px;height:12px}.diag-wrap::-webkit-scrollbar-track{background:#060A0F;border-radius:999px}.diag-wrap::-webkit-scrollbar-thumb{background:linear-gradient(180deg,rgba(244,217,169,.78),rgba(139,224,209,.44));border:3px solid #060A0F;border-radius:999px}
			.sticky{position:relative;z-index:2;background:rgba(8,13,19,.985);border-bottom:1px solid rgba(213,174,119,.22);box-shadow:0 12px 24px rgba(0,0,0,.24);overflow:visible}
			.diag-head{padding:16px 26px 22px;overflow:visible}.slicer-space{height:64px;margin-bottom:14px;border-radius:18px;border:1px dashed rgba(213,174,119,.16);background:linear-gradient(135deg,rgba(255,255,255,.025),rgba(139,224,209,.025));box-shadow:inset 0 1px 0 rgba(255,255,255,.04)}
			.kpis{display:grid;grid-template-columns:repeat(4,minmax(210px,1fr));gap:16px;overflow:visible}.kpi{position:relative;min-width:0;padding:20px 18px 17px;border-radius:20px;background:linear-gradient(155deg,rgba(18,31,42,.98),rgba(9,15,21,.96));border:1px solid rgba(255,255,255,.10);box-shadow:0 18px 34px rgba(0,0,0,.25),inset 0 1px 0 rgba(255,255,255,.06);overflow:visible;transition:transform .18s ease,border-color .18s ease,box-shadow .18s ease,background .18s ease}.kpi:before{content:'';position:absolute;left:18px;top:0;width:56px;height:5px;border-radius:0 0 10px 10px;background:linear-gradient(90deg,var(--gold),var(--teal));transition:width .18s ease,filter .18s ease}.kpi:hover{transform:translateY(-5px) scale(1.012);border-color:rgba(244,217,169,.55);box-shadow:0 26px 48px rgba(0,0,0,.34),0 0 0 1px rgba(213,174,119,.10),0 0 30px rgba(139,224,209,.10),inset 0 1px 0 rgba(255,255,255,.08)}.kpi:hover:before{width:86px;filter:drop-shadow(0 0 9px rgba(139,224,209,.48))}.kpi.primary{border-color:rgba(213,174,119,.46);background:linear-gradient(155deg,rgba(213,174,119,.18),rgba(18,31,42,.98) 38%,rgba(9,15,21,.96))}.kpi.attention{border-color:rgba(139,224,209,.32);background:linear-gradient(155deg,rgba(139,224,209,.13),rgba(18,31,42,.98) 38%,rgba(9,15,21,.96))}.kpi-label{color:var(--muted);font-size:13px;font-weight:1000;letter-spacing:.09em;text-transform:uppercase}.kpi-value{margin-top:10px;color:var(--gold);font-size:42px;font-weight:1000;line-height:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.kpi-note{margin-top:8px;color:var(--dim);font-size:14px;font-weight:850;line-height:1.25}
			[data-tip]{position:relative}.kpi[data-tip]:hover:after,.metric[data-tip]:hover:after,.prod-cell[data-tip]:hover:after,.table-head div[data-tip]:hover:after,.tag[data-tip]:hover:after,.stage-line[data-tip]:hover:after{content:attr(data-tip);position:absolute;left:50%;top:calc(100% + 12px);transform:translateX(-50%);width:max-content;max-width:390px;min-width:245px;z-index:9999;padding:14px 15px;border-radius:15px;background:linear-gradient(160deg,rgba(7,12,18,.99),rgba(15,27,36,.99));border:1px solid rgba(244,217,169,.42);color:#F4F7FA;font-size:14px;font-weight:850;line-height:1.35;text-align:left;text-transform:none;letter-spacing:0;white-space:normal;box-shadow:0 18px 40px rgba(0,0,0,.48),0 0 0 1px rgba(139,224,209,.08),inset 0 1px 0 rgba(255,255,255,.07);pointer-events:none}.kpi[data-tip]:hover:after{top:calc(100% + 14px);font-size:15px;min-width:310px}.table-head div[data-tip]:hover:after{top:calc(100% + 10px);font-size:13.5px;min-width:280px}.metric[data-tip]:hover:after{font-size:14px;min-width:280px}.prod-cell[data-tip]:hover:after{left:24px;transform:none;top:calc(100% - 8px);min-width:340px}.tag[data-tip]:hover:after{font-size:13px;min-width:250px}.stage-line[data-tip]:hover:after{left:0;transform:none;top:calc(100% + 8px)}
			.table-head,.row-grid{display:grid;grid-template-columns:285px repeat(9,minmax(98px,.85fr)) minmax(138px,1fr) minmax(138px,1fr);min-width:1580px}.table-head{position:sticky;top:0;z-index:65;background:#111D27;border-bottom:1px solid rgba(213,174,119,.26);box-shadow:0 14px 26px rgba(0,0,0,.35);overflow:visible}.table-head div{position:relative;padding:12px 8px;color:var(--gold2);font-size:11.5px;font-weight:1000;text-transform:uppercase;letter-spacing:.07em;text-align:center;border-right:1px solid rgba(255,255,255,.035);transition:background .18s ease,color .18s ease,text-shadow .18s ease}.table-head div:hover{background:rgba(213,174,119,.10);color:#FFE7BD;text-shadow:0 0 12px rgba(213,174,119,.35)}.table-head div:first-child{text-align:left;padding-left:24px}.rows{min-width:1580px}
			.diag-row{border-bottom:1px solid rgba(255,255,255,.065);transition:filter .18s ease}.diag-row summary{list-style:none;cursor:pointer}.diag-row summary::-webkit-details-marker{display:none}.diag-row[open]{filter:drop-shadow(0 14px 28px rgba(0,0,0,.24))}.row-grid{align-items:stretch;background:rgba(255,255,255,.02);transition:background .18s ease,transform .18s ease,box-shadow .18s ease}.row-grid:hover{background:linear-gradient(90deg,rgba(213,174,119,.105),rgba(139,224,209,.055));box-shadow:inset 0 0 0 1px rgba(244,217,169,.10);transform:translateX(2px)}
			.prod-cell{position:relative;padding:12px 16px;min-height:82px;display:flex;flex-direction:column;justify-content:center;transition:background .18s ease}.prod-cell:hover{background:rgba(255,255,255,.025)}.prod-title{color:#FFF7EC;font-size:17px;font-weight:1000;line-height:1.12;transition:color .18s ease,text-shadow .18s ease}.row-grid:hover .prod-title{color:#FFF0D7;text-shadow:0 0 16px rgba(213,174,119,.20)}.prod-sub{margin-top:5px;color:var(--muted);font-size:11.2px;font-weight:850;line-height:1.3}.prod-tags{display:flex;flex-wrap:wrap;gap:5px;margin-top:7px}.tag{position:relative;display:inline-flex;padding:4px 7px;border-radius:999px;border:1px solid rgba(255,255,255,.10);background:rgba(255,255,255,.05);font-size:10.5px;font-weight:950;color:var(--muted);transition:transform .16s ease,border-color .16s ease,background .16s ease}.tag:hover{transform:translateY(-2px);border-color:rgba(244,217,169,.38);background:rgba(213,174,119,.11)}.tag.bad{color:var(--red);border-color:rgba(255,156,147,.34);background:rgba(255,156,147,.08)}.tag.good{color:var(--teal);border-color:rgba(139,224,209,.32);background:rgba(139,224,209,.08)}
			.metric{position:relative;display:flex;flex-direction:column;justify-content:center;align-items:center;min-height:82px;text-align:center;padding:9px 6px;border-left:1px solid rgba(255,255,255,.06);transition:transform .18s ease,background .18s ease,box-shadow .18s ease}.metric:hover{transform:translateY(-4px);background:rgba(255,255,255,.045);box-shadow:inset 0 0 0 1px rgba(255,255,255,.055),0 18px 30px rgba(0,0,0,.20)}.metric b{color:var(--text);font-size:28px;font-weight:1000;line-height:1;transition:transform .18s ease,text-shadow .18s ease}.metric:hover b{transform:scale(1.08);text-shadow:0 0 14px rgba(139,224,209,.18)}.metric small{margin-top:7px;color:var(--muted);font-size:10.5px;font-weight:950;text-transform:uppercase;letter-spacing:.055em}.metric .pct{margin-top:6px;width:78%;height:6px;border-radius:999px;background:rgba(255,255,255,.08);overflow:hidden}.metric .pct span{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,var(--gold2),var(--teal));transition:filter .18s ease}.metric:hover .pct span{filter:drop-shadow(0 0 8px rgba(139,224,209,.55))}.metric.cad b{color:#A8B4C0}.metric.proc b{color:#9CCBFF}.metric.check b{color:#F4D9A9}.metric.oper b{color:#FFCF87}.metric.reu b{color:#8BE0D1}.metric.diag b{color:#B9F0FF}.metric.cred b{color:#7BEEA6}.metric.fim b{color:#B4BBC4}.metric.canc b{color:#FF9C93}.metric.money b{color:#F4D9A9;font-size:19px;line-height:1.08;white-space:normal;word-break:keep-all}.metric.money{padding-left:5px;padding-right:5px}.metric.money small{font-size:9px}
			.details{display:grid;grid-template-columns:1fr 1.25fr;gap:18px;padding:12px 16px 24px;background:rgba(2,7,12,.44);border-top:1px solid rgba(213,174,119,.16);animation:openFade .22s ease-out}@keyframes openFade{from{opacity:.25;transform:translateY(-6px)}to{opacity:1;transform:translateY(0)}}.card{border:1px solid rgba(213,174,119,.18);background:rgba(255,255,255,.04);border-radius:18px;padding:16px;min-width:0;transition:transform .18s ease,border-color .18s ease,box-shadow .18s ease}.card:hover{transform:translateY(-3px);border-color:rgba(244,217,169,.34);box-shadow:0 16px 32px rgba(0,0,0,.25)}.card-title{color:var(--gold);font-size:15px;font-weight:1000;letter-spacing:.06em;text-transform:uppercase;margin-bottom:13px}.stage-line{position:relative;display:grid;grid-template-columns:135px 1fr 70px 68px;align-items:center;gap:10px;min-height:36px;border-bottom:1px solid rgba(255,255,255,.055);font-size:14px;font-weight:850;transition:background .16s ease,padding-left .16s ease}.stage-line:hover{background:rgba(213,174,119,.07);padding-left:8px}.stage-line:last-child{border-bottom:none}.bar{height:9px;border-radius:999px;background:rgba(255,255,255,.08);overflow:hidden}.bar span{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,var(--gold2),var(--teal))}.num{text-align:right;font-weight:1000;color:#fff}.pcttxt{text-align:right;color:var(--muted);font-size:10.5px;font-weight:950}
			.det-head,.det-row{display:grid;grid-template-columns:.75fr 1.25fr .9fr 1fr 1fr .8fr;gap:9px;align-items:center}.det-head{color:var(--gold2);font-size:12px;font-weight:1000;text-transform:uppercase;letter-spacing:.055em;padding-bottom:9px;border-bottom:1px solid rgba(213,174,119,.18)}.det-row{min-height:38px;color:#E8EEF5;font-size:13px;font-weight:820;border-bottom:1px solid rgba(255,255,255,.05);transition:background .16s ease,transform .16s ease}.det-row:hover{background:rgba(139,224,209,.06);transform:translateX(3px)}.det-row div{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chip{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:5px 9px;font-size:11px;font-weight:1000;text-transform:uppercase;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.05)}.chip.proc{color:#9CCBFF}.chip.check{color:#F4D9A9}.chip.oper{color:#FFCF87}.chip.reu{color:#8BE0D1}.chip.diag{color:#B9F0FF}.chip.cred{color:#7BEEA6}.chip.outros{color:#A8B4C0}.empty{margin:24px;padding:34px;border:1px dashed rgba(213,174,119,.30);border-radius:18px;color:var(--muted);text-align:center;font-size:18px;font-weight:900}.foot{padding:12px 24px 26px;color:var(--dim);font-size:13px;font-weight:800}
			
			/* Força fundo sólido nos tooltips internos da tabela */
			.rows,.row-grid,.prod-cell,.metric,.table-head,.table-head div,.details,.card,.stage-line,.tag{overflow:visible!important}
			.metric[data-tip]:hover:after,
			.prod-cell[data-tip]:hover:after,
			.table-head div[data-tip]:hover:after,
			.stage-line[data-tip]:hover:after,
			.tag[data-tip]:hover:after{
			    background:#071018!important;
			    background-color:#071018!important;
			    opacity:1!important;
			    color:#F4F7FA!important;
			    border:1px solid rgba(244,217,169,.55)!important;
			    box-shadow:0 22px 46px rgba(0,0,0,.72),0 0 0 1px rgba(139,224,209,.10),inset 0 1px 0 rgba(255,255,255,.08)!important;
			    z-index:999999!important;
			    backdrop-filter:none!important;
			    -webkit-backdrop-filter:none!important;
			}
			.metric[data-tip]:hover:before,
			.prod-cell[data-tip]:hover:before,
			.table-head div[data-tip]:hover:before,
			.stage-line[data-tip]:hover:before,
			.tag[data-tip]:hover:before{
			    content:'';
			    position:absolute;
			    left:50%;
			    top:calc(100% + 4px);
			    transform:translateX(-50%) rotate(45deg);
			    width:12px;
			    height:12px;
			    background:#071018!important;
			    border-left:1px solid rgba(244,217,169,.50);
			    border-top:1px solid rgba(244,217,169,.50);
			    z-index:999998!important;
			    pointer-events:none;
			}
			.prod-cell[data-tip]:hover:before,
			.stage-line[data-tip]:hover:before{
			    left:34px;
			    transform:rotate(45deg);
			}
			
			
			/* Correção final: tooltip da tabela acima das células vizinhas, com fundo 100% sólido */
			.row-grid{position:relative;z-index:1;overflow:visible!important}
			.diag-row{position:relative;z-index:1;overflow:visible!important}
			.diag-row:hover{z-index:9000!important}
			.metric,.prod-cell,.stage-line,.tag,.table-head div{position:relative!important;overflow:visible!important}
			.metric:hover,.prod-cell:hover,.stage-line:hover,.tag:hover,.table-head div:hover{
			    z-index:999990!important;
			    isolation:isolate!important;
			}
			.metric[data-tip]:hover:after,
			.prod-cell[data-tip]:hover:after,
			.table-head div[data-tip]:hover:after,
			.stage-line[data-tip]:hover:after,
			.tag[data-tip]:hover:after{
			    background:#06111A!important;
			    background-image:linear-gradient(180deg,#06111A 0%,#06111A 100%)!important;
			    background-color:#06111A!important;
			    opacity:1!important;
			    color:#F7FAFC!important;
			    -webkit-text-fill-color:#F7FAFC!important;
			    border:1px solid rgba(244,217,169,.72)!important;
			    outline:1px solid rgba(139,224,209,.14)!important;
			    box-shadow:
			        inset 0 0 0 9999px #06111A,
			        0 26px 54px rgba(0,0,0,.86),
			        0 0 0 2px rgba(6,17,26,.98)!important;
			    z-index:999999!important;
			    mix-blend-mode:normal!important;
			    backdrop-filter:none!important;
			    -webkit-backdrop-filter:none!important;
			}
			.metric[data-tip]:hover:before,
			.prod-cell[data-tip]:hover:before,
			.table-head div[data-tip]:hover:before,
			.stage-line[data-tip]:hover:before,
			.tag[data-tip]:hover:before{
			    background:#06111A!important;
			    background-image:linear-gradient(180deg,#06111A 0%,#06111A 100%)!important;
			    box-shadow:inset 0 0 0 9999px #06111A!important;
			    opacity:1!important;
			    z-index:999998!important;
			}
			
			
			/* Faixa limpa: os filtros ativos são somente os slicers nativos do relatório */
			.slicer-space{height:auto;min-height:76px;margin-bottom:14px;border-radius:18px;border:0;background:transparent;box-shadow:none;padding:12px 0;display:flex;justify-content:flex-end;align-items:center}
			.detailbar{width:430px;display:flex;justify-content:stretch;align-items:center}
			.detail-pill{height:38px;width:100%;display:flex;align-items:center;justify-content:center;border-radius:11px;border:1px solid rgba(213,174,119,.42);background:linear-gradient(135deg,rgba(213,174,119,.16),rgba(139,224,209,.08));color:var(--gold);font-size:12px;font-weight:1000;letter-spacing:.08em;text-transform:uppercase;box-shadow:inset 0 1px 0 rgba(255,255,255,.05),0 10px 20px rgba(0,0,0,.16)}.detail-pill span{color:var(--teal);margin-left:7px}
			.no-match{margin:22px 24px;padding:24px;border:1px dashed rgba(213,174,119,.28);border-radius:16px;color:var(--muted);font-size:17px;font-weight:900;text-align:center;display:none}
			
			
			/* Tooltips flutuantes: não cortam nas bordas do visual */
			[data-tip]:hover:after,
			[data-tip]:hover:before{
			    display:none!important;
			}
			.float-tip{
			    position:fixed;
			    z-index:2147483647;
			    max-width:520px;
			    min-width:260px;
			    padding:16px 18px;
			    border-radius:15px;
			    background:#06111A;
			    color:#F7FAFC;
			    border:1px solid rgba(244,217,169,.70);
			    outline:1px solid rgba(139,224,209,.14);
			    box-shadow:0 26px 54px rgba(0,0,0,.86),0 0 0 2px rgba(6,17,26,.98),inset 0 1px 0 rgba(255,255,255,.08);
			    font-size:16px;
			    font-weight:850;
			    line-height:1.45;
			    pointer-events:none;
			    opacity:0;
			    transform:translate3d(0,0,0) scale(.98);
			    transition:opacity .10s ease, transform .10s ease;
			    white-space:normal;
			    text-align:left;
			    text-transform:none;
			    letter-spacing:0;
			}
			.float-tip.on{
			    opacity:1;
			    transform:translate3d(0,0,0) scale(1);
			}
			.float-tip:before{
			    content:'';
			    position:absolute;
			    width:12px;
			    height:12px;
			    background:#06111A;
			    border-left:1px solid rgba(244,217,169,.55);
			    border-top:1px solid rgba(244,217,169,.55);
			    transform:rotate(45deg);
			    left:var(--arrow-x,22px);
			    top:-7px;
			}
			
			
			/* Apenas o cabeçalho das colunas fica fixo na rolagem */
			.sticky{position:relative!important;top:auto!important}
			.table-head{position:sticky!important;top:0!important}
			
			
			/* Compactacao visual v12 */
			.table-head div{line-height:1.12;white-space:nowrap;word-break:normal}
			.prod-cell{min-height:82px!important;padding:12px 16px!important}
			.metric{min-height:82px!important}
			.metric b{font-size:28px!important}
			.metric.money b{font-size:18px!important;letter-spacing:-.03em}
			.metric.money small{font-size:8.5px!important}
			.prod-title{font-size:17px!important}
			.prod-sub{font-size:10.8px!important;line-height:1.25!important}
			.tag{font-size:10px!important;padding:4px 7px!important}
			.row-grid:hover{transform:none!important}
			.kpis{gap:12px}
			.kpi{padding:15px 16px 14px}
			.kpi-value{font-size:34px}
			.kpi-note{font-size:12px}
			.kpi-label{font-size:11.5px}
			
			
			/* Override final largura/altura */
			.table-head,.row-grid{grid-template-columns:285px repeat(9,minmax(98px,.85fr)) minmax(138px,1fr) minmax(138px,1fr)!important;min-width:1580px!important}
			.rows{min-width:1580px!important}
			
			@media(max-width:1000px){.kpis{grid-template-columns:repeat(4,minmax(210px,1fr));overflow-x:auto}.details{grid-template-columns:1fr}.table-head{top:0}.detailbar{width:360px}.slicer-space{min-height:96px}}
			
			/* Estilo v13: tabela mais proxima do exemplo enviado */
			.table-head,.row-grid{grid-template-columns:340px repeat(10,minmax(88px,.74fr)) minmax(132px,.95fr) minmax(132px,.95fr)!important;min-width:1740px!important}
			.rows{min-width:1620px!important}
			.table-head{background:linear-gradient(180deg,#0F1923 0%,#0A121A 100%)!important;border-bottom:1px solid rgba(213,174,119,.18)!important}
			.table-head div{padding:11px 10px!important;font-size:11px!important;letter-spacing:.09em!important;text-align:center!important}
			.diag-row{border-bottom:1px solid rgba(255,255,255,.055)!important}
			.row-grid{background:linear-gradient(90deg,rgba(11,18,25,.92) 0%,rgba(6,13,20,.96) 100%)!important}
			.row-grid:hover{background:linear-gradient(90deg,rgba(18,27,35,.96) 0%,rgba(7,15,23,.98) 100%)!important;box-shadow:none!important;transform:none!important}
			.prod-cell{min-height:92px!important;padding:10px 14px!important;display:flex!important;flex-direction:column!important;justify-content:center!important;align-items:flex-start!important}
			.prod-title{font-size:14px!important;font-weight:1000!important;line-height:1.15!important;margin-bottom:6px!important}
			.prod-sub{margin-top:0!important;font-size:11px!important;line-height:1.25!important;color:#AEB9C4!important;font-weight:800!important}
			.prod-tags{display:none!important}
			.prod-progress{margin-top:10px;width:100%;height:6px;border-radius:999px;background:rgba(255,255,255,.08);overflow:hidden;box-shadow:inset 0 1px 0 rgba(255,255,255,.05)}
			.prod-progress span{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,#F4D9A9 0%,#8BE0D1 100%)}
			.metric{min-height:92px!important;padding:8px 6px!important;gap:4px!important;background:transparent!important}
			.metric:hover{transform:none!important;background:rgba(255,255,255,.02)!important;box-shadow:inset 0 0 0 1px rgba(255,255,255,.03)!important}
			.metric b{font-size:18px!important;line-height:1.05!important;font-weight:1000!important}
			.metric small{margin-top:0!important;font-size:9.5px!important;line-height:1.15!important;color:#95A2AF!important;text-transform:uppercase!important;letter-spacing:.04em!important}
			.metric .pct{display:none!important}
			.metric.money b{font-size:18px!important;white-space:normal!important;line-height:1.05!important}
			.metric.money small{font-size:9px!important}
			.details{padding:14px 16px 16px!important}
			.card-title{font-size:12px!important}
			.det-head{font-size:10.5px!important}
			.det-row{font-size:12px!important}
			.kpi{border-radius:18px!important}
			.kpi-value{font-size:34px!important}
			@media(max-width:1000px){.table-head,.row-grid{grid-template-columns:300px repeat(10,minmax(84px,.75fr)) minmax(118px,.95fr) minmax(118px,.95fr)!important;min-width:1580px!important}.rows{min-width:1480px!important}}
			
			
			/* Correção v13.1: grade alinhada com 13 colunas reais */
			.table-head,
			.row-grid{
			    grid-template-columns:340px repeat(10,minmax(88px,.74fr)) minmax(132px,.95fr) minmax(132px,.95fr)!important;
			    min-width:1740px!important;
			}
			.rows{min-width:1740px!important}
			.table-head div{white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
			.row-grid > *{min-width:0!important}
			.metric{min-width:0!important}
			.metric b{white-space:nowrap!important}
			.metric.money b{white-space:normal!important}
			.prod-cell{min-width:0!important}
			@media(max-width:1000px){
			    .table-head,
			    .row-grid{
			        grid-template-columns:300px repeat(10,minmax(84px,.75fr)) minmax(118px,.95fr) minmax(118px,.95fr)!important;
			        min-width:1580px!important;
			    }
				.rows{min-width:1580px!important}
			}
			
			/* v14 - leitura ampliada da grade principal */
			.table-head div{font-size:12.8px!important;line-height:1.16!important;padding:13px 10px!important}
			.prod-title{font-size:18px!important;line-height:1.16!important;margin-bottom:7px!important}
			.prod-sub{font-size:12.5px!important;line-height:1.28!important}
			.metric b{font-size:21px!important;line-height:1.05!important}
			.metric small{font-size:10.6px!important;line-height:1.18!important}
			.metric.money b{font-size:20px!important;line-height:1.08!important}
			.metric.money small{font-size:9.8px!important}
			.det-head{font-size:11.5px!important}.det-row{font-size:13.5px!important}
			
			</style>
			"
			VAR vCards =
			    "<div class='kpis'>"
			        & "<div class='kpi primary' data-tip='<b>EMPRESAS</b><br/>• <b>O que é:</b> Quantidade de CNPJs únicos com oportunidades selecionadas no período comercial.<br/>• <b>Origem Comercial:</b> Tabela <code>CONTRATOS_OPORTUNIDADES</code>, coluna <code>[CNPJ_JOIN]</code>.<br/>• <b>Filtros:</b> O slicer de data de contrato filtra as oportunidades. Exibe todas as empresas sob análise comercial, independente de já possuírem ou não jobs operacionais correspondentes.'><div class='kpi-label'>Empresas</div><div class='kpi-value'>" & FORMAT ( vEmpresas, vIntFormat ) & "</div><div class='kpi-note'>CNPJs analisados no período</div></div>"
			        & "<div class='kpi primary' data-tip='<b>JOBS TOTAIS (ISOLAMENTO DE STATUS)</b><br/>• <b>O que é:</b> Quantidade total de jobs operacionais únicos vinculados ao recorte de oportunidades comerciais no período.<br/>• <b>Origem Operacional:</b> Tabela <code>JOBS_PRODUTO_AREA</code>, coluna <code>[JOB]</code>.<br/>• <b>Cruzamento de Dados:</b> Vinculado pelo <code>[CNPJ_JOIN]</code> do cliente e pelo prefixo numérico <code>[BASE_JOB_ID]</code> para isolar estritamente os jobs deste produto comercial.<br/>• <b>Última Movimentação:</b> Como a tabela operacional é histórica, agrupa-se por <code>[JOB]</code> e obtém-se o status mais recente com base na maior data entre Entrada de Tributo (<code>[TRIBUTO_DATA_ENTRADA]</code>) e Cadastro (<code>[DATA_CADASTRO]</code>) antes da contagem.'><div class='kpi-label'>Jobs Totais</div><div class='kpi-value'>" & FORMAT ( vJobsTotais, vIntFormat ) & "</div><div class='kpi-note'>Jobs atuais do recorte</div></div>"
			        & "<div class='kpi attention' data-tip='<b>JOBS ATIVOS (FILTRO DO FUNIL)</b><br/>• <b>O que é:</b> Subconjunto de jobs operacionais que estão em andamento técnico (não finalizados).<br/>• <b>Fases Ativas:</b> Jobs cujas etapas atuais estão classificadas como Cadastro/Outros, Procuração, Checklist, Operação, Reunião Técnica e Diagnóstico.<br/>• <b>Fases Excluídas:</b> Não considera as etapas terminais: Créditos (liquidação/compensação), Finalizado/Faturado e Cancelado/Perdido.<br/>• <b>Lógica:</b> Permite monitorar o volume em produção que requer esforço operacional.'><div class='kpi-label'>Jobs Ativos</div><div class='kpi-value'>" & FORMAT ( vJobsAtivos, vIntFormat ) & "</div><div class='kpi-note'>Sem créditos/cancelados</div></div>"
			        & "<div class='kpi' data-tip='<b>OPORTUNIDADES (BASE COMERCIAL)</b><br/>• <b>O que é:</b> Quantidade total de oportunidades de negócios registradas no período.<br/>• <b>Origem Comercial:</b> Tabela <code>CONTRATOS_OPORTUNIDADES</code>.<br/>• <b>Chave de Unicidade:</b> Contagem distinta baseada na chave composta <code>[job]</code> (ID do Job) + <code>[id_solucao]</code> (ID do Serviço) + <code>[CNPJ_JOIN]</code>.<br/>• <b>Lógica:</b> Define o universo comercial âncora do relatório, sobre o qual é analisada a evolução para a esteira operacional de jobs.'><div class='kpi-label'>Oportunidades</div><div class='kpi-value'>" & FORMAT ( vOportunidades, vIntFormat ) & "</div><div class='kpi-note'>job + id_solução + CNPJ</div></div>"
			    & "</div>"
			
			VAR vHead =
			    "<div class='table-head'>"
			        & "<div data-tip='<b>PRODUTO COMERCIAL (ÂNCORA)</b><br/>• <b>O que é:</b> Nome do produto comercial agrupado.<br/>• <b>Origem Comercial:</b> Tabela <code>CONTRATOS_OPORTUNIDADES</code>, coluna <code>[oportunidade]</code>.<br/>• <b>Prevenção de Vazamento:</b> Os jobs operacionais exibidos nas etapas de cada linha são filtrados de forma estrita pelo <code>[CNPJ_JOIN]</code> do cliente e pelo prefixo do ID do Job (<code>[BASE_JOB_ID]</code>). Isso impede que sub-jobs de outros produtos (ex: Previdenciária) vazem para a linha deste produto (ex: Tributária).'>Produto</div>"
			        & "<div data-tip='<b>JOBS ATIVOS DO PRODUTO</b><br/>• <b>O que é:</b> Soma de todos os jobs em andamento vinculados a este produto comercial.<br/>• <b>Lógica de cálculo:</b> Jobs cuja etapa atual (última movimentação registrada) está em uma das 6 fases operacionais ativas (Cadastro, Procuração, Checklist, Operação, Reunião Técnica e Diagnóstico).'>Ativos</div>"
			        & "<div data-tip='<b>ETAPA CADASTRO / OUTROS (ATIVA)</b><br/>• <b>O que é:</b> Jobs operacionais vinculados ao produto em fase inicial de recepção ou cadastramento.<br/>• <b>Regra de Mapeamento:</b> Jobs cujo <code>[NOME_AREA]</code> na última movimentação não corresponde a nenhuma palavra-chave das etapas principais do funil.<br/>• <b>Exemplos de áreas:</b> Triagem inicial, área cadastral, setor de recepção e áreas não mapeadas.'>Cadastro</div>"
			        & "<div data-tip='<b>FASE DE PROCURAÇÃO (ATIVA)</b><br/>• <b>O que é:</b> Jobs retidos na etapa de procurações eletrônicas do cliente.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém a palavra-chave <b>&quot;PROCURA&quot;</b>.<br/>• <b>Significado:</b> Indica pendência de assinatura, envio ou deferimento das procurações digitais junto à Receita Federal/e-CAC.'>Procur.</div>"
			        & "<div data-tip='<b>FASE DE CHECKLIST (ATIVA)</b><br/>• <b>O que é:</b> Jobs em fase de conferência e saneamento de documentos fiscais.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;CHECKLIST&quot;</b>, <b>&quot;QUALIDADE&quot;</b> ou <b>&quot;VALIDA&quot;</b>.<br/>• <b>Significado:</b> Conferência de documentos enviados pelo cliente e validação inicial de arquivos fiscais.'>Checklist</div>"
			        & "<div data-tip='<b>FASE DE OPERAÇÃO (ATIVA)</b><br/>• <b>O que é:</b> Jobs na principal fila de execução e cálculo técnico.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;OPER&quot;</b>, <b>&quot;PLANILH&quot;</b>, <b>&quot;RETIFIC&quot;</b>, <b>&quot;REVISÃO&quot;</b>, <b>&quot;JURÍD&quot;</b> ou <b>&quot;MANIPULA&quot;</b>.<br/>• <b>Significado:</b> Elaboração de planilhas de cálculo, revisão fiscal de arquivos SPED e retificações acessórias.'>Operação</div>"
			        & "<div data-tip='<b>FASE DE REUNIÃO TÉCNICA (ATIVA)</b><br/>• <b>O que é:</b> Projetos operacionalmente finalizados aguardando validação.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;REUNIÃO&quot;</b> ou <b>&quot;REUNIAO&quot;</b>.<br/>• <b>Significado:</b> Reuniões técnicas de alinhamento com o cliente para validação dos resultados calculados antes do protocolo.'>Reunião</div>"
			        & "<div data-tip='<b>FASE DE DIAGNÓSTICO (ATIVA)</b><br/>• <b>O que é:</b> Fase final de formalização técnica do projeto.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;DIAGN&quot;</b> ou <b>&quot;ENTREGA&quot;</b>.<br/>• <b>Significado:</b> Confecção do laudo de diagnóstico consolidado e montagem do dossiê de entrega para o cliente.'>Diagn.</div>"
			        & "<div data-tip='<b>FASE DE CRÉDITOS (TERMINAL)</b><br/>• <b>O que é:</b> Jobs concluídos operacionalmente que atingiram a fase de créditos.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;CRÉDIT&quot;</b>, <b>&quot;CREDIT&quot;</b>, <b>&quot;COMPENSA&quot;</b> ou <b>&quot;LIQUID&quot;</b>.<br/>• <b>Significado:</b> Fase de compensações administrativas ou homologação fiscal do direito creditório apurado.'>Créditos</div>"
			        & "<div data-tip='<b>FASE FINALIZADO / FATURADO (TERMINAL)</b><br/>• <b>O que é:</b> Jobs concluídos operacionalmente com sucesso e faturados comercialmente.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;FIM&quot;</b> ou <b>&quot;FATUR&quot;</b>.<br/>• <b>Significado:</b> Projetos concluídos com sucesso e faturamento liquidado. Não conta no funil ativo de pendências técnicas.'>Finaliz.</div>"
			        & "<div data-tip='<b>FASE CANCELADO / PERDIDO (TERMINAL)</b><br/>• <b>O que é:</b> Jobs suspensos, distratados ou perdidos comercialmente.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;DISTRATO&quot;</b>, <b>&quot;NÃO FATURADO&quot;</b>, <b>&quot;NÃO APROVADO&quot;</b> ou <b>&quot;NÃO APRESENTADO&quot;</b>.<br/>• <b>Significado:</b> Projetos formalmente cancelados, suspensos ou com perda de proposta técnica.'>Cancel.</div>"
			        & "<div data-tip='<b>HONORÁRIOS ESTIMADOS COMERCIAL</b><br/>• <b>O que é:</b> Soma da estimativa de crédito comercial contratada.<br/>• <b>Origem Comercial:</b> Tabela <code>CONTRATOS_OPORTUNIDADES</code>, coluna <code>[estimativa]</code>.<br/>• <b>Filtro:</b> Calculado diretamente sobre as oportunidades comerciais ativas no período selecionado no slicer de calendário.'>Hon. Est.</div>"
			        & "<div data-tip='<b>HONORÁRIOS ENCONTRADOS OPERACIONAL</b><br/>• <b>O que é:</b> Soma dos honorários de sucesso encontrados na base operacional de jobs.<br/>• <b>Origem Operacional:</b> Tabela <code>JOBS_PRODUTO_AREA</code>, coluna <code>[JOB_HONORARIOS_ENCONTRADOS]</code>.<br/>• <b>Lógica:</b> Vinculado estritamente por CNPJ e pelo ID base do job (prefixo) correspondentes à oportunidade comercial da linha.'>Hon. Enc.</div>"
			    & "</div>"
			
			VAR vRows =
			    CONCATENATEX (
			        vProductTop,
			        VAR p = [__Produto]
			        VAR vEmp = [__Empresas]
			        VAR vOpp = [__Oportunidades]
			        VAR vJobs = [__Jobs]
			        VAR vAtivos = [__Ativos]
			        VAR vSemJob = [__SemJob]
			        VAR vEstimativa = [__Estimativa]
			        VAR vCadOutros = [__CadastroOutros]
			        VAR vProc = [__Procuracao]
			        VAR vCheck = [__Checklist]
			        VAR vOper = [__Operacao]
			        VAR vReu = [__Reuniao]
			        VAR vDiag = [__Diagnostico]
			        VAR vCred = [__Creditos]
			        VAR vFinalizado = [__Finalizado]
			        VAR vCancelado = [__Cancelado]
			        VAR vCredValor = [__CreditosValor]
			        VAR vHonorEstimado = [__HonorEstimado]
			        VAR vHonorEncontrado = [__HonorEncontrado]
			        VAR vHonorEstimadoTxt =
			            SWITCH (
			                TRUE (),
			                ABS ( vHonorEstimado ) >= 1000000, "R$ " & FORMAT ( DIVIDE ( vHonorEstimado, 1000000 ), "0.0" ) & " mi",
			                ABS ( vHonorEstimado ) >= 1000, "R$ " & FORMAT ( DIVIDE ( vHonorEstimado, 1000 ), "0.0" ) & " mil",
			                "R$ " & FORMAT ( vHonorEstimado, "#,##0" )
			            )
			        VAR vHonorEncontradoTxt =
			            SWITCH (
			                TRUE (),
			                ABS ( vHonorEncontrado ) >= 1000000, "R$ " & FORMAT ( DIVIDE ( vHonorEncontrado, 1000000 ), "0.0" ) & " mi",
			                ABS ( vHonorEncontrado ) >= 1000, "R$ " & FORMAT ( DIVIDE ( vHonorEncontrado, 1000 ), "0.0" ) & " mil",
			                "R$ " & FORMAT ( vHonorEncontrado, "#,##0" )
			            )
			        VAR vPctAtivos = DIVIDE ( vAtivos, vJobs, 0 )
			        VAR vTotalEtapas = vCadOutros + vProc + vCheck + vOper + vReu + vDiag + vCred + vFinalizado + vCancelado
			        VAR vStageTable =
			            UNION (
			                ROW ( "Ordem", 1, "Etapa", "Cadastro/Outros", "Qtd", vCadOutros, "Class", "cad", "Tip", "<b>FASE CADASTRO / OUTROS (ATIVA)</b><br/>• <b>Significado:</b> Jobs operacionais vinculados ao produto em fase inicial de recepção ou cadastramento.<br/>• <b>Regra de Mapeamento:</b> Jobs cujo <code>[NOME_AREA]</code> na última movimentação não corresponde a nenhuma palavra-chave das etapas principais do funil.<br/>• <b>Áreas comuns:</b> Triagem inicial, cadastral, administrativo ou não mapeados." ),
			                ROW ( "Ordem", 2, "Etapa", "Procuração", "Qtd", vProc, "Class", "proc", "Tip", "<b>FASE DE PROCURAÇÃO (ATIVA)</b><br/>• <b>Significado:</b> Jobs retidos na etapa de procurações eletrônicas do cliente.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém a palavra-chave <b>&quot;PROCURA&quot;</b>.<br/>• <b>Uso prático:</b> Cobrar a assinatura, envio ou deferimento das procurações digitais no e-CAC da Receita Federal." ),
			                ROW ( "Ordem", 3, "Etapa", "Checklist", "Qtd", vCheck, "Class", "check", "Tip", "<b>FASE DE CHECKLIST (ATIVA)</b><br/>• <b>Significado:</b> Jobs em fase de conferência e saneamento de documentos fiscais.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;CHECKLIST&quot;</b>, <b>&quot;QUALIDADE&quot;</b> ou <b>&quot;VALIDA&quot;</b>.<br/>• <b>Uso prático:</b> Cobrar o saneamento de documentos fiscais pendentes por parte do cliente ou da equipe de triagem." ),
			                ROW ( "Ordem", 4, "Etapa", "Operação", "Qtd", vOper, "Class", "oper", "Tip", "<b>FASE DE OPERAÇÃO (ATIVA)</b><br/>• <b>Significado:</b> Jobs na principal fila de execução e cálculo técnico.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;OPER&quot;</b>, <b>&quot;PLANILH&quot;</b>, <b>&quot;RETIFIC&quot;</b>, <b>&quot;REVISÃO&quot;</b>, <b>&quot;JURÍD&quot;</b> ou <b>&quot;MANIPULA&quot;</b>.<br/>• <b>Uso prático:</b> Fila active de elaboração de cálculos técnicos, revisão fiscal e retificação de SPED." ),
			                ROW ( "Ordem", 5, "Etapa", "Reunião Tec", "Qtd", vReu, "Class", "reu", "Tip", "<b>FASE DE REUNIÃO TÉCNICA (ATIVA)</b><br/>• <b>Significado:</b> Projetos operacionalmente finalizados aguardando validação.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;REUNIÃO&quot;</b> ou <b>&quot;REUNIAO&quot;</b>.<br/>• <b>Uso prático:</b> Reuniões técnicas de alinhamento com o cliente para validação dos resultados calculados antes do protocolo." ),
			                ROW ( "Ordem", 6, "Etapa", "Diagnóstico", "Qtd", vDiag, "Class", "diag", "Tip", "<b>FASE DE DIAGNÓSTICO (ATIVA)</b><br/>• <b>Significado:</b> Fase final de formalização técnica do projeto comercial.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;DIAGN&quot;</b> ou <b>&quot;ENTREGA&quot;</b>.<br/>• <b>Uso prático:</b> Confecção do laudo de diagnóstico consolidado e dossiê de entrega para apresentação ao cliente." ),
			                ROW ( "Ordem", 7, "Etapa", "Créditos", "Qtd", vCred, "Class", "cred", "Tip", "<b>FASE DE CRÉDITOS (TERMINAL)</b><br/>• <b>Significado:</b> Jobs concluídos operacionalmente que atingiram a fase de créditos.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;CRÉDIT&quot;</b>, <b>&quot;CREDIT&quot;</b>, <b>&quot;COMPENSA&quot;</b> ou <b>&quot;LIQUID&quot;</b>.<br/>• <b>Status:</b> Trabalho técnico entregue com sucesso, créditos em fase de homologação fiscal ou compensações ativas." ),
			                ROW ( "Ordem", 8, "Etapa", "Finalizado/Faturado", "Qtd", vFinalizado, "Class", "fim", "Tip", "<b>FASE FINALIZADO / FATURADO (TERMINAL)</b><br/>• <b>Significado:</b> Jobs concluídos operacionalmente e com faturamento/honorários liquidados.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;FIM&quot;</b> ou <b>&quot;FATUR&quot;</b>.<br/>• <b>Status:</b> Projeto concluído operacionalmente com sucesso e devidamente faturado comercialmente." ),
			                ROW ( "Ordem", 9, "Etapa", "Cancelado/Perdido", "Qtd", vCancelado, "Class", "canc", "Tip", "<b>FASE CANCELADO / PERDIDO (TERMINAL)</b><br/>• <b>Significado:</b> Jobs suspensos, distratados ou perdidos comercialmente.<br/>• <b>Regra de Mapeamento:</b> O <code>[NOME_AREA]</code> da última movimentação do job contém <b>&quot;DISTRATO&quot;</b>, <b>&quot;NÃO FATURADO&quot;</b>, <b>&quot;NÃO APROVADO&quot;</b> ou <b>&quot;NÃO APRESENTADO&quot;</b>.<br/>• <b>Status:</b> Projetos formalmente suspensos ou cancelados na esteira operacional." )
			            )
			        VAR vStageCellsBase =
			            CONCATENATEX (
			                vStageTable,
			                VAR q = [Qtd]
			                VAR pct = DIVIDE ( q, vTotalEtapas, 0 )
			                RETURN
			                    "<div class='metric " & [Class] & "' data-tip='" & [Tip] & "<br/><br/><b>Estatística desta Célula:</b><br/>• <b>Jobs nesta Etapa:</b> " & FORMAT ( q, vIntFormat ) & " jobs operacionais.<br/>• <b>Representatividade:</b> " & FORMAT ( pct, vPctFormat ) & " do total exibido nas etapas deste produto no período selecionado.'><b>" & IF ( q = 0, "-", FORMAT ( q, vIntFormat ) ) & "</b><small>" & FORMAT ( pct, vPctFormat ) & " das etapas</small></div>",
			                "",
			                [Ordem], ASC
			            )
			        VAR vStageCells =
			            "<div class='metric active' data-tip='<b>TOTAL DE JOBS ATIVOS DO PRODUTO</b><br/>• <b>Qtd de Jobs Ativos:</b> " & FORMAT ( vAtivos, vIntFormat ) & " jobs operacionais em andamento.<br/>• <b>Fases consideradas ativas:</b> Cadastro, Procuração, Checklist, Operação, Reunião Técnica e Diagnóstico.<br/>• <b>Fases excluídas:</b> Não soma Créditos, Finalizado/Faturado e Cancelado/Perdido (que são etapas terminais).<br/>• <b>Filtros ativos:</b> Slicer de Período nativo restringe a data comercial, e Slicer de Área filtra os jobs.'><b>" & FORMAT ( vAtivos, vIntFormat ) & "</b><small>jobs ativos</small></div>"
			                & vStageCellsBase
			        VAR vMoneyCells =
			            "<div class='metric money' data-tip='<b>HONORÁRIOS ESTIMADOS COMERCIAL</b><br/>• <b>Valor Comercial:</b> " & vHonorEstimadoTxt & "<br/>• <b>Origem Comercial:</b> Soma da estimativa de crédito em <code>CONTRATOS_OPORTUNIDADES[estimativa]</code> para este produto comercial.<br/>• <b>Filtro:</b> Filtrado pela data de contrato das oportunidades selecionadas no slicer de período.'><b>" & vHonorEstimadoTxt & "</b><small>hon. est.</small></div>"
			                & "<div class='metric money' data-tip='<b>HONORÁRIOS ENCONTRADOS OPERACIONAL</b><br/>• <b>Valor Operacional apurado:</b> " & vHonorEncontradoTxt & "<br/>• <b>Origem Operacional:</b> Soma de <code>JOBS_PRODUTO_AREA[JOB_HONORARIOS_ENCONTRADOS]</code>.<br/>• <b>Regra de Vinculação:</b> Considera somente os jobs operacionais vinculados ao CNPJ e ID deste produto para evitar mistura com outros serviços.'><b>" & vHonorEncontradoTxt & "</b><small>hon. enc.</small></div>"
			        VAR cnpjs = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__CNPJ", [__CNPJ] ) )
			        VAR baseJobs = DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__JobCO", [__JobCO] ) )
			        VAR vJobsProduto =
			            FILTER (
			                vJobs_Status,
			                [__CNPJ] IN cnpjs
			                    && [__BaseJob] IN baseJobs
			            )
			        VAR vDetalhesPrimeiros =
			            TOPN (
			                vTopDetalhes,
			                vJobsProduto,
			                [__UltMov], ASC,
			                [__JOB], ASC
			            )
			        VAR vDetalhesTop =
			            TOPN (
			                vTopDetalhes,
			                vJobsProduto,
			                [__UltMov], DESC,
			                [__JOB], DESC
			            )
			        VAR vPrimeirosHTML =
			            CONCATENATEX (
			                vDetalhesPrimeiros,
			                VAR cls =
			                    SWITCH (
			                        [__Etapa],
			                        "PROCURAÇÃO", "proc",
			                        "CHECKLIST", "check",
			                        "OPERAÇÃO", "oper",
			                        "REUNIÃO TEC", "reu",
			                        "DIAGNÓSTICO", "diag",
			                        "CRÉDITOS", "cred",
			                        "FINALIZADO / FATURADO", "fim",
			                        "CANCELADO / PERDIDO", "canc",
			                        "outros"
			                    )
			                RETURN
			                    "<div class='det-row'>"
			                        & "<div>" & [__JOB] & "</div>"
			                        & "<div title='" & [__Cliente] & "'>" & [__Cliente] & "</div>"
			                        & "<div><span class='chip " & cls & "'>" & [__Etapa] & "</span></div>"
			                        & "<div title='" & [__Area] & "'>" & [__Area] & "</div>"
			                        & "<div title='" & [__Responsavel] & "'>" & [__Responsavel] & "</div>"
			                        & "<div>" & IF ( ISBLANK ( [__UltMov] ), "-", FORMAT ( [__UltMov], "dd/MM/yyyy" ) ) & "</div>"
			                    & "</div>",
			                "",
			                [__UltMov], ASC,
			                [__JOB], ASC
			            )
			        VAR vDetalhesHTML =
			            CONCATENATEX (
			                vDetalhesTop,
			                VAR cls =
			                    SWITCH (
			                        [__Etapa],
			                        "PROCURAÇÃO", "proc",
			                        "CHECKLIST", "check",
			                        "OPERAÇÃO", "oper",
			                        "REUNIÃO TEC", "reu",
			                        "DIAGNÓSTICO", "diag",
			                        "CRÉDITOS", "cred",
			                        "FINALIZADO / FATURADO", "fim",
			                        "CANCELADO / PERDIDO", "canc",
			                        "outros"
			                    )
			                RETURN
			                    "<div class='det-row'>"
			                        & "<div>" & [__JOB] & "</div>"
			                        & "<div title='" & [__Cliente] & "'>" & [__Cliente] & "</div>"
			                        & "<div><span class='chip " & cls & "'>" & [__Etapa] & "</span></div>"
			                        & "<div title='" & [__Area] & "'>" & [__Area] & "</div>"
			                        & "<div title='" & [__Responsavel] & "'>" & [__Responsavel] & "</div>"
			                        & "<div>" & IF ( ISBLANK ( [__UltMov] ), "-", FORMAT ( [__UltMov], "dd/MM/yyyy" ) ) & "</div>"
			                    & "</div>",
			                "",
			                [__UltMov], DESC
			            )
			        VAR vPeriodosProduto =
			            CONCATENATEX (
			                DISTINCT ( SELECTCOLUMNS ( FILTER ( vCO_Base, [__Produto] = p ), "__YM", FORMAT ( [__DataContrato], "yyyy-MM" ) ) ),
			                [__YM],
			                "|"
			            )
			        VAR vEtapaAttr =
			            IF ( vCadOutros > 0, " cad", "" )
			                & IF ( vProc > 0, " proc", "" )
			                & IF ( vCheck > 0, " check", "" )
			                & IF ( vOper > 0, " oper", "" )
			                & IF ( vReu > 0, " reu", "" )
			                & IF ( vDiag > 0, " diag", "" )
			                & IF ( vCred > 0, " cred", "" )
			                & IF ( vFinalizado > 0, " fim", "" )
			                & IF ( vCancelado > 0, " canc", "" )
			        VAR vStatusAttr =
			            IF ( vSemJob > 0, "semjob ", "" )
			                & IF ( vAtivos > 0, "ativo ", "semativo " )
			        VAR vProdutoAttr = SUBSTITUTE ( LOWER ( p ), "'", "" )
			        RETURN
			            "<details class='diag-row' data-prod='" & vProdutoAttr & "' data-periodos='" & vPeriodosProduto & "' data-etapas='" & vEtapaAttr & "' data-status='" & vStatusAttr & "'>"
			                & "<summary><div class='row-grid'>"
			                    & "<div class='prod-cell' data-tip='<b>PRODUTO COMERCIAL (ÂNCORA DE ALINHAMENTO)</b><br/>• <b>Nome do Produto:</b> " & p & "<br/>• <b>Origem Comercial:</b> Campo <code>CONTRATOS_OPORTUNIDADES[oportunidade]</code>.<br/>• <b>Métricas desta Linha comercial no período:</b><br/>  - <b>Oportunidades Comerciais:</b> " & FORMAT ( vOpp, vIntFormat ) & " registros comerciais.<br/>  - <b>Clientes (Empresas únicas):</b> " & FORMAT ( vEmp, vIntFormat ) & " CNPJs contratados.<br/>  - <b>Jobs operacionais localizados:</b> " & FORMAT ( vJobs, vIntFormat ) & " jobs vinculados.<br/>  - <b>Jobs ativos (em andamento):</b> " & FORMAT ( vAtivos, vIntFormat ) & " jobs ativos.<br/>  - <b>CNPJs sem correspondência:</b> " & FORMAT ( vSemJob, vIntFormat ) & " empresas contratadas que ainda não possuem job criado na base operacional.<br/>• <b>Regra de Prevenção de Vazamento:</b> O cruzamento entre a base comercial e a operacional é realizado tanto pelo <code>[CNPJ_JOIN]</code> quanto pelo <code>[BASE_JOB_ID]</code> (ID sem sufixos operacionais como -PRT). Isso garante que jobs operacionais pertencentes a outros produtos do mesmo cliente (ex: Previdenciária) não sejam exibidos indevidamente na linha deste produto (ex: Tributária).'><div class='prod-title'>" & p & "</div><div class='prod-sub'>" & FORMAT ( vOpp, vIntFormat ) & " oportunidades · " & FORMAT ( vEmp, vIntFormat ) & " empresas · " & FORMAT ( vJobs, vIntFormat ) & " jobs · " & FORMAT ( vAtivos, vIntFormat ) & " ativos" & IF ( vSemJob > 0, " · " & FORMAT ( vSemJob, vIntFormat ) & " CNPJs sem job", "" ) & "</div><div class='prod-progress'><span style='width:" & FORMAT ( ROUND ( vPctAtivos * 100, 0 ), "0" ) & "%'></span></div></div>"
			                    & vStageCells
			                    & vMoneyCells
			                & "</div></summary>"
			                & "<div class='details'>"
			                    & "<div class='card'><div class='card-title'>Primeiros jobs relacionados ao produto</div><div class='det-head'><div>Job</div><div>Cliente</div><div>Etapa</div><div>Área</div><div>Responsável</div><div>Mov.</div></div>" & IF ( ISBLANK ( vPrimeirosHTML ), "<div class='empty'>Nenhum job encontrado para os CNPJs deste produto.</div>", vPrimeirosHTML ) & "<div class='prod-tags' style='margin-top:14px'><span class='tag'>" & FORMAT ( vOpp, vIntFormat ) & " oportunidades</span><span class='tag'>" & FORMAT ( vEmp, vIntFormat ) & " empresas</span><span class='tag'>" & FORMAT ( vJobs, vIntFormat ) & " jobs encontrados</span><span class='tag good'>" & FORMAT ( vAtivos, vIntFormat ) & " ativos</span></div></div>"
			                    & "<div class='card'><div class='card-title'>Últimos jobs relacionados ao produto</div><div class='det-head'><div>Job</div><div>Cliente</div><div>Etapa</div><div>Área</div><div>Responsável</div><div>Mov.</div></div>" & IF ( ISBLANK ( vDetalhesHTML ), "<div class='empty'>Nenhum job encontrado para os CNPJs deste produto.</div>", vDetalhesHTML ) & "</div>"
			                & "</div>"
			            & "</details>",
			        "",
			        [__SemJob], DESC,
			        [__Oportunidades], DESC,
			        [__Jobs], DESC,
			        [__Produto], ASC
			    )
			
			VAR vNota =
			    IF (
			        COUNTROWS ( vProductSummary ) > vTopProdutos,
			        "Exibindo os " & FORMAT ( vTopProdutos, vIntFormat ) & " produtos com maior prioridade. Use os slicers para reduzir o recorte.",
			        ""
			    )
			
			
			VAR vJS =
			"
			<script>
			function _norm(s){
			  try{return (s||'').toString().toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g,'');}
			  catch(e){return (s||'').toString().toLowerCase();}
			}
			function bindFloatingTooltips(){
			  var tip=document.getElementById('floatTipMacro');
			  if(!tip){
			    tip=document.createElement('div');
			    tip.id='floatTipMacro';
			    tip.className='float-tip';
			    document.body.appendChild(tip);
			  }
			  function placeTip(ev){
			    var margin=12;
			    var gap=18;
			    var vw=window.innerWidth || document.documentElement.clientWidth;
			    var vh=window.innerHeight || document.documentElement.clientHeight;
			    tip.style.left='0px';
			    tip.style.top='0px';
			    var rect=tip.getBoundingClientRect();
			    var x=ev.clientX + gap;
			    var y=ev.clientY + gap;
			    if(x + rect.width + margin > vw){ x = vw - rect.width - margin; }
			    if(x < margin){ x = margin; }
			    if(y + rect.height + margin > vh){ y = ev.clientY - rect.height - gap; }
			    if(y < margin){ y = margin; }
			    var arrowX=Math.max(16, Math.min(rect.width-24, ev.clientX - x + 6));
			    tip.style.setProperty('--arrow-x', arrowX+'px');
			    tip.style.left=x+'px';
			    tip.style.top=y+'px';
			  }
			  document.querySelectorAll('[data-tip]').forEach(function(el){
			    if(el.getAttribute('data-ft-bound')==='1') return;
			    el.setAttribute('data-ft-bound','1');
			    el.addEventListener('mouseenter',function(ev){
			      var t=el.getAttribute('data-tip')||'';
			      if(!t)return;
			      tip.innerHTML=t;
			      tip.classList.add('on');
			      placeTip(ev);
			    });
			    el.addEventListener('mousemove',placeTip);
			    el.addEventListener('mouseleave',function(){
			      tip.classList.remove('on');
			    });
			  });
			}
			setTimeout(bindFloatingTooltips,200);
			</script>
			"
			
			RETURN
			    vCSS
			        & "<div class='diag-wrap'>"
			            & "<div class='sticky'><div class='diag-head'><div class='slicer-space'><div class='detailbar'><div class='detail-pill'>Abrir detalhamento <span>›</span></div></div></div>" & vCards & "</div></div>"
			            & vHead
			            & "<div class='rows'>" & IF ( ISBLANK ( vRows ), "<div class='empty'>Nenhum produto encontrado para os filtros atuais.</div>", vRows ) & "</div>"
			            & "<div class='foot'>" & vNota & "</div>"
			        & "</div>"
			        & vJS
			
			```
		displayFolder: HTML
		lineageTag: b0000702-d1ag-ba5e-b010-ba5e00000702

	column Column
		formatString: 0
		lineageTag: 2ec931fb-c2e0-4926-ad68-5e513c5ba130
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition medidas_html = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 1fcf0b6930bb4e10a61b1c725afbbaf7

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

